"""Dump the brain's deterministic language assets for the TS on-device port.

The on-device brain (mobile/src/brain/, web/src/brain/) needs byte-identical
behavior for the pieces it runs locally — the graded sentiment engine first.
This script serializes the AUTHORITATIVE runtime dicts (post-merge, exactly
what the Python engine looks up) plus the scalar tuning constants into
shared/brain_lexicon.json. The runtime forms are the generated TS modules
mobile/src/brain/lexicon.ts and web/src/brain/lexicon.ts (see TS_OUT below)
— pinned equal to the shared JSON by tests on both sides, the same standing
as shared/vectors.json and shared/generic_questions.json.

Run after any lexicon/constant change — the script writes ALL THREE
artifacts itself (the shared JSON contract and the two TS modules); there
is no manual copy step anymore. The old `cp .../mobile/src/brain/lexicon.json`
instruction named an output form that no longer exists (2026-09-19
audit, L-37):

    cd backend && ../.venv/bin/python scripts/dump_brain_lexicon.py

2026-09-26 audit L-3 follow-up: the payload additionally carries the
Spanish-scoring merge (sentiment_lexicon_es), the English-only negator set
(word_sets.negators_en) and the language-detection tables, so the on-device
ports can mirror the server's language-gated scoring (see brain.py's
SENTIMENT_LEXICON_ES / _negators_for / the detection heuristic).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services import brain  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "shared" / "brain_lexicon.json"
# The module forms: ESM JSON default-import interop proved unreliable
# under the app's transform stacks, so the runtime artifacts are plain TS
# modules (typed, bundled everywhere without loader ambiguity). The shared
# JSON stays as the cross-platform CONTRACT; a test pins them equal.
TS_OUTS = (
    Path(__file__).resolve().parents[2] / "mobile" / "src" / "brain" / "lexicon.ts",
    Path(__file__).resolve().parents[2] / "web" / "src" / "brain" / "lexicon.ts",
)

TS_PRELUDE = """/** GENERATED by backend/scripts/dump_brain_lexicon.py — do not hand-edit.
 * The runtime form of shared/brain_lexicon.json (a test pins the two
 * equal): the deterministic language assets of the on-device brain. A
 * plain exported object, deliberately — no type decoration here, no
 * interface: earlier generated prelude variants produced subtly
 * different module-evaluation behavior under the app transform stack.
 * Consumers type the shape at their import site.
 */
export const LEXICON = """

payload = {
    "v": 1,
    "note": "generated by backend/scripts/dump_brain_lexicon.py — do not hand-edit",
    "scalars": {
        "negation_scalar": brain.NEGATION_SCALAR,
        "sentiment_scale": brain.SENTIMENT_SCALE,
        "booster_scope": brain.BOOSTER_SCOPE,
    },
    "word_sets": {
        "but_words": sorted(brain.BUT_WORDS),
        "negators": sorted(brain.NEGATORS),
        # L-3 (2026-09-26): the EN-only view of the union above — the
        # union stays the default set; "en" scoring excludes the ES-only
        # negators ("sin", "ni", ...) that are English letter strings too.
        "negators_en": sorted(brain.NEGATORS_EN),
        "sense_words": sorted(brain.SENSE_WORDS),
    },
    "intensifiers": brain.INTENSIFIERS,
    "irregular_forms": brain.IRREGULAR_FORMS,
    # The pinned EN-winning merge (the historical default lookup).
    "sentiment_lexicon": brain.SENTIMENT_LEXICON,
    # L-3 (2026-09-26): the ES-scoring mirror merge (Spanish wins every
    # collision) selected when the detected language is "es".
    "sentiment_lexicon_es": brain.SENTIMENT_LEXICON_ES,
    # The server's language-detection heuristic (brain.py: ~min-50 scored
    # tokens, >=10% recognized share, es only when it beats en) so the
    # on-device ports classify the same way the corpus walk does.
    "language_detection": {
        "min_tokens": brain.LANGUAGE_MIN_TOKENS,
        "hit_floor": brain.LANGUAGE_HIT_FLOOR,
        "known_tokens_en": sorted(brain._KNOWN_TOKENS),
        "known_tokens_es": sorted(brain._KNOWN_TOKENS_ES),
    },
    "emoji_valences": brain.EMOJI_VALENCES,
    # Python iterates EMOJI_VALENCES in insertion order when appending
    # emoji tokens; sort_keys would scramble that in the JSON object. The
    # explicit order array preserves the engine's exact token sequence.
    "emoji_order": list(brain.EMOJI_VALENCES),
}

OUT.write_text(json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n")
compact = json.dumps(payload, sort_keys=True, separators=(",", ":"))
for ts_out in TS_OUTS:
    ts_out.write_text(TS_PRELUDE + compact + ";\n")
print(
    f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(brain.SENTIMENT_LEXICON)} sentiment words)"
    f" and {len(TS_OUTS)} TS modules"
)
