"""Dump the brain's deterministic language assets for the TS on-device port.

The on-device brain (mobile/src/brain/) needs byte-identical behavior for
the pieces it runs locally — the graded sentiment engine first. This script
serializes the AUTHORITATIVE runtime dicts (post-merge, exactly what the
Python engine looks up) plus the scalar tuning constants into
shared/brain_lexicon.json. The mobile copy (mobile/src/brain/lexicon.json)
is a byte-for-byte copy pinned to this file by tests on both sides — the
same standing as shared/vectors.json and shared/generic_questions.json.

Run after any lexicon/constant change:
    cd backend && ../.venv/bin/python scripts/dump_brain_lexicon.py
    cp ../shared/brain_lexicon.json ../mobile/src/brain/lexicon.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services import brain  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "shared" / "brain_lexicon.json"
# The mobile module form: ESM JSON default-import interop proved unreliable
# under the app's transform stack, so the runtime artifact is a plain TS
# module (typed, bundled everywhere without loader ambiguity). The shared
# JSON stays as the cross-platform CONTRACT; a test pins the two equal.
TS_OUT = Path(__file__).resolve().parents[2] / "mobile" / "src" / "brain" / "lexicon.ts"

TS_PRELUDE = """/** GENERATED by backend/scripts/dump_brain_lexicon.py — do not hand-edit.
 * The runtime form of shared/brain_lexicon.json (a test pins the two
 * equal): the deterministic language assets of the on-device brain. A
 * plain exported object, deliberately — no type decoration here, no
 * interface: earlier generated prelude variants produced subtly
 * different module-evaluation behavior under the app transform stack.
 * Consumers type the shape at their import site.
 */
export const LEXICON = """

payload = {
    "v": 1,
    "note": "generated by backend/scripts/dump_brain_lexicon.py — do not hand-edit",
    "scalars": {
        "negation_scalar": brain.NEGATION_SCALAR,
        "sentiment_scale": brain.SENTIMENT_SCALE,
        "booster_scope": brain.BOOSTER_SCOPE,
    },
    "word_sets": {
        "but_words": sorted(brain.BUT_WORDS),
        "negators": sorted(brain.NEGATORS),
        "sense_words": sorted(brain.SENSE_WORDS),
    },
    "intensifiers": brain.INTENSIFIERS,
    "irregular_forms": brain.IRREGULAR_FORMS,
    "sentiment_lexicon": brain.SENTIMENT_LEXICON,
    "emoji_valences": brain.EMOJI_VALENCES,
    # Python iterates EMOJI_VALENCES in insertion order when appending
    # emoji tokens; sort_keys would scramble that in the JSON object. The
    # explicit order array preserves the engine's exact token sequence.
    "emoji_order": list(brain.EMOJI_VALENCES),
}

OUT.write_text(json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n")
compact = json.dumps(payload, sort_keys=True, separators=(",", ":"))
TS_OUT.write_text(TS_PRELUDE + compact + ";\n")
print(
    f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(brain.SENTIMENT_LEXICON)} sentiment words)"
    f" and {TS_OUT}"
)
