"""Generate cross-platform brain vectors (shared/brain_vectors.json).

The on-device brain (mobile/src/brain/) must be byte-faithful to the
Python engine for the pieces it runs locally. This script emits golden
inputs and outputs — sentiment scores/components over a diverse text
corpus (negation, intensifiers, "but" re-weighting, stemming, emoji,
PA/NA splits) plus the statistics core (erfc tails, Fisher-z difference
p-values, Pearson r) — consumed by tests on BOTH platforms:
  - mobile: tests/brainVectors.test.ts runs the TS port against every
    vector (float equality for sentiment; 1e-9 for statistics),
  - backend: tests/test_brain_vectors.py regenerates and compares, so a
    Python-side engine change that breaks parity fails on the server too.

The same standing as shared/vectors.json for the crypto: regenerate after
any engine change,
    cd backend && ../.venv/bin/python scripts/gen_brain_vectors.py
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.services import brain, statsig  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "shared" / "brain_vectors.json"

TEXT_CASES: list[str] = [
    "quiet day, some work in the afternoon",
    "felt calm and grateful today",
    "i am happy today",
    "i am not happy today",
    "no stress at all today",
    "felt happy and calm but tired",
    "extremely bad no good very anxious",
    "it was very very good but honestly kind of awful afterwards",
    "working late on the presentations again, dreading tomorrow",
    "i slept terribly and cant stop thinking about the deadline",
    "cried all evening for no reason i can name",
    "proud of what we finished, relieved it shipped, exhausted though",
    "the interview went badly i suppose, but i realize now the reason i "
    "was nervous was because i cared about it",
    "walking home noticing the light, thinking about my sister, feeling okay",
    "absolutely wonderful 🎉 sunshine and coffee ☕ and no meetings",
    "terrible awful day 😞 but the dog 🐕 helped",
    "hardly slept, barely ate, somehow still standing",
    "not bad, not great, just a day",
    "so so so tired of everything",
    "understood why she said it, and knowing that helped more than i expected",
    "worried about mom again, the tests are friday",
    "running helped, outdoors helped, the run in the park always helps",
    "i don't know how i feel about the move yet",
    "because you asked, i will consider it",
    "",
    "🙂",
    "good good good good good",
    "sad sad happy",
    # Regression inputs from the TS-port debugging session: negation via
    # "nothing", morphological identity ("goodness" is not "good"), and
    # case handling all live here so both platforms stay pinned on them.
    "nothing emotional here",
    "goodness gracious",
    "GOOD day",
    "i realize now the reason was because i cared",
    # Spanish (2026-09-19): the merged-lexicon engine must score Spanish
    # identically on both platforms — negation, "pero" re-weighting,
    # intensifiers and pure valence all exercised.
    "hoy me siento muy feliz y tranquilo",
    "me siento triste y cansado con mucha ansiedad",
    "estoy cansado pero feliz",
    "no estoy bien",
    "nunca estoy tranquilo los domingos",
    "estoy muy muy agradecido por mi familia",
    "que dia tan horrible, todo salio mal",
]

STAT_CASES = {
    "erfc": [0.05, 0.467, 1.0, 1.5, 2.0, 2.5, 3.5, 5.0, 7.0],
    "pearson": [
        [[0.1, 0.4, -0.2, 0.5, 0.3], [0.2, 0.35, -0.1, 0.55, 0.25]],
        [[1, 2, 3, 4], [4, 3, 2, 1]],
        [[0.5, 0.5, 0.5, 0.5], [0.1, -0.3, 0.2, 0.0]],
    ],
    "fisher_z": [
        [0.44, 28, -0.1, 40],
        [0.7, 15, 0.5, 20],
        [0.9, 12, -0.8, 30],
        [0.05, 50, 0.02, 60],
    ],
}


def main() -> None:
    sentiment_vectors = []
    for text in TEXT_CASES:
        tokens = [t for t in __import__("re").findall(r"[a-z']+", text.lower())]
        tokens.extend(e for e in brain.EMOJI_VALENCES for _ in range(text.count(e)))
        pa, na = brain.sentiment_components(tokens)
        sentiment_vectors.append(
            {
                "text": text,
                "score": brain.sentiment_score(tokens),
                "pa": round(pa, 6),
                "na": round(na, 6),
            }
        )

    payload = {
        "v": 1,
        "note": "generated by backend/scripts/gen_brain_vectors.py — regenerate on engine change",
        "sentiment": sentiment_vectors,
        "stats": {
            "erfc": [[z, math.erfc(z)] for z in STAT_CASES["erfc"]],
            "pearson": [[xs, ys, brain._pearson(xs, ys)] for xs, ys in STAT_CASES["pearson"]],
            "fisher_z": [
                [r1, n1, r2, n2, statsig.fisher_z_difference_p(r1, n1, r2, n2)]
                for r1, n1, r2, n2 in STAT_CASES["fisher_z"]
            ],
        },
    }
    OUT.write_text(json.dumps(payload, indent=1) + "\n")
    print(
        f"wrote {OUT}: {len(sentiment_vectors)} sentiment vectors, "
        f"{len(payload['stats']['erfc'])} erfc, "
        f"{len(payload['stats']['pearson'])} pearson, "
        f"{len(payload['stats']['fisher_z'])} fisher-z"
    )


if __name__ == "__main__":
    main()
