/** Exercise screen adoption through actual HTTP, credential, native storage,
 * PBKDF and authenticated envelope providers. The receiver uses Node crypto
 * independently of the application's key and envelope implementation. */
import crypto from "node:crypto";
import React from "react";
import ReactTestRenderer,{act} from "react-test-renderer";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {Alert,KeyboardAvoidingView,Platform,Switch,Text,TextInput,TouchableOpacity} from "react-native";
import {LoginScreen,passwordPolicyError} from "../../src/screens/LoginScreen";
import {RecoveryScreen} from "../../src/screens/RecoveryScreen";
import {api,getBaseUrl,setBaseUrl} from "../../src/api/client";
import {vault} from "../../src/vault";
import {SessionProvider,useSession} from "../../src/store";
import {verifyUnlockProof} from "../../src/unlockProof";
import {takePendingOnboarding} from "../../src/onboarding";
import {secureStore,setSecureStoreBackend} from "../../src/secureStore";
import {prepareLocalRekey,pendingLocalRekey} from "../../src/localRekey";
import {recordMood,recentMoods} from "../../src/moodLog";
import {accountStorageKey} from "../../src/accountStorage";
import {__resetLocalKeyLifecycleForTests} from "../../src/localWriteGuard";
import {runTestControl} from "../helpers/testControl";
import storage from "../helpers/storageMock";
import * as keychain from "../helpers/keychainMock";
import * as files from "../helpers/expoFsMock";
import {engine} from "../helpers/nodeEngine";

(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const USER="a".repeat(32),OTHER="b".repeat(32),DATA=Buffer.alloc(32,7),KIT=Buffer.alloc(32,4),SALT=Buffer.alloc(16,3),PASSWORD="Native strong Passphrase 2026!",NAME="alice";
const PARAMS={algorithm:"pbkdf2-sha256",version:1,iterations:600000};
const hkdf=(key:Buffer,salt:Buffer,label:string)=>Buffer.from(crypto.hkdfSync("sha256",key,salt,label,32));
const MASTER=crypto.pbkdf2Sync(PASSWORD,SALT,600000,32,"sha256"),AUTH=hkdf(MASTER,Buffer.alloc(32),"mindpattern/auth/v1"),LEGACY_DATA=hkdf(MASTER,Buffer.alloc(32),"mindpattern/data/v1");
function seal(key:Buffer,data:Buffer,aad:unknown){const nonce=Buffer.alloc(12,9),cipher=crypto.createCipheriv("aes-256-gcm",key,nonce);cipher.setAAD(Buffer.from(JSON.stringify(aad)));return Buffer.concat([nonce,cipher.update(data),cipher.final(),cipher.getAuthTag()]).toString("base64");}
function unwrap(body:Record<string,any>,password=PASSWORD){const salt=Buffer.from(body.new_salt??body.salt,"base64"),params=body.new_kdf_params??body.kdf_params,master=crypto.pbkdf2Sync(password,salt,params.iterations,32,"sha256"),wrap=Buffer.from(body.wrapped_data_key,"base64"),decipher=crypto.createDecipheriv("aes-256-gcm",hkdf(master,salt,"mindpattern/envelope/v2"),wrap.subarray(0,12));decipher.setAAD(Buffer.from(JSON.stringify({context:"envelope",kdf_params:params,username:NAME})));decipher.setAuthTag(wrap.subarray(-16));return{data:Buffer.concat([decipher.update(wrap.subarray(12,-16)),decipher.final()]),auth:hkdf(master,Buffer.alloc(32),"mindpattern/auth/v1")};}
const WRAP=seal(hkdf(MASTER,SALT,"mindpattern/envelope/v2"),DATA,{context:"envelope",kdf_params:PARAMS,username:NAME});
let root:ReturnType<typeof ReactTestRenderer.create>|undefined,scheme:"v1"|"v2",cacheFailure:boolean,recoveryScheme:"v1"|"v2",registered:Buffer|undefined,reset:number,loginStatus:number;
let nativeBoundary:((path:string)=>Promise<void>)|undefined,nativeCompletion:((path:string)=>void)|undefined;
const platform=Platform.OS;
const nativeFileDelete=files.deleteAsync.getMockImplementation()!;
function response(url:string,body:unknown,status=200){const value=new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});Object.defineProperty(value,"url",{value:url});return value;}
function installServer(){vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{
 const path=new URL(url).pathname,body=init.body?JSON.parse(init.body as string):{},proof=recoveryScheme==="v1"?KIT:hkdf(KIT,Buffer.alloc(32),"mindpattern/recovery-verifier/v2");let value:unknown={},status=200;
 if(path.endsWith("/auth/salt"))value={salt:SALT.toString("base64")};
 else if(path.endsWith("/auth/login")){status=loginStatus;if(body.username!==NAME||body.verifier!==AUTH.toString("base64"))status=401;value=status===200?{token:"Native authenticated bearer",user_id:USER,role:"user"}:{detail:"credentials refused",code:"invalid_credentials"};}
 else if(path.endsWith("/auth/register")){try{const opened=unwrap(body);expect(body.username).toBe(NAME);expect(body.verifier).toBe(opened.auth.toString("base64"));expect(body.age_attestation).toBe("minimum_age_confirmed_v1");registered=opened.data;value={token:"Native registered bearer",user_id:USER,role:"user"};}catch(error){value={detail:String(error)};status=400;}}
 else if(path.endsWith("/auth/key-envelope"))value=scheme==="v1"?{key_scheme:"v1",salt:SALT.toString("base64")}:{key_scheme:"v2",salt:SALT.toString("base64"),kdf_params:PARAMS,wrapped_data_key:WRAP};
 else if(path.endsWith("/auth/recover")){if(body.username!==NAME||body.verifier!==proof.toString("base64")||body.scheme!==recoveryScheme)status=401;value=status===200?{token:"Native recovered bearer",user_id:USER,role:"user",key_scheme:"v2",recovery_scheme:recoveryScheme,username:NAME,recovery_wrapped_data_key:seal(hkdf(KIT,Buffer.alloc(32),recoveryScheme==="v1"?"mindpattern/recovery/v1":"mindpattern/recovery-seal/v2"),DATA,["recovery",USER,"data-key"])}:{detail:"recovery refused",code:"invalid_credentials"};}
 else if(path.endsWith("/processing/sessions")){expect(body.data_key).toBe(DATA.toString("base64"));value={session_token:"Native processing bearer"};}
 else if(path.endsWith("/account/recovery/password")){const opened=unwrap(body);expect(opened.data).toEqual(DATA);expect(body.new_verifier).toBe(opened.auth.toString("base64"));expect(body.proof).toBe(proof.toString("base64"));expect(new Headers(init.headers).get("X-Processing-Token")).toBe("Native processing bearer");reset++;}
 else if(path.endsWith("/insights"))value={active_days:12};else if(path.endsWith("/meta"))value={unlock_days:30};
 const result=response(url,value,status),json=result.json.bind(result);result.json=async()=>{const answer=await json();await nativeBoundary?.(path);nativeCompletion?.(path);return answer;};return result;
});}
function sessionState(){const s=useSession();return <Text>{`Native session ${s.authStatus} unlocked=${s.unlocked}`}</Text>;}
async function flush(){await act(async()=>{for(let i=0;i<60;i++)await Promise.resolve();});}
async function mount(screen:"login"|"recovery",navigation:any={navigate:()=>undefined}){await act(async()=>{root=ReactTestRenderer.create(<SessionProvider>{screen==="login"?<LoginScreen navigation={navigation}/>:<RecoveryScreen navigation={navigation}/>}{React.createElement(sessionState)}</SessionProvider>);});await flush();}
function text(){return root!.root.findAllByType(Text).map(node=>node.props.children).flat(Infinity).filter(x=>typeof x==="string"||typeof x==="number").join(" ");}
async function fill(label:string,value:string){const node=root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel===label);if(!node)throw Error(`missing Native input ${label}`);await act(async()=>node.props.onChangeText(value));}
function button(label:string){const node=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel===label);if(!node)throw Error(`missing Native action ${label}: ${text()}`);return node;}
async function press(label:string){const node=button(label);expect(node.props.disabled).not.toBe(true);await act(async()=>{void node.props.onPress();});await flush();}
async function complete(){await vi.waitFor(()=>expect(vault.isUnlocked()).toBe(true),{timeout:15000});await flush();}
async function fillRecovery(){await fill("Username",NAME);await fill("Recovery key",KIT.toString("base64"));await fill("New password (12+ characters)",PASSWORD);await fill("Confirm new password",PASSWORD);}
function deliver(turns:number,event:()=>void){if(turns===0)event();else queueMicrotask(()=>deliver(turns-1,event));}
/** Retain the real native-produced allocations at their custody boundary.
 * Native providers keep their actual crypto behavior; only completion-event
 * delivery and observation of the application's copies are added. */
function nativeKeyCustody(stage:"derivation"|"registration derivation"|"registration envelope"|"login envelope",turns:number){
 const owned=new Set<Buffer>(),masters=new Set<Buffer>(),nativeMasters=new Set<Buffer>(),nativeHkdf=new Set<ArrayBuffer>(),plainChunks=new Set<Buffer>();let triggered=false,replacement:Promise<void>|undefined;
 const replace=()=>{if(triggered)return;triggered=true;replacement=api.setSession("replacement Native crypto bearer",OTHER,"bob").then(()=>vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,11)},OTHER));};
 const pbkdf=engine.pbkdf2,hkdf=engine.hkdfSync,cipher=engine.createCipheriv,decipher=engine.createDecipheriv,allocate=Buffer.from,concat=Buffer.concat;
 vi.spyOn(engine,"pbkdf2").mockImplementation((password,salt,cost,length,hash,done)=>pbkdf(password,salt,cost,length,hash,(error,value)=>{if(value)nativeMasters.add(value);done(error,value);if(stage.includes("derivation"))deliver(turns,replace);}));
 vi.spyOn(engine,"hkdfSync").mockImplementation((...args)=>{const result=hkdf(...args);if(masters.has(args[1]))nativeHkdf.add(result);return result;});
 vi.spyOn(Buffer,"from").mockImplementation(((input:unknown,...args:unknown[])=>{const output=Reflect.apply(allocate,Buffer,[input,...args])as Buffer;if(nativeMasters.has(input as Buffer)){masters.add(output);owned.add(output);}else if(input instanceof Uint8Array&&nativeHkdf.has(input.buffer as ArrayBuffer))owned.add(output);return output;})as typeof Buffer.from);
 vi.spyOn(Buffer,"concat").mockImplementation(((list:readonly Uint8Array[],length?:number)=>{const result=concat(list,length);if(result.length===32&&list.some(chunk=>plainChunks.has(chunk as Buffer)))owned.add(result);return result;})as typeof Buffer.concat);
 vi.spyOn(engine,"createCipheriv").mockImplementation((...args)=>{const result=cipher(...args);if(owned.has(args[1])){const update=result.update.bind(result),tag=result.getAuthTag.bind(result);let keyPayload=false;result.update=(data)=>{if(data.length===32){owned.add(data);keyPayload=true;}return update(data);};result.getAuthTag=()=>{const value=tag();if(stage==="registration envelope"&&keyPayload)deliver(turns,replace);return value;};}return result;});
 vi.spyOn(engine,"createDecipheriv").mockImplementation((...args)=>{const result=decipher(...args);if(owned.has(args[1])){const update=result.update.bind(result),finish=result.final.bind(result);result.update=(data)=>{const value=update(data);if(value.length===32)plainChunks.add(value);return value;};result.final=()=>{const value=finish();if(stage==="login envelope")deliver(turns,replace);return value;};}return result;});
 return{owned,get triggered(){return triggered;},async finish(){await vi.waitFor(()=>expect(replacement).toBeDefined());await replacement;}};
}
beforeEach(async()=>{vi.useRealTimers();vi.restoreAllMocks();files.deleteAsync.mockImplementation(nativeFileDelete);files.__resetFiles();storage.__reset();keychain.__reset();runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);vault.lock();await api.clearSession();await setBaseUrl("http://localhost:8000");takePendingOnboarding();scheme="v2";cacheFailure=false;recoveryScheme="v2";registered=undefined;reset=0;loginStatus=200;nativeBoundary=undefined;nativeCompletion=undefined;Alert.alert.mockClear();installServer();});
afterEach(async()=>{if(root){await act(async()=>root!.unmount());root=undefined;}vi.useRealTimers();vi.restoreAllMocks();Object.defineProperty(Platform,"OS",{configurable:true,value:platform});vault.lock();await api.clearSession();vi.unstubAllGlobals();});

it.each(["v1","v2"]as const)("Native %s login installs the independently verified key and usable offline material",async selected=>{
 scheme=selected;await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await press("Sign in");await complete();const expected=selected==="v2"?DATA:LEGACY_DATA;
 expect(vault.get().dataKey).toEqual(expected);expect(vault.get().authKey).toEqual(AUTH);expect(vault.ownerUserId()).toBe(USER);expect(await verifyUnlockProof(expected,USER)).toBe("ok");expect(await api.getCachedSalt(NAME)).toBe(SALT.toString("base64"));expect(await api.getCachedKeyEnvelope(NAME)).toMatchObject({scheme:selected});expect(text()).toContain("Native session loggedIn unlocked=true");expect(takePendingOnboarding()).toBe(false);
});
it("Native registration's independently authenticated envelope is adopted and remains usable offline",async()=>{
 await mount("login");await press("New here? Create an account");await fill("Username",NAME);await fill("Password",PASSWORD);await fill("Confirm password",PASSWORD);await act(async()=>root!.root.findByType(Switch).props.onValueChange(true));await press("Create account");await complete();expect(registered).toBeDefined();expect(vault.get().dataKey).toEqual(registered);expect(await verifyUnlockProof(registered!,USER)).toBe("ok");expect(await api.getCachedSalt(NAME)).toBeTruthy();expect(await api.getCachedKeyEnvelope(NAME)).toMatchObject({scheme:"v2"});expect(text()).toContain("Native session loggedIn unlocked=true");expect(takePendingOnboarding()).toBe(true);
});
it.each(["v1","v2"]as const)("Native %s recovery preserves the journal key and routes the real session after the calm beat",async selected=>{
 recoveryScheme=selected;const nav={navigate:vi.fn()};await mount("recovery",nav);await fillRecovery();if(selected==="v1")await press("Use a legacy v1 kit (sends its key to your server)");await press("Recover and set new password");await complete();expect(reset).toBe(1);expect(vault.get().dataKey).toEqual(DATA);expect(vault.get().authKeyKnown).toBe(false);expect(vault.ownerUserId()).toBe(USER);expect(text()).toContain("Recovered. Your journal is unlocked");expect(text()).toContain("Native session loggedIn unlocked=true");expect(button("Recover and set new password").props.disabled).toBe(true);await vi.waitFor(()=>expect(nav.navigate).toHaveBeenCalledWith("Entry"),{timeout:2000});
});
it.each(["ios","android"])("Native %s keyboard and copied recovery-secret controls retain their platform contract",async os=>{
 Object.defineProperty(Platform,"OS",{configurable:true,value:os});await mount("recovery");expect(root!.root.findByType(KeyboardAvoidingView).props.behavior).toBe(os==="ios"?"padding":undefined);for(const label of ["Username","Recovery key"]){expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel===label)!.props.spellCheck).toBe(false);}
});
it("Native recovery acknowledges committed password reset despite unavailable offline-cache writes",async()=>{
 const write=storage.setItem.bind(storage);vi.spyOn(storage,"setItem").mockImplementation(async(key,value)=>{if(key.startsWith("@mindpattern/salt_")||key.startsWith("@mindpattern/keyenvelope_"))throw Error("Native cache unavailable");return write(key,value);});await mount("recovery");await fillRecovery();await press("Recover and set new password");await complete();expect(reset).toBe(1);expect(text()).toContain("Recovered. Your journal is unlocked and the new password is active.\nYour new password is active. Offline unlock could not be prepared");
});
it("Native login server editing changes the real origin and clears retained secret inputs",async()=>{
 await mount("login");await fill("Password",PASSWORD);await press("Change server");await fill("Selected server address","http://127.0.0.1:8181");await press("Save server");await vi.waitFor(async()=>expect(await getBaseUrl()).toBe("http://127.0.0.1:8181"));await flush();expect(text()).toContain("http://127.0.0.1:8181");expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Password")!.props.value).toBe("");expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Selected server address")).toBeUndefined();
});
it.each(["", "   "])("Native recovery keeps guidance for a missing copied key %j",async value=>{
 await mount("recovery");await fillRecovery();await fill("Recovery key",value);await press("Recover and set new password");expect(text()).toContain("Enter your username and the recovery key first.");expect(vault.isUnlocked()).toBe(false);
});
it.each(["", "   "])("Native recovery keeps guidance for a missing username %j",async value=>{
 await mount("recovery");await fillRecovery();await fill("Username",value);await press("Recover and set new password");expect(text()).toContain("Enter your username and the recovery key first.");expect(vault.isUnlocked()).toBe(false);
});
it("Native recovery clears a prior status while a corrected attempt is pending",async()=>{
 await mount("recovery");await press("Recover and set new password");expect(text()).toContain("Enter your username and the recovery key first.");await fillRecovery();let entered=false,release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);nativeBoundary=async path=>{if(path.endsWith("/auth/recover")){entered=true;await held;}};
 await press("Recover and set new password");await vi.waitFor(()=>expect(entered).toBe(true));expect(text()).not.toContain("Enter your username and the recovery key first.");expect(text()).toContain("Verifying…");release();await complete();
});
it("a Native crypto failure with empty diagnostic text retains the calm recovery error",async()=>{
 vi.spyOn(engine,"pbkdf2").mockImplementationOnce((_password,_salt,_cost,_length,_hash,done)=>queueMicrotask(()=>done(new DOMException("","OperationError"))));await mount("recovery");await fillRecovery();await press("Recover and set new password");await vi.waitFor(()=>expect(text()).toContain("Recovery did not complete."));expect(vault.isUnlocked()).toBe(false);
});
it.each(["abcde2468024","ABCDE2468024"])("Native registration preserves the three-class policy for %j",async password=>{
 await mount("login");await press("New here? Create an account");await fill("Username",NAME);await fill("Password",password);await fill("Confirm password",password);await act(async()=>root!.root.findByType(Switch).props.onValueChange(true));await press("Create account");expect(Alert.alert.mock.lastCall?.[1]).toContain("at least three character types");expect(vault.isUnlocked()).toBe(false);
});
it("a held Native recovery response cannot unlock after its screen is retired",async()=>{
 let entered=false,release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);nativeBoundary=async path=>{if(path.endsWith("/auth/recover")){entered=true;await held;}};await mount("recovery");await fillRecovery();await press("Recover and set new password");await vi.waitFor(()=>expect(entered).toBe(true));await act(async()=>{root!.unmount();root=undefined;});release();await new Promise(resolve=>setTimeout(resolve,500));await flush();expect(vault.isUnlocked()).toBe(false);expect(await api.isLoggedIn()).toBe(false);expect(reset).toBe(0);
});
it("an already retired Native sign-in event preserves a finite radio failure for the next live attempt",async()=>{
 await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);const queued=button("Sign in").props.onPress;await act(async()=>{root!.unmount();root=undefined;});const nativeFetch=globalThis.fetch;let refused=false;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(!refused&&new URL(url).pathname.endsWith("/auth/salt")){refused=true;throw new TypeError("Native radio temporarily unavailable");}return nativeFetch(url,init);});
 await act(async()=>{await queued();});await flush();Alert.alert.mockClear();await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await press("Sign in");await vi.waitFor(()=>expect(Alert.alert.mock.calls.length>0||vault.isUnlocked()).toBe(true),{timeout:15000});expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.lastCall?.[0]).toBe("Sign in failed");
});
it.each(Array.from({length:18},(_,index)=>index+1))("Native login completion delivery phase %i preserves a replacement account and its physical key",async turns=>{
 let replacement:Promise<void>|undefined;const replacementKey=Buffer.alloc(32,11);
 nativeCompletion=path=>{if(path.endsWith("/auth/login"))deliver(turns,()=>{replacement=api.setSession("replacement Native bearer",OTHER,"bob").then(()=>vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.from(replacementKey)},OTHER));});};
 await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await vi.waitFor(()=>expect(replacement).toBeDefined());await replacement;await flush();expect(await api.getUserId()).toBe(OTHER);expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(replacementKey);
});
it("a registration retired while its Native progress answer is held cannot enqueue onboarding for the replacement account",async()=>{
 let entered=false,release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);nativeBoundary=async path=>{if(path.endsWith("/insights")){entered=true;await held;}};await mount("login");await press("New here? Create an account");await fill("Username",NAME);await fill("Password",PASSWORD);await fill("Confirm password",PASSWORD);await act(async()=>root!.root.findByType(Switch).props.onValueChange(true));let pending!:Promise<void>;await act(async()=>{pending=button("Create account").props.onPress();});await vi.waitFor(()=>expect(entered).toBe(true),{timeout:15000});await act(async()=>{root!.unmount();root=undefined;});await api.setSession("replacement Native registered bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,11)},OTHER);release();await pending;await flush();expect(takePendingOnboarding()).toBe(false);expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,11));
});
it("a recovered Native session's delayed route cannot navigate the replacement account",async()=>{
 let route="Recovery";await mount("recovery",{navigate:(next:string)=>{route=next;}});await fillRecovery();await press("Recover and set new password");await complete();await api.setSession("replacement recovered Native bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,11)},OTHER);await new Promise(resolve=>setTimeout(resolve,1000));expect(route).toBe("Recovery");expect(vault.ownerUserId()).toBe(OTHER);
});

it.each(["aaaaa A longer phrase","A longer phrase aaaaa"])("the public password policy preserves valid passphrases with repeated edge characters %j",password=>{expect(passwordPolicyError(password)).toBe("");});
it("a Native cold-start login completes an actual prepared local rotation after online credential verification",async()=>{
 const old=Buffer.alloc(32,14);await api.setSession("prior Native bearer",USER,NAME);vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,13),dataKey:Buffer.from(old)},USER);await recordMood(old,USER,"2026-10-05",0.5);await prepareLocalRekey(USER,old,DATA);expect(await pendingLocalRekey(USER)).toBe(true);vault.lock();await api.clearSession();runTestControl(__resetLocalKeyLifecycleForTests);await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await flush();expect(vault.isUnlocked(),JSON.stringify(Alert.alert.mock.calls)+text()).toBe(true);expect(vault.get().dataKey).toEqual(DATA);expect(await pendingLocalRekey(USER)).toBe(false);expect(await recentMoods(DATA,USER,30)).toContainEqual({date:"2026-10-05",value:0.5});await recordMood(DATA,USER,"2026-10-04",0.75);expect(await recentMoods(DATA,USER,30)).toContainEqual({date:"2026-10-04",value:0.75});
});
it("a Native divergent local rotation remains authenticated and locked with honest continuation guidance",async()=>{
 const old=Buffer.alloc(32,14);await api.setSession("prior Native bearer",USER,NAME);vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,13),dataKey:Buffer.from(old)},USER);await recordMood(old,USER,"2026-10-05",0.5);await prepareLocalRekey(USER,old,DATA);await storage.setItem(accountStorageKey.moodLog(USER),"Native interrupted replacement");vault.lock();await api.clearSession();runTestControl(__resetLocalKeyLifecycleForTests);await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await flush();expect(await pendingLocalRekey(USER)).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(text()).toContain("Native session loggedIn unlocked=false");expect(Alert.alert.mock.lastCall?.[1]).toContain("A password change was interrupted.");for(const label of ["Password"]){expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel===label)!.props.value).toBe("");}expect(await storage.getItem(accountStorageKey.moodLog(USER))).toBe("Native interrupted replacement");
});
it("the Native legacy recovery selector announces the selected insecure compatibility mode",async()=>{await mount("recovery");await press("Use a legacy v1 kit (sends its key to your server)");expect(button("Legacy v1 selected — tap to use v2").props.disabled).toBe(false);});
it("a Native rejected recovery request gives local failure copy instead of provider details",async()=>{recoveryScheme="v1";await mount("recovery");await fillRecovery();await press("Recover and set new password");await vi.waitFor(()=>expect(text()).toContain("Recovery did not complete."));expect(text()).not.toContain("recovery refused");expect(vault.isUnlocked()).toBe(false);});
it("the Native recovery route from login reaches the public navigation receiver",async()=>{let route="Login";await mount("login",{navigate:(next:string)=>{route=next;}});await press("Forgot password? Use a recovery key");expect(route).toBe("Recovery");});
it.each(["not a server address","http://api.example:8000"])("the Native server editor refuses %j with calm local guidance",async address=>{await mount("login");await press("Change server");await fill("Selected server address",address);await press("Save server");await vi.waitFor(()=>expect(Alert.alert.mock.calls.length).toBeGreaterThan(0));expect(Alert.alert.mock.lastCall?.[0]).toBe("Invalid URL");expect(Alert.alert.mock.lastCall?.[1]).toContain("Enter a full URL like");expect(await getBaseUrl()).toBe("http://localhost:8000");expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Selected server address")?.props.value).toBe(address);});
it("the Native server editor initializes the selected address from the actual saved origin",async()=>{await mount("login");await press("Change server");const editor=root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Selected server address")!;expect(editor.props.value).toBe("http://localhost:8000");expect(editor.props.autoCorrect).toBe(false);expect(editor.props.spellCheck).toBe(false);});

it.each(["derivation","registration derivation","registration envelope","login envelope"]as const)("Native %s completion erases retired owned keys across provider event delivery",async stage=>{
 for(const turns of [0,1,2,3,4,5,6,7,8]){
  if(root){await act(async()=>root!.unmount());root=undefined;}vi.restoreAllMocks();vault.lock();await api.clearSession();storage.__reset();keychain.__reset();runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);await setBaseUrl("http://localhost:8000");installServer();
  await mount("login");const registration=stage.startsWith("registration");if(registration)await press("New here? Create an account");await fill("Username",NAME);await fill("Password",PASSWORD);if(registration){await fill("Confirm password",PASSWORD);await act(async()=>root!.root.findByType(Switch).props.onValueChange(true));}const witness=nativeKeyCustody(stage,turns);await act(async()=>{await button(registration?"Create account":"Sign in").props.onPress();});await witness.finish();await flush();expect(witness.triggered).toBe(true);expect(witness.owned.size).toBeGreaterThan(0);expect([...witness.owned].every(key=>key.every(byte=>byte===0)),`${stage} Native event delivery ${turns} erases every owned key`).toBe(true);expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,11));
 }
});

it("a retained Native recovery tap cannot replace the completed recovery confirmation",async()=>{await mount("recovery");await fillRecovery();const queued=button("Recover and set new password").props.onPress;await press("Recover and set new password");await complete();await act(async()=>queued());await flush();expect(text()).toContain("Recovered. Your journal is unlocked");expect(text()).not.toContain("Enter your username and the recovery key first.");expect(reset).toBe(1);});
it("a Native failed recovery attempt releases its synchronous admission guard for a corrected attempt",async()=>{recoveryScheme="v1";await mount("recovery");await fillRecovery();await press("Recover and set new password");await vi.waitFor(()=>expect(text()).toContain("Recovery did not complete."));await press("Use a legacy v1 kit (sends its key to your server)");await press("Recover and set new password");await complete();expect(reset).toBe(1);expect(text()).toContain("Recovered. Your journal is unlocked");});
it("an already retired Native recovery tap preserves finite provider availability for the next live attempt",async()=>{
 await mount("recovery");await fillRecovery();const queued=button("Recover and set new password").props.onPress;await act(async()=>{root!.unmount();root=undefined;});const nativeFetch=globalThis.fetch;let refused=false;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(!refused&&new URL(url).pathname.endsWith("/auth/recover")){refused=true;throw new TypeError("Native recovery radio temporarily unavailable");}return nativeFetch(url,init);});await act(async()=>queued());await flush();await mount("recovery");await fillRecovery();await press("Recover and set new password");await vi.waitFor(()=>expect(text().includes("Recovery did not complete.")||vault.isUnlocked()).toBe(true),{timeout:15000});expect(vault.isUnlocked()).toBe(false);expect(text()).toContain("Recovery did not complete.");
});
it("a Native pending-rotation read retired by replacement cannot publish its old alert",async()=>{
 await api.setSession("prior Native bearer",USER,NAME);vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,13),dataKey:Buffer.alloc(32,14)},USER);await prepareLocalRekey(USER,Buffer.alloc(32,14),DATA);vault.lock();await api.clearSession();runTestControl(__resetLocalKeyLifecycleForTests);let entered=false,release!:()=>void;const held=new Promise<void>(resolve=>release=resolve),read=storage.getItem,journal=accountStorageKey.localRekey("http://localhost:8000",USER);vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key===journal&&!entered){entered=true;await held;}return value;});const nativeFetch=globalThis.fetch;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>new URL(url).pathname.endsWith("/auth/key-envelope")?response(url,{invalid:"Native unrecognized envelope"}):nativeFetch(url,init));await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);let pending!:Promise<void>;await act(async()=>{pending=button("Sign in").props.onPress();});await vi.waitFor(()=>expect(entered).toBe(true),{timeout:15000});await api.setSession("replacement Native bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,11)},OTHER);Alert.alert.mockClear();release();await pending;await flush();expect(Alert.alert.mock.calls).toEqual([]);expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,11));
});

it.each(["login","recovery"]as const)("two retained Native %s taps preserve the admitted attempt and its provider answer",async screen=>{
 const target=screen==="login"?"/auth/salt":"/auth/recover";let entered=false,release!:()=>void,requests=0;const held=new Promise<void>(resolve=>release=resolve);nativeBoundary=async path=>{if(path.endsWith(target)){entered=true;await held;}};const nativeFetch=globalThis.fetch;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>new URL(url).pathname.endsWith(target)&&++requests>1?response(url,{detail:"Native duplicate challenge refused"},503):nativeFetch(url,init));await mount(screen);if(screen==="login"){await fill("Username",NAME);await fill("Password",PASSWORD);}else await fillRecovery();const queued=button(screen==="login"?"Sign in":"Recover and set new password").props.onPress;let first:Promise<void>|undefined,second:Promise<void>|undefined;await act(async()=>{first=queued();second=queued();});await vi.waitFor(()=>expect(entered).toBe(true));await flush();expect(Alert.alert.mock.calls).toEqual([]);expect(text()).not.toContain("Recovery did not complete.");release();await first;await second;await complete();expect(vault.get().dataKey).toEqual(DATA);if(screen==="recovery")expect(reset).toBe(1);
});
it("the Native registration age attestation starts unconfirmed and keeps the account action disabled",async()=>{await mount("login");await press("New here? Create an account");await fill("Username",NAME);await fill("Password",PASSWORD);await fill("Confirm password",PASSWORD);expect(root!.root.findByType(Switch).props.value).toBe(false);expect(button("Create account").props.disabled).toBe(true);expect(vault.isUnlocked()).toBe(false);});
it("the Native pending-rotation recovery guidance retains its honest dialog title",async()=>{
 const old=Buffer.alloc(32,14);await api.setSession("prior Native bearer",USER,NAME);vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,13),dataKey:Buffer.from(old)},USER);await recordMood(old,USER,"2026-10-05",0.5);await prepareLocalRekey(USER,old,DATA);await storage.setItem(accountStorageKey.moodLog(USER),"Native interrupted replacement");vault.lock();await api.clearSession();runTestControl(__resetLocalKeyLifecycleForTests);await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await flush();expect(Alert.alert.mock.lastCall?.[0]).toBe("Could not change password");
});

it.each(["late old answer","late read failure"])("Native initial server lookup cannot overwrite a confirmed edit after %s",async outcome=>{
 await api.confirmCurrentOrigin();let initial=true,reached=false,release!:()=>void;const held=new Promise<void>(resolve=>release=resolve),read=storage.getItem;vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/base_url"&&initial){reached=true;await held;if(outcome==="late read failure")throw new TypeError("Native initial origin lookup unavailable");}return value;});await mount("login");expect(reached).toBe(true);await press("Change server");await fill("Selected server address","http://127.0.0.1:8181");initial=false;await press("Save server");await vi.waitFor(async()=>expect(await getBaseUrl()).toBe("http://127.0.0.1:8181"));await flush();expect(text()).toContain("This server is different from the one you usually sign in to.");expect(text()).toContain("Server: http://127.0.0.1:8181");release();await flush();expect(text()).toContain("This server is different from the one you usually sign in to.");expect(text()).toContain("Server: http://127.0.0.1:8181");
});
it("a Native login whose rotation-index read fails retains sign-in failure instead of inventing pending recovery",async()=>{
 const read=storage.getItem,journal=accountStorageKey.localRekey("http://localhost:8000",USER);vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(key===journal)throw new TypeError("Native checkpoint storage unavailable");return read(key);});await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await flush();expect(vault.isUnlocked()).toBe(false);expect(text()).toContain("Native session loggedOut unlocked=false");expect(Alert.alert.mock.lastCall?.[0]).toBe("Sign in failed");expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Password")!.props.value).toBe(PASSWORD);
});
it("Native Login renders the retained scratch-erasure failure from the actual cold-start provider",async()=>{
 const path=files.cacheDirectory+"mindpattern-voice-playback/native-retained/voice.m4a";files.__seedFile(path);const remove=files.deleteAsync.getMockImplementation()!;vi.spyOn(files,"deleteAsync").mockImplementation(async(uri,options)=>{if(uri.endsWith("mindpattern-voice-playback/"))throw new TypeError("Native scratch is unavailable");return remove(uri,options);});await mount("login");expect(text()).toContain("This device has not finished removing deleted-account data");expect(files.__hasFile(path)).toBe(true);const warning=root!.root.findAllByType(Text).find(node=>node.props.accessibilityRole==="alert"&&String(node.props.children).includes("deleted-account"))!;expect(warning).toBeDefined();expect(warning.props.style).toMatchObject({color:"#d98a80"});
});
it("the first Native Login commit has no selected-server label or changed-server warning before lookup",async()=>{
 let first:string|undefined;function NativeCommit(){React.useLayoutEffect(()=>{first=text();},[]);return null;}await act(async()=>{root=ReactTestRenderer.create(<SessionProvider><LoginScreen navigation={{navigate:()=>undefined}}/><NativeCommit/>{React.createElement(sessionState)}</SessionProvider>);});await flush();expect(first).toBeDefined();expect(first).not.toContain("Server:");expect(first).not.toContain("This server is different from the one you usually sign in to.");expect(text()).toContain("Server: http://localhost:8000");
});
it("a Native current-server lookup failure does not invent a changed-origin warning",async()=>{
 await api.confirmCurrentOrigin();const read=storage.getItem;vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(key==="@mindpattern/base_url")throw new TypeError("Native initial server lookup unavailable");return read(key);});await mount("login");expect(text()).not.toContain("This server is different from the one you usually sign in to.");
});
it("Native server editing erases the visible registration password confirmation",async()=>{
 await mount("login");await press("New here? Create an account");await fill("Password",PASSWORD);await fill("Confirm password",PASSWORD);await press("Change server");await fill("Selected server address","http://127.0.0.1:8181");await press("Save server");await vi.waitFor(async()=>expect(await getBaseUrl()).toBe("http://127.0.0.1:8181"));await flush();for(const label of ["Password","Confirm password"])expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel===label)!.props.value).toBe("");expect(root!.root.findAllByType(TextInput).some(node=>node.props.accessibilityLabel==="Selected server address")).toBe(false);
});
it("an accepted Native registration with a retained account checkpoint clears both secrets and offers authenticated recovery",async()=>{
 const old=Buffer.alloc(32,14);await api.setSession("prior Native bearer",USER,NAME);vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,13),dataKey:Buffer.from(old)},USER);await prepareLocalRekey(USER,old,DATA);vault.lock();await api.clearSession();runTestControl(__resetLocalKeyLifecycleForTests);await mount("login");await press("New here? Create an account");await fill("Username",NAME);await fill("Password",PASSWORD);await fill("Confirm password",PASSWORD);await act(async()=>root!.root.findByType(Switch).props.onValueChange(true));await act(async()=>{await button("Create account").props.onPress();});await flush();expect(vault.isUnlocked()).toBe(false);expect(text()).toContain("Native session loggedIn unlocked=false");expect(Alert.alert.mock.lastCall?.[0]).toBe("Could not change password");expect(Alert.alert.mock.lastCall?.[1]).toContain("A password change was interrupted.");for(const label of ["Password","Confirm password"])expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel===label)!.props.value).toBe("");
});
it("a retired Native sign-in credential read preserves a finite checkpoint failure for the next live sign-in",async()=>{
 let armed=false,entered=false,release!:()=>void;const held=new Promise<void>(resolve=>release=resolve),read=storage.getItem,journal=accountStorageKey.localRekey("http://localhost:8000",USER);let outage=true,old=true;vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(armed&&key==="@mindpattern/user_id"){armed=false;entered=true;await held;}if(key===journal&&outage){outage=false;throw new TypeError("Native checkpoint is temporarily unavailable");}return value;});const fetch=globalThis.fetch;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(old&&new URL(url).pathname.endsWith("/auth/key-envelope")){armed=true;return response(url,{invalid:"Native unrecognized envelope"});}return fetch(url,init);});await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);let pending!:Promise<void>;await act(async()=>{pending=button("Sign in").props.onPress();});await vi.waitFor(()=>expect(entered).toBe(true),{timeout:15000});await act(async()=>{root!.unmount();root=undefined;});await api.setSession("replacement Native bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,11)},OTHER);release();await pending;old=false;await api.clearSession();vault.lock();Alert.alert.mockClear();await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await flush();expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.lastCall?.[0]).toBe("Sign in failed");
});

it("a Native pre-credential radio failure cannot authenticate a retained cold-start rotation checkpoint",async()=>{
 const old=Buffer.alloc(32,14);await api.setSession("prior Native bearer",USER,NAME);vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,13),dataKey:Buffer.from(old)},USER);await prepareLocalRekey(USER,old,DATA);vault.lock();runTestControl(__resetLocalKeyLifecycleForTests);
 const path=files.cacheDirectory+"mindpattern-voice-playback/native-retained/voice.m4a";files.__seedFile(path);const remove=files.deleteAsync.getMockImplementation()!;files.deleteAsync.mockImplementation(async(uri,options)=>{if(uri.endsWith("mindpattern-voice-playback/"))throw new TypeError("Native scratch is unavailable");return remove(uri,options);});
 const nativeFetch=globalThis.fetch;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>new URL(url).pathname.endsWith("/auth/salt")?response(url,{detail:"Native radio temporarily unavailable"},503):nativeFetch(url,init));
 await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await flush();expect(text()).toContain("Native session loggedOut unlocked=false");expect(Alert.alert.mock.lastCall?.[0]).toBe("Sign in failed");expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Password")!.props.value).toBe(PASSWORD);expect(files.__hasFile(path)).toBe(true);
});

it.each(Array.from({length:15},(_,index)=>index))("Native checkpoint completion phase %i cannot unlock a retired sign-in",async turns=>{
 const journal=accountStorageKey.localRekey("http://localhost:8000",USER),read=storage.getItem;let retirement:Promise<void>|undefined,triggered=false;vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key===journal&&!triggered){triggered=true;deliver(turns,()=>{retirement=api.clearSession();vault.lock();});}return value;});
 await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await vi.waitFor(()=>expect(retirement).toBeDefined());await retirement;await flush();expect(vault.isUnlocked()).toBe(false);expect(await api.isLoggedIn()).toBe(false);
});

it.each([20,21,22])("Native legacy proof completion phase %i clears accepted credentials before a subsequent session retirement",async turns=>{
 const write=storage.setItem;let retirement:Promise<void>|undefined;vi.spyOn(storage,"setItem").mockImplementation(async(key,value)=>{await write(key,value);if(key===accountStorageKey.unlockProof(USER))deliver(turns,()=>{retirement=api.clearSession();vault.lock();});});
 const nativeFetch=globalThis.fetch;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>new URL(url).pathname.endsWith("/auth/key-envelope")?response(url,{detail:"Native legacy endpoint absent"},404):nativeFetch(url,init));await mount("login");await fill("Username",NAME);await fill("Password",PASSWORD);await act(async()=>{await button("Sign in").props.onPress();});await retirement;await flush();expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Password")!.props.value).toBe("");expect(vault.isUnlocked()).toBe(false);expect(await api.isLoggedIn()).toBe(false);
});
