/** Accessible editing activates the actual SessionProvider's five-minute idle deadline. */
import React from "react";
import ReactTestRenderer,{act} from "react-test-renderer";
import {beforeEach,afterEach,it,expect,vi} from "vitest";
import {Text,TextInput,TouchableOpacity,ScrollView,View} from "react-native";
import {AudioModule,__resetAudioMock} from "../helpers/expoAudioMock";
import {api} from "../../src/api/client";
import {SessionProvider,useSession,takeStashedDraft} from "../../src/store";
import {EntryScreen} from "../../src/screens/EntryScreen";
import {ThemeProvider} from "../../src/theme";
import {vault} from "../../src/vault";
import {secureStore,setSecureStoreBackend} from "../../src/secureStore";
import {__resetLocalKeyLifecycleForTests,installLocalDataKey} from "../../src/localWriteGuard";
import {__resetJournalDraftRuntimeForTests,waitJournalDraftWrites} from "../../src/journalDraft";
import {runTestControl} from "../helpers/testControl";
import {accountStorageKey} from "../../src/accountStorage";
import {clearThresholdNotice} from "../../src/thresholdNotice";
import {t as tr} from "../../src/strings";
import storage from "../helpers/storageMock";
import * as keychain from "../helpers/keychainMock";
const USER="a".repeat(32),KEY=Buffer.alloc(32,86);
const thresholdReleases:Array<()=>void>=[];
let nativeActiveDays:number,nativeUnlockDays:number,nativeInsightsStatus:number;
let root:ReturnType<typeof ReactTestRenderer.create>|undefined,session:ReturnType<typeof useSession>;
function Probe(){session=useSession();return <Text accessibilityLabel="Native editor session state">{JSON.stringify({auth:session.authStatus,unlocked:session.unlocked,loading:session.activeDaysLoading})}</Text>;}
function state(){return JSON.parse(root!.root.findAllByType(Text).find(n=>n.props.accessibilityLabel==="Native editor session state")!.props.children);}
async function press(label:string){const button=root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel===label)!;expect(button,label).toBeDefined();await act(async()=>button.props.onPress());}
beforeEach(async()=>{
 vi.useRealTimers();vi.restoreAllMocks();nativeActiveDays=3;nativeUnlockDays=30;nativeInsightsStatus=200;__resetAudioMock();storage.__reset();keychain.__reset();runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);runTestControl(__resetJournalDraftRuntimeForTests);takeStashedDraft(USER);vault.lock();await api.setSession("Native editor idle bearer",USER,"alice");await clearThresholdNotice(USER);vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,85),dataKey:Buffer.from(KEY)},USER);installLocalDataKey(USER,vault.get().dataKey);
 vi.stubGlobal("fetch",async(url:string)=>{const path=new URL(url).pathname;let value:unknown={};if(path.endsWith("/meta"))value={unlock_days:nativeUnlockDays};else if(path.endsWith("/insights"))value=nativeInsightsStatus===200?{phase:"baseline",active_days:nativeActiveDays,days_remaining:nativeUnlockDays-nativeActiveDays}:{error:{code:"server_error",message:"The Native progress provider is temporarily unavailable"}};else throw new Error("Unexpected Native editor idle route "+path);const response=new Response(JSON.stringify(value),{status:path.endsWith("/insights")?nativeInsightsStatus:200});Object.defineProperty(response,"url",{value:url});return response;});
});
afterEach(async()=>{vi.useRealTimers();for(const release of thresholdReleases.splice(0))release();if(root){await act(async()=>root!.unmount());root=undefined;}await waitJournalDraftWrites();vi.restoreAllMocks();vault.lock();await api.clearSession();vi.unstubAllGlobals();});
it.each(["typing","open details","close details","mood","energy","sleep","tag","starter","microphone","summary"])("the actual Native vault stays open while %s is activated accessibly",async action=>{
 await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><SessionProvider><Probe/><EntryScreen navigation={{navigate:()=>{},addListener:()=>()=>{}}}/></SessionProvider></ThemeProvider>);});await vi.waitFor(()=>expect(state()).toEqual({auth:"loggedIn",unlocked:true,loading:false}));await vi.waitFor(()=>expect(root!.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==="Journal entry")?.props.editable).toBe(true));if(["close details","mood","energy","sleep","tag","summary"].includes(action))await press("Add details (optional)");if(action==="summary"){await press("Mood: Good");await press("Hide details");}if(action==="microphone")AudioModule.requestRecordingPermissionsAsync.mockResolvedValueOnce({granted:false});vi.useFakeTimers();await act(async()=>vi.advanceTimersByTimeAsync(120000));if(action==="typing")await act(async()=>root!.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==="Journal entry")!.props.onChangeText("These are independently owned native editing words"));else if(action==="starter")await act(async()=>root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel?.startsWith("Start with:"))!.props.onPress());else if(action==="summary")await act(async()=>root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel?.startsWith("Details added:"))!.props.onPress());else if(action==="microphone")await press("Record instead");else if(action==="screen touch")await act(async()=>root!.root.findAllByType(View).find(n=>typeof n.props.onTouchStart==="function")!.props.onTouchStart());else await press(({"open details":"Add details (optional)","close details":"Hide details",mood:"Mood: Good",energy:"Energy: Energized",sleep:"Sleep: Rested",tag:"Tag: work"}as Record<string,string>)[action]);await act(async()=>vi.advanceTimersByTimeAsync(180000));expect(state().unlocked).toBe(true);await act(async()=>vi.advanceTimersByTimeAsync(120000));expect(state().unlocked).toBe(false);expect(vault.isUnlocked()).toBe(false);
});

function renderedWords(){const flat=(v:unknown):string=>Array.isArray(v)?v.map(flat).join(""):typeof v==="string"||typeof v==="number"?String(v):"";return root!.root.findAllByType(Text).map(n=>flat(n.props.children)).join(" ");}
async function mountProgressEditor(){await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><SessionProvider><Probe/><EntryScreen navigation={{navigate:()=>{},addListener:()=>()=>{}}}/></SessionProvider></ThemeProvider>);});await vi.waitFor(()=>expect(state()).toEqual({auth:"loggedIn",unlocked:true,loading:false}));await vi.waitFor(()=>expect(renderedWords()).not.toContain("Loading device draft"));}
it("a public progress retry obtains a real Native receipt and shows the actual metadata threshold card only once",async()=>{
 nativeInsightsStatus=500;nativeUnlockDays=15;await mountProgressEditor();await vi.waitFor(()=>expect(renderedWords()).toContain(tr("entry.progressUnavailable")));expect(root!.root.findAllByType(View).filter(n=>n.props.accessibilityRole==="progressbar")).toHaveLength(0);expect(renderedWords()).not.toContain(tr("entry.readyBody",{days:15}));nativeInsightsStatus=200;nativeActiveDays=15;await press(tr("entry.progressRetry"));await vi.waitFor(()=>expect(renderedWords()).toContain(tr("entry.readyBody",{days:15})));expect(root!.root.findAllByType(View).find(n=>n.props.accessibilityRole==="progressbar")!.props.accessibilityValue).toEqual({min:0,max:15,now:15});await vi.waitFor(async()=>expect(await secureStore.getItem(accountStorageKey.thresholdNotice(USER))).toBe("1"));await press(tr("entry.dismissReadyA11y"));expect(renderedWords()).not.toContain(tr("entry.readyBody",{days:15}));await act(async()=>root!.unmount());root=undefined;await waitJournalDraftWrites();await mountProgressEditor();expect(renderedWords()).not.toContain(tr("entry.readyBody",{days:15}));
});
it("a failed actual Native threshold-stamp write still shows the card and keeps writing available",async()=>{
 nativeActiveDays=30;const write=storage.setItem.bind(storage);vi.spyOn(storage,"setItem").mockImplementation(async(slot,value)=>{if(slot===accountStorageKey.thresholdNotice(USER))throw new Error("The Native threshold store exhausted its capacity");return write(slot,value);});await mountProgressEditor();await vi.waitFor(()=>expect(renderedWords()).toContain(tr("entry.readyBody",{days:30})));await act(async()=>root!.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==="Journal entry")!.props.onChangeText("Writing remains available while the Native stamp cannot persist"));expect(renderedWords()).toContain(tr("entry.readyBody",{days:30}));await press(tr("entry.dismissReadyA11y"));expect(renderedWords()).not.toContain(tr("entry.readyBody",{days:30}));
});

it("an unmounted actual Native threshold read cannot consume the card's first presentation receipt",async()=>{
 nativeActiveDays=30;let entered=false,release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});thresholdReleases.push(release);const read=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await read(slot);if(first&&slot===accountStorageKey.thresholdNotice(USER)){first=false;entered=true;await held;}return value;});await mountProgressEditor();await vi.waitFor(()=>expect(entered).toBe(true));expect(renderedWords()).not.toContain(tr("entry.readyBody",{days:30}));await act(async()=>root!.unmount());root=undefined;await waitJournalDraftWrites();release();await act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});expect(await read(accountStorageKey.thresholdNotice(USER))).toBeNull();vi.restoreAllMocks();await mountProgressEditor();await vi.waitFor(()=>expect(renderedWords()).toContain(tr("entry.readyBody",{days:30})));
});
it("actual retained Native progress cannot announce a threshold card after the physical account receipt disappeared before editor mount",async()=>{
 nativeActiveDays=30;await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><SessionProvider><Probe/></SessionProvider></ThemeProvider>);});await vi.waitFor(()=>expect(state()).toEqual({auth:"loggedIn",unlocked:true,loading:false}));await vi.waitFor(()=>expect(session.activeDaysKnown).toBe(true));await secureStore.removeItem("@mindpattern/user_id");await act(async()=>{root!.update(<ThemeProvider><SessionProvider><Probe/><EntryScreen navigation={{navigate:()=>{},addListener:()=>()=>{}}}/></SessionProvider></ThemeProvider>);});await act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});expect(renderedWords()).not.toContain(tr("entry.readyBody",{days:30}));expect(await secureStore.getItem(accountStorageKey.thresholdNotice(USER))).toBeNull();expect(await secureStore.getItem(accountStorageKey.thresholdNotice("null"))).toBeNull();
});
