/** Actual credential/HTTP/AES feedback and single-use processing receipts. */
import React from "react";
import ReactTestRenderer,{act as reactAct} from "react-test-renderer";
import {beforeEach,afterEach,it,expect,vi} from "vitest";
import {Alert,Text,TouchableOpacity} from "react-native";
import {api} from "../../src/api/client";
import {QuestionScreen} from "../../src/screens/QuestionScreen";
import {ThemeProvider} from "../../src/theme";
import {vault} from "../../src/vault";
import {encrypt,decrypt,buildAad} from "../../src/crypto/envelope";
import {recordPatternMute} from "../../src/questionFeedback";
import {accountStorageKey} from "../../src/accountStorage";
import {installLocalDataKey,__resetLocalKeyLifecycleForTests} from "../../src/localWriteGuard";
import {secureStore,setSecureStoreBackend} from "../../src/secureStore";
import {runTestControl} from "../helpers/testControl";
import {nativeGrantedPress} from "../helpers/nativePressability";
import {publicSurface} from "../helpers/publicSurface";
import {assertPublicSurface} from "../helpers/publicSurfaceOracle";
import {setFlagsFromString} from "node:v8";
import {engine} from "../../src/crypto/engine";
import {prepareLocalRekey} from "../../src/localRekey";
import {runInNewContext} from "node:vm";
import storage from "../helpers/storageMock";
import * as keychain from "../helpers/keychainMock";
import {setLocale,t as tr} from "../../src/strings";
import {peekDraft,stashDraft,takeStashedDraft} from "../../src/store";
const USER="a".repeat(32),OTHER="b".repeat(32),KEY=Buffer.alloc(32,61),NEXT=Buffer.alloc(32,62),DATE="2026-09-11",QUESTION="Which native moment changed the course of your day?";
const session={touchActivity:()=>{},unlockDays:30};
vi.mock("../../src/store",async original=>({...await original<typeof import("../../src/store")>(),useSession:()=>session}));
let root:ReturnType<typeof ReactTestRenderer.create>|undefined;
let surfaceStage=0;
async function act<T>(operation:()=>T|Promise<T>){await reactAct(operation);if(root)assertPublicSurface(publicSurface(root),++surfaceStage);}
let destination:string;
let nativeQuestionKey:Buffer,nativeQuestionText:string;
let summary:unknown,questionStatus:number,recomputeFailure:string|undefined,insightsStatus:number,storedPid:unknown;
let recomputeBoundary:(()=>Promise<void>)|undefined;
let processing:Map<string,Buffer>,deliveredKeys:Buffer[],consumedFeedback:unknown[];
const releases:Array<()=>void>=[];
const flush=async()=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});
function words(){const flat=(v:unknown):string=>Array.isArray(v)?v.map(flat).join(""):typeof v==="string"||typeof v==="number"?String(v):"";return root!.root.findAllByType(Text).map(n=>flat(n.props.children)).join(" ");}
async function press(label:string){const node=root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel===label);expect(node,label).toBeDefined();await act(async()=>{await node!.props.onPress();});await flush();}
async function alertButton(label:string){const node=vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.find(n=>n.text===label);expect(node,label).toBeDefined();await act(async()=>{await node!.onPress?.();});await flush();}
async function mount(){await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><QuestionScreen navigation={{navigate:(route:string)=>{destination=route;}}}/></ThemeProvider>);});await flush();}
function hold(){let entered=false,release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve;});releases.push(release);return{run:async()=>{entered=true;await pending;},entered:()=>entered,release};}
beforeEach(async()=>{
 surfaceStage=0;
 vi.useRealTimers();vi.restoreAllMocks();setLocale("en");storage.__reset();keychain.__reset();runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);vault.lock();await api.setSession("native question bearer",USER,"alice");vault.unlock({masterKey:Buffer.alloc(32,63),authKey:Buffer.alloc(32,64),dataKey:Buffer.from(KEY)},USER);installLocalDataKey(USER,vault.get().dataKey);
 nativeQuestionKey=KEY;nativeQuestionText=QUESTION;recomputeBoundary=undefined;summary={phase:"insight",active_days:40,days_remaining:0};insightsStatus=200;storedPid="topic:native-question";questionStatus=200;recomputeFailure=undefined;processing=new Map();deliveredKeys=[];consumedFeedback=[];destination="Question";takeStashedDraft(USER);takeStashedDraft(OTHER);vi.mocked(Alert.alert).mockClear();
 vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const path=new URL(url).pathname;let value:unknown={},status=200;
  if(path.endsWith("/insights")){status=insightsStatus;value=status===200?summary:{code:"service_unavailable",detail:"The Native pattern provider is unavailable"};}
  else if(path.endsWith("/questions/today")){status=questionStatus;value=status===200?{for_date:DATE,blob:encrypt(nativeQuestionKey,Buffer.from(JSON.stringify({for_date:DATE,question:nativeQuestionText,pattern_pid:storedPid})),buildAad("question",USER,DATE)).toString("base64")}:{code:"not_found",detail:"No Native question has been stored"};}
  else if(path.endsWith("/processing/sessions")){const key=Buffer.from(JSON.parse(String(init.body)).data_key,"base64"),token="native-session-"+deliveredKeys.length;deliveredKeys.push(key);processing.set(token,key);value={session_token:token};}
  else if(path.endsWith("/insights/recompute")){const token=new Headers(init.headers).get("X-Processing-Token")!,key=processing.get(token);processing.delete(token);if(!key){status=403;value={code:"processing_session_invalid",detail:"The Native key receipt has been consumed"};}else if(recomputeFailure){status=400;value={code:recomputeFailure,detail:"The Native feedback receipt was rejected"};recomputeFailure=undefined;}else{const body=init.body?JSON.parse(String(init.body)):{};if(body.feedback_blob)consumedFeedback.push(JSON.parse(decrypt(key,Buffer.from(body.feedback_blob,"base64"),buildAad("feedback",USER,new Date().toISOString().slice(0,10))).toString("utf8")));questionStatus=200;value={question_stored:true};}}
  else throw new Error("Unexpected Native question route "+path);
  const response=new Response(JSON.stringify(value),{status});Object.defineProperty(response,"url",{value:url});if(path.endsWith("/insights/recompute")){const read=response.json.bind(response);response.json=async()=>{const answer=await read();await recomputeBoundary?.();return answer;};}return response;
 });
});
afterEach(async()=>{for(const release of releases.splice(0))release();await flush();if(root){await act(async()=>root!.unmount());root=undefined;}vi.restoreAllMocks();vault.lock();await api.clearSession();vi.unstubAllGlobals();});
it("a Native stored question decrypts using the server's own date without a processing key shipment",async()=>{await mount();expect(words()).toContain(QUESTION);expect(deliveredKeys).toEqual([]);expect(processing.size).toBe(0);expect(vi.mocked(Alert.alert).mock.calls).toEqual([]);});
it.each([true,false])("a Native feedback answer resonated=%s persists its independent encrypted receipt",async resonated=>{
 await mount();await press(resonated?"This question resonated with me":"This question does not land for me");const raw=await storage.getItem(accountStorageKey.feedback(USER));expect(raw).toBeTruthy();expect(JSON.parse(decrypt(KEY,Buffer.from(raw!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated}]);expect(words()).toContain(resonated?"Noted — questions like this":"Noted — this one");
});
it("a pending Native feedback answer cannot append an old question into a replacement key's receipt",async()=>{
 await mount();const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(slot==="@mindpattern/user_id"&&first){first=false;await held.run();}return value;});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));
 vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);await recordPatternMute(NEXT,USER,"replacement-pattern",false);const before=await storage.getItem(accountStorageKey.feedback(USER));held.release();await flush();expect(await storage.getItem(accountStorageKey.feedback(USER))).toBe(before);expect(words()).not.toContain("Noted — questions like this");
});
it("a retired Native consent dialog cannot authorize shipment of a replacement account's key",async()=>{
 questionStatus=404;await mount();await press("Show today's question");expect(vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.some(n=>n.text==="Continue")).toBe(true);await api.setSession("replacement Native bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},OTHER);installLocalDataKey(OTHER,vault.get().dataKey);await alertButton("Continue");await flush();expect(deliveredKeys).toEqual([]);expect(await storage.getItem(accountStorageKey.keyShipmentConsent(OTHER))).toBeNull();
});
it("a Native acknowledged consent sends the actual key once and consumes independently decryptable feedback",async()=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"topic:native-feedback",true);await mount();await press("Show today's question");expect(deliveredKeys).toEqual([]);await alertButton("Continue");await flush();expect(deliveredKeys).toEqual([KEY]);expect(consumedFeedback).toEqual([{feedback:[],muted:["topic:native-feedback"],unmuted:[]}]);expect(processing.size).toBe(0);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();expect(words()).toContain(QUESTION);
});
it("a Native rejected feedback token is consumed and recovery uses a fresh single-use key receipt",async()=>{
 questionStatus=404;recomputeFailure="feedback_blob_invalid";await recordPatternMute(KEY,USER,"topic:invalid-feedback",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();await press("Show today's question");await flush();expect(words()).toContain(QUESTION);expect(deliveredKeys).toEqual([KEY,KEY]);expect(processing.size).toBe(0);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();
});
it("finite Native progress counts cannot overflow the baseline day counter or caption",async()=>{
 summary={phase:"baseline",active_days:1e308,days_remaining:1e308};await mount();expect(words()).not.toContain("Infinity");expect(words()).toContain("30 days");
});
it("a Native question bridge places the shown question in this account's editor",async()=>{
 await mount();await press("Write about this question");expect(peekDraft(USER)).toBe(QUESTION);expect(destination).toBe("Entry");
});
it.each([false,true])("a pending Native question bridge preserves replacement account writing after unmount=%s",async unmount=>{
 await mount();const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(slot==="@mindpattern/user_id"&&first){first=false;await held.run();}return value;});await press("Write about this question");await vi.waitFor(()=>expect(held.entered()).toBe(true));
 vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);stashDraft(USER,"Replacement writing belongs to the new account context");if(unmount){await act(async()=>root!.unmount());root=undefined;}held.release();await flush();expect(peekDraft(USER)).toBe("Replacement writing belongs to the new account context");expect(destination).toBe("Question");
});
it("a held Native processing-origin read cannot ship a retired key into replacement credentials",async()=>{
 questionStatus=404;await mount();await press("Show today's question");const held=hold(),get=storage.getItem.bind(storage);let first=true;vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(slot==="@mindpattern/base_url"&&first){first=false;await held.run();}return value;});await alertButton("Continue");await vi.waitFor(()=>expect(held.entered()).toBe(true));
 await api.setSession("replacement Native bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},OTHER);installLocalDataKey(OTHER,vault.get().dataKey);held.release();await flush();expect(deliveredKeys).toEqual([]);expect(processing.size).toBe(0);
});
it("replacement Native vault keys clear the previous question and its confirmation disclosure",async()=>{
 await mount();await press("This question resonated with me");expect(words()).toContain("Noted — questions like this");await act(async()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);});await flush();expect(words()).not.toContain(QUESTION);expect(words()).not.toContain("Noted — questions like this");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(false);expect(root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(false);
});
it("a Native auth-key adoption keeps the still-owned question visible",async()=>{
 await mount();await act(async()=>vault.adoptAuthKey(Buffer.alloc(32,65)));await flush();expect(words()).toContain(QUESTION);expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);
});
it("a finite Native feedback-write refusal leaves an honest retry and the old receipt intact",async()=>{
 await recordPatternMute(KEY,USER,"an earlier Native event",true);const slot=accountStorageKey.feedback(USER),before=await storage.getItem(slot);await mount();const write=storage.setItem.bind(storage);let refuse=true;vi.spyOn(storage,"setItem").mockImplementation(async(k,v)=>{if(k===slot&&refuse)throw new Error("Native feedback store is full");return write(k,v);});await press("This question resonated with me");expect(await storage.getItem(slot)).toBe(before);expect(words()).toContain("could not be saved just now");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);refuse=false;await press("This question does not land for me");const current=await storage.getItem(slot);expect(JSON.parse(decrypt(KEY,Buffer.from(current!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"an earlier Native event",mute:true},{pid:"topic:native-question",resonated:false}]);expect(words()).toContain("Noted — this one");
});
it.each(["active_days","days_remaining"] as const)("an overflowed Native %s count cannot appear in baseline progress",async field=>{
 summary={phase:"baseline",active_days:4,days_remaining:26,[field]:Number.POSITIVE_INFINITY};await mount();expect(words()).not.toContain("Infinity");expect(words()).not.toContain("Day ");expect(words()).toContain("30 days");
});
it.each([null,"26",{},[]])("a Native malformed remaining count %j cannot manufacture a day counter",async value=>{
 summary={phase:"baseline",active_days:4,days_remaining:value};await mount();expect(words()).not.toContain("Day 4 of");expect(words()).toContain("30 days");
});

it.each([401,500])("a genuine Native question HTTP %s refusal cannot fall through to a key shipment",async code=>{
 questionStatus=code;await mount();expect(words()).not.toContain(QUESTION);expect(deliveredKeys).toEqual([]);expect(processing.size).toBe(0);expect(root!.root.findAllByType(Text).some(n=>n.props.accessibilityRole==="alert")).toBe(true);expect(vi.mocked(Alert.alert).mock.calls).toEqual([]);
});
it("a genuine Native insight outage stays on the error path without a baseline invention",async()=>{
 insightsStatus=500;await mount();expect(words()).not.toContain("Day ");expect(words()).not.toContain(QUESTION);expect(deliveredKeys).toEqual([]);expect(root!.root.findAllByType(Text).some(n=>n.props.accessibilityRole==="alert")).toBe(true);
});
it("an absent Native account cannot decrypt or recompute the shown question",async()=>{
 await secureStore.removeItem("@mindpattern/user_id");await mount();expect(words()).not.toContain(QUESTION);expect(deliveredKeys).toEqual([]);expect(root!.root.findAllByType(Text).some(n=>n.props.accessibilityRole==="alert")).toBe(true);expect(vi.mocked(Alert.alert).mock.calls.length).toBeGreaterThan(0);
});
it.each([null,17,""])("a Native question with pid=%j cannot persist a false pattern feedback receipt",async pid=>{
 storedPid=pid;await mount();expect(words()).toContain(QUESTION);if(pid===""){await press("This question resonated with me");expect(words()).not.toContain("Noted —");}else expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(false);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();
});
it("an in-flight Native feedback tap removes the answer controls until its receipt commits",async()=>{
 await mount();const held=hold(),write=storage.setItem.bind(storage);let first=true;vi.spyOn(storage,"setItem").mockImplementation(async(slot,value)=>{if(first&&slot===accountStorageKey.feedback(USER)){first=false;await held.run();}return write(slot,value);});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me"||n.props.accessibilityLabel==="This question does not land for me")).toBe(false);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();held.release();await flush();expect(words()).toContain("Noted — questions like this");expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true}]);
});

it("a stale but authentic Native account-id receipt cannot attribute this question to another account",async()=>{
 await mount();await secureStore.setItem("@mindpattern/user_id",OTHER);await press("This question resonated with me");expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();expect(await storage.getItem(accountStorageKey.feedback(OTHER))).toBeNull();expect(words()).not.toContain("Noted —");expect(words()).toContain("could not be saved just now");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);
});
it("a Native account mismatch at consent admission produces an honest refusal without key shipment",async()=>{
 questionStatus=404;await mount();await secureStore.setItem("@mindpattern/user_id",OTHER);await press("Show today's question");expect(deliveredKeys).toEqual([]);expect(processing.size).toBe(0);expect(words()).toContain("match");expect(vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.some(n=>n.text==="Continue")).not.toBe(true);
});
it("a Native account-id refusal at feedback admission restores an honest retry",async()=>{
 await mount();const get=secureStore.getItem.bind(secureStore);vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{if(slot==="@mindpattern/user_id")throw new Error("The Native Keychain provider is temporarily unavailable");return get(slot);});await press("This question resonated with me");expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();expect(words()).toContain("could not be saved just now");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);
});
it("an unmounted Native question cannot retain a newly obtained processing key after the origin await",async()=>{
 questionStatus=404;await mount();await press("Show today's question");const held=hold(),get=storage.getItem.bind(storage);let first=true;vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/base_url"){first=false;await held.run();}return value;});await alertButton("Continue");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>root!.unmount());root=undefined;held.release();await flush();expect(processing.size).toBe(0);expect(deliveredKeys).toEqual([]);
});

it("a missing actual Native account receipt leaves this feedback tap available for an honest retry",async()=>{
 await mount();await secureStore.removeItem("@mindpattern/user_id");await press("This question resonated with me");expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();expect(words()).toContain("could not be saved just now");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);
});

it("a Native recompute can acknowledge only its consumed receipt while a later public feedback tap remains queued",async()=>{
 await recordPatternMute(KEY,USER,"the earlier consumed Native event",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold();recomputeBoundary=held.run;questionStatus=404;await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));expect(consumedFeedback).toEqual([{feedback:[],muted:["the earlier consumed Native event"],unmuted:[]}]);await press("This question resonated with me");expect(words()).toContain("Noted — questions like this");held.release();await flush();expect(words()).toContain(QUESTION);const pending=await storage.getItem(accountStorageKey.feedback(USER));expect(pending).toBeTruthy();expect(JSON.parse(decrypt(KEY,Buffer.from(pending!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true}]);
});
it("a missing Native account receipt after consent leaves the exact current-session refusal without shipment",async()=>{
 questionStatus=404;await mount();await press("Show today's question");await secureStore.removeItem("@mindpattern/user_id");await alertButton("Continue");await flush();expect(deliveredKeys).toEqual([]);expect(processing.size).toBe(0);expect(words()).toContain(tr("common.sessionDamagedTitle"));expect(vi.mocked(Alert.alert).mock.calls.at(-1)?.[0]).toBe(tr("question.loadFailedTitle"));expect(root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(false);
});
it("a newly published Native account receipt after consent cannot adopt the retained old-vault question key",async()=>{
 questionStatus=404;await mount();await press("Show today's question");await secureStore.setItem("@mindpattern/user_id",OTHER);await alertButton("Continue");await flush();expect(deliveredKeys).toEqual([]);expect(processing.size).toBe(0);expect(words()).toContain(tr("common.sessionDamagedTitle"));expect(vault.ownerUserId()).toBe(USER);expect(vault.get().dataKey).toEqual(KEY);
});
it("a retained Native feedback tap cannot adopt a newer same-key credential lifetime",async()=>{
 await mount();const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();}return value;});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));await api.setSession("new Native same-key credential receipt",USER,"alice");held.release();await flush();expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();expect(words()).not.toContain("Noted —");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);await press("This question does not land for me");expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:false}]);
});
it("a late Native feedback-write completion cannot acknowledge the next question",async()=>{
 await mount();const held=hold(),write=storage.setItem.bind(storage);let first=true;vi.spyOn(storage,"setItem").mockImplementation(async(slot,value)=>{await write(slot,value);if(first&&slot===accountStorageKey.feedback(USER)){first=false;await held.run();}});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));nativeQuestionText="The next Native question has not yet been answered";storedPid="topic:next-native-question";await press(tr("question.refresh"));held.release();await flush();expect(words()).toContain(nativeQuestionText);expect(words()).not.toContain("Noted —");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true}]);
});
it.each([false,true])("a Native recompute with no feedback blob preserves a later public answer after refusal=%s",async refuse=>{
 await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold();recomputeBoundary=held.run;questionStatus=404;if(refuse)recomputeFailure="feedback_blob_invalid";await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));expect(consumedFeedback).toEqual([]);await press("This question resonated with me");const slot=accountStorageKey.feedback(USER),before=await storage.getItem(slot);expect(before).toBeTruthy();held.release();await flush();expect(await storage.getItem(slot)).toBe(before);expect(JSON.parse(decrypt(KEY,Buffer.from(before!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true}]);expect(words()).toContain(QUESTION);
});
it("a consent result and the next Native activation delivered before one commit still ship one processing key",async()=>{
 questionStatus=404;await mount();await press("Show today's question");const callback=vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.find(n=>n.text==="Continue")!.onPress!,button=root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==="Show today's question")!,gesture=nativeGrantedPress(button.props),held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();}return value;});try{await act(async()=>{callback();gesture.release();});await vi.waitFor(()=>expect(held.entered()).toBe(true));await flush();expect(deliveredKeys).toEqual([]);held.release();await flush();expect(deliveredKeys).toEqual([KEY]);expect(words()).toContain(QUESTION);}finally{gesture.dispose();held.release();}
});
it("a Native account-key transition clears a visible failed question request",async()=>{
 questionStatus=500;await mount();expect(root!.root.findAllByType(Text).some(n=>n.props.accessibilityRole==="alert")).toBe(true);await act(async()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);});expect(root!.root.findAllByType(Text).some(n=>n.props.accessibilityRole==="alert")).toBe(false);expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="Show today's question")).toBe(true);
});
it("a Native account-key transition clears the previous baseline writing prompt",async()=>{
 summary={phase:"baseline",active_days:3,days_remaining:27};await mount();expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel===tr("question.refresh"))).toBe(true);await act(async()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);});expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="Show today's question")).toBe(true);expect(words()).not.toContain("Day 3 of");
});
it.each(["load","processing"] as const)("a retired Native %s finishes the unchanged question view's busy state after credential renewal",async stage=>{
 await mount();if(stage==="processing"){questionStatus=404;await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");}const held=hold(),get=secureStore.getItem.bind(secureStore);let ordinal=0;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(slot==="@mindpattern/user_id"&&++ordinal===(stage==="processing"?5:1)){await held.run();}return value;});await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));expect(root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel===tr("question.refresh"))!.props.disabled).toBe(true);await api.setSession("the renewed Native question credential",USER,"alice");held.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel===tr("question.refresh"))!.props.disabled).toBe(false);await press(tr("question.refresh"));expect(words()).toContain(QUESTION);expect(deliveredKeys).toEqual(stage==="processing"?[KEY]:[]);
});
it("a completed Native question visit releases its retired view allocation",async()=>{
 await mount();const retired=new WeakRef(root!.root.findByType(QuestionScreen));await act(async()=>{root!.unmount();root=undefined;});setFlagsFromString("--expose-gc");const collect=runInNewContext("gc") as ()=>void;let retained=true;for(let attempt=0;attempt<5;attempt++){await new Promise(resolve=>setTimeout(resolve,0));collect();retained=retired.deref()!==undefined;if(!retained)break;}expect(retained).toBe(false);
});
it("an old Native feedback refusal cannot replace the new key's acknowledged answer or restore its already-used controls",async()=>{
 await mount();const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();}return value;});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));
 await act(async()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);});nativeQuestionKey=NEXT;nativeQuestionText="The replacement Native question belongs to this key";await press("Show today's question");expect(words()).toContain(nativeQuestionText);await press("This question does not land for me");expect(words()).toContain("Noted — this one");held.release();await flush();expect(words()).toContain("Noted — this one");expect(words()).not.toContain("could not be saved just now");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me"||n.props.accessibilityLabel==="This question does not land for me")).toBe(false);expect(JSON.parse(decrypt(NEXT,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:false}]);
});
it("newly published Native credentials cannot attribute the retained old-vault question's feedback to the new account",async()=>{
 await mount();await api.setSession("new Native OTHER credential receipt",OTHER,"bob");expect(vault.ownerUserId()).toBe(USER);await press("This question resonated with me");expect(await storage.getItem(accountStorageKey.feedback(OTHER))).toBeNull();expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();expect(words()).toContain("could not be saved just now");expect(words()).not.toContain("Noted —");
});
it("an unrelated Native recompute rejection preserves its feedback receipt and never consumes a second processing key",async()=>{
 questionStatus=404;recomputeFailure="processing_session_invalid";await recordPatternMute(KEY,USER,"the owned Native pending event",true);const before=await storage.getItem(accountStorageKey.feedback(USER));await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();await press("Show today's question");expect(deliveredKeys).toEqual([KEY]);expect(processing.size).toBe(0);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBe(before);expect(words()).not.toContain(QUESTION);expect(root!.root.findAllByType(Text).some(n=>n.props.accessibilityRole==="alert")).toBe(true);
});
it("the actually recomputed Native question exposes its new pattern's answer controls and persists their receipt",async()=>{
 questionStatus=404;await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();await press("Show today's question");expect(words()).toContain(QUESTION);await press("This question resonated with me");expect(words()).toContain("Noted — questions like this");expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true}]);
});
it("a Native Android question answer delivers the enabled ten-millisecond physical feedback pulse",async()=>{
 const {Platform,Vibration}=await import("react-native"),{setHapticsEnabled}=await import("../../src/haptics");const prior=Platform.OS,pulses:unknown[]=[];try{Object.defineProperty(Platform,"OS",{configurable:true,value:"android"});vi.mocked(Vibration.vibrate).mockImplementation(value=>{pulses.push(value);});await setHapticsEnabled(true);await mount();await press("This question resonated with me");expect(pulses).toEqual([10]);expect(words()).toContain("Noted — questions like this");}finally{Object.defineProperty(Platform,"OS",{configurable:true,value:prior});}
});
it("a failed fresh Native retry still quarantines exactly the feedback receipt refused before that retry",async()=>{
 questionStatus=404;recomputeFailure="feedback_blob_invalid";let first=true;recomputeBoundary=async()=>{if(first){first=false;recomputeFailure="processing_session_invalid";}};await recordPatternMute(KEY,USER,"the refused Native receipt",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();await press("Show today's question");expect(deliveredKeys).toEqual([KEY,KEY]);expect(words()).not.toContain(QUESTION);expect(root!.root.findAllByType(Text).some(n=>n.props.accessibilityRole==="alert")).toBe(true);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();
});
it("a retained Native feedback append cannot commit after the same-key question view unmounts during its actual receipt read",async()=>{
 await mount();const held=hold(),get=storage.getItem.bind(storage);let first=true;vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const wire=await get(slot);if(first&&slot===accountStorageKey.feedback(USER)){first=false;await held.run();}return wire;});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>root!.unmount());root=undefined;expect(vault.get().dataKey).toEqual(KEY);held.release();await flush();expect(await get(accountStorageKey.feedback(USER))).toBeNull();
});
it("a retired Native question cannot send or consume feedback obtained after its encrypted receipt read completes",async()=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"the still-pending Native feedback",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");const slot=accountStorageKey.feedback(USER),before=await storage.getItem(slot);await mount();const held=hold(),get=storage.getItem.bind(storage);let first=true;vi.spyOn(storage,"getItem").mockImplementation(async key=>{const wire=await get(key);if(first&&key===slot){first=false;await held.run();}return wire;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));expect(deliveredKeys).toEqual([KEY]);await act(async()=>root!.unmount());root=undefined;held.release();await flush();expect(consumedFeedback).toEqual([]);expect(await get(slot)).toBe(before);
});
it("two Native question activations delivered in one frame admit only one processing key shipment",async()=>{
 questionStatus=404;await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const button=root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==="Show today's question")!,first=nativeGrantedPress(button.props),second=nativeGrantedPress(button.props);try{await act(async()=>{first.release();second.release();});await flush();expect(words()).toContain(QUESTION);expect(deliveredKeys).toEqual([KEY]);expect(processing.size).toBe(0);}finally{first.dispose();second.dispose();}
});
it("a newly stored Native question restores its own answer controls after an older question was acknowledged",async()=>{
 await mount();await press("This question resonated with me");nativeQuestionText="The newer Native question asks about today's support";storedPid="topic:new-native-question";await press(tr("question.refresh"));expect(words()).toContain(nativeQuestionText);expect(words()).not.toContain("Noted — questions like this");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);await press("This question does not land for me");expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true},{pid:"topic:new-native-question",resonated:false}]);
});
it("two Native answer releases in one frame persist only the first acknowledgment for this question",async()=>{
 await mount();const buttons=root!.root.findAllByType(TouchableOpacity),first=nativeGrantedPress(buttons.find(n=>n.props.accessibilityLabel==="This question resonated with me")!.props),second=nativeGrantedPress(buttons.find(n=>n.props.accessibilityLabel==="This question does not land for me")!.props);try{await act(async()=>{first.release();second.release();});await flush();expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true}]);expect(words()).toContain("Noted — questions like this");}finally{first.dispose();second.dispose();}
});
it("an old Native answer cannot acknowledge or hide the replacement question after its account read completes",async()=>{
 await mount();const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();}return value;});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));nativeQuestionText="This replacement Native question needs its own answer";storedPid="topic:replacement-question";await press(tr("question.refresh"));held.release();await flush();expect(words()).toContain(nativeQuestionText);expect(words()).not.toContain("Noted —");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();
});
it.each([
 ["processing request origin","processing","@mindpattern/base_url",2],
 ["processing bearer","processing","@mindpattern/token",1],
 ["processing owner","processing","@mindpattern/user_id",2],
 ["processing username","processing","@mindpattern/username",1],
 ["recompute origin","recompute","@mindpattern/base_url",1],
 ["recompute bearer","recompute","@mindpattern/token",1],
 ["recompute owner","recompute","@mindpattern/user_id",1],
 ["recompute username","recompute","@mindpattern/username",1],
] as const)("the retired question refuses Native %s delivery before feedback consumption",async(_label,phase,slot,occurrence)=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"the owned Native boundary receipt",true);const feedbackSlot=accountStorageKey.feedback(USER),before=await storage.getItem(feedbackSlot);await mount();await press("Show today's question");const held=hold(),get=storage.getItem.bind(storage);let ordinal=0;vi.spyOn(storage,"getItem").mockImplementation(async name=>{const value=await get(name);if(name===slot&&(phase==="processing"||deliveredKeys.length===1)&&++ordinal===occurrence)await held.run();return value;});await alertButton("Continue");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>root!.unmount());root=undefined;held.release();await flush();expect(deliveredKeys).toEqual(phase==="processing"?[]:[KEY]);expect(consumedFeedback).toEqual([]);expect(await get(feedbackSlot)).toBe(before);
});
it.each([
 ["processing","headers"],["processing","body"],["recompute","headers"],["recompute","body"],
] as const)("the retired question does not clear pending feedback after Native %s %s delivery",async(phase,stage)=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"the unacknowledged Native response receipt",true);const slot=accountStorageKey.feedback(USER),before=await storage.getItem(slot);await mount();await press("Show today's question");const held=hold(),nativeFetch=globalThis.fetch;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args),path=new URL(String(args[0])).pathname;if(path.endsWith(phase==="processing"?"/processing/sessions":"/insights/recompute")){if(stage==="headers")await held.run();else{const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();return value;};}}return response;});await alertButton("Continue");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>root!.unmount());root=undefined;held.release();await flush();expect(deliveredKeys).toEqual([KEY]);expect(await storage.getItem(slot)).toBe(before);expect(consumedFeedback).toHaveLength(phase==="processing"?0:1);
});
it("the retired question does not quarantine feedback or ship a retry key after a late Native refusal",async()=>{
 questionStatus=404;recomputeFailure="feedback_blob_invalid";await recordPatternMute(KEY,USER,"the refused but retired Native receipt",true);const slot=accountStorageKey.feedback(USER),before=await storage.getItem(slot);await mount();await press("Show today's question");const held=hold();recomputeBoundary=held.run;await alertButton("Continue");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>root!.unmount());root=undefined;held.release();await flush();expect(deliveredKeys).toEqual([KEY]);expect(await storage.getItem(slot)).toBe(before);
});
it("the first Native question frame admits an explicit load without an invented busy state",async()=>{
 let initialDisabled:unknown;function Parent(){React.useLayoutEffect(()=>{initialDisabled=root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel==="Show today's question")!.props.disabled;},[]);return <QuestionScreen navigation={{navigate:()=>{}}}/>;}await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><Parent/></ThemeProvider>);});await flush();expect(initialDisabled).toBe(false);expect(words()).toContain(QUESTION);
});
it("refreshing the same stored Native question preserves its existing acknowledgment and used controls",async()=>{
 await mount();await press("This question resonated with me");const slot=accountStorageKey.feedback(USER),before=await storage.getItem(slot);await press(tr("question.refresh"));expect(words()).toContain(QUESTION);expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(false);expect(await storage.getItem(slot)).toBe(before);
});
it.each(["text","pid"] as const)("a stored Native question with a changed %s gets an independent answer",async field=>{
 await mount();await press("This question resonated with me");if(field==="text")nativeQuestionText="A changed Native question with the same pattern";else storedPid="topic:a-different-native-pattern";await press(tr("question.refresh"));expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);await press("This question does not land for me");expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true},{pid:storedPid,resonated:false}]);
});
it("a second Native recompute may ask the same words while admitting its own new answer",async()=>{
 questionStatus=404;await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();await press("Show today's question");await press("This question resonated with me");questionStatus=404;await press(tr("question.refresh"));expect(deliveredKeys).toEqual([KEY,KEY]);expect(words()).not.toContain("Noted —");expect(root!.root.findAllByType(TouchableOpacity).some(n=>n.props.accessibilityLabel==="This question resonated with me")).toBe(true);await press("This question does not land for me");expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:false}]);
});
it.each(Array.from({length:32},(_,i)=>i+1))("a Native processing completion retired after %i handoffs leaves the replacement question's storage lane available",async hops=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"the Native handoff feedback receipt",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold(),blocked=hold(),nativeFetch=globalThis.fetch,get=storage.getItem.bind(storage),slot=accountStorageKey.feedback(USER);let retired=false,replacement=false,lane:Promise<unknown>=Promise.resolve();vi.spyOn(storage,"getItem").mockImplementation(name=>{const obsolete=retired&&!replacement;const pending=lane.then(async()=>{const value=await get(name);if(obsolete&&name===slot)await blocked.run();return value;});lane=pending.then(()=>{},()=>{});return pending;});vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(new URL(String(args[0])).pathname.endsWith("/processing/sessions")){const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{retired=true;reactAct(()=>{root!.unmount();root=undefined;});}};queueMicrotask(step);return value;};}return response;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));held.release();await new Promise(resolve=>setTimeout(resolve,0));expect(retired).toBe(true);replacement=true;questionStatus=200;try{await mount();expect(words()).toContain(QUESTION);}finally{held.release();blocked.release();await flush();}
});
it("a completed Native compute keeps its overlapping phase load visibly busy until that load delivers",async()=>{
 questionStatus=404;await mount();await press("Show today's question");const continued=vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.find(button=>button.text==="Continue")!;
 const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!,gesture=nativeGrantedPress(button.props),phase=hold(),computed=hold(),nativeFetch=globalThis.fetch;
 recomputeBoundary=computed.run;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(new URL(String(args[0])).pathname.endsWith("/insights")){const read=response.json.bind(response);response.json=async()=>{const value=await read();await phase.run();return value;};}return response;});
 try{await act(async()=>{continued.onPress?.();gesture.release();});await vi.waitFor(()=>expect(phase.entered()&&computed.entered()).toBe(true));computed.release();await flush();expect(words()).toContain(QUESTION);expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel===tr("question.refresh"))!.props.disabled).toBe(true);phase.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel===tr("question.refresh"))!.props.disabled).toBe(false);expect(deliveredKeys).toEqual([KEY]);}finally{gesture.dispose();phase.release();computed.release();await flush();}
});
it("an old Native key's completion cannot clear a newer credential-renewed question's pending load",async()=>{
 await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();questionStatus=404;const old=hold(),current=hold(),get=secureStore.getItem.bind(secureStore);let ordinal=0;
 vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(slot==="@mindpattern/user_id"){ordinal++;if(ordinal===5)await old.run();if(ordinal===10)await current.run();}return value;});
 await press(tr("question.refresh"));await vi.waitFor(()=>expect(old.entered()).toBe(true));await act(async()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);});nativeQuestionKey=NEXT;nativeQuestionText="The pending Native replacement question";
 await press("Show today's question");await vi.waitFor(()=>expect(current.entered()).toBe(true));await api.setSession("Native renewed replacement credential",USER,"alice");old.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(true);expect(deliveredKeys).toEqual([]);current.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(false);
});
it("a first-frame Native question activation does not reserve the replacement key's automatic load",async()=>{
 const held=hold(),get=storage.getItem.bind(storage);let initial=true;
 vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(initial&&slot==="@mindpattern/base_url"){initial=false;await held.run();}return value;});
 function Parent(){React.useLayoutEffect(()=>{const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!,gesture=nativeGrantedPress(button.props);gesture.release();gesture.dispose();vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);nativeQuestionKey=NEXT;nativeQuestionText="The automatic Native replacement question";},[]);return <QuestionScreen navigation={{navigate:()=>{}}}/>;}
 try{await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><Parent/></ThemeProvider>);});await flush();expect(held.entered()).toBe(true);expect(words()).toContain(nativeQuestionText);expect(deliveredKeys).toEqual([]);}finally{held.release();await flush();}
});
it("a queued Native answer from the old displayed question cannot append into keys replaced before its frame commits",async()=>{
 await mount();const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="This question resonated with me")!,gesture=nativeGrantedPress(button.props);
 try{await act(async()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);gesture.release();});await flush();expect(words()).not.toContain(QUESTION);expect(await storage.getItem(accountStorageKey.feedback(USER))).toBeNull();expect(words()).not.toContain("Noted —");}finally{gesture.dispose();}
});
it("a question load delivering after the Native vault locks retires quietly without accessing locked keys",async()=>{
 await mount();const held=hold(),get=secureStore.getItem.bind(secureStore),hostEmit=process.emit.bind(process),unhandled:unknown[]=[];vi.spyOn(process,"emit").mockImplementation((event,...args)=>{if(event==="unhandledRejection"){unhandled.push(args[0]);return true;}return hostEmit(event,...args);});let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();}return value;});await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>vault.lock());held.release();await flush();await new Promise(resolve=>setTimeout(resolve,0));expect(unhandled.length).toBe(0);expect(words()).not.toContain(QUESTION);expect(deliveredKeys).toEqual([]);expect(vi.mocked(Alert.alert).mock.calls).toEqual([]);
});
it.each([["stored-question account",2],["consent account",4]] as const)("a retired Native %s delivery leaves the replacement question's credential lane available",async(_label,occurrence)=>{
 questionStatus=404;await mount();const held=hold(),blocked=hold(),secureGet=secureStore.getItem.bind(secureStore),get=storage.getItem.bind(storage);let ordinal=0,retired=false,replacement=false,lane:Promise<unknown>=Promise.resolve();
 vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await secureGet(slot);if(slot==="@mindpattern/user_id"&&++ordinal===occurrence)await held.run();return value;});
 vi.spyOn(storage,"getItem").mockImplementation(slot=>{const obsolete=retired&&!replacement,pending=lane.then(async()=>{const value=await get(slot);if(obsolete)await blocked.run();return value;});lane=pending.then(()=>{},()=>{});return pending;});
 await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>{root!.unmount();root=undefined;});retired=true;held.release();await new Promise(resolve=>setTimeout(resolve,0));replacement=true;questionStatus=200;nativeQuestionText="The replacement Native question has an available provider";
 try{await mount();expect(words()).toContain(nativeQuestionText);expect(deliveredKeys).toEqual([]);}finally{held.release();blocked.release();await flush();}
});
it("a consent read finishing after Native view retirement cannot display its old processing dialog",async()=>{
 questionStatus=404;await mount();const held=hold(),get=storage.getItem.bind(storage);let first=true;vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot===accountStorageKey.keyShipmentConsent(USER)){first=false;await held.run();}return value;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>{root!.unmount();root=undefined;});held.release();await flush();expect(vi.mocked(Alert.alert).mock.calls).toEqual([]);expect(deliveredKeys).toEqual([]);
});
it("a retired Native phase response leaves the replacement question's credential lane available",async()=>{
 questionStatus=404;await mount();const held=hold(),blocked=hold(),nativeFetch=globalThis.fetch,get=storage.getItem.bind(storage);let first=true,retired=false,replacement=false,lane:Promise<unknown>=Promise.resolve();
 vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(first&&new URL(String(args[0])).pathname.endsWith("/insights")){first=false;const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();return value;};}return response;});
 vi.spyOn(storage,"getItem").mockImplementation(slot=>{const obsolete=retired&&!replacement,pending=lane.then(async()=>{const value=await get(slot);if(obsolete)await blocked.run();return value;});lane=pending.then(()=>{},()=>{});return pending;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>{root!.unmount();root=undefined;});retired=true;held.release();await new Promise(resolve=>setTimeout(resolve,0));replacement=true;questionStatus=200;nativeQuestionText="The replacement Native phase can finish reading its question";try{await mount();expect(words()).toContain(nativeQuestionText);}finally{held.release();blocked.release();await flush();}
});
it("a queued Native writing bridge cannot put the old question into the replacement account's editor",async()=>{
 await mount();await api.setSession("Native replacement bridge owner",OTHER,"bob");const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Write about this question")!,gesture=nativeGrantedPress(button.props);
 try{await act(async()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},OTHER);installLocalDataKey(OTHER,vault.get().dataKey);gesture.release();});await flush();expect(peekDraft(OTHER)).toBeNull();expect(peekDraft(USER)).toBeNull();expect(destination).toBe("Question");}finally{gesture.dispose();}
});
it("a credential owner's Native writing bridge cannot reattribute a question still held by another vault owner",async()=>{
 await mount();await api.setSession("Native credential-only bridge replacement",OTHER,"bob");await press("Write about this question");expect(vault.ownerUserId()).toBe(USER);expect(peekDraft(OTHER)).toBeNull();expect(peekDraft(USER)).toBeNull();expect(destination).toBe("Question");
});
it("renewed Native credentials for the same physical question still allow its account-bound editor bridge",async()=>{
 await mount();await api.setSession("Native renewed same-owner writing receipt",USER,"alice");await press("Write about this question");expect(peekDraft(USER)).toBe(QUESTION);expect(peekDraft(OTHER)).toBeNull();expect(destination).toBe("Entry");
});
it.each(["question cipher","processing permit"] as const)("a retired Native %s does not occupy the finite primitive context budget needed by the replacement view",async stage=>{
 await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold(),nativeFetch=globalThis.fetch,get=secureStore.getItem.bind(secureStore);let first=true,ordinal=0;
 if(stage==="question cipher")vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(first&&new URL(String(args[0])).pathname.endsWith("/questions/today")){first=false;const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();return value;};}return response;});
 else{questionStatus=404;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(slot==="@mindpattern/user_id"&&++ordinal===5)await held.run();return value;});}
 await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>{root!.unmount();root=undefined;});
 // Installed HybridCipher.final retains EVP_CIPHER_CTX until the JSI object
 // is collected; HybridHash.digest likewise retains its EVP_MD_CTX. Model
 // eight remaining allocations before the next host collection. WeakRefs
 // release reservations when those actual provider objects are collected.
 // A fresh load needs two requests' three encrypted credential reads, one
 // direct UID read, and its question cipher: eight contexts, no spare.
 const contexts:Array<WeakRef<object>>=[],borrow=<T extends object>(create:()=>T):T=>{if(contexts.filter(ref=>ref.deref()!==undefined).length>=8)throw new Error("The Native primitive context pool is full until collection");const context=create();contexts.push(new WeakRef(context));return context;},decipher=engine.createDecipheriv.bind(engine),hash=engine.createHash.bind(engine);
 vi.spyOn(engine,"createDecipheriv").mockImplementation((...args)=>borrow(()=>decipher(...args)));vi.spyOn(engine,"createHash").mockImplementation((...args)=>borrow(()=>hash(...args)));
 held.release();await new Promise(resolve=>setTimeout(resolve,0));questionStatus=200;nativeQuestionText="The fresh Native question owns the remaining crypto capacity";try{await mount();expect(words()).toContain(nativeQuestionText);expect(deliveredKeys).toEqual([]);}finally{held.release();await flush();}
});
it("an old first-frame Native load cannot clear the replacement key's busy indicator after credential renewal",async()=>{
 const old=hold(),fresh=hold(),get=storage.getItem.bind(storage);let ordinal=0;vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(slot==="@mindpattern/base_url"){if(++ordinal===1)await old.run();else if(ordinal===2)await fresh.run();}return value;});
 function Parent(){React.useLayoutEffect(()=>{const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!,gesture=nativeGrantedPress(button.props);gesture.release();gesture.dispose();vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);nativeQuestionKey=NEXT;},[]);return <QuestionScreen navigation={{navigate:()=>{}}}/>;}
 try{await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><Parent/></ThemeProvider>);});await vi.waitFor(()=>expect(old.entered()&&fresh.entered()).toBe(true));await api.setSession("Native first-frame replacement credential",USER,"alice");old.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(true);fresh.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(false);}finally{old.release();fresh.release();await flush();}
});
it("a granted Native Show release after a same-frame vault lock never exposes a locked-key runtime error",async()=>{
 await mount();const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel===tr("question.refresh"))!,gesture=nativeGrantedPress(button.props),hostEmit=process.emit.bind(process),unhandled:unknown[]=[];
 vi.spyOn(process,"emit").mockImplementation((event,...args)=>{if(event==="unhandledRejection"){unhandled.push(args[0]);return true;}return hostEmit(event,...args);});try{await act(async()=>{vault.lock();gesture.release();});await flush();await new Promise(resolve=>setTimeout(resolve,0));expect(unhandled.length).toBe(0);expect(deliveredKeys).toEqual([]);expect(words()).not.toContain(QUESTION);}finally{gesture.dispose();}
});
it.each(Array.from({length:32},(_,i)=>i+1))("a Native question body retired after %i handoffs never publishes its old decrypted question into replacement keys",async hops=>{
 await mount();const held=hold(),nativeFetch=globalThis.fetch;let first=true,replaced=false;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(first&&new URL(String(args[0])).pathname.endsWith("/questions/today")){first=false;const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{replaced=true;reactAct(()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);});}};queueMicrotask(step);return value;};}return response;});await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));held.release();await flush();expect(replaced).toBe(true);expect(words()).not.toContain(QUESTION);expect(deliveredKeys).toEqual([]);
});
it.each(["error","notice"] as const)("an accepted delayed Native consent result clears the prior %s while its new compute is pending",async kind=>{
 if(kind==="error")questionStatus=404;await mount();questionStatus=404;await press(kind==="error"?"Show today's question":tr("question.refresh"));const continued=vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.find(button=>button.text==="Continue")!;
 if(kind==="error"){insightsStatus=500;await press("Show today's question");insightsStatus=200;expect(root!.root.findAllByType(Text).some(node=>node.props.accessibilityRole==="alert")).toBe(true);}else{await press("This question resonated with me");expect(words()).toContain("Noted — questions like this");}
 const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();}return value;});await act(async()=>continued.onPress?.());await vi.waitFor(()=>expect(held.entered()).toBe(true));expect(root!.root.findAllByType(Text).some(node=>node.props.accessibilityRole==="alert")).toBe(false);expect(words()).not.toContain("Noted —");held.release();await flush();expect(words()).toContain(QUESTION);
});
it.each(Array.from({length:32},(_,i)=>i+1))("a Native feedback refusal retired after %i handoffs leaves the replacement question's feedback lane available",async hops=>{
 questionStatus=404;recomputeFailure="feedback_blob_invalid";await recordPatternMute(KEY,USER,"the Native rejection-handoff receipt",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold(),blocked=hold(),nativeFetch=globalThis.fetch,get=storage.getItem.bind(storage),slot=accountStorageKey.feedback(USER);let retired=false,replacement=false,first=true,lane:Promise<unknown>=Promise.resolve();
 vi.spyOn(storage,"getItem").mockImplementation(name=>{const obsolete=retired&&!replacement,pending=lane.then(async()=>{const value=await get(name);if(obsolete&&name===slot)await blocked.run();return value;});lane=pending.then(()=>{},()=>{});return pending;});
 vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(first&&new URL(String(args[0])).pathname.endsWith("/insights/recompute")){first=false;const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{retired=true;reactAct(()=>{root!.unmount();root=undefined;});}};queueMicrotask(step);return value;};}return response;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));held.release();await new Promise(resolve=>setTimeout(resolve,0));expect(retired).toBe(true);replacement=true;questionStatus=200;nativeQuestionText="The current Native rejection-handoff question";
 try{await mount();await press("This question resonated with me");expect(words()).toContain("Noted — questions like this");}finally{held.release();blocked.release();await flush();}
});
it.each(Array.from({length:32},(_,i)=>i+1))("a Native recomputed question retired after %i body handoffs never publishes its old text into replacement keys",async hops=>{
 await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();questionStatus=404;const held=hold(),nativeFetch=globalThis.fetch;let first=true,replaced=false;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(first&&deliveredKeys.length===1&&new URL(String(args[0])).pathname.endsWith("/questions/today")){first=false;const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{replaced=true;reactAct(()=>{vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32),dataKey:Buffer.from(NEXT)},USER);installLocalDataKey(USER,vault.get().dataKey);});}};queueMicrotask(step);return value;};}return response;});await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));held.release();await flush();expect(replaced).toBe(true);expect(words()).not.toContain(QUESTION);expect(deliveredKeys).toEqual([KEY]);
});
it("a prepared Native key rotation refuses the recompute waiting on its old feedback receipt",async()=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"the old-key Native rotation feedback",true);const slot=accountStorageKey.feedback(USER),before=await storage.getItem(slot);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold(),get=storage.getItem.bind(storage);let first=true;vi.spyOn(storage,"getItem").mockImplementation(async name=>{const raw=await get(name);if(first&&name===slot&&deliveredKeys.length===1){first=false;await held.run();}return raw;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));await prepareLocalRekey(USER,KEY,NEXT);held.release();await flush();expect(consumedFeedback).toEqual([]);expect(deliveredKeys).toEqual([KEY]);expect(await get(slot)).toBe(before);expect(words()).not.toContain(QUESTION);
});
it("Native credential renewal during an accepted feedback commit restores the same question's retry instead of publishing its retired acknowledgment",async()=>{
 await mount();const held=hold(),write=storage.setItem.bind(storage);let first=true;vi.spyOn(storage,"setItem").mockImplementation(async(name,value)=>{await write(name,value);if(first&&name===accountStorageKey.feedback(USER)){first=false;await held.run();}});await press("This question resonated with me");await vi.waitFor(()=>expect(held.entered()).toBe(true));const renewed=api.setSession("Native renewed accepted-feedback credential",USER,"alice");held.release();await renewed;await flush();expect(words()).toContain("could not be saved just now");expect(words()).not.toContain("Noted —");expect(root!.root.findAllByType(TouchableOpacity).some(node=>node.props.accessibilityLabel==="This question resonated with me")).toBe(true);expect(JSON.parse(decrypt(KEY,Buffer.from((await storage.getItem(accountStorageKey.feedback(USER)))!,"base64"),buildAad("feedback-local",USER)).toString("utf8"))).toMatchObject([{pid:"topic:native-question",resonated:true}]);
});

it("two granted Native Show releases before one commit offer one consent dialog",async()=>{
 questionStatus=404;await mount();const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!,first=nativeGrantedPress(button.props),second=nativeGrantedPress(button.props);try{await act(async()=>{first.release();second.release();});await flush();expect(vi.mocked(Alert.alert).mock.calls.filter(call=>call[0]===tr("question.keyShipTitle"))).toHaveLength(1);expect(deliveredKeys).toEqual([]);}finally{first.dispose();second.dispose();}
});
it("a granted Native Show gesture configured while consent computation is busy cannot publish another stored question",async()=>{
 questionStatus=404;await mount();await press("Show today's question");const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!,gesture=nativeGrantedPress(button.props),held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();}return value;});try{await alertButton("Continue");await vi.waitFor(()=>expect(held.entered()).toBe(true));const current=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!;expect(current.props.disabled).toBe(true);gesture.configure(current.props);questionStatus=200;nativeQuestionText="A new stored Native question must wait for the owned computation";await act(async()=>gesture.release());await flush();expect(words()).not.toContain(nativeQuestionText);expect(deliveredKeys).toEqual([]);}finally{held.release();gesture.dispose();await flush();}
});
it("a consent dialog completing after same-key view unmount cannot persist consent for the replacement view",async()=>{
 questionStatus=404;await mount();await press("Show today's question");const continued=vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.find(button=>button.text==="Continue")!;await act(async()=>{root!.unmount();root=undefined;});await act(async()=>continued.onPress?.());await flush();expect(await storage.getItem(accountStorageKey.keyShipmentConsent(USER))).toBeNull();vi.mocked(Alert.alert).mockClear();await mount();await press("Show today's question");expect(vi.mocked(Alert.alert).mock.calls.at(-1)?.[0]).toBe(tr("question.keyShipTitle"));expect(deliveredKeys).toEqual([]);
});
it("a retired Native local account-read failure cannot display a dialog over the replacement view",async()=>{
 await mount();const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const value=await get(slot);if(first&&slot==="@mindpattern/user_id"){first=false;await held.run();throw new Error("The Native credential provider refused the retired read");}return value;});await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));await act(async()=>{root!.unmount();root=undefined;});held.release();await flush();expect(vi.mocked(Alert.alert).mock.calls).toEqual([]);await mount();expect(words()).toContain(QUESTION);
});
it("an old Native loader cannot clear the new credential lifetime's loading indicator",async()=>{
 questionStatus=404;await mount();const old=hold(),fresh=hold(),get=storage.getItem.bind(storage);let ordinal=0;vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const raw=await get(slot);if(slot==="@mindpattern/base_url"){if(++ordinal===1)await old.run();else if(ordinal===2)await fresh.run();}return raw;});const button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!,first=nativeGrantedPress(button.props),second=nativeGrantedPress(button.props);let renewed:Promise<void>=Promise.resolve();try{await act(async()=>{first.release();renewed=api.setSession("Native renewed overlapping loader",USER,"alice");second.release();});await renewed;await vi.waitFor(()=>expect(old.entered()&&fresh.entered()).toBe(true));old.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(true);}finally{old.release();fresh.release();first.dispose();second.dispose();await flush();}
});
it("a frozen Native replacement processing receipt is not consumed by its old-key retry",async()=>{
 questionStatus=404;recomputeFailure="feedback_blob_invalid";await recordPatternMute(KEY,USER,"the rejected Native retry feedback",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold(),nativeFetch=globalThis.fetch;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(deliveredKeys.length===2&&new URL(String(args[0])).pathname.endsWith("/processing/sessions")){const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();return value;};}return response;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));await prepareLocalRekey(USER,KEY,NEXT);held.release();await flush();expect(deliveredKeys).toEqual([KEY,KEY]);expect(processing.size).toBe(1);expect(words()).not.toContain(QUESTION);
});
it("a Native account mismatch in the writing bridge explains the refusal without another account's draft",async()=>{
 await mount();await secureStore.setItem("@mindpattern/user_id",OTHER);await press("Write about this question");expect(vi.mocked(Alert.alert).mock.calls.at(-1)?.slice(0,2)).toEqual([tr("common.sessionDamagedTitle"),tr("question.sessionMismatch")]);expect(peekDraft(OTHER)).toBeNull();expect(destination).toBe("Question");
});
it.each(Array.from({length:32},(_,i)=>i+1))("a Native consumed feedback receipt retired after %i completion handoffs leaves the new question's credential provider available",async hops=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"the consumed Native handoff receipt",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const blocked=hold(),remove=storage.removeItem.bind(storage),get=secureStore.getItem.bind(secureStore),slot=accountStorageKey.feedback(USER);let retired=false,replacement=false,first=true,lane:Promise<unknown>=Promise.resolve();
 vi.spyOn(secureStore,"getItem").mockImplementation(name=>{const obsolete=retired&&!replacement,pending=lane.then(async()=>{const value=await get(name);if(obsolete&&name==="@mindpattern/user_id")await blocked.run();return value;});lane=pending.then(()=>{},()=>{});return pending;});
 vi.spyOn(storage,"removeItem").mockImplementation(async name=>{await remove(name);if(first&&name===slot){first=false;let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{retired=true;reactAct(()=>{root!.unmount();root=undefined;});}};queueMicrotask(step);}});await press("Show today's question");await new Promise(resolve=>setTimeout(resolve,0));expect(retired).toBe(true);replacement=true;nativeQuestionText="The new Native question after consumed feedback owns its credential lane";
 try{await mount();expect(words()).toContain(nativeQuestionText);}finally{blocked.release();await flush();}
});

it("an old Native consent computation cannot clear the new credential lifetime's computation indicator",async()=>{
 questionStatus=404;await mount();await press("Show today's question");const consent=vi.mocked(Alert.alert).mock.calls.at(-1)?.[2]?.find(button=>button.text==="Continue")!,button=root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!,gesture=nativeGrantedPress(button.props),old=hold(),fresh=hold(),get=secureStore.getItem.bind(secureStore),write=storage.setItem.bind(storage);let ordinal=0,first=true;
 vi.spyOn(storage,"setItem").mockImplementation(async(name,value)=>{if(first&&name===accountStorageKey.keyShipmentConsent(USER)){first=false;throw new Error("The Native consent write is temporarily full");}return write(name,value);});vi.spyOn(secureStore,"getItem").mockImplementation(async slot=>{const raw=await get(slot);if(slot==="@mindpattern/user_id"){if(++ordinal===1)await old.run();else if(ordinal===6)await fresh.run();}return raw;});let renewed:Promise<void>=Promise.resolve();try{await act(async()=>{consent.onPress?.();renewed=api.setSession("Native renewed overlapping computation",USER,"alice");gesture.release();});await renewed;await vi.waitFor(()=>expect(old.entered()).toBe(true));await flush();expect(vi.mocked(Alert.alert).mock.calls.filter(call=>call[0]===tr("question.keyShipTitle"))).toHaveLength(2);await alertButton("Continue");await vi.waitFor(()=>expect(fresh.entered()).toBe(true));old.release();await flush();expect(root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel==="Show today's question")!.props.disabled).toBe(true);}finally{old.release();fresh.release();gesture.dispose();await flush();}
});

it("a processing receipt arriving during Native key preparation cannot reserve the feedback read needed by the rotation checkpoint",async()=>{
 questionStatus=404;await recordPatternMute(KEY,USER,"the Native prepared-generation processing receipt",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const body=hold(),origin=hold(),blocked=hold(),nativeFetch=globalThis.fetch;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(new URL(String(args[0])).pathname.endsWith("/processing/sessions")){const read=response.json.bind(response);response.json=async()=>{const value=await read();await body.run();return value;};}return response;});await press("Show today's question");await vi.waitFor(()=>expect(body.entered()).toBe(true));const get=storage.getItem.bind(storage);let first=true,originReleased=false,lane:Promise<unknown>=Promise.resolve();vi.spyOn(storage,"getItem").mockImplementation(name=>{if(first&&name==="@mindpattern/base_url"){first=false;return get(name).then(async value=>{await origin.run();return value;});}if(name===accountStorageKey.feedback(USER)){const unavailable=!originReleased,pending=lane.then(async()=>{const value=await get(name);if(unavailable)await blocked.run();return value;});lane=pending.then(()=>{},()=>{});return pending;}return get(name);});let prepared=false;const transition=prepareLocalRekey(USER,KEY,NEXT).then(()=>{prepared=true;});await vi.waitFor(()=>expect(origin.entered()).toBe(true));body.release();await flush();originReleased=true;origin.release();try{await Promise.race([transition,new Promise(resolve=>setTimeout(resolve,180))]);expect(prepared).toBe(true);expect(processing.size).toBe(1);expect(consumedFeedback).toEqual([]);}finally{body.release();origin.release();blocked.release();await transition;await flush();}
});

it.each(Array.from({length:32},(_,i)=>i+1))("a fresh Native retry processing body at %i handoffs preserves the finite Native request admission boundary",async hops=>{
 questionStatus=404;recomputeFailure="feedback_blob_invalid";await recordPatternMute(KEY,USER,"the Native retry preparation handoff",true);await storage.setItem(accountStorageKey.keyShipmentConsent(USER),"1");await mount();const held=hold(),nativeFetch=globalThis.fetch;let prepared:Promise<void>=Promise.resolve(),started=false;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(deliveredKeys.length===2&&new URL(String(args[0])).pathname.endsWith("/processing/sessions")){const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{started=true;prepared=prepareLocalRekey(USER,KEY,NEXT);}};queueMicrotask(step);return value;};}return response;});await press("Show today's question");await vi.waitFor(()=>expect(held.entered()).toBe(true));held.release();await flush();await prepared;await flush();expect(started).toBe(true);expect(deliveredKeys).toEqual([KEY,KEY]);expect(processing.size).toBe(hops <= 15 ? 1 : 0);expect(consumedFeedback).toEqual([]);expect(words()).not.toContain(QUESTION);
});

it.each(Array.from({length:32},(_,i)=>i+1))("a Native summary body retired after %i handoffs never reserves the next question's credential lane",async hops=>{
 await mount();const held=hold(),blocked=hold(),nativeFetch=globalThis.fetch,get=secureStore.getItem.bind(secureStore);let first=true,retired=false,replacement=false,lane:Promise<unknown>=Promise.resolve();vi.spyOn(secureStore,"getItem").mockImplementation(name=>{const obsolete=retired&&!replacement,pending=lane.then(async()=>{const raw=await get(name);if(obsolete)await blocked.run();return raw;});lane=pending.then(()=>{},()=>{});return pending;});vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(first&&new URL(String(args[0])).pathname.endsWith("/insights")){first=false;const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{retired=true;reactAct(()=>{root!.unmount();root=undefined;});}};queueMicrotask(step);return value;};}return response;});await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));held.release();await new Promise(resolve=>setTimeout(resolve,0));expect(retired).toBe(true);replacement=true;nativeQuestionText="The Native summary-handoff replacement question is available";try{await mount();expect(words()).toContain(nativeQuestionText);}finally{held.release();blocked.release();await flush();}
});
it.each(Array.from({length:32},(_,i)=>i+1))("a Native stored question body retired after %i handoffs leaves its cipher context for the new view",async hops=>{
 await mount();const held=hold(),nativeFetch=globalThis.fetch;let first=true,retired=false;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{const response=await nativeFetch(...args);if(first&&new URL(String(args[0])).pathname.endsWith("/questions/today")){first=false;const read=response.json.bind(response);response.json=async()=>{const value=await read();await held.run();let remaining=hops;const step=()=>{if(--remaining>0)queueMicrotask(step);else{retired=true;reactAct(()=>{root!.unmount();root=undefined;});const contexts:Array<WeakRef<object>>=[],borrow=<T extends object>(create:()=>T):T=>{if(contexts.filter(ref=>ref.deref()!==undefined).length>=8)throw new Error("The Native cipher pool is full until collection");const context=create();contexts.push(new WeakRef(context));return context;},decipher=engine.createDecipheriv.bind(engine),hash=engine.createHash.bind(engine);vi.spyOn(engine,"createDecipheriv").mockImplementation((...args)=>borrow(()=>decipher(...args)));vi.spyOn(engine,"createHash").mockImplementation((...args)=>borrow(()=>hash(...args)));}};queueMicrotask(step);return value;};}return response;});await press(tr("question.refresh"));await vi.waitFor(()=>expect(held.entered()).toBe(true));held.release();await new Promise(resolve=>setTimeout(resolve,0));expect(retired).toBe(true);nativeQuestionText="The Native cipher-handoff replacement question has capacity";try{await mount();expect(words()).toContain(nativeQuestionText);}finally{held.release();await flush();}
});
