import React from "react";
import crypto from "node:crypto";
import ReactTestRenderer,{act} from "react-test-renderer";
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { Alert,TextInput,TouchableOpacity } from "react-native";
import { UnlockScreen } from "../../src/screens/UnlockScreen";
import { ThemeProvider } from "../../src/theme";
import { SessionProvider } from "../../src/store";
import { vault } from "../../src/vault";
import { api,DEFAULT_BASE_URL } from "../../src/api/client";
import { secureStore,setSecureStoreBackend } from "../../src/secureStore";
import { __resetLocalKeyLifecycleForTests } from "../../src/localWriteGuard";
import { runTestControl } from "../helpers/testControl";
import storage from "../helpers/storageMock";
import * as files from "../helpers/expoFsMock";
import * as keychain from "../helpers/keychainMock";
import { engine } from "../helpers/nodeEngine";
import { storeUnlockProof,verifyUnlockProof } from "../../src/unlockProof";
import { enableBiometricUnlock,hasBiometricUnlock } from "../../src/biometricUnlock";
import { unlockFailureCount,recordUnlockFailure } from "../../src/unlockBackoff";
import { cacheEnvelope,cachedEnvelope } from "../../src/keyScheme";
import { accountStorageKey } from "../../src/accountStorage";
import { prepareLocalRekey,pendingLocalRekey,markLocalRekeyPhase,resumeLocalRekey } from "../../src/localRekey";
import { publicSurface } from "../helpers/publicSurface";
import { assertPublicSurface } from "../helpers/publicSurfaceOracle";

// The Native stack mounts only its first route; AppNavigator retains its real
// session branch and screen lifetime. No screen/controller is substituted.
vi.mock("@react-navigation/native-stack",async()=>{
 const React=await import("react");
 const first=(children:any):any=>{for(const child of React.Children.toArray(children)){if(React.isValidElement(child)){if(child.type===React.Fragment){const found=first((child.props as any).children);if(found)return found;}else return child;}}return null;};
 return {createNativeStackNavigator:()=>({Navigator:({children}:any)=>first(children),Screen:({component:Component}:any)=>Component?React.createElement(Component,{navigation:{navigate:()=>{},popToTop:()=>{},replace:()=>{}}}):null})};
});

const USER="a".repeat(32),OTHER="b".repeat(32),SALT=Buffer.alloc(16,3),PASSWORD="the account's known password",RANDOM_DATA=Buffer.alloc(32,7);
function derive(password=PASSWORD){const master=crypto.pbkdf2Sync(password,SALT,600000,32,"sha256");return {masterKey:master,authKey:Buffer.from(crypto.hkdfSync("sha256",master,Buffer.alloc(32),Buffer.from("mindpattern/auth/v1"),32)),dataKey:Buffer.from(crypto.hkdfSync("sha256",master,Buffer.alloc(32),Buffer.from("mindpattern/data/v1"),32))};}
const known=derive();
function envelope(cost=600000,password=PASSWORD,dataKey=RANDOM_DATA){const params={algorithm:"pbkdf2-sha256",version:1,iterations:cost},master=crypto.pbkdf2Sync(password,SALT,cost,32,"sha256"),key=Buffer.from(crypto.hkdfSync("sha256",master,SALT,Buffer.from("mindpattern/envelope/v2"),32)),nonce=Buffer.alloc(12,6),cipher=crypto.createCipheriv("aes-256-gcm",key,nonce);cipher.setAAD(Buffer.from(JSON.stringify({context:"envelope",kdf_params:params,username:"alice"})));return {key_scheme:"v2",salt:SALT.toString("base64"),kdf_params:params,wrapped_data_key:Buffer.concat([nonce,cipher.update(dataKey),cipher.final(),cipher.getAuthTag()]).toString("base64")};}
type Root=ReturnType<typeof ReactTestRenderer.create>;
let root:Root|undefined,saltStatus:number,loginStatus:number,envelopeStatus:number,envelopeValue:unknown,loginOwner:string,serverSalt:Buffer,serverVerifier:string,rekeyStatus:number;
const nativeDelete=files.deleteAsync.getMockImplementation()!;
beforeEach(async()=>{
 vi.useRealTimers();vi.restoreAllMocks();storage.__reset();files.__resetFiles();files.deleteAsync.mockImplementation(nativeDelete);keychain.__reset();keychain.__setBiometryType(null);runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);vault.lock();Alert.alert.mockClear();saltStatus=200;loginStatus=0;envelopeStatus=404;envelopeValue=undefined;loginOwner=USER;serverSalt=Buffer.from(SALT);serverVerifier=known.authKey.toString("base64");rekeyStatus=200;
 await api.setSession("native-bearer",USER,"alice");await api.cacheSalt("alice",SALT.toString("base64"));await storeUnlockProof(known.dataKey,USER);
 vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const path=new URL(url).pathname,body=init.body?JSON.parse(String(init.body)):null;let value:unknown={},status=200;if(path.endsWith("/auth/salt")){status=saltStatus;value={salt:serverSalt.toString("base64")};}else if(path.endsWith("/auth/login")){status=loginStatus||(body.verifier===serverVerifier?200:401);value=status===200?{token:"fresh-native-bearer",user_id:loginOwner}:{detail:"untrusted server feedback"};}else if(path.endsWith("/auth/key-envelope")){status=envelopeStatus;value=envelopeValue??{detail:"legacy server endpoint"};}else if(path.endsWith("/account/password")){status=rekeyStatus;if(status===200){serverSalt=Buffer.from(body.new_salt,"base64");serverVerifier=body.new_verifier;envelopeValue={key_scheme:"v2",salt:body.new_salt,kdf_params:body.new_kdf_params??{algorithm:"pbkdf2-sha256",version:1,iterations:600000},wrapped_data_key:body.wrapped_data_key};}else value={detail:"native password transaction unavailable"};}else if(path.endsWith("/processing/sessions"))value={session_token:"native-processing-receipt"};else if(path.endsWith("/consents"))value=[];else if(path.endsWith("/processing/rekey")){status=rekeyStatus;if(status===200){serverSalt=Buffer.from(body.new_salt,"base64");serverVerifier=body.new_verifier;value={credential_rotated:true,operation_id:body.operation_id,entries:1,insights:0,measures:0,consents_rewrapped:0,recovery_invalidated:true};}else value={detail:"native atomic transaction unavailable"};}else if(path.endsWith("/insights"))value={active_days:5};else if(path.endsWith("/meta"))value={unlock_days:30};else if(path.endsWith("/auth/logout"))value={};else throw new Error("unexpected native route "+path);const response=new Response(JSON.stringify(value),{status});Object.defineProperty(response,"url",{value:url});return response;});
});
afterEach(async()=>{assertPublicSurface({view:root?publicSurface(root):null,alerts:Alert.alert.mock.calls.map(([title,message,buttons])=>({title,message,buttons:buttons?.map((button:any)=>({text:button.text,style:button.style}))}))},1);if(root){await act(async()=>root!.unmount());root=undefined;}vi.useRealTimers();vi.restoreAllMocks();vault.lock();await api.clearSession();vi.unstubAllGlobals();});
async function mount(){await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><SessionProvider><UnlockScreen navigation={{navigate:()=>{}}}/></SessionProvider></ThemeProvider>);});for(let i=0;i<32;i++)await act(async()=>{await Promise.resolve();});}
function password(){return root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Password")!;}
async function type(value=PASSWORD){await act(async()=>password().props.onChangeText(value));}
function button(label="Unlock"){return root!.root.findAllByType(TouchableOpacity).find(node=>node.props.accessibilityLabel===label)!;}
async function unlock(){expect(button()).toBeDefined();expect(button().props.disabled).not.toBe(true);await act(async()=>{await button().props.onPress();});}
it("opens a fresh native legacy account on the independently derived data key and clears old failure count",async()=>{await recordUnlockFailure("alice",USER);await mount();await type();await unlock();expect(vault.ownerUserId()).toBe(USER);expect(vault.get()).toMatchObject({dataKey:known.dataKey,authKey:known.authKey,authKeyKnown:true});expect(await unlockFailureCount("alice")).toBe(0);expect(await secureStore.getItem("@mindpattern/token")).toBe("fresh-native-bearer");expect(password().props.value).toBe("");expect(await verifyUnlockProof(known.dataKey,USER)).toBe("ok");expect(Alert.alert.mock.calls).toEqual([]);});
it.each([600000,800000])("opens the native random-data envelope with its declared %s derivation cost",async cost=>{envelopeStatus=200;envelopeValue=envelope(cost);await mount();await type();await unlock();expect(vault.get()).toMatchObject({dataKey:RANDOM_DATA,authKey:known.authKey,authKeyKnown:true});expect(await verifyUnlockProof(RANDOM_DATA,USER)).toBe("ok");expect(password().props.value).toBe("");expect(Alert.alert.mock.calls).toEqual([]);});
it.each(["legacy","v2"])("opens a verified native %s account offline while retaining its existing bearer",async scheme=>{saltStatus=500;if(scheme==="v2"){const row=envelope();await cacheEnvelope("alice",{scheme:"v2",saltB64:row.salt,kdfParams:row.kdf_params as any,wrappedB64:row.wrapped_data_key});}await mount();await type();await unlock();expect(vault.get().dataKey).toEqual(scheme==="v2"?RANDOM_DATA:known.dataKey);expect(await secureStore.getItem("@mindpattern/token")).toBe("native-bearer");expect(Alert.alert.mock.calls).toEqual([]);});
it("keeps the real password input private and refuses empty accessible unlock activation",async()=>{await mount();expect(password().props).toMatchObject({secureTextEntry:true,textContentType:"password",autoComplete:"current-password",value:""});expect(button().props.disabled).toBe(true);await act(async()=>{await password().props.onSubmitEditing();});expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toEqual([]);});
it.each(["missing username","missing owner","missing offline salt","missing offline proof","unconfirmed scheme","invalid scheme"])("refuses native unlock with %s and leaves its key vault locked",async failure=>{if(failure==="missing username")await secureStore.removeItem("@mindpattern/username");if(failure==="missing owner")await secureStore.removeItem("@mindpattern/user_id");if(failure==="missing offline salt"){saltStatus=500;await api.clearCachedSalt("alice");}if(failure==="missing offline proof"){saltStatus=500;await storage.removeItem(accountStorageKey.unlockProof(USER));}if(failure==="unconfirmed scheme")envelopeStatus=500;if(failure==="invalid scheme"){envelopeStatus=200;envelopeValue={key_scheme:"v3",salt:SALT.toString("base64"),kdf_params:null,wrapped_data_key:null};}await mount();await type();await unlock();expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toHaveLength(1);expect(password().props.value).toBe(PASSWORD);});
it("rejects a native login proof returning another account without adopting its bearer",async()=>{loginOwner=OTHER;await mount();await type();await unlock();expect(vault.isUnlocked()).toBe(false);expect(await secureStore.getItem("@mindpattern/token")).toBe("native-bearer");expect(Alert.alert.mock.calls).toHaveLength(1);});
it("restores native biometric local decryption with an unknown auth key and clears the password input",async()=>{keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);await mount();await type();expect(button("Unlock with biometrics")).toBeDefined();await act(async()=>button("Unlock with biometrics").props.onPress());await vi.waitFor(()=>expect(vault.isUnlocked()).toBe(true));expect(vault.get()).toMatchObject({dataKey:known.dataKey,authKey:Buffer.alloc(32),authKeyKnown:false});expect(password().props.value).toBe("");expect(await hasBiometricUnlock(USER)).toBe(true);});
it.each(["unmount","replacement credentials"])("erases a held native password allocation after %s without unlocking the abandoned screen",async retirement=>{await mount();await type();const pbkdf=engine.pbkdf2;let ready!:()=>void,release:()=>void=()=>{},allocation:Buffer|undefined;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{const callback=args.pop();return (pbkdf as(...values:any[])=>unknown)(...args,(error:Error|null,key:Buffer)=>{allocation=key;ready();release=()=>callback(error,key);});}) as any);let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([started,pending]);});if(retirement==="unmount"){await act(async()=>{root!.unmount();root=undefined;});}else{await api.setSession("replacement-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},OTHER);}try{await act(async()=>{release();await pending;});expect(allocation).toBeDefined();expect(allocation!.every(byte=>byte===0)).toBe(true);expect(vault.isUnlocked()).toBe(retirement!=="unmount");if(retirement!=="unmount"){expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}expect(Alert.alert.mock.calls).toEqual([]);}finally{release();await pending;}});
it("erases native derived authentication and data allocations delivered after the unlock view retires",async()=>{
 await mount();await type();const from=Buffer.from,allocations:Buffer[]=[];vi.spyOn(Buffer,"from").mockImplementation(((...args:any[])=>{const value=(from as(...args:any[])=>Buffer)(...args);if(args[0] instanceof Uint8Array&&!Buffer.isBuffer(args[0])&&(value.equals(known.authKey)||value.equals(known.dataKey)))allocations.push(value);return value;}) as any);
 const pbkdf=engine.pbkdf2;let ready!:()=>void,release:()=>void=()=>{};const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{const callback=args.pop();return (pbkdf as(...values:any[])=>unknown)(...args,(error:Error|null,key:Buffer)=>{ready();release=()=>callback(error,key);});}) as any);let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([started,pending]);});await act(async()=>{root!.unmount();root=undefined;});try{await act(async()=>{release();await pending;});expect(allocations.length).toBeGreaterThanOrEqual(2);for(const allocation of allocations)expect(allocation.every(byte=>byte===0)).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toEqual([]);}finally{release();await pending;}
});

function nativeDerivationDelivery(){
 const derive=engine.pbkdf2;let delivered!:()=>void;const complete=new Promise<void>(resolve=>{delivered=resolve;});vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{const callback=args.pop();return (derive as(...values:any[])=>unknown)(...args,(error:Error|null,key:Buffer)=>{callback(error,key);delivered();});}) as any);return complete;
}
it.each(["online","offline"])("keeps an actual native %s wrong-password attempt busy until its exact retry floor",async mode=>{
 if(mode==="online")loginStatus=401;else saltStatus=500;await mount();await type("another password");const delivered = nativeDerivationDelivery();vi.useFakeTimers({toFake:["setTimeout","clearTimeout"]});let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([delivered,pending]);for(let i=0;i<256;i++)await Promise.resolve();});
 try{expect(await unlockFailureCount("alice")).toBe(1);expect(button().props.accessibilityState).toMatchObject({disabled:true,busy:true});expect(Alert.alert.mock.calls).toEqual([]);await act(async()=>vi.advanceTimersByTimeAsync(499));expect(Alert.alert.mock.calls).toEqual([]);await act(async()=>{await vi.advanceTimersByTimeAsync(1);await pending;});expect(Alert.alert.mock.calls).toHaveLength(1);expect(button().props.accessibilityState).toMatchObject({disabled:false,busy:false});expect(vault.isUnlocked()).toBe(false);}finally{await vi.runAllTimersAsync();await pending;}
});
it("retains a replacement vault and suppresses old feedback when the native wrong-password retry timer finishes",async()=>{
 loginStatus=401;await mount();await type();const delivered = nativeDerivationDelivery();vi.useFakeTimers({toFake:["setTimeout","clearTimeout"]});let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([delivered,pending]);for(let i=0;i<256;i++)await Promise.resolve();});await api.setSession("replacement-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},OTHER);try{await act(async()=>{await vi.advanceTimersByTimeAsync(500);await pending;});expect(Alert.alert.mock.calls).toEqual([]);expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));}finally{await vi.runAllTimersAsync();await pending;}
});
async function prepareInterruptedRotation(withCheckpointSalt=true,nativeRoot=false){
 const chosen="the account's previously chosen new password",salt=Buffer.alloc(16,12),master=crypto.pbkdf2Sync(chosen,salt,600000,32,"sha256"),dataKey=Buffer.from(crypto.hkdfSync("sha256",master,Buffer.alloc(32),Buffer.from("mindpattern/data/v1"),32));
 await storage.setItem(accountStorageKey.pendingRotationSalt(USER),salt.toString("base64"));await prepareLocalRekey(USER,known.dataKey,dataKey,withCheckpointSalt?{oldSaltB64:SALT.toString("base64")}:undefined);master.fill(0);dataKey.fill(0);if(nativeRoot)await mountNavigator();else await mount();await vi.waitFor(()=>expect(button("Finish interrupted password change")).toBeDefined());return chosen;
}
it("finishes a real native interrupted rotation and permits a fresh unlock with its chosen password",async()=>{
 const chosen=await prepareInterruptedRotation();const newInput=root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!;expect(newInput.props).toMatchObject({secureTextEntry:true,autoCapitalize:"none",autoCorrect:false,value:""});await type();await act(async()=>newInput.props.onChangeText(chosen));await act(async()=>button("Finish interrupted password change").props.onPress());
 await vi.waitFor(()=>expect(Alert.alert.mock.calls).toEqual([["Password changed","The password change is complete. Unlock with your new password."]]),{timeout:30000});expect(await pendingLocalRekey(USER)).toBe(false);expect(vault.isUnlocked()).toBe(false);expect(password().props.value).toBe("");expect(button("Finish interrupted password change")).toBeUndefined();await type(chosen);await unlock();expect(vault.ownerUserId()).toBe(USER);expect(vault.isUnlocked()).toBe(true);expect(await verifyUnlockProof(vault.get().dataKey,USER)).toBe("ok");
});
it("keeps the original native checkpoint and explains an interrupted rotation refused by the endpoint",async()=>{
 const chosen=await prepareInterruptedRotation();rekeyStatus=500;await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toHaveLength(1),{timeout:30000});expect(Alert.alert.mock.calls[0]![0]).toBe("Could not change password");expect(await pendingLocalRekey(USER)).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(password().props.value).toBe(PASSWORD);expect(button("Finish interrupted password change")).toBeDefined();
});

it("suppresses an old account's interrupted-rotation gate when its native checkpoint read finishes after replacement",async()=>{
 await prepareLocalRekey(USER,known.dataKey,Buffer.alloc(32,12),{oldSaltB64:SALT.toString("base64")});const slot=accountStorageKey.localRekey(new URL(DEFAULT_BASE_URL).origin,USER),read=secureStore.getItem;let ready!:()=>void,release:()=>void=()=>{},first=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key===slot&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});await mount();await api.setSession("replacement-bearer",OTHER,"bob");try{await act(async()=>{release();for(let i=0;i<256;i++)await Promise.resolve();});expect(root!.root.findAllByType(TextInput).some(node=>node.props.accessibilityLabel==="Previously chosen new password")).toBe(false);expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}finally{release();}
});
it("suppresses an old account's native biometric offer when its quiet keychain read finishes after replacement",async()=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);const read=keychain.hasGenericPassword;let ready!:()=>void,release:()=>void=()=>{},first=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(keychain,"hasGenericPassword").mockImplementation(async options=>{const value=await read(options);if(options?.service?.endsWith("."+USER)&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});await mount();await api.setSession("replacement-bearer",OTHER,"bob");try{await act(async()=>{release();for(let i=0;i<256;i++)await Promise.resolve();});expect(button("Unlock with biometrics")).toBeUndefined();expect(await hasBiometricUnlock(OTHER)).toBe(false);expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}finally{release();}
});

it.each(["wrong proof","missing proof","cancelled keychain","missing owner"])("refuses native biometric unlock after %s and retains the private password alternative",async failure=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,failure==="wrong proof"?Buffer.alloc(32,29):known.dataKey);if(failure==="missing proof")await storage.removeItem(accountStorageKey.unlockProof(USER));await mount();await type();expect(button("Unlock with biometrics")).toBeDefined();if(failure==="cancelled keychain")keychain.__failReads(true);if(failure==="missing owner")await secureStore.removeItem("@mindpattern/user_id");await act(async()=>button("Unlock with biometrics").props.onPress());keychain.__failReads(false);expect(vault.isUnlocked()).toBe(false);expect(password().props.value).toBe(PASSWORD);expect(button().props.disabled).not.toBe(true);expect(Alert.alert.mock.calls).toEqual([]);expect(await hasBiometricUnlock(USER)).toBe(failure!=="wrong proof");
});

it.each(["unmount","replacement credentials"])("erases a real native biometric allocation delivered after %s",async retirement=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);await mount();const read=keychain.getGenericPassword;let release:()=>void=()=>{},ready!:()=>void,first=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(keychain,"getGenericPassword").mockImplementation(async options=>{const value=await read(options);if(options?.service?.endsWith("."+USER)&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const from=Buffer.from,allocations:Buffer[]=[];vi.spyOn(Buffer,"from").mockImplementation(((...args:any[])=>{const value=(from as(...values:any[])=>Buffer)(...args);if(args[0]===known.dataKey.toString("base64")&&args[1]==="base64")allocations.push(value);return value;}) as any);let pending!:Promise<void>;await act(async()=>{pending=button("Unlock with biometrics").props.onPress();await Promise.race([started,pending]);});await act(async()=>{if(retirement==="unmount"){root!.unmount();root=undefined;}else{await api.setSession("replacement-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},OTHER);}});try{await act(async()=>{release();await pending;});expect(allocations.length).toBeGreaterThan(0);expect(allocations.every(value=>value.every(byte=>byte===0))).toBe(true);if(retirement==="replacement credentials"){expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));}else expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toEqual([]);}finally{release();await pending;}
});

it("refuses an authenticated native envelope with altered ciphertext without exposing a decoded data key",async()=>{
 envelopeStatus=200;const row=envelope(),wire=Buffer.from(row.wrapped_data_key,"base64");wire[20]^=1;envelopeValue={...row,wrapped_data_key:wire.toString("base64")};await mount();await type();const delivered=nativeDerivationDelivery();vi.useFakeTimers({toFake:["setTimeout","clearTimeout"]});let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([delivered,pending]);for(let i=0;i<256;i++)await Promise.resolve();});try{await act(async()=>{await vi.advanceTimersByTimeAsync(10000);await pending;});expect(vault.isUnlocked()).toBe(false);expect(password().props.value).toBe(PASSWORD);expect(Alert.alert.mock.calls).toHaveLength(1);expect(await unlockFailureCount("alice")).toBe(1);}finally{await vi.runAllTimersAsync();await pending;}
});

it.each(["unmount","replacement credentials"])("refuses an authentic offline proof delivered after %s without reopening an abandoned key vault",async retirement=>{
 saltStatus=500;await mount();await type();const read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key===accountStorageKey.unlockProof(USER)&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([started,pending]);});await act(async()=>{if(retirement==="unmount"){root!.unmount();root=undefined;}else{await api.setSession("replacement-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},OTHER);}});try{await act(async()=>{release();await pending;});if(retirement==="replacement credentials"){expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}else expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toEqual([]);}finally{release();await pending;}
});

it.each(["unmount","replacement credentials"])("erases an authentic native envelope data-key allocation delivered after %s",async retirement=>{
 envelopeStatus=200;envelopeValue=envelope(800000);await mount();await type();const pbkdf=engine.pbkdf2;let count=0,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{const callback=args.pop();const stage=++count;return (pbkdf as(...values:any[])=>unknown)(...args,(error:Error|null,key:Buffer)=>{if(stage===2){ready();release=()=>callback(error,key);}else callback(error,key);});}) as any);const concat=Buffer.concat,allocations:Buffer[]=[];vi.spyOn(Buffer,"concat").mockImplementation(((...args:any[])=>{const value=(concat as(...values:any[])=>Buffer)(...args);if(value.equals(RANDOM_DATA))allocations.push(value);return value;}) as any);let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([started,pending]);});await act(async()=>{if(retirement==="unmount"){root!.unmount();root=undefined;}else{await api.setSession("replacement-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},OTHER);}});try{await act(async()=>{release();await pending;});expect(allocations.length).toBeGreaterThan(0);for(const value of allocations)expect(value.every(byte=>byte===0)).toBe(true);if(retirement==="replacement credentials"){expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));}else expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toEqual([]);}finally{release();await pending;}
});

it("erases an authenticated Native random data key when a different pending journal refuses key adoption",async()=>{
 await prepareLocalRekey(USER,known.dataKey,Buffer.alloc(32,12),{oldSaltB64:SALT.toString("base64")});envelopeStatus=200;envelopeValue=envelope();await mount();await type();const concat=Buffer.concat,allocations:Buffer[]=[];vi.spyOn(Buffer,"concat").mockImplementation(((...args:any[])=>{const value=(concat as(...values:any[])=>Buffer)(...args);if(value.equals(RANDOM_DATA))allocations.push(value);return value;}) as any);await unlock();expect(vault.isUnlocked()).toBe(false);expect(await pendingLocalRekey(USER)).toBe(true);expect(allocations.length).toBeGreaterThan(0);for(const value of allocations)expect(value.every(byte=>byte===0)).toBe(true);expect(Alert.alert.mock.calls).toHaveLength(1);expect(password().props.value).toBe(PASSWORD);
});
it.each(["wrong current password","absent checkpoint salt","absent account name"])("refuses Native interrupted-rotation proof for %s without discarding its checkpoint",async failure=>{
 const chosen=await prepareInterruptedRotation(failure!=="absent checkpoint salt");if(failure==="absent checkpoint salt"){await api.clearCachedSalt("alice");}else if(failure==="absent account name")await secureStore.removeItem("@mindpattern/username");await type(failure==="wrong current password"?"a wrong password":PASSWORD);await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toHaveLength(1));expect(vault.isUnlocked()).toBe(false);expect(await pendingLocalRekey(USER)).toBe(true);expect(Alert.alert.mock.calls[0][0]).toBe("Could not change password");
});

it("finishes an authentic prepared Native v2 journal only after online credential confirmation",async()=>{await prepareLocalRekey(USER,known.dataKey,RANDOM_DATA,{oldSaltB64:SALT.toString("base64")});envelopeStatus=200;envelopeValue=envelope();await mount();await type();await unlock();expect(vault.isUnlocked()).toBe(true);expect(vault.get().dataKey).toEqual(RANDOM_DATA);expect(await pendingLocalRekey(USER)).toBe(false);expect(Alert.alert.mock.calls).toEqual([]);});
it("opens a physically cached Native legacy marker using the authentic offline proof",async()=>{saltStatus=500;await cacheEnvelope("alice",{scheme:"v1",saltB64:SALT.toString("base64"),kdfParams:null,wrappedB64:null});await mount();await type();await unlock();expect(vault.isUnlocked()).toBe(true);expect(vault.get().dataKey).toEqual(known.dataKey);expect(await verifyUnlockProof(known.dataKey,USER)).toBe("ok");expect(Alert.alert.mock.calls).toEqual([]);});

it("reports a Native envelope-provider failure without counting it as a wrong password",async()=>{
 envelopeStatus=200;envelopeValue=envelope();await mount();await type();const decipher=engine.createDecipheriv,kek=Buffer.from(crypto.hkdfSync("sha256",known.masterKey,SALT,Buffer.from("mindpattern/envelope/v2"),32));let refused=false;vi.spyOn(engine,"createDecipheriv").mockImplementation(((...args:any[])=>{if(Buffer.isBuffer(args[1])&&args[1].equals(kek)){refused=true;throw new Error("Native AES envelope provider unavailable");}return (decipher as(...values:any[])=>any)(...args);}) as any);await unlock();expect(refused).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(await unlockFailureCount("alice")).toBe(0);expect(Alert.alert.mock.calls).toHaveLength(1);expect(Alert.alert.mock.calls[0][1]).toBe("your account's key envelope could not be opened on this server. Nothing was changed — try again, and contact support if it repeats.");expect(password().props.value).toBe(PASSWORD);
});
it("reports unavailable Native salt storage without charging the password retry counter",async()=>{
 saltStatus=500;await api.clearCachedSalt("alice");await mount();await type();await unlock();expect(vault.isUnlocked()).toBe(false);expect(await unlockFailureCount("alice")).toBe(0);expect(Alert.alert.mock.calls).toHaveLength(1);expect(password().props.value).toBe(PASSWORD);
});
it.each(["both passwords absent","current password absent","chosen password absent"])("keeps an interrupted Native checkpoint idle when %s",async missing=>{
 await prepareInterruptedRotation();if(missing!=="both passwords absent"&&missing!=="current password absent")await type();if(missing!=="both passwords absent"&&missing!=="chosen password absent")await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText("a newly chosen password"));await act(async()=>button("Finish interrupted password change").props.onPress());for(let i=0;i<32;i++)await act(async()=>Promise.resolve());expect(Alert.alert.mock.calls).toEqual([]);expect(await pendingLocalRekey(USER)).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(button().props.accessibilityState.busy).toBe(false);
});
it("erases Native interrupted-rotation derivation allocations after the current password proof fails",async()=>{
 const chosen=await prepareInterruptedRotation(),wrongPassword="a wrong current password",wrong=derive(wrongPassword);await type(wrongPassword);await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const from=Buffer.from,allocations:Buffer[]=[];vi.spyOn(Buffer,"from").mockImplementation(((...args:any[])=>{const value=(from as(...values:any[])=>Buffer)(...args);if(args[0] instanceof Uint8Array&&(value.equals(wrong.masterKey)||value.equals(wrong.authKey)||value.equals(wrong.dataKey)))allocations.push(value);return value;}) as any);await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toHaveLength(1));expect(allocations.length).toBeGreaterThanOrEqual(3);for(const value of allocations)expect(value.every(byte=>byte===0)).toBe(true);expect(await pendingLocalRekey(USER)).toBe(true);expect(vault.isUnlocked()).toBe(false);
});
it("refuses a physically removed Native account during offline unlock",async()=>{
 saltStatus=500;await mount();await type();const transport=fetch;let release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const value=await transport(url,init);if(new URL(url).pathname.endsWith("/auth/salt")){ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([started,pending]);});await secureStore.removeItem("@mindpattern/user_id");try{await act(async()=>{release();await pending;});expect(vault.isUnlocked()).toBe(false);expect(password().props.value).toBe(PASSWORD);expect(Alert.alert.mock.calls).toEqual([["Unlock failed","no saved account on this device — please sign in"]]);}finally{release();await pending;}
});
it("refuses a restored different Native account before adopting an authentic offline key",async()=>{
 saltStatus=500;await mount();await type();const read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key===accountStorageKey.unlockProof(USER)){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([started,pending]);});await secureStore.setItem("@mindpattern/user_id",OTHER);try{await act(async()=>{release();await pending;});expect(vault.isUnlocked()).toBe(false);expect(password().props.value).toBe(PASSWORD);expect(Alert.alert.mock.calls).toEqual([["Unlock failed","The saved account changed before key adoption."]]);expect(await secureStore.getItem("@mindpattern/user_id")).toBe(OTHER);}finally{release();await pending;}
});
it("refuses a cached Native v2 envelope provider failure after an accepted online password",async()=>{
 const row=envelope();envelopeStatus=500;await cacheEnvelope("alice",{scheme:"v2",saltB64:row.salt,kdfParams:row.kdf_params as any,wrappedB64:row.wrapped_data_key});await mount();await type();const decipher=engine.createDecipheriv,kek=Buffer.from(crypto.hkdfSync("sha256",known.masterKey,SALT,Buffer.from("mindpattern/envelope/v2"),32));let refused=false;vi.spyOn(engine,"createDecipheriv").mockImplementation(((...args:any[])=>{if(Buffer.isBuffer(args[1])&&args[1].equals(kek)){refused=true;throw new Error("Native cached-envelope AES unavailable");}return (decipher as(...values:any[])=>any)(...args);}) as any);await unlock();expect(refused).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(await unlockFailureCount("alice")).toBe(0);expect(Alert.alert.mock.calls).toEqual([["Unlock failed","your account's key envelope could not be opened on this server. Nothing was changed — try again, and contact support if it repeats."]]);expect(password().props.value).toBe(PASSWORD);
});
it.each(["continue current account","replace account"])("keeps a Native interrupted-rotation operation private while its credential delivery is pending: %s",async retirement=>{
 const chosen=await prepareInterruptedRotation();await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const read=secureStore.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key==="@mindpattern/user_id"){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let pending!:Promise<void>;await act(async()=>{pending=button("Finish interrupted password change").props.onPress();await started;});assertPublicSurface({view:publicSurface(root!),alerts:[]},2);expect(button("Finish interrupted password change").props.disabled).toBe(true);expect(button().props.accessibilityState.busy).toBe(true);if(retirement==="replace account"){await api.setSession("replacement-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},OTHER);}
 try{await act(async()=>{release();await pending;});if(retirement==="continue current account")await vi.waitFor(()=>expect(Alert.alert.mock.calls).toHaveLength(1),{timeout:30000});else await vi.waitFor(()=>expect(button().props.accessibilityState.busy).toBe(false));if(retirement==="replace account"){expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));expect(Alert.alert.mock.calls).toEqual([]);expect(await pendingLocalRekey(USER)).toBe(true);}else{expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toEqual([["Password changed","The password change is complete. Unlock with your new password."]]);expect(await pendingLocalRekey(USER)).toBe(false);expect(root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")).toBeUndefined();}}
 finally{release();await pending;}
});
it("finishes a missing-account Native biometric attempt before an unavailable presence provider",async()=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);await mount();await type();await secureStore.removeItem("@mindpattern/user_id");const presence=keychain.hasGenericPassword;let release:()=>void=()=>{},unavailable=true;vi.spyOn(keychain,"hasGenericPassword").mockImplementation(async options=>{if(unavailable&&options?.service?.endsWith(".null"))await new Promise<void>(resolve=>{release=resolve;});return presence(options);});try{await act(async()=>{button("Unlock with biometrics").props.onPress();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));});expect(button().props.accessibilityState.busy).toBe(false);expect(vault.isUnlocked()).toBe(false);expect(password().props.value).toBe(PASSWORD);expect(Alert.alert.mock.calls).toEqual([]);}finally{unavailable=false;release();await act(async()=>Promise.resolve());await vi.waitFor(()=>expect(button().props.accessibilityState.busy).toBe(false));}
});
it.each(["checkpoint salt without cache","cached salt without checkpoint context"])("finishes an authentic Native interrupted rotation using %s",async source=>{
 const chosen=await prepareInterruptedRotation(source==="checkpoint salt without cache");if(source==="checkpoint salt without cache")await api.clearCachedSalt("alice");await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toEqual([["Password changed","The password change is complete. Unlock with your new password."]]),{timeout:30000});expect(vault.isUnlocked()).toBe(false);expect(await pendingLocalRekey(USER)).toBe(false);expect(password().props.value).toBe("");
});
it("refreshes the actual Native random-key proof after an accepted online password uses a cached envelope",async()=>{
 const row=envelope();envelopeStatus=500;await cacheEnvelope("alice",{scheme:"v2",saltB64:row.salt,kdfParams:row.kdf_params as any,wrappedB64:row.wrapped_data_key});await mount();await type();await unlock();expect(vault.get().dataKey).toEqual(RANDOM_DATA);expect(await verifyUnlockProof(RANDOM_DATA,USER)).toBe("ok");expect(Alert.alert.mock.calls).toEqual([]);
});
it("retains the fetched Native v2 envelope for the next authentic offline unlock",async()=>{
 envelopeStatus=200;envelopeValue=envelope();await mount();await type();await unlock();expect(vault.get().dataKey).toEqual(RANDOM_DATA);vault.lock();saltStatus=500;envelopeStatus=500;await type();await unlock();expect(vault.get().dataKey).toEqual(RANDOM_DATA);expect(await verifyUnlockProof(RANDOM_DATA,USER)).toBe("ok");expect(Alert.alert.mock.calls).toEqual([]);
});
it("persists the explicit Native v1 scheme receipt with its verified local proof",async()=>{
 envelopeStatus=200;envelopeValue={key_scheme:"v1",salt:SALT.toString("base64"),kdf_params:null,wrapped_data_key:null};await mount();await type();await unlock();expect(vault.get().dataKey).toEqual(known.dataKey);expect(await verifyUnlockProof(known.dataKey,USER)).toBe("ok");expect(await cachedEnvelope("alice")).toEqual({scheme:"v1",saltB64:SALT.toString("base64"),kdfParams:null,wrappedB64:null});expect(Alert.alert.mock.calls).toEqual([]);
});
it("opens the authentic matching-cost Native envelope without depending on a second derivation provider",async()=>{
 envelopeStatus=200;envelopeValue=envelope();await mount();await type();const pbkdf=engine.pbkdf2;let first=true;vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{if(first){first=false;return (pbkdf as(...values:any[])=>unknown)(...args);}const callback=args.at(-1);queueMicrotask(()=>callback(new Error("Native second derivation provider unavailable")));}) as any);await unlock();expect(vault.get().dataKey).toEqual(RANDOM_DATA);expect(await verifyUnlockProof(RANDOM_DATA,USER)).toBe("ok");expect(Alert.alert.mock.calls).toEqual([]);
});
it("keeps a password submission's Native authentication custody when an already queued biometric press is delivered",async()=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);await mount();await type();const submit=password().props.onSubmitEditing,biometric=button("Unlock with biometrics").props.onPress,pbkdf=engine.pbkdf2;let release:()=>void=()=>{},ready!:()=>void,first=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{const callback=args.pop();return (pbkdf as(...values:any[])=>unknown)(...args,(error:Error|null,key:Buffer)=>{if(first){first=false;ready();release=()=>callback(error,key);}else callback(error,key);});}) as any);let pending!:Promise<void>;await act(async()=>{pending=submit();biometric();await Promise.race([started,pending]);});
 try{await act(async()=>{release();await pending;});await vi.waitFor(()=>expect(button().props.accessibilityState.busy).toBe(false));expect(vault.get()).toMatchObject({dataKey:known.dataKey,authKey:known.authKey,authKeyKnown:true});expect(await secureStore.getItem("@mindpattern/token")).toBe("fresh-native-bearer");expect(Alert.alert.mock.calls).toEqual([]);}finally{release();await pending;}
});
it("keeps a queued interrupted-rotation press from superseding an admitted Native password attempt",async()=>{
 const chosen=await prepareInterruptedRotation();await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const submit=password().props.onSubmitEditing,finish=button("Finish interrupted password change").props.onPress,pbkdf=engine.pbkdf2;let release:()=>void=()=>{},ready!:()=>void,first=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{const callback=args.pop();return (pbkdf as(...values:any[])=>unknown)(...args,(error:Error|null,key:Buffer)=>{if(first){first=false;ready();release=()=>callback(error,key);}else callback(error,key);});}) as any);let pending!:Promise<void>;await act(async()=>{pending=submit();finish();await started;});
 try{await act(async()=>{release();await pending;});await vi.waitFor(()=>expect(button().props.accessibilityState.busy).toBe(false),{timeout:30000});expect(await pendingLocalRekey(USER)).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(Alert.alert.mock.calls).toHaveLength(1);expect(Alert.alert.mock.calls[0][0]).toBe("Unlock failed");}finally{release();await pending;}
});
it("retains the first Native wrong-password pause when its encrypted counter provider refuses persistence",async()=>{
 loginStatus=401;await mount();await type();const write=storage.setItem;vi.spyOn(storage,"setItem").mockImplementation(async(key,value)=>{if(key===accountStorageKey.unlockFailure("alice"))throw new Error("Native guessing-counter volume unavailable");return write(key,value);});const delivered=nativeDerivationDelivery();vi.useFakeTimers({toFake:["setTimeout","clearTimeout"]});let pending!:Promise<void>;await act(async()=>{pending=button().props.onPress();await Promise.race([delivered,pending]);for(let i=0;i<256;i++)await Promise.resolve();});
 try{await act(async()=>vi.advanceTimersByTimeAsync(499));expect(Alert.alert.mock.calls).toEqual([]);await act(async()=>{await vi.advanceTimersByTimeAsync(1);await pending;});expect(Alert.alert.mock.calls).toHaveLength(1);expect(vault.isUnlocked()).toBe(false);expect(await unlockFailureCount("alice")).toBe(0);}finally{await vi.runAllTimersAsync();await pending;}
});
it("finishes an unmounted Native wrong-password attempt before scheduling its old pause after a counter delivery",async()=>{
 loginStatus=401;await mount();await type();const read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key===accountStorageKey.unlockFailure("alice")){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});vi.useFakeTimers({toFake:["setTimeout","clearTimeout"]});let pending!:Promise<void>,settled=false;await act(async()=>{pending=button().props.onPress().then(()=>{settled=true;});await started;});await act(async()=>{root!.unmount();root=undefined;});
 try{release();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(Alert.alert.mock.calls).toEqual([]);}finally{release();await vi.runAllTimersAsync();await pending;}expect(await unlockFailureCount("alice")).toBe(1);
});
it("finishes an authenticated Native already-applied checkpoint during biometric unlock",async()=>{
 const old=derive("the earlier account password");await storeUnlockProof(old.dataKey,USER);await prepareLocalRekey(USER,old.dataKey,known.dataKey,{oldSaltB64:SALT.toString("base64")});await markLocalRekeyPhase(USER,"credential");const slot=accountStorageKey.localRekey(new URL(DEFAULT_BASE_URL).origin,USER),sealedCheckpoint=await Promise.all((await storage.getAllKeys()).filter(key=>key===slot||key.startsWith(slot+".chunk.")).map(async key=>[key,(await storage.getItem(key))!] as const));await resumeLocalRekey(USER,known.dataKey);await storeUnlockProof(known.dataKey,USER);keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);for(const [key,value]of sealedCheckpoint)await storage.setItem(key,value);await mount();await act(async()=>button("Unlock with biometrics").props.onPress());await vi.waitFor(()=>expect(vault.isUnlocked()).toBe(true));expect(vault.get().dataKey).toEqual(known.dataKey);expect(await pendingLocalRekey(USER)).toBe(false);expect(await storage.getItem(slot)).toBeNull();expect(await verifyUnlockProof(known.dataKey,USER)).toBe("ok");expect(Alert.alert.mock.calls).toEqual([]);old.masterKey.fill(0);old.authKey.fill(0);old.dataKey.fill(0);
});
it("erases actual Native interrupted-rotation allocations delivered after account replacement",async()=>{
 const chosen=await prepareInterruptedRotation();await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const pbkdf=engine.pbkdf2,from=Buffer.from,allocations:Buffer[]=[];let release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(engine,"pbkdf2").mockImplementation(((...args:any[])=>{const callback=args.pop();return (pbkdf as(...values:any[])=>unknown)(...args,(error:Error|null,key:Buffer)=>{ready();release=()=>callback(error,key);});}) as any);vi.spyOn(Buffer,"from").mockImplementation(((...args:any[])=>{const value=(from as(...values:any[])=>Buffer)(...args);if(args[0] instanceof Uint8Array&&(value.equals(known.masterKey)||value.equals(known.authKey)||value.equals(known.dataKey)))allocations.push(value);return value;}) as any);await act(async()=>{button("Finish interrupted password change").props.onPress();await started;});await api.setSession("replacement-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},OTHER);
 try{await act(async()=>release());await vi.waitFor(()=>expect(button().props.accessibilityState.busy).toBe(false));expect(allocations.length).toBeGreaterThanOrEqual(3);for(const allocation of allocations)expect(allocation.every(byte=>byte===0)).toBe(true);expect(vault.ownerUserId()).toBe(OTHER);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));expect(Alert.alert.mock.calls).toEqual([]);}finally{release();}
});

it("reports a cached Native offline envelope-provider refusal with honest retry copy",async()=>{
 const row=envelope();saltStatus=500;await cacheEnvelope("alice",{scheme:"v2",saltB64:row.salt,kdfParams:row.kdf_params as any,wrappedB64:row.wrapped_data_key});await mount();await type();const decipher=engine.createDecipheriv,kek=Buffer.from(crypto.hkdfSync("sha256",known.masterKey,SALT,Buffer.from("mindpattern/envelope/v2"),32));vi.spyOn(engine,"createDecipheriv").mockImplementation(((...args:any[])=>{if(Buffer.isBuffer(args[1])&&args[1].equals(kek))throw new Error("Native offline envelope AES unavailable");return (decipher as(...values:any[])=>any)(...args);}) as any);await unlock();expect(vault.isUnlocked()).toBe(false);expect(await unlockFailureCount("alice")).toBe(0);expect(Alert.alert.mock.calls).toEqual([["Unlock failed","your account's key envelope could not be opened on this server. Nothing was changed — try again, and contact support if it repeats."]]);expect(password().props.value).toBe(PASSWORD);
});

async function mountNavigator(){
 const {AppNavigator}=await import("../../src/navigation");await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><SessionProvider><AppNavigator/></SessionProvider></ThemeProvider>);});for(let i=0;i<32;i++)await act(async()=>{await Promise.resolve();});expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(1);
}
it.each((["password","biometric"] as const).flatMap(mode=>[1,2,3,4,5,6,7,8].map(phase=>[mode,phase] as const)))("keeps Root Native %s cancellation final at rekey delivery phase %s",async(mode,phase)=>{
 if(mode==="biometric"){keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);}await mountNavigator();if(mode==="password")await type();const leave=button("Sign out instead").props.onPress,read=storage.getItem,slot=accountStorageKey.localRekey(new URL(DEFAULT_BASE_URL).origin,USER);let armed=true,retired=false,revived=false,ready!:()=>void;const delivered=new Promise<void>(resolve=>{ready=resolve;});const unsubscribe=vault.subscribe(()=>{if(retired&&vault.isUnlocked())revived=true;});
 const nativeRead=vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(armed&&key===slot){armed=false;let remaining=phase;const next=()=>{if(--remaining>0)queueMicrotask(next);else{if(root!.root.findAllByType(UnlockScreen).length){retired=true;leave();}ready();}};queueMicrotask(next);}return value;});
 try{await act(async()=>{await button(mode==="password"?"Unlock":"Unlock with biometrics").props.onPress();await delivered;});for(let i=0;i<32;i++)await act(async()=>{await Promise.resolve();});expect(revived).toBe(false);if(retired){expect(vault.isUnlocked()).toBe(false);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);expect(await secureStore.getItem("@mindpattern/token")).toBeNull();}else expect(vault.get().dataKey).toEqual(known.dataKey);expect(Alert.alert.mock.calls).toEqual([]);assertPublicSurface({view:publicSurface(root),alerts:[]},phase+1);}finally{unsubscribe();nativeRead.mockRestore();}

});

it("keeps the Native biometric offer hidden when a retained wrap outlives device support",async()=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);keychain.__setBiometryType(null);await mount();expect(button("Unlock with biometrics")).toBeUndefined();expect(password().props.value).toBe("");expect(vault.isUnlocked()).toBe(false);
});

it("keeps the Root Native vault restricted while interrupted rotation holds its real processing delivery",async()=>{
 const chosen=await prepareInterruptedRotation(true,true);await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const fetch=globalThis.fetch;let ready!:()=>void,release:()=>void=()=>{};const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{if(new URL(String(args[0])).pathname.endsWith("/processing/rekey")){ready();await new Promise<void>(resolve=>{release=resolve;});}return fetch(...args);});
 await act(async()=>{button("Finish interrupted password change").props.onPress();await started;});try{expect(vault.isUnlocked()).toBe(false);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(1);expect(button("Finish interrupted password change").props.disabled).toBe(true);assertPublicSurface({view:publicSurface(root),alerts:[]},2);}finally{await act(async()=>release());}
 await vi.waitFor(()=>expect(Alert.alert.mock.calls).toEqual([["Password changed","The password change is complete. Unlock with your new password."]]),{timeout:30000});expect(vault.isUnlocked()).toBe(false);expect(await pendingLocalRekey(USER)).toBe(false);
});

it("keeps the Root Native route restricted at the first delegate checkpoint delivery",async()=>{
 const chosen=await prepareInterruptedRotation(true,true);await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const get=storage.getItem.bind(storage),slot=accountStorageKey.localRekey(new URL(DEFAULT_BASE_URL).origin,USER);let ready!:()=>void,release:()=>void=()=>{},armed=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await get(key);if(armed&&key===slot&&vault.canReauthenticate()){armed=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let pending!:Promise<void>;
 await act(async()=>{pending=button("Finish interrupted password change").props.onPress();await started;});try{expect(vault.canReauthenticate()).toBe(true);expect(vault.isUnlocked()).toBe(false);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(1);expect(button("Finish interrupted password change").props.disabled).toBe(true);assertPublicSurface({view:publicSurface(root),alerts:[]},2);}finally{await act(async()=>{release();await pending;});}
});

it("locks the Native retained data key after a confirmed journal rotation and accepts its next unlock",async()=>{
 // A prepared v1 journal can coexist with a subsequent server v2 upgrade;
 // the retained journal deliberately keeps the delegate on its v1 path.
 // The sampled Native pending salt and unchanged chosen password retain the
 // same planned data key; all checkpoint bytes use the shipped sealed writer.
 await storage.setItem(accountStorageKey.pendingRotationSalt(USER),SALT.toString("base64"));await prepareLocalRekey(USER,known.dataKey,known.dataKey,{oldSaltB64:SALT.toString("base64")});envelopeStatus=200;envelopeValue=envelope(600000,PASSWORD,known.dataKey);await mount();await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(PASSWORD));await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toEqual([["Password changed","The password change is complete. Unlock with your new password."]]),{timeout:30000});expect(vault.isUnlocked()).toBe(false);expect(vault.canReauthenticate()).toBe(false);expect(vault.ownerUserId()).toBeNull();expect(password().props.value).toBe("");await type();await unlock();expect(vault.get().dataKey).toEqual(known.dataKey);expect(await pendingLocalRekey(USER)).toBe(false);expect(await verifyUnlockProof(known.dataKey,USER)).toBe("ok");
});

it("releases the Native restricted journal key after an interrupted rotation credential refusal",async()=>{
 await storage.setItem(accountStorageKey.pendingRotationSalt(USER),SALT.toString("base64"));await prepareLocalRekey(USER,known.dataKey,known.dataKey,{oldSaltB64:SALT.toString("base64")});envelopeStatus=200;envelopeValue=envelope(600000,PASSWORD,known.dataKey);rekeyStatus=503;const buffers:Buffer[]=[];const unsubscribe=vault.subscribe(()=>{if(vault.canReauthenticate()){const keys=vault.get();buffers.push(keys.authKey,keys.dataKey);}});
 try{await mount();await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(PASSWORD));await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toHaveLength(1),{timeout:30000});expect(Alert.alert.mock.calls[0][0]).toBe("Could not change password");expect(vault.canReauthenticate()).toBe(false);expect(vault.ownerUserId()).toBeNull();expect(buffers.length).toBeGreaterThanOrEqual(2);for(const key of buffers)expect(key.every(byte=>byte===0)).toBe(true);expect(await pendingLocalRekey(USER)).toBe(true);}finally{unsubscribe();}
});
it("erases the Native restricted key after an early rotation username provider refusal",async()=>{
 const chosen=await prepareInterruptedRotation();await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const get=storage.getItem.bind(storage),buffers:Buffer[]=[];let refused=false;vi.spyOn(storage,"getItem").mockImplementation(async slot=>{if(refused&&slot==="@mindpattern/username")throw new Error("Native username storage unavailable");return get(slot);});const unsubscribe=vault.subscribe(()=>{if(vault.canReauthenticate()){const keys=vault.get();buffers.push(keys.authKey,keys.dataKey);refused=true;}});
 try{await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toHaveLength(1));expect(refused).toBe(true);expect(Alert.alert.mock.calls[0][0]).toBe("Could not change password");expect(vault.canReauthenticate()).toBe(false);expect(vault.ownerUserId()).toBeNull();expect(buffers.length).toBeGreaterThanOrEqual(2);for(const key of buffers)expect(key.every(byte=>byte===0)).toBe(true);expect(await pendingLocalRekey(USER)).toBe(true);}finally{unsubscribe();}
});
it("lets a new Root Native biometric probe finish behind a retired quiet provider delivery",async()=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);saltStatus=500;const supported=keychain.getSupportedBiometryType;let first=true,releaseSupported:()=>void=()=>{},releaseStorage:()=>void=()=>{},queueMode=false,holdOnce=true;vi.spyOn(keychain,"getSupportedBiometryType").mockImplementation(async()=>{const value=await supported();if(first){first=false;await new Promise<void>(resolve=>{releaseSupported=resolve;});}return value;});await mountNavigator();await type();await act(async()=>button().props.onPress());for(let i=0;i<32;i++)await act(async()=>{await Promise.resolve();});expect(vault.isUnlocked()).toBe(true);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);
 // Installed Android AsyncStorage executes physical reads on SerialExecutor.
 // An obsolete request must not occupy that executor ahead of a new route.
 const read=storage.getItem;let lane=Promise.resolve();vi.spyOn(storage,"getItem").mockImplementation(key=>{const pending=lane.then(async()=>{const value=await read(key);if(queueMode&&holdOnce&&key==="@mindpattern/user_id"){holdOnce=false;await new Promise<void>(resolve=>{releaseStorage=resolve;});}return value;});lane=pending.then(()=>{},()=>{});return pending;});
 try{queueMode=true;await act(async()=>{releaseSupported();for(let i=0;i<32;i++)await Promise.resolve();});queueMode=false;await act(async()=>vault.lock());await vi.waitFor(()=>expect(button("Unlock with biometrics")).toBeDefined(),{timeout:1500});expect(vault.isUnlocked()).toBe(false);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(1);expect(Alert.alert.mock.calls).toEqual([]);}finally{releaseSupported();releaseStorage();for(let i=0;i<32;i++)await act(async()=>{await Promise.resolve();});}
});

it("lets a new Root Native probe finish behind a retired account provider delivery",async()=>{
 saltStatus=500;const read=storage.getItem.bind(storage);let first=true,ready!:()=>void,releaseAccount:()=>void=()=>{},releaseStorage:()=>void=()=>{};const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const fromUnlock=Boolean(root&&root.root.findAllByType(UnlockScreen).length);const value=await read(key);if(first&&fromUnlock&&key==="@mindpattern/user_id"){first=false;ready();await new Promise<void>(resolve=>{releaseAccount=resolve;});}return value;});await mountNavigator();await started;await type();await act(async()=>button().props.onPress());for(let i=0;i<32;i++)await act(async()=>{await Promise.resolve();});expect(vault.isUnlocked()).toBe(true);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);
 let lane=Promise.resolve(),queueMode=false,holdOnce=true;vi.spyOn(storage,"getItem").mockImplementation(key=>{const pending=lane.then(async()=>{const value=await read(key);if(queueMode&&holdOnce&&key==="@mindpattern/base_url"){holdOnce=false;await new Promise<void>(resolve=>{releaseStorage=resolve;});}return value;});lane=pending.then(()=>{},()=>{});return pending;});
 try{queueMode=true;await act(async()=>{releaseAccount();for(let i=0;i<64;i++)await Promise.resolve();});queueMode=false;await act(async()=>vault.lock());await vi.waitFor(()=>expect(button("Unlock with biometrics")).toBeDefined(),{timeout:1500});expect(vault.isUnlocked()).toBe(false);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(1);expect(Alert.alert.mock.calls).toEqual([]);}finally{releaseAccount();releaseStorage();for(let i=0;i<32;i++)await act(async()=>{await Promise.resolve();});}
});

it.each([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])("keeps Root Native cancellation final at rotation cleanup delivery phase %s",async phase=>{
 const chosen=await prepareInterruptedRotation(true,true);await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const remove=storage.removeItem.bind(storage),slot=accountStorageKey.biometricOwner(USER);let receipts=0,delivered=false,retired=false,beforeAlerts=0;
 vi.spyOn(storage,"removeItem").mockImplementation(async key=>{await remove(key);if(key===slot&&++receipts===2){let remaining=phase;const next=()=>{if(--remaining>0)queueMicrotask(next);else{delivered=true;if(root!.root.findAllByType(UnlockScreen).length){retired=true;beforeAlerts=Alert.alert.mock.calls.length;button("Sign out instead").props.onPress();}}};queueMicrotask(next);}});
 await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(delivered).toBe(true),{timeout:30000});for(let i=0;i<64;i++)await act(async()=>{await Promise.resolve();});if(retired){expect(Alert.alert.mock.calls).toHaveLength(beforeAlerts);expect(vault.isUnlocked()).toBe(false);expect(await secureStore.getItem("@mindpattern/token")).toBeNull();expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);}assertPublicSurface({view:publicSurface(root),alerts:Alert.alert.mock.calls.map(([title,message]:any[])=>({title,message}))},phase+1);
});

it.each([200,503])("locks the actual Native v2 key when a previously observed checkpoint is missing at completion: %s",async status=>{
 await storage.setItem(accountStorageKey.pendingRotationSalt(USER),SALT.toString("base64"));await prepareLocalRekey(USER,known.dataKey,known.dataKey,{oldSaltB64:SALT.toString("base64")});envelopeStatus=200;envelopeValue=envelope(600000,PASSWORD,known.dataKey);rekeyStatus=status;await mount();await vi.waitFor(()=>expect(button("Finish interrupted password change")).toBeDefined());
 // The current card is a prior authenticated Native read, not a fresh
 // journal existence proof. A missing Native index may route its later
 // delegate through the genuine v2 envelope path; all crypto stays real.
 await storage.removeItem(accountStorageKey.localRekey(new URL(DEFAULT_BASE_URL).origin,USER));await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(PASSWORD));const fetch=globalThis.fetch;let delivered=false;vi.stubGlobal("fetch",async(...args:Parameters<typeof fetch>)=>{if(new URL(String(args[0])).pathname.endsWith("/account/password"))delivered=true;return fetch(...args);});const buffers:Buffer[]=[];const unsubscribe=vault.subscribe(()=>{if(vault.canReauthenticate()){const keys=vault.get();buffers.push(keys.authKey,keys.dataKey);}});
 try{await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(Alert.alert.mock.calls).toHaveLength(1),{timeout:30000});expect(delivered).toBe(true);expect(Alert.alert.mock.calls[0][0]).toBe(status===200?"Password changed":"Could not change password");expect(vault.canReauthenticate()).toBe(false);expect(vault.ownerUserId()).toBeNull();expect(buffers.length).toBeGreaterThanOrEqual(2);for(const key of buffers)expect(key.every(byte=>byte===0)).toBe(true);}finally{unsubscribe();}
});

it("keeps a replacement Native credential quiet after a retired biometric proof reports absent",async()=>{
 keychain.__setBiometryType("FaceID");await enableBiometricUnlock(USER,known.dataKey);await storage.removeItem(accountStorageKey.unlockProof(USER));await mountNavigator();expect(button("Unlock with biometrics")).toBeDefined();const read=storage.getItem.bind(storage);let ready!:()=>void,release:()=>void=()=>{},first=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key===accountStorageKey.unlockProof(USER)){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});
 await act(async()=>button("Unlock with biometrics").props.onPress());await started;await api.setSession("replacement Native bearer",USER,"alice");try{await act(async()=>release());await vi.waitFor(()=>expect(button("Unlock with biometrics")?.props.disabled).toBe(false));expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(1);expect(vault.canReauthenticate()).toBe(false);expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement Native bearer");expect(Alert.alert.mock.calls).toEqual([]);assertPublicSurface({view:publicSurface(root),alerts:[]},2);}finally{release();}
});

it.each([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])("keeps Root Native cancellation final at rotation proof delivery phase %s",async phase=>{
 const chosen=await prepareInterruptedRotation(true,true);await type();await act(async()=>root!.root.findAllByType(TextInput).find(node=>node.props.accessibilityLabel==="Previously chosen new password")!.props.onChangeText(chosen));const read=storage.getItem.bind(storage),slot=accountStorageKey.unlockProof(USER);let delivered=false,retired=false,revived=false,armed=true,beforeAlerts=0;
 const unsubscribe=vault.subscribe(()=>{if(retired&&vault.canReauthenticate())revived=true;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(armed&&key===slot){armed=false;let remaining=phase;const next=()=>{if(--remaining>0)queueMicrotask(next);else{delivered=true;if(root!.root.findAllByType(UnlockScreen).length){retired=true;beforeAlerts=Alert.alert.mock.calls.length;button("Sign out instead").props.onPress();}}};queueMicrotask(next);}return value;});
 try{await act(async()=>button("Finish interrupted password change").props.onPress());await vi.waitFor(()=>expect(delivered).toBe(true),{timeout:30000});for(let i=0;i<64;i++)await act(async()=>{await Promise.resolve();});expect(revived).toBe(false);if(retired){expect(vault.canReauthenticate()).toBe(false);expect(Alert.alert.mock.calls).toHaveLength(beforeAlerts);await vi.waitFor(async()=>expect(await secureStore.getItem("@mindpattern/token")).toBeNull(),{timeout:1500});expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);}assertPublicSurface({view:publicSurface(root),alerts:Alert.alert.mock.calls.map(([title,message]:any[])=>({title,message}))},phase+1);}finally{unsubscribe();}
});

it("removes Native saved credentials on Root signout while a retained rotation checkpoint freezes local writes",async()=>{
 await prepareInterruptedRotation(true,true);await act(async()=>button("Sign out instead").props.onPress());await vi.waitFor(async()=>expect(await secureStore.getItem("@mindpattern/token")).toBeNull(),{timeout:1500});expect(vault.canReauthenticate()).toBe(false);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);expect(await pendingLocalRekey(USER)).toBe(true);assertPublicSurface({view:publicSurface(root),alerts:Alert.alert.mock.calls.map(([title,message]:any[])=>({title,message}))},2);
});

// These phases precede a fresh account-read admission. Other phases can
// already own Native IO when cancellation arrives; that IO must drain.
it.each([1,2,3,4,5,6,9,10,11,12,13,14,15,16,17,18,19])("lets Root Native signout finish before obsolete account IO at username delivery phase %s",async phase=>{
 await mountNavigator();await type();const read=storage.getItem.bind(storage);let lane=Promise.resolve(),armed=true,retired=false,baseRead=false,retiredOwnerReads=0,release:()=>void=()=>{},delivered=false;
 vi.spyOn(storage,"getItem").mockImplementation(key=>{
  const pending=lane.then(async()=>{
   const value=await read(key);
   if(retired&&key==="@mindpattern/base_url")baseRead=true;
   if(retired&&key==="@mindpattern/user_id"&&++retiredOwnerReads===2&&!baseRead)await new Promise<void>(resolve=>{release=resolve;});
   if(armed&&key==="@mindpattern/username"){
    armed=false;let remaining=phase;const next=()=>{if(--remaining>0)queueMicrotask(next);else{delivered=true;if(root!.root.findAllByType(UnlockScreen).length){retired=true;button("Sign out instead").props.onPress();}}};queueMicrotask(next);
   }
   return value;
  });
  lane=pending.then(()=>{},()=>{});return pending;
 });
 try{
  await act(async()=>{button().props.onPress();for(let i=0;i<128;i++)await Promise.resolve();});
  await vi.waitFor(()=>expect(delivered).toBe(true));expect(retired).toBe(true);
  await vi.waitFor(async()=>expect(await read("@mindpattern/token")).toBeNull(),{timeout:1500});
  expect(vault.canReauthenticate()).toBe(false);expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);expect(Alert.alert.mock.calls).toEqual([]);
 }finally{release();for(let i=0;i<64;i++)await act(async()=>{await Promise.resolve();});}
});

it.each(["after route commit","before route commit"])("keeps queued Native keyboard submissions retired while Root signout awaits its credential receipt: %s",async delivery=>{
 await mountNavigator();await type();await secureStore.removeItem("@mindpattern/username");
 const read=storage.getItem.bind(storage);let usernames=0,owners=0;let releaseFirst!:()=>void,releaseSecond!:()=>void,releaseOwner!:()=>void;
 const firstReceipt=new Promise<void>(resolve=>{releaseFirst=resolve;}),secondReceipt=new Promise<void>(resolve=>{releaseSecond=resolve;}),ownerReceipt=new Promise<void>(resolve=>{releaseOwner=resolve;});
 vi.spyOn(storage,"getItem").mockImplementation(async slot=>{
  const value=await read(slot);
  // Native storage has completed these reads. Hold only bridge delivery;
  // the physical executor remains free for the current signout cleanup.
  if(slot==="@mindpattern/username"){
   const receipt=++usernames;
   if(receipt===1)await firstReceipt;
   if(receipt===3)await secondReceipt;
  }
  if(slot==="@mindpattern/user_id"&&++owners===1)await ownerReceipt;
  return value;
 });
 let second:Promise<void>|undefined,third:Promise<void>|undefined;
 try{
  // Fabric can batch already queued native events before committing the
  // parent's logged-out route. Every input reads its current installed props.
  await act(async()=>{
   const first=password().props.onSubmitEditing();button("Sign out instead").props.onPress();second=password().props.onSubmitEditing();
   for(let i=0;i<32;i++)await Promise.resolve();releaseFirst();await first;
   if(delivery==="before route commit"){releaseSecond();await second;}
   third=password().props.onSubmitEditing();if(delivery==="before route commit")await third;
  });
  expect(Alert.alert.mock.calls).toEqual([]);
  releaseOwner();releaseSecond();await Promise.all([second,third]);
  await vi.waitFor(async()=>expect(await secureStore.getItem("@mindpattern/token")).toBeNull(),{timeout:1500});
  expect(root!.root.findAllByType(UnlockScreen)).toHaveLength(0);expect(vault.canReauthenticate()).toBe(false);expect(Alert.alert.mock.calls).toEqual([]);
 }finally{releaseFirst();releaseSecond();releaseOwner();await Promise.all([second,third]);}
});
