import crypto from "node:crypto";
import * as nativeVolume from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { api,DEFAULT_BASE_URL,canonicalOrigin } from "../src/api/client";
import { vault } from "../src/vault";
import { secureStore,setSecureStoreBackend } from "../src/secureStore";
import { captureLocalWritePermit,__resetLocalKeyLifecycleForTests } from "../src/localWriteGuard";
import { runTestControl } from "./helpers/testControl";
import storage from "./helpers/storageMock";
import * as fs from "./helpers/expoFsMock";
import * as sharing from "./helpers/expoSharingMock";
import * as keychain from "./helpers/keychainMock";
import { accountStorageKey,ACCOUNT_STORAGE_PREFIX } from "../src/accountStorage";
import { encryptAudio,decryptAudio } from "../src/crypto/journalCrypto";
import { enqueueAudio,listSavedAudio,audioQueueCount,audioQueueStatus,flushAudioQueue,retryAudioQueue,releaseAudioParent,removeSavedAudio,exportSavedAudio,prepareAudioRekey,cleanupAudioRekey,clearAudioQueue,abortInFlightAudioFlush,MAX_TAKE_BYTES,AudioTooLargeError,AudioQueueFullError } from "../src/audioQueue";
import { cacheEnvelope } from "../src/keyScheme";
const USER="a".repeat(32),OTHER="b".repeat(32),KEY=Buffer.alloc(32,7),SALT=Buffer.alloc(16,3),origin=canonicalOrigin(DEFAULT_BASE_URL),scope=Buffer.from(`${origin}\0${USER}`).toString("base64url"),slot=(id:string)=>`${ACCOUNT_STORAGE_PREFIX.audioQueue}${origin}:${USER}:${id}`;
const native={read:fs.readAsStringAsync.getMockImplementation()!,write:fs.writeAsStringAsync.getMockImplementation()!,remove:fs.deleteAsync.getMockImplementation()!,mkdir:fs.makeDirectoryAsync.getMockImplementation()!};
let status:number,uploads:Record<string,unknown>[],parentPresent:boolean,envelopeStatus:number,envelope:unknown;
beforeEach(async()=>{
 vi.restoreAllMocks();storage.__reset();fs.__resetFiles();fs.readAsStringAsync.mockImplementation(native.read);fs.writeAsStringAsync.mockImplementation(native.write);fs.deleteAsync.mockImplementation(native.remove);fs.makeDirectoryAsync.mockImplementation(native.mkdir);sharing.shareAsync.mockReset();sharing.shareAsync.mockResolvedValue();sharing.isAvailableAsync.mockReset();sharing.isAvailableAsync.mockResolvedValue(true);keychain.__reset();runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);abortInFlightAudioFlush();vault.lock();
 status=200;uploads=[];parentPresent=false;envelopeStatus=404;envelope=null;await api.setSession("native-bearer",USER,"alice");await api.cacheSalt("alice",SALT.toString("base64"));vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.from(KEY)},USER);
 vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const path=new URL(url).pathname;let value:unknown={},code=200;if(path.endsWith("/audio/attachments")){if(status===200)uploads.push(JSON.parse(String(init.body)));code=status;value=code===200?{}:{detail:"native attachment refused"};}else if(path.endsWith("/auth/key-envelope")){code=envelopeStatus;value=envelope??{detail:"legacy envelope endpoint absent"};}else if(path.includes("/entries/")){code=parentPresent?200:404;value=parentPresent?{id:"server-entry",client_entry_id:path.split("/").at(-1),blob:"",entry_date:"2026-10-07",content_version:1}:{detail:"parent has not committed"};}else throw new Error("unexpected native route "+path);const response=new Response(JSON.stringify(value),{status:code});Object.defineProperty(response,"url",{value:url});return response;});
});
afterEach(async()=>{vi.restoreAllMocks();vault.lock();await api.clearSession();vi.unstubAllGlobals();});
async function keep(id="recording",options:{parentPending?:boolean,durationSeconds?:number}={}){const blob=encryptAudio({dataKey:KEY},USER,id,Buffer.from("the user's retained spoken words"));await enqueueAudio({userId:USER,clientEntryId:id,...blob,mime:"audio/m4a",durationSeconds:options.durationSeconds??4,parentPending:options.parentPending},captureLocalWritePermit(USER,KEY));return blob.blobB64;}
async function descriptor(id="recording"){return JSON.parse((await storage.getItem(slot(id)))!);}
it("reports the exact saved revision and native timestamp while retaining authenticated ciphertext",async()=>{const blob=await keep();const row=await descriptor();expect(await listSavedAudio(USER)).toEqual([{id:"recording",queuedAt:row.queuedAt,needsAttention:false,revision:row.revision}]);expect(await audioQueueStatus(USER)).toEqual({total:1,needsAttention:0});expect(await fs.readAsStringAsync(row.uri)).toBe(blob);expect(row).toMatchObject({v:2,scope,mime:"audio/m4a",durationSeconds:4});});
it.each(["rejection","parentPending"])("discloses retained native %s metadata without deleting its file",async field=>{await keep();const row=await descriptor();row[field]=field==="rejection"?409:true;await storage.setItem(slot("recording"),JSON.stringify(row));expect(await listSavedAudio(USER)).toEqual([{id:"recording",queuedAt:row.queuedAt,needsAttention:true,revision:row.revision}]);expect(await audioQueueStatus(USER)).toEqual({total:1,needsAttention:1});expect(fs.__hasFile(row.uri)).toBe(true);});
it.each([null,"invalid json",{}, {mime:4,durationSeconds:4,queuedAt:1,blobB64:"cipher"},{mime:"audio/m4a",durationSeconds:-1,queuedAt:1,blobB64:"cipher"},{mime:"audio/m4a",durationSeconds:"4",queuedAt:1,blobB64:"cipher"},{mime:"audio/m4a",durationSeconds:4,queuedAt:null,blobB64:"cipher"}])("keeps an unreadable native descriptor in visible custody (%j)",async value=>{await storage.setItem(slot("damaged"),typeof value==="string"?value:JSON.stringify(value));expect(await listSavedAudio(USER)).toEqual([{id:"damaged",queuedAt:0,needsAttention:true,revision:undefined}]);expect(await audioQueueStatus(USER)).toEqual({total:1,needsAttention:1});expect(await flushAudioQueue()).toBe(0);expect(await storage.getItem(slot("damaged"))).not.toBeNull();});
it.each(["foreign scope","scope punctuation","wrong root","suffix traversal","missing revision"])("refuses an unsafe native file descriptor (%s) while preserving every unrelated file",async mode=>{await keep();const row=await descriptor(),unrelated=fs.documentDirectory+"unrelated-file";fs.__seedFile(unrelated,"another application's file");if(mode==="foreign scope")row.scope=Buffer.from("foreign").toString("base64url");if(mode==="scope punctuation")row.scope=scope+".";if(mode==="wrong root")row.uri=unrelated;if(mode==="suffix traversal")row.uri=row.uri+"/../unrelated-file";if(mode==="missing revision")delete row.revision;await storage.setItem(slot("recording"),JSON.stringify(row));expect(await listSavedAudio(USER)).toEqual([{id:"recording",queuedAt:0,needsAttention:true,revision:undefined}]);expect(await flushAudioQueue()).toBe(0);expect(fs.__hasFile(unrelated)).toBe(true);});
it.each(["missing file","oversized file"])("discloses a native %s without dropping the descriptor",async mode=>{await keep();const row=await descriptor();if(mode==="missing file")await fs.deleteAsync(row.uri);else fs.__seedFile(row.uri,"x".repeat(MAX_TAKE_BYTES+1));expect(await listSavedAudio(USER)).toEqual([{id:"recording",queuedAt:row.queuedAt,needsAttention:true,revision:row.revision}]);expect(await audioQueueStatus(USER)).toEqual({total:1,needsAttention:1});expect(await flushAudioQueue()).toBe(0);expect(await audioQueueCount(USER)).toBe(1);});
it("accepts the exact retained byte bound as authenticated audio and rejects one byte more",async()=>{const id="bounded",blob=encryptAudio({dataKey:KEY},USER,id,Buffer.alloc(4_499_972,9));expect(blob.blobB64.length).toBe(MAX_TAKE_BYTES);await enqueueAudio({userId:USER,clientEntryId:id,...blob,mime:"audio/m4a",durationSeconds:0},captureLocalWritePermit(USER,KEY));expect(await listSavedAudio(USER)).toMatchObject([{id,needsAttention:false}]);expect(await flushAudioQueue()).toBe(1);expect(decryptAudio({dataKey:KEY},USER,id,String(uploads[0]!.blob))).toEqual(Buffer.alloc(4_499_972,9));await expect(enqueueAudio({userId:USER,clientEntryId:"too-large",blobB64:blob.blobB64+"x",mime:"audio/m4a",durationSeconds:0},captureLocalWritePermit(USER,KEY))).rejects.toBeInstanceOf(AudioTooLargeError);},120000);
it.each([-1,Infinity,NaN])("refuses an invalid native recording duration %j before retaining a descriptor",async duration=>{await expect(keep("bad-duration",{durationSeconds:duration})).rejects.toThrow("Invalid recording");expect(await audioQueueCount(USER)).toBe(0);});
it("removes a partial native ciphertext file after its write fails",async()=>{const write=fs.writeAsStringAsync.getMockImplementation()!;fs.writeAsStringAsync.mockImplementation(async(uri,value,...args)=>{await write(uri,value,...args);throw new Error("native ciphertext disk full");});await expect(keep()).rejects.toThrow("native ciphertext disk full");expect(await listSavedAudio(USER)).toEqual([]);for(const[uri]of fs.writeAsStringAsync.mock.calls)expect(fs.__hasFile(uri)).toBe(false);});
it("retains an old native revision if replacement descriptor persistence fails",async()=>{const blob=await keep(),old=await descriptor();const write=storage.setItem;vi.spyOn(storage,"setItem").mockImplementation(async(key,value)=>{if(key===slot("recording"))throw new Error("native descriptor disk full");return write(key,value);});await expect(keep()).rejects.toThrow("native descriptor disk full");expect(await descriptor()).toEqual(old);expect(await fs.readAsStringAsync(old.uri)).toBe(blob);for(const[uri]of fs.writeAsStringAsync.mock.calls)if(uri!==old.uri)expect(fs.__hasFile(uri)).toBe(false);});
it("migrates a legacy native blob only after file completion and uploads its exact authored metadata",async()=>{const blob=encryptAudio({dataKey:KEY},USER,"legacy",Buffer.from("legacy spoken words"));await storage.setItem(slot("legacy"),JSON.stringify({...blob,mime:"audio/m4a",durationSeconds:0,queuedAt:123}));expect(await flushAudioQueue()).toBe(1);expect(uploads).toEqual([{client_entry_id:"legacy",blob:blob.blobB64,mime:"audio/m4a",duration_seconds:0}]);expect(await listSavedAudio(USER)).toEqual([]);});
it.each([401,403,404,409,413,500])("retains the native recording after HTTP %s and supports deliberate retry",async failure=>{await keep();status=failure;expect(await flushAudioQueue()).toBe(0);expect(await audioQueueCount(USER)).toBe(1);expect((await listSavedAudio(USER))[0]!.needsAttention).toBe(failure!==401&&failure!==500);status=200;await api.setSession("replacement-bearer",USER,"alice");await retryAudioQueue(USER);expect(uploads).toHaveLength(1);expect(await listSavedAudio(USER)).toEqual([]);});
it("does not retry a rejected native take before its 15-minute deadline",async()=>{await keep();status=409;await flushAudioQueue();const row=await descriptor();expect(row).toMatchObject({rejection:409,notBefore:expect.any(Number)});status=200;vi.useFakeTimers({toFake:["Date"]});vi.setSystemTime(row.notBefore-1);expect(await flushAudioQueue()).toBe(0);vi.setSystemTime(row.notBefore);expect(await flushAudioQueue()).toBe(1);vi.useRealTimers();});
it("recovers an acknowledged parent from the native endpoint and keeps an absent parent's recording",async()=>{await keep("parent-one",{parentPending:true});expect(await flushAudioQueue()).toBe(0);await retryAudioQueue(USER);expect(await audioQueueCount(USER)).toBe(1);parentPresent=true;await retryAudioQueue(USER);expect(uploads).toHaveLength(1);expect(await listSavedAudio(USER)).toEqual([]);});
it("releases an admitted native parent's descriptor without changing its voice bytes",async()=>{const blob=await keep("parent-one",{parentPending:true});await releaseAudioParent(USER,"parent-one",captureLocalWritePermit(USER,KEY));expect((await listSavedAudio(USER))[0]!.needsAttention).toBe(false);expect(await flushAudioQueue()).toBe(1);expect(uploads[0]!.blob).toBe(blob);});
it("exports a complete native legacy bundle whose ciphertext opens independently and preserves custody",async()=>{const blob=await keep();await exportSavedAudio(USER,"recording");const uri=sharing.shareAsync.mock.calls[0]![0],bundle=JSON.parse(await fs.readAsStringAsync(uri)),row=await descriptor();expect(bundle).toEqual({version:2,user_id:USER,username:"alice",salt:SALT.toString("base64"),key_scheme:"v1",kdf_params:null,wrapped_data_key:null,entries:[],insights:[],measures:[],audio:[{client_entry_id:"recording",blob,mime_type:"audio/m4a",duration_seconds:4,content_version:1,created_at:new Date(row.queuedAt).toISOString()}]});expect(decryptAudio({dataKey:KEY},USER,"recording",bundle.audio[0].blob)).toEqual(Buffer.from("the user's retained spoken words"));expect(await audioQueueCount(USER)).toBe(1);await removeSavedAudio(USER,"recording",row.revision);expect(fs.__hasFile(uri)).toBe(false);expect(fs.__hasFile(row.uri)).toBe(false);expect(await listSavedAudio(USER)).toEqual([]);});
it("exports the current native v2 envelope with independently usable unlock parameters",async()=>{
 await keep();const password="the exported account's actual password",params={algorithm:"pbkdf2-sha256",version:1,iterations:600000} as const,salt=SALT.toString("base64"),master=crypto.pbkdf2Sync(password,SALT,params.iterations,32,"sha256"),kek=Buffer.from(crypto.hkdfSync("sha256",master,SALT,Buffer.from("mindpattern/envelope/v2"),32)),nonce=Buffer.alloc(12,6),cipher=crypto.createCipheriv("aes-256-gcm",kek,nonce);cipher.setAAD(Buffer.from(JSON.stringify({context:"envelope",kdf_params:params,username:"alice"})));const wrapped=Buffer.concat([nonce,cipher.update(KEY),cipher.final(),cipher.getAuthTag()]).toString("base64");
 await cacheEnvelope("alice",{scheme:"v2",saltB64:salt,kdfParams:params,wrappedB64:wrapped});await exportSavedAudio(USER,"recording");const uri=sharing.shareAsync.mock.calls[0]![0],bundle=JSON.parse(await fs.readAsStringAsync(uri));expect(bundle).toMatchObject({key_scheme:"v2",kdf_params:params,wrapped_data_key:wrapped,salt,user_id:USER});
 const freshMaster=crypto.pbkdf2Sync(password,Buffer.from(bundle.salt,"base64"),bundle.kdf_params.iterations,32,"sha256"),freshKek=Buffer.from(crypto.hkdfSync("sha256",freshMaster,Buffer.from(bundle.salt,"base64"),Buffer.from("mindpattern/envelope/v2"),32)),envelopeBytes=Buffer.from(bundle.wrapped_data_key,"base64"),decipher=crypto.createDecipheriv("aes-256-gcm",freshKek,envelopeBytes.subarray(0,12));decipher.setAAD(Buffer.from(JSON.stringify({context:"envelope",kdf_params:bundle.kdf_params,username:bundle.username})));decipher.setAuthTag(envelopeBytes.subarray(-16));const freshData=Buffer.concat([decipher.update(envelopeBytes.subarray(12,-16)),decipher.final()]);expect(decryptAudio({dataKey:freshData},bundle.user_id,bundle.audio[0].client_entry_id,bundle.audio[0].blob)).toEqual(Buffer.from("the user's retained spoken words"));expect(await audioQueueCount(USER)).toBe(1);master.fill(0);kek.fill(0);freshMaster.fill(0);freshKek.fill(0);freshData.fill(0);
});
it.each([401,403,404,409,413])("sets the exact future native retry deadline after HTTP %s",async failure=>{
 vi.useFakeTimers({toFake:["Date"]});vi.setSystemTime(10_000);try{await keep();status=failure;expect(await flushAudioQueue()).toBe(0);const row=await descriptor();expect(row.notBefore).toBe(910_000);status=200;expect(await flushAudioQueue()).toBe(0);vi.setSystemTime(909_999);expect(await flushAudioQueue()).toBe(0);vi.setSystemTime(910_000);expect(await flushAudioQueue()).toBe(1);expect(decryptAudio({dataKey:KEY},USER,"recording",String(uploads[0]!.blob))).toEqual(Buffer.from("the user's retained spoken words"));}finally{vi.useRealTimers();}
});
async function physicalDirectoryVolume(){
 const volume=await nativeVolume.mkdtemp(join(tmpdir(),"mindpattern-audio-native-directory-"));const physical=(uri:string)=>join(volume,uri.slice(fs.documentDirectory.length));
 fs.makeDirectoryAsync.mockImplementation(async(uri:string,options?:{intermediates?:boolean})=>{if(!uri.startsWith(fs.documentDirectory))throw new Error("native directory is outside the app volume");await nativeVolume.mkdir(physical(uri),{recursive:options?.intermediates===true});});
 return {physical,cleanup:()=>nativeVolume.rm(volume,{recursive:true,force:true})};
}
it("creates the account's physical native recording directory on a fresh device volume",async()=>{
 const volume=await physicalDirectoryVolume();try{const blob=await keep(),row=await descriptor();expect((await nativeVolume.stat(volume.physical(row.uri.slice(0,row.uri.lastIndexOf("/")+1)))).isDirectory()).toBe(true);expect(await fs.readAsStringAsync(row.uri)).toBe(blob);expect(await audioQueueCount(USER)).toBe(1);}finally{await volume.cleanup();}
});
it("permits a second native ciphertext export into the account's existing physical share directory",async()=>{
 const volume=await physicalDirectoryVolume();try{await keep();await exportSavedAudio(USER,"recording");await exportSavedAudio(USER,"recording");expect(sharing.shareAsync.mock.calls).toHaveLength(2);const uri=sharing.shareAsync.mock.calls[1]![0];expect((await nativeVolume.stat(volume.physical(uri.slice(0,uri.lastIndexOf("/")+1)))).isDirectory()).toBe(true);expect(JSON.parse(await fs.readAsStringAsync(uri)).audio).toHaveLength(1);expect(await audioQueueCount(USER)).toBe(1);}finally{await volume.cleanup();}
});
it.each(["missing descriptor","missing username","missing salt","unknown envelope","unavailable sharing"])("refuses native export with an honest %s outcome while keeping the only recording",async failure=>{if(failure!=="missing descriptor")await keep();if(failure==="missing username")await secureStore.removeItem("@mindpattern/username");if(failure==="missing salt")await api.clearCachedSalt("alice");if(failure==="unknown envelope")envelopeStatus=500;if(failure==="unavailable sharing")sharing.isAvailableAsync.mockResolvedValue(false);const message={"missing descriptor":"This saved recording could not be read","missing username":"No saved account","missing salt":"Unlock online once before exporting this recording","unknown envelope":"The account's encryption format could not be verified; unlock online before exporting","unavailable sharing":"File sharing is unavailable on this device"}[failure]!;await expect(exportSavedAudio(USER,"recording")).rejects.toThrow(message);expect(sharing.shareAsync.mock.calls).toEqual([]);expect(await audioQueueCount(USER)).toBe(failure==="missing descriptor"?0:1);});
it("prepares native replacements that open with the new key without changing the retained old copies",async()=>{const old=await keep(),before=await descriptor(),nextKey=Buffer.alloc(32,8),changes=await prepareAudioRekey(USER,KEY,nextKey);expect(changes).toHaveLength(1);expect(changes[0]).toMatchObject({key:slot("recording"),before:JSON.stringify(before)});const next=JSON.parse(changes[0]!.after);expect(decryptAudio({dataKey:nextKey},USER,"recording",await fs.readAsStringAsync(next.uri))).toEqual(Buffer.from("the user's retained spoken words"));expect(await fs.readAsStringAsync(before.uri)).toBe(old);await cleanupAudioRekey(changes,"after");expect(fs.__hasFile(next.uri)).toBe(false);expect(fs.__hasFile(before.uri)).toBe(true);});
it("removes earlier staged native replacements after a later retained take is corrupt",async()=>{await keep("a-good");await keep("z-bad");const originalUris=[(await descriptor("a-good")).uri,(await descriptor("z-bad")).uri];fs.__seedFile(originalUris[1],"corrupt ciphertext");const firstWrites=fs.writeAsStringAsync.mock.calls.length;await expect(prepareAudioRekey(USER,KEY,Buffer.alloc(32,8))).rejects.toThrow();for(const[uri]of fs.writeAsStringAsync.mock.calls.slice(firstWrites))expect(fs.__hasFile(uri)).toBe(false);for(const uri of originalUris)expect(fs.__hasFile(uri)).toBe(true);expect(await audioQueueCount(USER)).toBe(2);});
it("reports an unreadable native rekey descriptor before producing replacements",async()=>{await storage.setItem(slot("corrupt"),"invalid descriptor");await expect(prepareAudioRekey(USER,KEY,Buffer.alloc(32,8))).rejects.toThrow("A retained recording needs repair before key rotation");expect(await storage.getItem(slot("corrupt"))).toBe("invalid descriptor");});
it("clears the entire scoped native directory including crash-left exports without deleting another owner's files",async()=>{await keep();const orphan=fs.documentDirectory+`mindpattern-audio/${scope}/orphan.enc`,other=fs.documentDirectory+`mindpattern-audio/${Buffer.from(`${origin}\0${OTHER}`).toString("base64url")}/other.enc`;fs.__seedFile(orphan);fs.__seedFile(other);await clearAudioQueue(USER);expect(fs.__hasFile(orphan)).toBe(false);expect(fs.__hasFile(other)).toBe(true);expect(await audioQueueCount(USER)).toBe(0);});
it.each([{withLegacyBlob:false,relabeled:false},{withLegacyBlob:true,relabeled:false},{withLegacyBlob:false,relabeled:true},{withLegacyBlob:true,relabeled:true}])("preserves another account's authenticated native file when a foreign descriptor occupies a replaced local slot (%j)",async({withLegacyBlob,relabeled})=>{
 const otherKey=Buffer.alloc(32,8);await api.setSession("other-bearer",OTHER,"bob");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,3),dataKey:Buffer.from(otherKey)},OTHER);const blob=encryptAudio({dataKey:otherKey},OTHER,"foreign",Buffer.from("the other account's retained voice"));await enqueueAudio({userId:OTHER,clientEntryId:"foreign",...blob,mime:"audio/m4a",durationSeconds:4},captureLocalWritePermit(OTHER,otherKey));const foreign=JSON.parse((await storage.getItem(`${ACCOUNT_STORAGE_PREFIX.audioQueue}${origin}:${OTHER}:foreign`))!);
 await api.setSession("native-bearer",USER,"alice");vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.from(KEY)},USER);await storage.setItem(slot("recording"),JSON.stringify({...foreign,...(relabeled?{scope}:{}),...(withLegacyBlob?{blobB64:blob.blobB64}:{})}));await keep();expect(fs.__hasFile(foreign.uri)).toBe(true);expect(decryptAudio({dataKey:otherKey},OTHER,"foreign",await fs.readAsStringAsync(foreign.uri))).toEqual(Buffer.from("the other account's retained voice"));expect(await listSavedAudio(USER)).toMatchObject([{id:"recording",needsAttention:false}]);
});

it("opens the native share sheet with the JSON media type and universal type identifier",async()=>{await keep();await exportSavedAudio(USER,"recording");expect(sharing.shareAsync.mock.calls[0]?.[1]).toEqual({mimeType:"application/json",UTI:"public.json"});});

it("exports an authentic cached envelope even while the native network radio is unavailable",async()=>{
 await keep();await cacheEnvelope("alice",{scheme:"v1",saltB64:SALT.toString("base64"),kdfParams:null,wrappedB64:null});const transport=fetch;let release:()=>void=()=>{};vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(new URL(url).pathname.endsWith("/auth/key-envelope"))await new Promise<void>(resolve=>{release=resolve;});return transport(url,init);});let settled=false;const pending=exportSavedAudio(USER,"recording").then(()=>{settled=true;});try{await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(sharing.shareAsync.mock.calls).toHaveLength(1);}finally{release();await pending;}
});

it.each(["upload","removal","export","parent release"])("refuses an admitted native %s after the explicit recording queue cancellation",async operation=>{
 await keep("recording",{parentPending:operation==="parent release"});const row=await descriptor(),read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key===slot("recording")&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let pending:Promise<unknown>;if(operation==="upload")pending=flushAudioQueue();else if(operation==="removal")pending=removeSavedAudio(USER,"recording",row.revision);else if(operation==="export")pending=exportSavedAudio(USER,"recording");else pending=releaseAudioParent(USER,"recording",captureLocalWritePermit(USER,KEY));const observed=pending.catch(error=>error);await Promise.race([started,observed]);abortInFlightAudioFlush();try{release();await observed;expect(await storage.getItem(slot("recording"))).toBe(JSON.stringify(row));expect(await fs.readAsStringAsync(row.uri)).toBeDefined();expect(uploads).toEqual([]);expect(sharing.shareAsync.mock.calls).toEqual([]);}finally{release();await observed;}
});

it("retains the public error identities used to explain device recording capacity",()=>{expect(new AudioTooLargeError()).toMatchObject({name:"AudioTooLargeError",message:"kept-recording queue: take exceeds the on-device bound"});expect(new AudioQueueFullError()).toMatchObject({name:"AudioQueueFullError",message:"kept-recording queue is full — sync or remove a saved take first"});});

it("preserves a legacy take's rejected status and retry receipt during native file migration after another server failure",async()=>{
 const id="legacy-rejected",blob=encryptAudio({dataKey:KEY},USER,id,Buffer.from("the account's legacy spoken words"));await storage.setItem(slot(id),JSON.stringify({blobB64:blob.blobB64,mime:"audio/m4a",durationSeconds:4,queuedAt:1,rejection:409,notBefore:9000}));vi.useFakeTimers({toFake:["Date"]});vi.setSystemTime(10000);status=500;try{expect(await flushAudioQueue()).toBe(0);expect(await descriptor(id)).toMatchObject({v:2,rejection:409,notBefore:9000});expect(await listSavedAudio(USER)).toMatchObject([{id,needsAttention:true}]);status=200;vi.setSystemTime(8999);expect(await flushAudioQueue()).toBe(0);expect(uploads).toEqual([]);vi.setSystemTime(9000);expect(await flushAudioQueue()).toBe(1);expect(decryptAudio({dataKey:KEY},USER,id,String(uploads[0].blob))).toEqual(Buffer.from("the account's legacy spoken words"));}finally{vi.useRealTimers();}
});

it.each(["successful staging","failed native staging"])("erases the actual decrypted native voice allocation after %s",async failure=>{
 await keep();const concat=Buffer.concat,allocations:Buffer[]=[];vi.spyOn(Buffer,"concat").mockImplementation(((...args:any[])=>{const value=(concat as(...values:any[])=>Buffer)(...args);if(value.equals(Buffer.from("the user's retained spoken words")))allocations.push(value);return value;}) as any);if(failure==="failed native staging")fs.writeAsStringAsync.mockRejectedValueOnce(new Error("native staging volume unavailable"));const pending=prepareAudioRekey(USER,KEY,Buffer.alloc(32,8));if(failure==="failed native staging")await expect(pending).rejects.toThrow("native staging volume unavailable");else await pending;expect(allocations.length).toBeGreaterThan(0);for(const value of allocations)expect(value.every(byte=>byte===0)).toBe(true);expect(fs.__hasFile((await descriptor()).uri)).toBe(true);
});

it("does not resurrect a retired native upload epoch when explicit abort is followed by account queue clearing",async()=>{
 await keep();const row=await descriptor(),read=fs.readAsStringAsync.getMockImplementation()!;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});fs.readAsStringAsync.mockImplementation(async(uri,...options)=>{const value=await read(uri,...options);if(uri===row.uri&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const pending=flushAudioQueue();await Promise.race([started,pending]);abortInFlightAudioFlush();await clearAudioQueue(USER);const fresh=await keep();try{release();expect(await pending).toBe(0);expect(uploads).toEqual([]);expect(await audioQueueCount(USER)).toBe(1);expect(await flushAudioQueue()).toBe(1);expect(uploads[0].blob).toBe(fresh);}finally{release();await pending;}
});

it.each(["save","remove","export","release parent","upload"].flatMap(operation=>["queue cancellation","replacement credentials"].map(retirement=>({operation,retirement}))))("completes retired native $operation after $retirement without waiting for an unavailable old descriptor provider",async({operation,retirement})=>{
 await keep("recording",{parentPending:operation==="release parent"});const row=await descriptor(),read=storage.getItem;let initial=true,releaseOrigin:()=>void=()=>{},releaseDescriptor:()=>void=()=>{},ready!:()=>void,retired=false;const started=new Promise<void>(resolve=>{ready=resolve;});
 vi.spyOn(storage,"getItem").mockImplementation(async key=>{const raw=await read(key);if(key==="@mindpattern/base_url"&&initial){initial=false;ready();await new Promise<void>(resolve=>{releaseOrigin=resolve;});}else if(retired&&key===slot("recording"))await new Promise<void>(resolve=>{releaseDescriptor=resolve;});return raw;});
 let pending:Promise<unknown>;if(operation==="save")pending=keep();else if(operation==="remove")pending=removeSavedAudio(USER,"recording",row.revision);else if(operation==="export")pending=exportSavedAudio(USER,"recording");else if(operation==="release parent")pending=releaseAudioParent(USER,"recording",captureLocalWritePermit(USER,KEY));else pending=flushAudioQueue();let settled=false;const observed=pending.catch(error=>error).then(value=>{settled=true;return value;});await Promise.race([started,observed]);
 if(retirement==="queue cancellation")abortInFlightAudioFlush();else await api.setSession("replacement-bearer",USER,"alice");retired=true;
 try{releaseOrigin();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);const value=await observed;if(operation==="save"||operation==="remove"||operation==="export"){expect(value).toBeInstanceOf(Error);if(retirement==="queue cancellation")expect((value as Error).message).toBe({save:"Recording save was cancelled by account cleanup",remove:"Recording removal was cancelled by account cleanup",export:"Recording export was cancelled by account cleanup"}[operation]);}expect(uploads).toEqual([]);expect(sharing.shareAsync.mock.calls).toEqual([]);}finally{retired=false;releaseOrigin();releaseDescriptor();await observed;}
 expect(await storage.getItem(slot("recording"))).toBe(JSON.stringify(row));expect(fs.__hasFile(row.uri)).toBe(true);
});

it("retains a newer native take when an older legacy descriptor arrives after its replacement",async()=>{
 const blob=encryptAudio({dataKey:KEY},USER,"recording",Buffer.from("legacy words"));await storage.setItem(slot("recording"),JSON.stringify({blobB64:blob.blobB64,mime:"audio/m4a",durationSeconds:4,queuedAt:1}));const read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const raw=await read(key);if(first&&key===slot("recording")){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return raw;});const pending=flushAudioQueue();await Promise.race([started,pending]);const fresh=await keep(),row=await descriptor();try{release();expect(await pending).toBe(0);expect(await descriptor()).toEqual(row);expect(uploads).toEqual([]);expect(await fs.readAsStringAsync(row.uri)).toBe(fresh);expect(await flushAudioQueue()).toBe(1);expect(uploads[0].blob).toBe(fresh);}finally{release();await pending;}
});

it("releases canceled native legacy migration custody before a fresh recording is admitted",async()=>{
 const blob=encryptAudio({dataKey:KEY},USER,"recording",Buffer.from("legacy canceled words"));await storage.setItem(slot("recording"),JSON.stringify({blobB64:blob.blobB64,mime:"audio/m4a",durationSeconds:4,queuedAt:1}));const read=storage.getItem;let count=0,releaseFirst:()=>void=()=>{},releaseSecond:()=>void=()=>{},ready!:()=>void,blocked=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const raw=await read(key);if(key===slot("recording")){count++;if(count===1){ready();await new Promise<void>(resolve=>{releaseFirst=resolve;});}else if(count===2&&blocked)await new Promise<void>(resolve=>{releaseSecond=resolve;});}return raw;});const pending=flushAudioQueue();await Promise.race([started,pending]);abortInFlightAudioFlush();releaseFirst();let settled=false;const fresh=keep("fresh").then(value=>{settled=true;return value;});try{await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);expect(await fresh).toBeDefined();expect(uploads).toEqual([]);}finally{blocked=false;releaseFirst();releaseSecond();await pending;await fresh;}
});

it("lists native kept recordings in stable identifier order after reverse admission",async()=>{await keep("z-last");await keep("a-first");expect((await listSavedAudio(USER)).map(row=>row.id)).toEqual(["a-first","z-last"]);});

it("refuses an unrecognised prefix before the native encrypted filename while keeping its descriptor",async()=>{
 await keep();const row=await descriptor(),unsafe={...row,uri:row.uri.replace(row.revision,"unexpected-"+row.revision)};fs.__seedFile(unsafe.uri,await fs.readAsStringAsync(row.uri));await storage.setItem(slot("recording"),JSON.stringify(unsafe));expect(await listSavedAudio(USER)).toEqual([{id:"recording",queuedAt:0,needsAttention:true,revision:undefined}]);expect(await flushAudioQueue()).toBe(0);expect(fs.__hasFile(unsafe.uri)).toBe(true);
});
it("uploads an authentic legacy take with an unrecognised legacy version field",async()=>{
 const blob=encryptAudio({dataKey:KEY},USER,"recording",Buffer.from("legacy version words"));await storage.setItem(slot("recording"),JSON.stringify({v:1,blobB64:blob.blobB64,mime:"audio/m4a",durationSeconds:4,queuedAt:1}));expect(await listSavedAudio(USER)).toEqual([{id:"recording",queuedAt:1,needsAttention:false,revision:undefined}]);expect(await flushAudioQueue()).toBe(1);expect(decryptAudio({dataKey:KEY},USER,"recording",String(uploads[0].blob))).toEqual(Buffer.from("legacy version words"));
});
it("removes an absent native descriptor as an idempotent public operation",async()=>{
 await expect(removeSavedAudio(USER,"already-removed")).resolves.toBeUndefined();expect(await audioQueueCount(USER)).toBe(0);await expect(releaseAudioParent(USER,"already-removed",captureLocalWritePermit(USER,KEY))).resolves.toBeUndefined();expect(await audioQueueCount(USER)).toBe(0);
});
it("removes an unreadable saved take whose native file was already lost",async()=>{
 await keep();const row=await descriptor();await fs.deleteAsync(row.uri);const remove=native.remove;fs.deleteAsync.mockImplementation(async(uri,options)=>{if(!fs.__hasFile(uri)&&!options?.idempotent)throw new Error("Native recording file is absent");return remove(uri,options);});await expect(removeSavedAudio(USER,"recording",row.revision)).resolves.toBeUndefined();expect(await storage.getItem(slot("recording"))).toBeNull();expect(await audioQueueCount(USER)).toBe(0);
});
it("reports the native write failure when no recording file was created",async()=>{
 const remove=native.remove;fs.deleteAsync.mockImplementation(async(uri,options)=>{if(!fs.__hasFile(uri)&&!options?.idempotent)throw new Error("Native recording file is absent");return remove(uri,options);});fs.writeAsStringAsync.mockRejectedValueOnce(new Error("Native recording volume is full"));await expect(keep()).rejects.toThrow("Native recording volume is full");expect(await audioQueueCount(USER)).toBe(0);
});
it.each([[],["cipher"],{},null,4,false])("discloses a malformed legacy Native voice value %j without pretending its timestamp is readable",async blobB64=>{await storage.setItem(slot("legacy-invalid"),JSON.stringify({blobB64,mime:"audio/m4a",durationSeconds:4,queuedAt:123}));expect(await listSavedAudio(USER)).toEqual([{id:"legacy-invalid",queuedAt:0,needsAttention:true,revision:undefined}]);expect(await flushAudioQueue()).toBe(0);expect(uploads).toEqual([]);});
it("accepts the exact authentic legacy Native byte bound and rejects an oversized legacy record",async()=>{const id="legacy-bound",blob=encryptAudio({dataKey:KEY},USER,id,Buffer.alloc(4_499_972,9));expect(blob.blobB64.length).toBe(MAX_TAKE_BYTES);await storage.setItem(slot(id),JSON.stringify({blobB64:blob.blobB64,mime:"audio/m4a",durationSeconds:0,queuedAt:123}));expect(await listSavedAudio(USER)).toEqual([{id,queuedAt:123,needsAttention:false,revision:undefined}]);expect(await flushAudioQueue()).toBe(1);expect(uploads[0].blob).toBe(blob.blobB64);await storage.setItem(slot("oversized-legacy"),JSON.stringify({blobB64:blob.blobB64+"x",mime:"audio/m4a",durationSeconds:0,queuedAt:123}));expect(await listSavedAudio(USER)).toEqual([{id:"oversized-legacy",queuedAt:0,needsAttention:true,revision:undefined}]);});
it.each(["missing","legacy replacement"])("refuses the retained native removal revision for a %s descriptor",async kind=>{const blob=await keep(),row=await descriptor();if(kind==="missing")await storage.removeItem(slot("recording"));else await storage.setItem(slot("recording"),JSON.stringify({blobB64:blob,mime:"audio/m4a",durationSeconds:4,queuedAt:123,revision:row.revision}));const retained=await storage.getItem(slot("recording"));await expect(removeSavedAudio(USER,"recording",row.revision)).rejects.toThrow("The saved recording changed; refresh before removing it");expect(await storage.getItem(slot("recording"))).toBe(retained);expect(fs.__hasFile(row.uri)).toBe(true);});
it("reports the unavailable Native persistent-directory capability before attempting a recording save",async()=>{vi.spyOn(fs,"documentDirectory","get").mockReturnValue(null as any);const mkdir=fs.makeDirectoryAsync.getMockImplementation()!;fs.makeDirectoryAsync.mockImplementation(async(uri,...options)=>{if(!uri.startsWith("file://"))throw new Error("Native directory URI is invalid");return mkdir(uri,...options);});await expect(keep()).rejects.toThrow("Persistent recording storage is unavailable");expect(await listSavedAudio(USER)).toEqual([]);});

it("uses an explicit Native queue-status owner while another authenticated account has no recordings",async()=>{await keep();await api.setSession("other-bearer",OTHER,"bob");expect(await audioQueueStatus(USER)).toEqual({total:1,needsAttention:0});});
it("returns exact ownerless Native queue receipts without manufacturing erasure storage",async()=>{await api.clearSession();const before=await storage.getAllKeys();expect(await audioQueueStatus()).toEqual({total:0,needsAttention:0});expect(await flushAudioQueue()).toBe(0);await clearAudioQueue();expect(await storage.getAllKeys()).toEqual(before);});
it("completes a canceled Native page inventory without consulting unavailable retired voice descriptors",async()=>{
 await keep();const inventory=storage.getAllKeys,read=storage.getItem;let first=true,releaseInventory:()=>void=()=>{},releaseDescriptor:()=>void=()=>{},ready!:()=>void,retired=false;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getAllKeys").mockImplementation(async()=>{const keys=await inventory();if(first){first=false;ready();await new Promise<void>(resolve=>{releaseInventory=resolve;});}return keys;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(retired&&key===slot("recording"))await new Promise<void>(resolve=>{releaseDescriptor=resolve;});return read(key);});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});await Promise.race([started,pending]);abortInFlightAudioFlush();retired=true;try{releaseInventory();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);expect(uploads).toEqual([]);}finally{retired=false;releaseInventory();releaseDescriptor();await pending;}
});
it("refuses obsolete Native legacy migration before an unavailable staging volume can hold its completion",async()=>{
 const legacy=encryptAudio({dataKey:KEY},USER,"recording",Buffer.from("obsolete legacy voice"));await storage.setItem(slot("recording"),JSON.stringify({blobB64:legacy.blobB64,mime:"audio/m4a",durationSeconds:4,queuedAt:123}));const read=storage.getItem;let first=true,releaseRead:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const raw=await read(key);if(first&&key===slot("recording")){first=false;ready();await new Promise<void>(resolve=>{releaseRead=resolve;});}return raw;});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});await Promise.race([started,pending]);await keep();const fresh=await descriptor(),mkdir=fs.makeDirectoryAsync.getMockImplementation()!;let releaseVolume:()=>void=()=>{},unavailable=true;fs.makeDirectoryAsync.mockImplementation(async(uri,...options)=>{if(unavailable)await new Promise<void>(resolve=>{releaseVolume=resolve;});return mkdir(uri,...options);});try{releaseRead();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);expect(await descriptor()).toEqual(fresh);expect(uploads).toEqual([]);}finally{unavailable=false;releaseRead();releaseVolume();await pending;}
});

it("refuses an empty Native recording identifier before writing its encrypted voice",async()=>{const blob=encryptAudio({dataKey:KEY},USER,"recording",Buffer.from("retained native voice"));await expect(enqueueAudio({userId:USER,clientEntryId:"",...blob,mime:"audio/m4a",durationSeconds:4},captureLocalWritePermit(USER,KEY))).rejects.toThrow("Invalid recording");expect(await listSavedAudio(USER)).toEqual([]);});
it("refuses to adopt replacement credentials when an earlier Native upload-owner lookup completes",async()=>{await keep();const read=secureStore.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key==="@mindpattern/user_id"){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const pending=flushAudioQueue();await Promise.race([started,pending]);await api.setSession("replacement-bearer",USER,"alice");try{release();expect(await pending).toBe(0);expect(uploads).toEqual([]);expect(await audioQueueCount(USER)).toBe(1);expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}finally{release();await pending;}});

it.each(["descriptor","account","envelope","salt","blob","sharing","directory"])("finishes canceled Native export after %s delivery before an unavailable subsequent provider",async stage=>{
 await keep();if(stage!=="salt")await cacheEnvelope("alice",{scheme:"v1",saltB64:SALT.toString("base64"),kdfParams:null,wrappedB64:null});const read=storage.getItem,secureRead=secureStore.getItem,fileRead=native.read,mkdir=native.mkdir,write=native.write,capability=sharing.isAvailableAsync.getMockImplementation()!;let admitted=false,retired=false,release:()=>void=()=>{},releaseNext:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});
 const nativeDelivery=async<T,>(name:string,value:T):Promise<T>=>{if(name===stage&&!admitted){admitted=true;ready();await new Promise<void>(resolve=>{release=resolve;});}else if(retired&&name===({descriptor:"account",account:"envelope",envelope:"blob",salt:"blob",blob:"sharing",sharing:"directory",directory:"write"} as Record<string,string>)[stage])await new Promise<void>(resolve=>{releaseNext=resolve;});return value;};
 vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key===slot("recording"))return nativeDelivery("descriptor",value);if(key===ACCOUNT_STORAGE_PREFIX.keyEnvelope+Buffer.from("alice").toString("base64url"))return nativeDelivery("envelope",value);if(key===ACCOUNT_STORAGE_PREFIX.salt+Buffer.from("alice").toString("base64url"))return nativeDelivery("salt",value);return value;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await secureRead(key);return key==="@mindpattern/username"?nativeDelivery("account",value):value;});fs.readAsStringAsync.mockImplementation(async(...args)=>nativeDelivery("blob",await fileRead(...args)));sharing.isAvailableAsync.mockImplementation(async()=>nativeDelivery("sharing",await capability()));fs.makeDirectoryAsync.mockImplementation(async(...args)=>{await nativeDelivery("directory",undefined);return mkdir(...args);});fs.writeAsStringAsync.mockImplementation(async(...args)=>{await nativeDelivery("write",undefined);return write(...args);});let settled=false;const pending=exportSavedAudio(USER,"recording").catch(error=>error).then(value=>{settled=true;return value;});await Promise.race([started,pending]);expect(admitted).toBe(true);abortInFlightAudioFlush();retired=true;
 try{release();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect((await pending).message).toBe("Recording export was cancelled by account cleanup");expect(sharing.shareAsync.mock.calls).toEqual([]);}finally{retired=false;release();releaseNext();await pending;}
 expect(await audioQueueCount(USER)).toBe(1);
});
it("preserves a canceled Native save's public reason after its actual file write finishes",async()=>{
 const write=native.write;let release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});fs.writeAsStringAsync.mockImplementation(async(...args)=>{await write(...args);ready();await new Promise<void>(resolve=>{release=resolve;});});const pending=keep().catch(error=>error);await Promise.race([started,pending]);abortInFlightAudioFlush();try{release();expect((await pending).message).toBe("Recording save was cancelled by account cleanup");expect(await audioQueueCount(USER)).toBe(0);}finally{release();await pending;}
});
it("acknowledges this account's Native upload while an earlier clear of another account completes",async()=>{
 await keep();const read=storage.getItem;let first=true,releaseClear:()=>void=()=>{},clearReady!:()=>void;const clearing=new Promise<void>(resolve=>{clearReady=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/base_url"&&first){first=false;clearReady();await new Promise<void>(resolve=>{releaseClear=resolve;});}return value;});const clear=clearAudioQueue(OTHER);await Promise.race([clearing,clear]);const transport=fetch;let releaseHttp:()=>void=()=>{},httpReady!:()=>void;const uploading=new Promise<void>(resolve=>{httpReady=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/audio/attachments")){httpReady();await new Promise<void>(resolve=>{releaseHttp=resolve;});}return response;});const pending=flushAudioQueue();await Promise.race([uploading,pending]);try{releaseClear();await clear;releaseHttp();expect(await pending).toBe(1);expect(await audioQueueCount(USER)).toBe(0);expect(uploads).toHaveLength(1);}finally{releaseClear();releaseHttp();await clear;await pending;}
});
it("refuses corrupt Native descriptors when the persistent directory capability is unavailable",async()=>{
 await keep();const row=await descriptor();vi.spyOn(fs,"documentDirectory","get").mockReturnValue(null as any);await storage.setItem(slot("recording"),JSON.stringify({...row,uri:`nullmindpattern-audio/${scope}/${row.revision}.enc`}));expect(await listSavedAudio(USER)).toEqual([{id:"recording",queuedAt:0,needsAttention:true,revision:undefined}]);expect(await flushAudioQueue()).toBe(0);
});
it("ignores a damaged ownerless Native queue key after sign out",async()=>{
 await storage.setItem(`${ACCOUNT_STORAGE_PREFIX.audioQueue}${origin}:null:damaged`,"corrupt ciphertext descriptor");await api.clearSession();expect(await audioQueueStatus()).toEqual({total:0,needsAttention:0});
});
it.each(["canceled upload","retired retry","retired upload"])("completes %s before an unavailable retired Native account inventory",async operation=>{
 await keep();const read=storage.getItem,keys=storage.getAllKeys;let first=true,retired=false,release:()=>void=()=>{},releaseProvider:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/base_url"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}else if(retired&&key.startsWith(ACCOUNT_STORAGE_PREFIX.audioErase))await new Promise<void>(resolve=>{releaseProvider=resolve;});return value;});vi.spyOn(storage,"getAllKeys").mockImplementation(async()=>{if(retired)await new Promise<void>(resolve=>{releaseProvider=resolve;});return keys();});let settled=false;const pending=(operation.includes("upload")?flushAudioQueue():retryAudioQueue(USER)).catch(error=>error).then(value=>{settled=true;return value;});await Promise.race([started,pending]);if(operation==="canceled upload")abortInFlightAudioFlush();else await api.setSession("replacement-bearer",USER,"alice");retired=true;try{release();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);if(operation==="canceled upload")expect(await pending).toBe(0);else expect(await pending).toBeInstanceOf(Error);expect(uploads).toEqual([]);}finally{retired=false;release();releaseProvider();await pending;}
});
it("retains a parent's Native retry receipt until its server acknowledgement is available",async()=>{
 await keep("recording",{parentPending:true});const row=await descriptor();await storage.setItem(slot("recording"),JSON.stringify({...row,rejection:409,notBefore:Date.now()+900000}));await retryAudioQueue(USER);await releaseAudioParent(USER,"recording",captureLocalWritePermit(USER,KEY));expect(await audioQueueStatus(USER)).toEqual({total:1,needsAttention:1});expect(await flushAudioQueue()).toBe(0);expect(uploads).toEqual([]);expect(await descriptor()).toMatchObject({rejection:409,notBefore:expect.any(Number)});
});
it("cancels a Native export whose empty envelope cache has just completed before the old radio is queried",async()=>{
 await keep();const read=storage.getItem;let first=true,release:()=>void=()=>{},releaseRadio:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key===ACCOUNT_STORAGE_PREFIX.keyEnvelope+Buffer.from("alice").toString("base64url")){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const transport=fetch;let unavailable=true;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(unavailable&&new URL(url).pathname.endsWith("/auth/key-envelope"))await new Promise<void>(resolve=>{releaseRadio=resolve;});return transport(url,init);});let settled=false;const pending=exportSavedAudio(USER,"recording").catch(error=>error).then(value=>{settled=true;return value;});await Promise.race([started,pending]);abortInFlightAudioFlush();try{release();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect((await pending).message).toBe("Recording export was cancelled by account cleanup");expect(sharing.shareAsync.mock.calls).toEqual([]);}finally{unavailable=false;release();releaseRadio();await pending;}
});
it.each([200,409])("settles a canceled Native HTTP %s acknowledgement before a retired descriptor provider",async code=>{
 await keep();status=code;const transport=fetch,read=storage.getItem;let releaseHttp:()=>void=()=>{},releaseProvider:()=>void=()=>{},ready!:()=>void,retired=false;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/audio/attachments")){ready();await new Promise<void>(resolve=>{releaseHttp=resolve;});}return response;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(retired&&(key.startsWith(ACCOUNT_STORAGE_PREFIX.audioErase)||key===slot("recording")))await new Promise<void>(resolve=>{releaseProvider=resolve;});return read(key);});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});await Promise.race([started,pending]);abortInFlightAudioFlush();retired=true;try{releaseHttp();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);}finally{retired=false;releaseHttp();releaseProvider();await pending;}expect(await audioQueueCount(USER)).toBe(1);
});
it("preserves a replacement Native revision when an older HTTP acknowledgement arrives",async()=>{
 await keep();const transport=fetch;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(first&&new URL(url).pathname.endsWith("/audio/attachments")){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return response;});const pending=flushAudioQueue();await Promise.race([started,pending]);const fresh=await keep(),row=await descriptor();try{release();expect(await pending).toBe(0);expect(await descriptor()).toEqual(row);expect(await fs.readAsStringAsync(row.uri)).toBe(fresh);expect(await flushAudioQueue()).toBe(1);expect(uploads[1].blob).toBe(fresh);}finally{release();await pending;}
});
it("retains this Native take after its same-generation clear fails while its old HTTP result is pending",async()=>{
 await keep();const read=storage.getItem;let first=true,releaseClear:()=>void=()=>{},clearReady!:()=>void;const clearing=new Promise<void>(resolve=>{clearReady=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/base_url"&&first){first=false;clearReady();await new Promise<void>(resolve=>{releaseClear=resolve;});}return value;});const clear=clearAudioQueue(USER).catch(error=>error);await Promise.race([clearing,clear]);const transport=fetch;let releaseHttp:()=>void=()=>{},httpReady!:()=>void;const uploading=new Promise<void>(resolve=>{httpReady=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/audio/attachments")){httpReady();await new Promise<void>(resolve=>{releaseHttp=resolve;});}return response;});const pending=flushAudioQueue();await Promise.race([uploading,pending]);const remove=native.remove;fs.deleteAsync.mockImplementation(async(uri,...options)=>{if(uri===`${fs.documentDirectory}mindpattern-audio/${scope}/`)throw new Error("Native account directory is unavailable");return remove(uri,...options);});try{releaseClear();expect((await clear).message).toBe("Native account directory is unavailable");releaseHttp();expect(await pending).toBe(0);expect(await audioQueueCount(USER)).toBe(1);}finally{releaseClear();releaseHttp();await clear;await pending;}
});
it("stops Native uploads at session expiry before an unavailable next voice descriptor",async()=>{
 await keep("a-first");await keep("z-second");status=401;const read=storage.getItem;let release:()=>void=()=>{},unavailable=true;vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(unavailable&&key===slot("z-second"))await new Promise<void>(resolve=>{release=resolve;});return read(key);});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});try{await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);expect(await descriptor("a-first")).toMatchObject({notBefore:expect.any(Number)});expect(uploads).toEqual([]);}finally{unavailable=false;release();await pending;}
});
it("stops Native uploads after an origin-pin refusal before an unavailable independent descriptor",async()=>{
 await keep("a-first");await keep("z-second");const fileRead=native.read,read=storage.getItem;let blobDelivered=false,guardRead=false,changed=false,unavailable=true,release:()=>void=()=>{};fs.readAsStringAsync.mockImplementation(async(...args)=>{const value=await fileRead(...args);blobDelivered=true;return value;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(key==="@mindpattern/base_url"&&blobDelivered){if(!guardRead)guardRead=true;else if(!changed){changed=true;await storage.setItem(key,"https://restored-native.example");}}if(changed&&unavailable&&key===slot("z-second"))await new Promise<void>(resolve=>{release=resolve;});return read(key);});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});try{await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(changed).toBe(true);expect(settled).toBe(true);expect(await pending).toBe(0);expect(uploads).toEqual([]);expect(await storage.getItem(slot("a-first"))).not.toBeNull();}finally{unavailable=false;release();await pending;}
});
it("retries independent Native voice while preserving an unreadable earlier descriptor",async()=>{
 await storage.setItem(slot("a-corrupt"),"invalid Native voice descriptor");const blob=await keep("z-valid");await expect(retryAudioQueue(USER)).resolves.toBeUndefined();expect(uploads).toHaveLength(1);expect(uploads[0].blob).toBe(blob);expect(await listSavedAudio(USER)).toEqual([{id:"a-corrupt",queuedAt:0,needsAttention:true,revision:undefined}]);
});
it.each(["queue cancellation","replacement credentials"])("preserves legacy Native ciphertext and removes its staged file after %s during physical migration",async retirement=>{
 const blob=encryptAudio({dataKey:KEY},USER,"legacy",Buffer.from("the user's interrupted legacy voice")),raw=JSON.stringify({...blob,mime:"audio/m4a",durationSeconds:4,queuedAt:1});await storage.setItem(slot("legacy"),raw);let uri="",release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});fs.writeAsStringAsync.mockImplementation(async(...args)=>{await native.write(...args);uri=args[0];ready();await new Promise<void>(resolve=>{release=resolve;});});const pending=flushAudioQueue();await Promise.race([started,pending]);let replacement:Promise<void>|undefined;if(retirement==="queue cancellation")abortInFlightAudioFlush();else {replacement=api.setSession("replacement-bearer",USER,"alice");await new Promise<void>(resolve=>setImmediate(resolve));}
 try{release();expect(await pending).toBe(0);await replacement;expect(await storage.getItem(slot("legacy"))).toBe(raw);expect(fs.__hasFile(uri)).toBe(false);expect(uploads).toEqual([]);}finally{release();await pending;await replacement;}
});
it("preserves the later Native removal cancellation reason and the saved physical voice",async()=>{
 await keep();const row=await descriptor(),read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key===slot("recording")){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const pending=removeSavedAudio(USER,"recording",row.revision).catch(error=>error);await Promise.race([started,pending]);abortInFlightAudioFlush();try{release();expect((await pending).message).toBe("Recording removal was cancelled by account cleanup");expect(await descriptor()).toEqual(row);expect(fs.__hasFile(row.uri)).toBe(true);}finally{release();await pending;}
});
it("finishes canceled Native legacy-envelope export before an unavailable old salt provider",async()=>{
 await keep();const transport=fetch,read=storage.getItem;let releaseHttp:()=>void=()=>{},releaseSalt:()=>void=()=>{},ready!:()=>void,retired=false;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const value=await transport(url,init);if(new URL(url).pathname.endsWith("/auth/key-envelope")){ready();await new Promise<void>(resolve=>{releaseHttp=resolve;});}return value;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(retired&&key===ACCOUNT_STORAGE_PREFIX.salt+Buffer.from("alice").toString("base64url"))await new Promise<void>(resolve=>{releaseSalt=resolve;});return read(key);});let settled=false;const pending=exportSavedAudio(USER,"recording").catch(error=>error).then(value=>{settled=true;return value;});await Promise.race([started,pending]);abortInFlightAudioFlush();retired=true;
 try{releaseHttp();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect((await pending).message).toBe("Recording export was cancelled by account cleanup");expect(sharing.shareAsync.mock.calls).toEqual([]);}finally{retired=false;releaseHttp();releaseSalt();await pending;}
});
it.each(["before joining","after joining"])("finishes canceled Native export %s the physical recording mutex",async phase=>{
 await keep();await cacheEnvelope("alice",{scheme:"v1",saltB64:SALT.toString("base64"),kdfParams:null,wrappedB64:null});let releaseWrite:()=>void=()=>{},releaseSharing:()=>void=()=>{},releaseDirectory:()=>void=()=>{},writeReady!:()=>void,sharingReady!:()=>void,blocked=false;const writing=new Promise<void>(resolve=>{writeReady=resolve;}),capability=new Promise<void>(resolve=>{sharingReady=resolve;});fs.writeAsStringAsync.mockImplementation(async(...args)=>{await native.write(...args);if(args[0].endsWith(".enc")){writeReady();await new Promise<void>(resolve=>{releaseWrite=resolve;});}});const saving=keep("independent").catch(error=>error);await Promise.race([writing,saving]);sharing.isAvailableAsync.mockImplementation(async()=>{sharingReady();if(phase==="before joining")await new Promise<void>(resolve=>{releaseSharing=resolve;});return true;});fs.makeDirectoryAsync.mockImplementation(async(...args)=>{if(blocked&&args[0].endsWith("exports/"))await new Promise<void>(resolve=>{releaseDirectory=resolve;});return native.mkdir(...args);});let settled=false;const pending=exportSavedAudio(USER,"recording").catch(error=>error).then(value=>{settled=true;return value;});await Promise.race([capability,pending]);await new Promise<void>(resolve=>setImmediate(resolve));abortInFlightAudioFlush();blocked=true;
 try{if(phase==="before joining"){releaseSharing();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);}releaseWrite();await saving;await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect((await pending).message).toBe("Recording export was cancelled by account cleanup");expect(sharing.shareAsync.mock.calls).toEqual([]);expect(await audioQueueCount(USER)).toBe(1);}finally{blocked=false;releaseWrite();releaseSharing();releaseDirectory();await saving;await pending;}
});
it("finishes a Native upload whose physical credential backend now belongs to another account before querying the old origin",async()=>{
 await keep();const fileRead=native.read,read=storage.getItem;let releaseBlob:()=>void=()=>{},releaseOrigin:()=>void=()=>{},ready!:()=>void,retired=false;const started=new Promise<void>(resolve=>{ready=resolve;});fs.readAsStringAsync.mockImplementation(async(...args)=>{const value=await fileRead(...args);ready();await new Promise<void>(resolve=>{releaseBlob=resolve;});return value;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(retired&&key==="@mindpattern/base_url")await new Promise<void>(resolve=>{releaseOrigin=resolve;});return read(key);});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});await Promise.race([started,pending]);await secureStore.setItem("@mindpattern/user_id",OTHER);retired=true;
 try{releaseBlob();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);expect(uploads).toEqual([]);}finally{retired=false;releaseBlob();releaseOrigin();await pending;}expect(await audioQueueCount(USER)).toBe(1);
});
it("preserves Native export cancellation before initializing an unavailable sharing module",async()=>{
 await keep();await cacheEnvelope("alice",{scheme:"v1",saltB64:SALT.toString("base64"),kdfParams:null,wrappedB64:null});vi.doMock("expo-sharing",()=>{throw new Error("Cannot find native module 'ExpoSharing'");});const fileRead=native.read;let release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});fs.readAsStringAsync.mockImplementation(async(...args)=>{const value=await fileRead(...args);ready();await new Promise<void>(resolve=>{release=resolve;});return value;});const pending=exportSavedAudio(USER,"recording").catch(error=>error);
 try{await Promise.race([started,pending]);abortInFlightAudioFlush();release();expect((await pending).message).toBe("Recording export was cancelled by account cleanup");expect(await audioQueueCount(USER)).toBe(1);}finally{release();await pending;vi.doUnmock("expo-sharing");}
});
it("finishes Native export retired during sharing module initialization before an unavailable capability provider",async()=>{
 await keep();await cacheEnvelope("alice",{scheme:"v1",saltB64:SALT.toString("base64"),kdfParams:null,wrappedB64:null});let releaseModule:()=>void=()=>{},releaseCapability:()=>void=()=>{},ready!:()=>void,unavailable=true;const started=new Promise<void>(resolve=>{ready=resolve;});vi.doMock("expo-sharing",async()=>{ready();await new Promise<void>(resolve=>{releaseModule=resolve;});return {...sharing,isAvailableAsync:async()=>{if(unavailable)await new Promise<void>(resolve=>{releaseCapability=resolve;});return true;}};});let settled=false;const pending=exportSavedAudio(USER,"recording").catch(error=>error).then(value=>{settled=true;return value;});
 try{await Promise.race([started,pending]);abortInFlightAudioFlush();releaseModule();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect((await pending).message).toBe("Recording export was cancelled by account cleanup");expect(await audioQueueCount(USER)).toBe(1);}finally{unavailable=false;releaseModule();releaseCapability();await pending;vi.doUnmock("expo-sharing");}
});
it.each(["inventory","acknowledgement","acknowledgement descriptor"])("settles an account-retired Native flush after %s without reading an unavailable old voice descriptor",async phase=>{
 await keep("a-first");await keep("z-second");const read=storage.getItem,inventory=storage.getAllKeys,transport=fetch;let first=true,acknowledged=false,retired=false,release:()=>void=()=>{},releaseProvider:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const value=await transport(url,init);if(new URL(url).pathname.endsWith("/audio/attachments"))acknowledged=true;return value;});vi.spyOn(storage,"getAllKeys").mockImplementation(async()=>{const value=await inventory();if(phase==="inventory"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(retired&&key===slot(phase==="acknowledgement"?"z-second":"a-first"))await new Promise<void>(resolve=>{releaseProvider=resolve;});const value=await read(key);if(phase!=="inventory"&&first&&acknowledged&&key.startsWith(ACCOUNT_STORAGE_PREFIX.audioErase)){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});await Promise.race([started,pending]);await api.setSession("replacement-bearer",OTHER,"bob");retired=true;
 try{release();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);}finally{retired=false;release();releaseProvider();await pending;}expect(await audioQueueCount(USER)).toBe(2);expect(uploads).toHaveLength(phase==="inventory"?0:1);
});
it.each([200,409])("settles canceled Native HTTP %s cleanup after a marker delivery before the descriptor provider",async code=>{
 await keep();status=code;const read=storage.getItem,transport=fetch;let first=true,acknowledged=false,retired=false,release:()=>void=()=>{},releaseProvider:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const value=await transport(url,init);if(new URL(url).pathname.endsWith("/audio/attachments"))acknowledged=true;return value;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(retired&&key===slot("recording"))await new Promise<void>(resolve=>{releaseProvider=resolve;});const value=await read(key);if(first&&acknowledged&&key.startsWith(ACCOUNT_STORAGE_PREFIX.audioErase)){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});let settled=false;const pending=flushAudioQueue().then(value=>{settled=true;return value;});await Promise.race([started,pending]);abortInFlightAudioFlush();retired=true;
 try{release();await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(settled).toBe(true);expect(await pending).toBe(0);}finally{retired=false;release();releaseProvider();await pending;}expect(await audioQueueCount(USER)).toBe(1);
});
it.each([200,409])("preserves canceled Native HTTP %s recording metadata after its acknowledgement descriptor delivery",async code=>{
 await keep();const row=await descriptor();status=code;const read=storage.getItem,transport=fetch;let first=true,acknowledged=false,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const value=await transport(url,init);if(new URL(url).pathname.endsWith("/audio/attachments"))acknowledged=true;return value;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&acknowledged&&key===slot("recording")){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const pending=flushAudioQueue();await Promise.race([started,pending]);abortInFlightAudioFlush();try{release();expect(await pending).toBe(0);expect(await descriptor()).toEqual(row);expect(fs.__hasFile(row.uri)).toBe(true);}finally{release();await pending;}
});
