/** Actual session, sealed credential, onboarding and screen behavior. The Native
 * stack adapter retains one visible route and renders its real native header;
 * it does not mount inactive screens or replace screen controllers. */
import React from "react";
import crypto from "node:crypto";
import ReactTestRenderer,{act as reactAct} from "react-test-renderer";
import {afterEach,beforeEach,it,expect,vi} from "vitest";
import {Text,TouchableOpacity,TextInput,Alert} from "react-native";
import {api,DEFAULT_BASE_URL} from "../src/api/client";
import {secureStore} from "../src/secureStore";
import {ThemeProvider} from "../src/theme";
import {SessionProvider} from "../src/store";
import {vault} from "../src/vault";
import {queueOnboarding,takePendingOnboarding,clearOnboardingSeen} from "../src/onboarding";
import {queueNotificationRoute,takePendingNotificationRoute,notifyNavigationReady} from "../src/notificationRoute";
import {accountStorageKey} from "../src/accountStorage";
import {publicSurface} from "./helpers/publicSurface";
import {assertPublicSurface} from "./helpers/publicSurfaceOracle";
import storage from "./helpers/storageMock";
import * as files from "./helpers/expoFsMock";
import * as keychain from "./helpers/keychainMock";
const stack=vi.hoisted(()=>({ready:true,navigate:undefined as undefined|((screen:string)=>void)}));
vi.mock("@react-navigation/native-stack",async()=>{
 const React=await import("react"),{Text}=await import("react-native");
 const collect=(children:any):any[]=>React.Children.toArray(children).flatMap(child=>React.isValidElement(child)?child.type===React.Fragment?collect((child.props as any).children):[child]:[]);
 function Navigator({children}:any){
  const routes=collect(children),[chosen,setChosen]=React.useState<string|null>(null),current=routes.find(route=>route.props.name===chosen)??routes[0];
  React.useLayoutEffect(()=>{const go=(name:string)=>{if(routes.some(route=>route.props.name===name))setChosen(name);};stack.navigate=go;const ref={isReady:()=>stack.ready,navigate:go};navigationRef.current=ref;return()=>{if(navigationRef.current===ref)navigationRef.current=null;stack.navigate=undefined;};});
  if(!current)return null;const{component:Screen,options={},name}=current.props,navigation={navigate:(to:string)=>stack.navigate?.(to),replace:(to:string)=>stack.navigate?.(to),popToTop:()=>setChosen(null)};
  return <>{options.headerShown!==false&&<Text accessibilityRole="header">{options.title??name}</Text>}<Screen key={name} navigation={navigation}/></>;
 }
 return{createNativeStackNavigator:()=>({Navigator,Screen:()=>null})};
});
vi.mock("@react-navigation/native",()=>({NavigationContainer:({children}:any)=>children}));
vi.mock("react-native-safe-area-context",()=>({SafeAreaProvider:({children}:any)=>children}));
const{AppNavigator,navigationRef}=await import("../src/navigation");
const USER="a".repeat(32),OTHER="b".repeat(32),KEY=Buffer.alloc(32,19),SALT=Buffer.alloc(16,3),PASSWORD="a known account password";
const MASTER=crypto.pbkdf2Sync(PASSWORD,SALT,600000,32,"sha256"),AUTH=Buffer.from(crypto.hkdfSync("sha256",MASTER,Buffer.alloc(32),Buffer.from("mindpattern/auth/v1"),32));
let root:ReturnType<typeof ReactTestRenderer.create>|undefined,stage=0,release:()=>void=()=>{},serverOwner=USER;
async function act<T>(run:()=>T|Promise<T>){await reactAct(run);if(root)assertPublicSurface(publicSurface(root),++stage);}
async function flush(){await act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});}
function words(){const flat=(value:any):string=>Array.isArray(value)?value.map(flat).join(""):typeof value==="string"||typeof value==="number"?String(value):"";return root!.root.findAllByType(Text).map(n=>flat(n.props.children)).join(" ");}
function button(label:string){return root!.root.findAllByType(TouchableOpacity).find(n=>n.props.accessibilityLabel===label||React.Children.toArray(n.props.children).some(c=>React.isValidElement(c)&&(c.props as any).children===label));}
async function press(label:string){const b=button(label);expect(b,label).toBeDefined();await act(async()=>{await b!.props.onPress();});await flush();}
async function mount(){await act(async()=>{root=ReactTestRenderer.create(<ThemeProvider><SessionProvider><AppNavigator/></SessionProvider></ThemeProvider>);});for(let i=0;i<6;i++)await flush();}
async function seed(owner=USER,seen=true,unlocked=true){await api.setSession("native-route-bearer",owner,"alice");if(seen)await storage.setItem(accountStorageKey.onboardingSeen(owner),"1");else await clearOnboardingSeen(owner);if(unlocked)vault.unlock({masterKey:Buffer.from(MASTER),authKey:Buffer.from(AUTH),dataKey:Buffer.from(KEY)},owner);}
beforeEach(async()=>{stage=0;release=()=>{};vi.restoreAllMocks();storage.__reset();files.__resetFiles();keychain.__reset();vault.lock();stack.ready=true;stack.navigate=undefined;navigationRef.current=null;takePendingOnboarding();takePendingNotificationRoute();serverOwner=USER;await clearOnboardingSeen(USER);await clearOnboardingSeen(OTHER);Alert.alert.mockClear();vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const path=new URL(url).pathname;let body:any={},status=200;if(path.endsWith("/auth/salt"))body={salt:SALT.toString("base64")};else if(path.endsWith("/auth/login"))body={token:"new-route-bearer",user_id:serverOwner};else if(path.endsWith("/auth/key-envelope")||path.includes("/questions/"))status=404;else if(path.endsWith("/insights"))body={phase:"baseline",active_days:0,days_remaining:30};else if(path.endsWith("/meta"))body={unlock_days:30};else if(path.endsWith("/entries")||path.endsWith("/measures")||path.endsWith("/consents"))body=[];else if(path.endsWith("/processing/sessions"))body={session_token:"route-processing"};else if(path.endsWith("/progress"))body={active_days:0};const response=new Response(JSON.stringify(body),{status});Object.defineProperty(response,"url",{value:url});return response;});});
afterEach(async()=>{release();await flush();if(root){await act(async()=>root!.unmount());root=undefined;}vi.restoreAllMocks();vi.unstubAllGlobals();vault.lock();await api.clearSession();navigationRef.current=null;takePendingOnboarding();takePendingNotificationRoute();});
it("a Native settled account opens its journal rather than an extra onboarding screen",async()=>{await seed();await mount();expect(words()).toContain("Save entry");expect(words()).not.toContain("Write each day");});
it("a pending Native onboarding invitation leads the first unlocked route",async()=>{await seed(USER,false);queueOnboarding();await mount();expect(words()).toContain("Write each day");expect(words()).not.toContain("Save entry");});
it("a tapped Native measure reminder leads the first unlocked route",async()=>{await seed();queueNotificationRoute("mindpattern-measure-reminder");await mount();expect(words()).toContain("Wellbeing measures");expect(words()).not.toContain("Save entry");});
it("a foreground Native measure tap waits for ready and then opens its visible questionnaire",async()=>{await seed();await mount();stack.ready=false;await act(async()=>queueNotificationRoute("mindpattern-measure-reminder"));expect(words()).toContain("Save entry");stack.ready=true;await act(async()=>notifyNavigationReady());await flush();expect(words()).toContain("Wellbeing measures");});
it("Native background lock retains an unseen account's onboarding gate on its next unlocked entry",async()=>{await seed(USER,false);await mount();expect(words()).toContain("Write each day");await act(async()=>vault.lock());expect(words()).toContain("Locked");await act(async()=>vault.unlock({masterKey:Buffer.from(MASTER),authKey:Buffer.from(AUTH),dataKey:Buffer.from(KEY)},USER));await flush();expect(words()).toContain("Write each day");});
it("a Native seen account stays on its journal through a foreground notification-ready event without a pending destination",async()=>{await seed();await mount();await act(async()=>notifyNavigationReady());await flush();expect(words()).toContain("Save entry");});
it("an unavailable persisted Native onboarding read fails toward the ordinary journal",async()=>{await seed();const get=storage.getItem.bind(storage);vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(key===accountStorageKey.onboardingSeen(USER))throw Error("Native onboarding read unavailable");return get(key);});await mount();expect(words()).toContain("Save entry");});
it("a physical Native owner removal after boot's authentic receipt resolves the missing-owner gate",async()=>{await seed();const get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await get(key);if(first&&key==="@mindpattern/user_id"){first=false;await secureStore.removeItem(key);}return value;});await mount();expect(words()).toContain("Save entry");expect(await api.getUserId()).toBeNull();});
it("a Native persisted onboarding read holds the boot splash until its receipt arrives",async()=>{await seed(USER,false);const get=storage.getItem.bind(storage);let entered=false;vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await get(key);if(!entered&&key===accountStorageKey.onboardingSeen(USER)){entered=true;await new Promise<void>(resolve=>{release=resolve;});}return value;});await mount();expect(entered).toBe(true);expect(words()).toContain("Fathom");expect(words()).not.toContain("Save entry");await act(async()=>release());await flush();expect(words()).toContain("Write each day");});
it("Native locked crisis resources retain a hidden unlock header and the localized help title",async()=>{await seed(USER,true,false);await mount();expect(words()).toContain("Locked");expect(root!.root.findAllByType(Text).filter(n=>n.props.accessibilityRole==="header").map(n=>n.props.children)).not.toContain("Unlock");await press("Need help now? Crisis resources");expect(words()).toContain("Get help");});
it("a Native safety-plan navigation presents the product header rather than the internal route name",async()=>{await seed();await mount();await act(async()=>stack.navigate?.("SafetyPlan"));await flush();expect(root!.root.findAllByType(Text).filter(n=>n.props.accessibilityRole==="header").map(n=>n.props.children)).toContain("My safety plan");});
async function signInReplacement(){
 serverOwner=OTHER;await storage.setItem(accountStorageKey.onboardingSeen(OTHER),"1");
 await act(async()=>{root!.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==="Username")!.props.onChangeText("alice");root!.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==="Password")!.props.onChangeText(PASSWORD);});await press("Sign in");
}
it("a retired Native onboarding receipt cannot let the replacement account through its unresolved gate",async()=>{
 await seed(USER,false,false);const get=storage.getItem.bind(storage);let oldEntered=false,newEntered=false,releaseOld:()=>void=()=>{},releaseNew:()=>void=()=>{};release=()=>{releaseOld();releaseNew();};
 vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await get(key);if(!oldEntered&&key===accountStorageKey.onboardingSeen(USER)){oldEntered=true;await new Promise<void>(resolve=>{releaseOld=resolve;});}else if(!newEntered&&key===accountStorageKey.onboardingSeen(OTHER)){newEntered=true;await new Promise<void>(resolve=>{releaseNew=resolve;});}return value;});
 await mount();expect(oldEntered).toBe(true);await press("Sign out instead");expect(words()).toContain("Sign in");await signInReplacement();expect(newEntered).toBe(true);expect(words()).toContain("Fathom");expect(words()).not.toContain("Save entry");await act(async()=>releaseOld());await flush();expect(words()).not.toContain("Save entry");expect(words()).not.toContain("Write each day");await act(async()=>releaseNew());await flush();expect(words()).toContain("Save entry");
});
it("the exported Native navigation bridge remains quiet before the container mounts",()=>{navigationRef.current=null;expect(navigationRef.isReady()).toBe(false);expect(()=>navigationRef.navigate("Measures")).not.toThrow();});
it("a Native measure tap waits behind the locked route and survives until that account unlocks",async()=>{await seed(USER,true,false);await mount();await act(async()=>queueNotificationRoute("mindpattern-measure-reminder"));expect(words()).toContain("Locked");await act(async()=>vault.unlock({masterKey:Buffer.from(MASTER),authKey:Buffer.from(AUTH),dataKey:Buffer.from(KEY)},USER));await flush();expect(words()).toContain("Wellbeing measures");});
it("a Native measure tap leaves required onboarding visible until the panels finish",async()=>{await seed(USER,false);await mount();expect(words()).toContain("Write each day");await act(async()=>queueNotificationRoute("mindpattern-measure-reminder"));await flush();expect(words()).toContain("Write each day");expect(words()).not.toContain("Wellbeing measures");});
it.each([2,3,4,5,6,7,8])("a retired Native owner receipt %i cannot occupy the replacement onboarding read lane",async occurrence=>{
 await seed(USER,true,false);const getSecure=secureStore.getItem.bind(secureStore),getNative=storage.getItem.bind(storage);let reads=0,releaseOwner:()=>void=()=>{},releaseTransaction:()=>void=()=>{},armed=false,occupied=false;const transaction=new Promise<void>(resolve=>{releaseTransaction=resolve;});release=()=>{releaseOwner();releaseTransaction();};
 vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await getSecure(key);if(key==="@mindpattern/user_id"&&++reads===occurrence)await new Promise<void>(resolve=>{releaseOwner=resolve;});return value;});
 vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(armed&&key===accountStorageKey.onboardingSeen(USER)){occupied=true;await transaction;}else if(occupied&&key===accountStorageKey.onboardingSeen(OTHER))await transaction;return getNative(key);});
 await mount();await act(async()=>{root!.unmount();root=undefined;});await api.setSession("replacement-route-bearer",OTHER,"alice");await storage.setItem(accountStorageKey.onboardingSeen(OTHER),"1");vault.unlock({masterKey:Buffer.from(MASTER),authKey:Buffer.from(AUTH),dataKey:Buffer.from(KEY)},OTHER);armed=true;await act(async()=>releaseOwner());await mount();expect(words()).toContain("Save entry");expect(words()).not.toContain("Write each day");
});
it("a cold Native measure tap selects its initial screen even before container readiness",async()=>{await seed();stack.ready=false;queueNotificationRoute("mindpattern-measure-reminder");await mount();expect(words()).toContain("Wellbeing measures");expect(words()).not.toContain("Save entry");});
it("the public Native bridge can reach the titled offline crisis route while onboarding storage is pending",async()=>{await seed(USER,false);const get=storage.getItem.bind(storage);vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await get(key);if(key===accountStorageKey.onboardingSeen(USER))await new Promise<void>(resolve=>{release=resolve;});return value;});await mount();expect(words()).toContain("Fathom");await act(async()=>navigationRef.navigate("Crisis"));expect(root!.root.findAllByType(Text).filter(n=>n.props.accessibilityRole==="header").map(n=>n.props.children)).toContain("Get help");});

it("actual Native App language delivery can mount a logged-in navigator while onboarding still waits",async()=>{
 await seed(USER,false);const read=secureStore.getItem.bind(secureStore),get=storage.getItem.bind(storage);let releaseLanguage:()=>void=()=>{},releaseSeen:()=>void=()=>{};release=()=>{releaseLanguage();releaseSeen();};vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/language_pref")await new Promise<void>(resolve=>{releaseLanguage=resolve;});return value;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await get(key);if(key===accountStorageKey.onboardingSeen(USER))await new Promise<void>(resolve=>{releaseSeen=resolve;});return value;});const{default:App}=await import("../App");await act(async()=>{root=ReactTestRenderer.create(<App/>);});for(let i=0;i<6;i++)await flush();expect(words()).not.toContain("Save entry");await act(async()=>releaseLanguage());await flush();expect(words()).toContain("Fathom");expect(words()).not.toContain("Save entry");await act(async()=>releaseSeen());await flush();expect(words()).toContain("Write each day");
});
it("actual Native late language delivery consumes a cold measure tap at the first already-authenticated main render",async()=>{
 await seed();stack.ready=false;queueNotificationRoute("mindpattern-measure-reminder");const read=secureStore.getItem.bind(secureStore);vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/language_pref")await new Promise<void>(resolve=>{release=resolve;});return value;});const{default:App}=await import("../App");await act(async()=>{root=ReactTestRenderer.create(<App/>);});for(let i=0;i<6;i++)await flush();await act(async()=>release());await flush();expect(words()).toContain("Wellbeing measures");expect(words()).not.toContain("Save entry");
});
it("a completed Native onboarding stays completed across a later lock and unavailable flag read",async()=>{
 await seed(USER,false);await mount();await press("Continue to panel 2 of 3");await press("Continue to panel 3 of 3");await press("I understand — start writing");await flush();expect(words()).toContain("Save entry");await act(async()=>vault.lock());const get=storage.getItem.bind(storage);vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await get(key);if(key===accountStorageKey.onboardingSeen(USER))await new Promise<void>(resolve=>{release=resolve;});return value;});await act(async()=>vault.unlock({masterKey:Buffer.from(MASTER),authKey:Buffer.from(AUTH),dataKey:Buffer.from(KEY)},USER));await flush();expect(words()).toContain("Save entry");expect(words()).not.toContain("Write each day");
});
it("a remounted Native provider with a retained vault and missing bearer preserves the next tap until real sign-in",async()=>{
 await seed();await secureStore.removeItem("@mindpattern/token");stack.ready=false;await mount();expect(words()).toContain("Sign in");expect(vault.isUnlocked()).toBe(true);await act(async()=>queueNotificationRoute("mindpattern-measure-reminder"));await act(async()=>{root!.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==="Username")!.props.onChangeText("alice");root!.root.findAllByType(TextInput).find(n=>n.props.accessibilityLabel==="Password")!.props.onChangeText(PASSWORD);});await press("Sign in");await flush();expect(words()).toContain("Wellbeing measures");expect(words()).not.toContain("Save entry");
});
it("actual Native cold owner refusal leaves an initially empty onboarding mirror safe at later unlock",async()=>{
 await seed(USER,true,false);const get=secureStore.getItem.bind(secureStore);let ownerReads=0;vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await get(key);if(key==="@mindpattern/user_id"&&++ownerReads>1)throw Error("Native owner provider unavailable after boot receipt");return value;});const{default:App}=await import("../App");await act(async()=>{root=ReactTestRenderer.create(<App/>);});for(let i=0;i<6;i++)await flush();expect(words()).toContain("Locked");stack.ready=false;await act(async()=>queueNotificationRoute("mindpattern-measure-reminder"));await act(async()=>vault.unlock({masterKey:Buffer.from(MASTER),authKey:Buffer.from(AUTH),dataKey:Buffer.from(KEY)},USER));await flush();expect(words()).toContain("Wellbeing measures");expect(words()).not.toContain("Save entry");
});
