/** Public freshness promises backed by actual sealed Native marks. */
import {beforeEach,afterEach,it,expect,vi} from "vitest";
import {api,setBaseUrl} from "../src/api/client";
import {secureStore,setSecureStoreBackend} from "../src/secureStore";
import {accountStorageKey} from "../src/accountStorage";
import {checkAnalysisGeneration,resetAnalysisGenerationMirrors} from "../src/stateSeqGuard";
import {__resetLocalKeyLifecycleForTests} from "../src/localWriteGuard";
import {runTestControl} from "./helpers/testControl";
import storage from "./helpers/storageMock";
import * as keychain from "./helpers/keychainMock";
const USER="a".repeat(32);const releases:Array<()=>void>=[];
function hold(){let entered=false,release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});releases.push(release);return{run:async()=>{entered=true;await gate;},entered:()=>entered,release};}
beforeEach(async()=>{vi.restoreAllMocks();storage.__reset();keychain.__reset();runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);runTestControl(resetAnalysisGenerationMirrors);await api.setSession("Native generation check bearer",USER,"alice");});
afterEach(async()=>{for(const release of releases.splice(0))release();vi.restoreAllMocks();await api.clearSession();});
it("a queued Native generation check cannot adopt a replacement credential scope",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;await held.run();}return value;});const old=checkAnalysisGeneration(USER,10,10).then(()=>"accepted",()=>"refused");await vi.waitFor(()=>expect(held.entered()).toBe(true));const queued=checkAnalysisGeneration(USER,11,11).then(()=>"accepted",()=>"refused");await api.setSession("replacement Native generation check bearer",USER,"alice");held.release();expect(await old).toBe("refused");expect(await queued).toBe("refused");expect(await get(slot)).toBe("9");await expect(checkAnalysisGeneration(USER,12,12)).resolves.toBeUndefined();expect(await get(slot)).toBe("12");
});
it("a Native generation promise cannot report acceptance after its physical receipt completes into a retired scope",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const held=hold(),set=secureStore.setItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"setItem").mockImplementation(async(name,value)=>{await set(name,value);if(first&&name===slot){first=false;await held.run();}});const old=checkAnalysisGeneration(USER,10,10).then(()=>"accepted",()=>"refused");await vi.waitFor(()=>expect(held.entered()).toBe(true));expect(await secureStore.getItem(slot)).toBe("10");const replacement=api.setSession("replacement Native receipt bearer",USER,"alice");held.release();expect(await old).toBe("refused");await replacement;await expect(checkAnalysisGeneration(USER,11,11)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("11");
});
it("a genuine Native sealed-write refusal keeps the live mirror and repairs it through a later accepted check",async()=>{
 const slot=accountStorageKey.stateSequence(USER),write=storage.setItem.bind(storage);let refuse=true;vi.spyOn(storage,"setItem").mockImplementation(async(name,value)=>{if(name===slot&&refuse)throw new Error("Native metadata volume has no remaining capacity");return write(name,value);});await expect(checkAnalysisGeneration(USER,13,13)).resolves.toBeUndefined();expect(await storage.getItem(slot)).toBeNull();await expect(checkAnalysisGeneration(USER,12,12)).rejects.toThrow("freshness check");refuse=false;await expect(checkAnalysisGeneration(USER,13,13)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("13");
});
it("an older completed Native check cannot detach the still-pending successor from the account lane",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const firstRead=hold(),secondWrite=hold(),get=secureStore.getItem.bind(secureStore),set=secureStore.setItem.bind(secureStore);let first=true,second=true;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;await firstRead.run();}return value;});vi.spyOn(secureStore,"setItem").mockImplementation(async(name,value)=>{if(second&&name===slot&&value==="12"){second=false;await secondWrite.run();}return set(name,value);});const old=checkAnalysisGeneration(USER,10,10);await vi.waitFor(()=>expect(firstRead.entered()).toBe(true));const successor=checkAnalysisGeneration(USER,12,12);firstRead.release();await old;await vi.waitFor(()=>expect(secondWrite.entered()).toBe(true));const latest=checkAnalysisGeneration(USER,13,13);await new Promise(resolve=>setTimeout(resolve,0));secondWrite.release();await Promise.all([successor,latest]);expect(await get(slot)).toBe("13");runTestControl(resetAnalysisGenerationMirrors);await expect(checkAnalysisGeneration(USER,12,12)).rejects.toThrow("freshness check");
});
it("retired queued Native checks leave the serial mark provider available to the replacement caller",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"100");const held=hold(),provider=hold(),get=secureStore.getItem.bind(secureStore);let first=true,afterRetirement=false,oldChecksComplete=false,lane:Promise<unknown>=Promise.resolve();vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{if(name===slot&&afterRetirement){const obsolete=!oldChecksComplete;const receipt=lane.then(async()=>{if(obsolete)await provider.run();return get(name);});lane=receipt.catch(()=>{});return receipt;}const value=await get(name);if(first&&name===slot){first=false;await held.run();}return value;});const old=checkAnalysisGeneration(USER,101,101).then(()=>"accepted",()=>"refused");await vi.waitFor(()=>expect(held.entered()).toBe(true));const queued=checkAnalysisGeneration(USER,102,102).then(()=>"accepted",()=>"refused");const finished=Promise.all([old,queued]).then(result=>{oldChecksComplete=true;return result;});await api.setSession("replacement Native serial-provider bearer",USER,"alice");afterRetirement=true;held.release();await new Promise(resolve=>setTimeout(resolve,0));const current=checkAnalysisGeneration(USER,10,10).then(()=>"accepted",error=>String(error.message));const result=await Promise.race([current,new Promise<string>(resolve=>setTimeout(()=>resolve("the current caller is waiting behind an obsolete Native receipt"),50))]);expect(result).toContain("freshness check");provider.release();expect(await finished).toEqual(["refused","refused"]);await current;expect(await get(slot)).toBe("100");
});
it.each([1,2,3,4,5,6,7,8])("a Native credential completion at callback turn %s cannot admit a refused generation into the current mirror",async turns=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const get=secureStore.getItem.bind(secureStore);let first=true,replacement:Promise<void>|undefined;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;const schedule=(remaining:number)=>queueMicrotask(()=>{if(remaining===1)replacement=api.setSession("replacement Native callback receipt bearer",USER,"alice");else schedule(remaining-1);});schedule(turns);}return value;});const outcome=await checkAnalysisGeneration(USER,1000,1000).then(()=>"accepted",()=>"refused");await new Promise(resolve=>setTimeout(resolve,0));await replacement;const mark=await get(slot);if(outcome==="refused"&&mark==="9"){await expect(checkAnalysisGeneration(USER,10,10)).resolves.toBeUndefined();expect(await get(slot)).toBe("10");}else await expect(checkAnalysisGeneration(USER,10,10)).rejects.toThrow("freshness check");
});
it("a late Native old-origin mark read cannot revive erased rollback metadata for a same-id account on the new server",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;await held.run();}return value;});const old=checkAnalysisGeneration(USER,10,10).then(()=>"accepted",()=>"refused");await vi.waitFor(()=>expect(held.entered()).toBe(true));await expect(setBaseUrl("https://replacement-native-generation.example")).resolves.toBeNull();expect(await storage.getItem(slot)).toBeNull();await api.setSession("new-server Native generation bearer",USER,"alice");held.release();expect(await old).toBe("refused");await expect(checkAnalysisGeneration(USER,1,1)).resolves.toBeUndefined();expect(await get(slot)).toBe("1");
});
it("a previously accepted old-origin mark cannot constrain a same-id account on the replacement server",async()=>{
 await checkAnalysisGeneration(USER,9,9);await expect(setBaseUrl("https://replacement-native-accepted-generation.example")).resolves.toBeNull();expect(await storage.getItem(accountStorageKey.stateSequence(USER))).toBeNull();await api.setSession("new-server Native accepted-generation bearer",USER,"alice");await expect(checkAnalysisGeneration(USER,1,1)).resolves.toBeUndefined();expect(await secureStore.getItem(accountStorageKey.stateSequence(USER))).toBe("1");
});
it("a new-origin Native check does not wait behind a retired old-origin read lane",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;await held.run();}return value;});const old=checkAnalysisGeneration(USER,10,10).then(()=>"accepted",()=>"refused");await vi.waitFor(()=>expect(held.entered()).toBe(true));await setBaseUrl("https://replacement-native-pending-generation.example");await api.setSession("new-server Native independent-lane bearer",USER,"alice");const current=checkAnalysisGeneration(USER,1,1).then(()=>"accepted",()=>"refused");const outcome=await Promise.race([current,new Promise<string>(resolve=>setTimeout(()=>resolve("waiting for the unrelated old provider"),50))]);held.release();expect(await old).toBe("refused");await current;expect(outcome).toBe("accepted");expect(await get(slot)).toBe("1");await expect(checkAnalysisGeneration(USER,2,2)).resolves.toBeUndefined();expect(await get(slot)).toBe("2");
});
it("same-origin Native reauthentication preserves a failed-persist process high-water mirror",async()=>{
 const slot=accountStorageKey.stateSequence(USER),write=storage.setItem.bind(storage);vi.spyOn(storage,"setItem").mockImplementation(async(name,value)=>{if(name===slot)throw new Error("Native mark volume is temporarily full");return write(name,value);});await expect(checkAnalysisGeneration(USER,13,13)).resolves.toBeUndefined();expect(await storage.getItem(slot)).toBeNull();await api.setSession("reauthenticated same-origin Native mirror bearer",USER,"alice");await expect(checkAnalysisGeneration(USER,12,12)).rejects.toThrow("freshness check");
});
it("Native generation checks retired with their view refuse both an admitted read and its queued successor",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true,current=true;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;await held.run();}return value;});const old=checkAnalysisGeneration(USER,1000,1000,()=>current).then(()=>"accepted",()=>"refused");await vi.waitFor(()=>expect(held.entered()).toBe(true));const queued=checkAnalysisGeneration(USER,2000,2000,()=>current).then(()=>"accepted",()=>"refused");current=false;held.release();expect(await old).toBe("refused");expect(await queued).toBe("refused");expect(await get(slot)).toBe("9");await expect(checkAnalysisGeneration(USER,10,10,()=>true)).resolves.toBeUndefined();expect(await get(slot)).toBe("10");
});
it.each(["sealed-read","legacy-read","migration-write","mark-write"] as const)("a Native %s receipt cannot acknowledge generation acceptance after its view retires",async phase=>{
 const slot=accountStorageKey.stateSequence(USER),held=hold(),get=secureStore.getItem.bind(secureStore),set=secureStore.setItem.bind(secureStore),rawRead=storage.getItem.bind(storage);let first=true,current=true,sealedFinished=false;
 if(phase==="legacy-read"||phase==="migration-write")await storage.setItem(slot,"9");else await secureStore.setItem(slot,"9");
 vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot&&phase==="sealed-read"){first=false;await held.run();}sealedFinished=true;return value;});
 vi.spyOn(storage,"getItem").mockImplementation(async name=>{const value=await rawRead(name);if(first&&name===slot&&phase==="legacy-read"&&sealedFinished){first=false;await held.run();}return value;});
 vi.spyOn(secureStore,"setItem").mockImplementation(async(name,value)=>{await set(name,value);if(first&&name===slot&&(phase==="migration-write"||phase==="mark-write")){first=false;await held.run();}});
 const target=phase==="mark-write"?1000:10;const pending=checkAnalysisGeneration(USER,target,target,()=>current).then(()=>"accepted",()=>"refused");await vi.waitFor(()=>expect(held.entered()).toBe(true));current=false;held.release();expect(await pending).toBe("refused");const retained=Number(phase==="legacy-read"?await rawRead(slot):await get(slot));if(phase==="legacy-read")expect(await rawRead(slot)).toBe("9");expect(retained).toBe(phase==="mark-write"?1000:9);await expect(checkAnalysisGeneration(USER,retained+1,retained+1,()=>true)).resolves.toBeUndefined();expect(await get(slot)).toBe(String(retained+1));
});
it.each(["prefix9","9suffix","prefix9suffix","9\n"])("a malformed authenticated Native mark %j cannot bypass the current process high-water receipt",async malformed=>{
 const slot=accountStorageKey.stateSequence(USER);await checkAnalysisGeneration(USER,13,13);await secureStore.setItem(slot,malformed);await expect(checkAnalysisGeneration(USER,12,12)).rejects.toThrow("freshness check");await expect(checkAnalysisGeneration(USER,14,14)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("14");
});
it("a multi-digit plaintext Native legacy mark remains authoritative before its sealed migration",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await storage.setItem(slot,"109");await expect(checkAnalysisGeneration(USER,108,108)).rejects.toThrow("freshness check");expect(await secureStore.getItem(slot)).toBe("109");await expect(checkAnalysisGeneration(USER,110,110)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("110");
});
it.each(["sealed","legacy"] as const)("a stale %s Native mark is repaired to the failed-persist mirror before a fresh-process read",async format=>{
 const slot=accountStorageKey.stateSequence(USER),set=storage.setItem.bind(storage);let refuse=true;vi.spyOn(storage,"setItem").mockImplementation(async(name,value)=>{if(name===slot&&refuse)throw new Error("The Native mark volume has no capacity for this write");return set(name,value);});await expect(checkAnalysisGeneration(USER,13,13)).resolves.toBeUndefined();expect(await storage.getItem(slot)).toBeNull();refuse=false;if(format==="sealed")await secureStore.setItem(slot,"9");else await storage.setItem(slot,"9");await expect(checkAnalysisGeneration(USER,13,13)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("13");runTestControl(resetAnalysisGenerationMirrors);await expect(checkAnalysisGeneration(USER,12,12)).rejects.toThrow("freshness check");
});
it.each(["prefix109","109suffix","prefix109suffix","109\n"])("a malformed plaintext Native legacy mark %j cannot be adopted as a durable generation",async malformed=>{
 const slot=accountStorageKey.stateSequence(USER);await storage.setItem(slot,malformed);await expect(checkAnalysisGeneration(USER,1,1)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("1");runTestControl(resetAnalysisGenerationMirrors);await expect(checkAnalysisGeneration(USER,0,0)).rejects.toThrow("freshness check");
});
it.each(Array.from({length:6},(_,index)=>index+1))("a Native sealed-read handoff at microtask %s refuses a generation whose view has retired",async turns=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const get=secureStore.getItem.bind(secureStore);let first=true,current=true;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;const schedule=(remaining:number)=>queueMicrotask(()=>{if(remaining===1)current=false;else schedule(remaining-1);});schedule(turns);}return value;});const outcome=await checkAnalysisGeneration(USER,9,9,()=>current).then(()=>"accepted",()=>"refused");expect(outcome).toBe("refused");expect(await get(slot)).toBe("9");await expect(checkAnalysisGeneration(USER,10,10,()=>true)).resolves.toBeUndefined();expect(await get(slot)).toBe("10");
});
it.each(Array.from({length:6},(_,index)=>index+1))("a Native mark-write handoff at microtask %s cannot acknowledge a retired view",async turns=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const set=secureStore.setItem.bind(secureStore);let first=true,current=true;vi.spyOn(secureStore,"setItem").mockImplementation(async(name,value)=>{await set(name,value);if(first&&name===slot){first=false;const schedule=(remaining:number)=>queueMicrotask(()=>{if(remaining===1)current=false;else schedule(remaining-1);});schedule(turns);}});const outcome=await checkAnalysisGeneration(USER,1000,1000,()=>current).then(()=>"accepted",()=>"refused");expect(outcome).toBe("refused");expect(await secureStore.getItem(slot)).toBe("1000");await expect(checkAnalysisGeneration(USER,1001,1001,()=>true)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("1001");
});
it("an already retired view refuses before waiting behind an unrelated live Native mark receipt",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"9");const held=hold(),get=secureStore.getItem.bind(secureStore);let first=true;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;await held.run();}return value;});const live=checkAnalysisGeneration(USER,10,10,()=>true);await vi.waitFor(()=>expect(held.entered()).toBe(true));const retired=checkAnalysisGeneration(USER,11,11,()=>false).then(()=>"accepted",()=>"refused");const outcome=await Promise.race([retired,new Promise<string>(resolve=>setTimeout(()=>resolve("waiting behind the unrelated Native receipt"),50))]);held.release();await live;await retired;expect(outcome).toBe("refused");expect(await get(slot)).toBe("10");
});
it("a genuine failed sealed Native read preserves the documented mirror-only decision",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await storage.setItem(slot,"109");const get=storage.getItem.bind(storage);let first=true;vi.spyOn(storage,"getItem").mockImplementation(async name=>{if(first&&name===slot){first=false;throw new Error("The Native storage provider refused this read");}return get(name);});await expect(checkAnalysisGeneration(USER,108,108)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("108");runTestControl(resetAnalysisGenerationMirrors);await expect(checkAnalysisGeneration(USER,107,107)).rejects.toThrow("freshness check");
});
it.each(["same-generation","unreadable-mark"] as const)("%s accepts without occupying an unnecessary held Native repair write",async scenario=>{
 const slot=accountStorageKey.stateSequence(USER);await checkAnalysisGeneration(USER,13,13);if(scenario==="unreadable-mark")await secureStore.setItem(slot,"9");const get=storage.getItem.bind(storage),set=storage.setItem.bind(storage),held=hold();let first=true;vi.spyOn(storage,"getItem").mockImplementation(async name=>{if(scenario==="unreadable-mark"&&first&&name===slot){first=false;throw new Error("The Native mark read is temporarily unavailable");}return get(name);});vi.spyOn(storage,"setItem").mockImplementation(async(name,value)=>{if(name===slot)await held.run();return set(name,value);});const checking=checkAnalysisGeneration(USER,13,13).then(()=>"accepted",()=>"refused");const outcome=await Promise.race([checking,new Promise<string>(resolve=>setTimeout(()=>resolve("waiting for an unnecessary Native write"),50))]);held.release();await checking;expect(outcome).toBe("accepted");await expect(checkAnalysisGeneration(USER,12,12)).rejects.toThrow("freshness check");
});
it("an authenticated Native read pins a same-generation receipt against later physical deletion",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"13");await expect(checkAnalysisGeneration(USER,13,13)).resolves.toBeUndefined();await storage.removeItem(slot);await expect(checkAnalysisGeneration(USER,12,12)).rejects.toThrow("freshness check");await expect(checkAnalysisGeneration(USER,13,13)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("13");
});
it.each([1,2])("a retired Native read at handoff %s cannot contaminate the replacement view's process mirror",async turns=>{
 const slot=accountStorageKey.stateSequence(USER);await secureStore.setItem(slot,"109");const get=secureStore.getItem.bind(secureStore);let first=true,current=true,replacement:Promise<void>|undefined;vi.spyOn(secureStore,"getItem").mockImplementation(async name=>{const value=await get(name);if(first&&name===slot){first=false;const schedule=(remaining:number)=>queueMicrotask(()=>{if(remaining===1){current=false;replacement=secureStore.setItem(slot,"9");}else schedule(remaining-1);});schedule(turns);}return value;});await expect(checkAnalysisGeneration(USER,109,109,()=>current)).rejects.toThrow();await replacement;expect(await get(slot)).toBe("9");await expect(checkAnalysisGeneration(USER,12,12,()=>true)).resolves.toBeUndefined();expect(await get(slot)).toBe("12");
});
it("a genuine Native legacy migration write refusal retains its authoritative generation and permits a later repair",async()=>{
 const slot=accountStorageKey.stateSequence(USER);await storage.setItem(slot,"109");const set=storage.setItem.bind(storage);let refuse=true;vi.spyOn(storage,"setItem").mockImplementation(async(name,value)=>{if(name===slot&&refuse)throw new Error("The Native metadata volume cannot commit this migration");return set(name,value);});await expect(checkAnalysisGeneration(USER,109,109)).resolves.toBeUndefined();expect(await storage.getItem(slot)).toBe("109");await expect(checkAnalysisGeneration(USER,108,108)).rejects.toThrow("freshness check");refuse=false;await expect(checkAnalysisGeneration(USER,110,110)).resolves.toBeUndefined();expect(await secureStore.getItem(slot)).toBe("110");
});
