import React from "react";
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { Text } from "react-native";
import { api,ApiError,canonicalOrigin,setBaseUrl,getBaseUrl } from "../src/api/client";
import { SessionProvider,useSession,stashDraft,peekDraft,takeStashedDraft,peekStashedJournalDraft } from "../src/store";
import { newJournalDraft } from "../src/journalDraft";
import { vault } from "../src/vault";
import { secureStore,setSecureStoreBackend } from "../src/secureStore";
import { __resetLocalKeyLifecycleForTests } from "../src/localWriteGuard";
import { runTestControl } from "./helpers/testControl";
import storage from "./helpers/storageMock";
import * as files from "./helpers/expoFsMock";
import { accountStorageKey,ACCOUNT_STORAGE_PREFIX } from "../src/accountStorage";
import { flushQueue } from "../src/offlineQueue";
import { storeUnlockProof,unlockProofExists } from "../src/unlockProof";
import { recordCrisisDialogShown,crisisDialogShownOn } from "../src/crisisDialog";
import { setMeasureReminderEnabled,getMeasureReminderPrefs,recordMeasureCompleted,lastMeasureCompletedOn } from "../src/measureReminders";
import { enableBiometricUnlock,hasBiometricUnlock } from "../src/biometricUnlock";
import { setReminderEnabled } from "../src/reminders";
import { syncReminderSchedule } from "../src/reminderSync";
import { enqueueAudio,audioQueueCount,flushAudioQueue } from "../src/audioQueue";
import { encryptAudio,decryptAudio } from "../src/crypto/journalCrypto";
import { emitAppState } from "./helpers/rnMock";
import ReactTestRenderer,{act} from "react-test-renderer";
const {notificationDevice}=vi.hoisted(()=>({notificationDevice:{rows:new Map<string,unknown>(),permission:async():Promise<unknown>=>({authorizationStatus:1})}}));
vi.mock("@notifee/react-native",()=>({default:{requestPermission:()=>notificationDevice.permission(),createChannel:async()=>"channel",createTriggerNotification:async(notification:{id:string},trigger:unknown)=>{notificationDevice.rows.set(notification.id,trigger);return notification.id;},cancelNotification:async(id:string)=>{notificationDevice.rows.delete(id);},cancelAllNotifications:async()=>{notificationDevice.rows.clear();},getTriggerNotifications:async()=>[...notificationDevice.rows].map(([id,trigger])=>({notification:{id},trigger})),getDisplayedNotifications:async()=>[]},TriggerType:{TIMESTAMP:0},RepeatFrequency:{DAILY:1}}));

type Root=ReturnType<typeof ReactTestRenderer.create>;
async function render(element:React.ReactElement){let result!:Root;await act(async()=>{result=ReactTestRenderer.create(element);});return result;}

const USER="a".repeat(32),OTHER="b".repeat(32);
const nativeDelete=files.deleteAsync.getMockImplementation()!;
let session:ReturnType<typeof useSession>,root:Root|undefined,serverDays:unknown,responseStatus:number,serverUnlockDays:unknown;
function Probe(){session=useSession();return <Text>{JSON.stringify({auth:session.authStatus,unlocked:session.unlocked,days:session.activeDays,known:session.activeDaysKnown,loading:session.activeDaysLoading,unlockDays:session.unlockDays,erasure:session.erasureIncomplete})}</Text>;}
function state(){return JSON.parse(root!.root.findByType(Text).props.children);}
async function mount(unlockDays=45){root=await render(<SessionProvider><Probe/></SessionProvider>);await vi.waitFor(()=>expect(state()).toEqual({auth:"loggedIn",unlocked:false,days:5,known:true,loading:false,unlockDays,erasure:false}));}
beforeEach(async()=>{
 vi.useRealTimers();vi.restoreAllMocks();storage.__reset();files.__resetFiles();files.deleteAsync.mockImplementation(nativeDelete);runTestControl(setSecureStoreBackend,null);runTestControl(__resetLocalKeyLifecycleForTests);vault.lock();serverDays=5;responseStatus=200;serverUnlockDays=45;
 await api.setSession("native-bearer",USER,"alice");
 notificationDevice.rows=new Map();notificationDevice.permission=async()=>({authorizationStatus:1});const notifications=notificationDevice.rows;vi.stubGlobal("require",(name:string)=>{if(name!=="@notifee/react-native")throw new Error("unavailable native module "+name);return {default:{getTriggerNotifications:async()=>[...notifications].map(([id,trigger])=>({notification:{id},trigger})),getDisplayedNotifications:async()=>[],cancelNotification:async(id:string)=>{notifications.delete(id);},cancelAllNotifications:async()=>{notifications.clear();},createChannel:async()=>"channel",createTriggerNotification:async(notification:{id:string},trigger:unknown)=>{notifications.set(notification.id,trigger);return notification.id;},requestPermission:async()=>({authorizationStatus:1})},TriggerType:{TIMESTAMP:0},RepeatFrequency:{DAILY:1}};});
 vi.stubGlobal("fetch",vi.fn(async(url:string)=>{const path=new URL(url).pathname;let value:unknown;if(path.endsWith("/insights"))value=responseStatus===200?{active_days:serverDays}:{code:"account_deleted",detail:"untrusted account response"};else if(path.endsWith("/meta"))value={unlock_days:serverUnlockDays};else if(path.endsWith("/auth/logout"))value={};else throw new Error("unexpected native route "+path);const response=new Response(JSON.stringify(value),{status:path.endsWith("/insights")?responseStatus:200});Object.defineProperty(response,"url",{value:url});return response;}));
});
afterEach(async()=>{if(root){await act(async()=>root!.unmount());root=undefined;}vi.useRealTimers();vi.restoreAllMocks();vault.lock();await api.clearSession();vi.unstubAllGlobals();});
it("preserves the first cold-start native editor fallback without a fresh-login callback",async()=>{
 stashDraft(USER,"cold editor fallback");expect(peekDraft(USER)).toBe("cold editor fallback");expect(takeStashedDraft(USER)).toBe("cold editor fallback");expect(peekDraft(USER)).toBeNull();expect(peekStashedJournalDraft(USER,canonicalOrigin(new URL(await getBaseUrl()).origin))).toBeNull();
});
it.each(["wrong account","wrong origin","text only"])("refuses rich editor fallback for %s while preserving its actual owner",async kind=>{
 await mount();await act(async()=>session.markLoggedIn());const origin=canonicalOrigin(new URL(await getBaseUrl()).origin),draft={...newJournalDraft(),text:"owned native editor",mood:.5,tags:["work"]};stashDraft(USER,draft.text,kind==="text only"?undefined:draft,origin);
 expect(peekStashedJournalDraft(kind==="wrong account"?OTHER:USER,kind==="wrong origin"?"https://another.native.test":origin)).toBeNull();expect(peekDraft(USER)).toBe(draft.text);
 if(kind!=="text only"){const restored=peekStashedJournalDraft(USER,origin);expect(restored).toEqual(draft);restored!.tags.push("borrowed change");expect(peekStashedJournalDraft(USER,origin)).toEqual(draft);}
});
it.each(["exact origin","unspecified origin","legacy unspecified origin","foreign origin"])("restores text fallback under the shipped %s contract",async kind=>{
 await mount();await act(async()=>session.markLoggedIn());const origin=canonicalOrigin(new URL(await getBaseUrl()).origin);stashDraft(USER,"owned fallback",undefined,kind==="legacy unspecified origin"?undefined:origin);
 expect(takeStashedDraft(OTHER,origin)).toBeNull();expect(peekDraft(USER)).toBe("owned fallback");const result=takeStashedDraft(USER,kind==="unspecified origin"?undefined:kind==="foreign origin"?"https://another.native.test":origin);
 expect(result).toBe(kind==="foreign origin"?null:"owned fallback");expect(peekDraft(USER)).toBe(kind==="foreign origin"?"owned fallback":null);
});
it("renders every safe session default and permits its public no-op callbacks outside a provider",async()=>{
 root=await render(<Probe/>);expect(state()).toEqual({auth:"loading",unlocked:false,days:0,known:false,loading:false,unlockDays:30,erasure:false});
 await act(async()=>{session.markLoggedIn();session.setUnlockDays(99);session.touchActivity();await session.refreshActiveDays();expect(await session.beginProgressRead()).toBeNull();session.finishProgressRead({owner:USER,generation:0,request:0});session.applyActiveDays(12,{owner:USER,generation:0,request:0});await session.signOut();});
 expect(state()).toEqual({auth:"loading",unlocked:false,days:0,known:false,loading:false,unlockDays:30,erasure:false});
});
it.each([0,0.75,7.9,3650,3651,10000])("renders an authoritative public progress value %s with its bounded integer semantics",async days=>{
 await mount();await act(async()=>{const read=await session.beginProgressRead();expect(read?.owner).toBe(USER);session.applyActiveDays(days,read!);});expect(state()).toMatchObject({days:Math.min(3650,Math.floor(days)),known:true,loading:false});
});
it.each([-1,NaN,Infinity,-Infinity,"12",null,undefined,{},[]])("retains known progress while refusing an invalid public value %j",async days=>{
 await mount();await act(async()=>{const read=await session.beginProgressRead();session.applyActiveDays(days,read!);});expect(state()).toMatchObject({days:5,known:true,loading:true});
});
it("retains authoritative progress when native JSON contains an overflowing numeric exponent",async()=>{
 await mount();const transport=fetch;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(new URL(url).pathname.endsWith("/insights")){const response=new Response('{"active_days":1e400}',{status:200});Object.defineProperty(response,"url",{value:url});return response;}return transport(url,init);});
 await act(async()=>session.refreshActiveDays());expect(state()).toMatchObject({days:5,known:true,loading:false});
});
it("finishes a current public progress read without changing its known count",async()=>{
 await mount();let read:Awaited<ReturnType<typeof session.beginProgressRead>>;await act(async()=>{read=await session.beginProgressRead();});expect(state()).toMatchObject({days:5,known:true,loading:true});await act(async()=>session.finishProgressRead(read!));expect(state()).toMatchObject({days:5,known:true,loading:false});
});
it("keeps a newer progress read loading after an older read finishes or tries to publish",async()=>{
 await mount();let old:Awaited<ReturnType<typeof session.beginProgressRead>>,next:typeof old;await act(async()=>{old=await session.beginProgressRead();next=await session.beginProgressRead();session.finishProgressRead(old!);session.applyActiveDays(123,old!);});expect(state()).toMatchObject({days:5,known:true,loading:true});await act(async()=>session.applyActiveDays(12,next!));expect(state()).toMatchObject({days:12,known:true,loading:false});
});
it("invalidates a progress receipt when a new login generation takes ownership",async()=>{
 await mount();let old:Awaited<ReturnType<typeof session.beginProgressRead>>;await act(async()=>{old=await session.beginProgressRead();session.markLoggedIn();session.finishProgressRead(old!);session.applyActiveDays(123,old!);});expect(state()).toMatchObject({days:5,known:true,loading:true});
});
it("clears another account's count while its new native progress read is still loading",async()=>{
 await mount();await api.setSession("new-native-bearer",OTHER,"bob");let read:Awaited<ReturnType<typeof session.beginProgressRead>>;await act(async()=>{read=await session.beginProgressRead();});expect(read!.owner).toBe(OTHER);expect(state()).toMatchObject({days:0,known:false,loading:true});await act(async()=>session.applyActiveDays(9,read!));expect(state()).toMatchObject({days:9,known:true,loading:false});
});
it("clears progress and finishes a read when native credential storage has no account",async()=>{
 await mount();await api.clearSession();await act(async()=>{expect(await session.beginProgressRead()).toBeNull();});expect(state()).toMatchObject({days:0,known:false,loading:false});
});
it("finishes a failed native credential read while retaining the last authoritative count",async()=>{
 await mount();const get=secureStore.getItem;vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{if(key==="@mindpattern/user_id")throw new Error("native credentials unavailable");return get(key);});await act(async()=>{expect(await session.beginProgressRead()).toBeNull();});expect(state()).toMatchObject({days:5,known:true,loading:false});
});
it("locks the rendered vault at the exact native inactivity deadline",async()=>{
 await mount();vi.useFakeTimers();await act(async()=>vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.alloc(32,3)},USER));expect(state().unlocked).toBe(true);
 await act(async()=>vi.advanceTimersByTimeAsync(299999));expect(state().unlocked).toBe(true);await act(async()=>vi.advanceTimersByTimeAsync(1));expect(state().unlocked).toBe(false);
});
it("restarts the native inactivity countdown from actual interaction",async()=>{
 await mount();vi.useFakeTimers();await act(async()=>vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.alloc(32,3)},USER));await act(async()=>vi.advanceTimersByTimeAsync(120000));await act(async()=>session.touchActivity());await act(async()=>vi.advanceTimersByTimeAsync(180000));expect(state().unlocked).toBe(true);await act(async()=>vi.advanceTimersByTimeAsync(120000));expect(state().unlocked).toBe(false);
});
it.each(["background","inactive"])("locks the actual native vault when AppState enters %s",async event=>{
 await mount();await act(async()=>vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.alloc(32,3)},USER));expect(state().unlocked).toBe(true);await act(async()=>emitAppState(event));expect(state().unlocked).toBe(false);
});
it("wipes plaintext and rejects abandoned editor cleanup after native sign-out",async()=>{
 await mount();await act(async()=>session.markLoggedIn());stashDraft(USER,"unsent old-account plaintext");expect(peekDraft(USER)).toBe("unsent old-account plaintext");await act(async()=>session.signOut());stashDraft(USER,"abandoned editor plaintext");expect(peekDraft(USER)).toBeNull();expect(state()).toMatchObject({auth:"loggedOut",unlocked:false,days:0,known:false,loading:false});expect(await api.getUserId()).toBeNull();
});
it("wipes plaintext and rendered progress on native server-origin retirement",async()=>{
 await mount();await act(async()=>session.markLoggedIn());stashDraft(USER,"old-origin plaintext");await act(async()=>setBaseUrl("https://another.native.test"));stashDraft(USER,"abandoned old-origin plaintext");expect(peekDraft(USER)).toBeNull();expect(state()).toMatchObject({auth:"loggedOut",unlocked:false,days:0,known:false,loading:false});expect(await api.getUserId()).toBeNull();
});
it.each(["voice cleanup","erasure inventory"])("fails closed before session hydration after a native %s failure",async boundary=>{
 if(boundary==="voice cleanup")vi.spyOn(files,"deleteAsync").mockRejectedValue(new Error("native scratch disk unavailable"));else vi.spyOn(storage,"getAllKeys").mockRejectedValue(new Error("native erasure inventory unavailable"));
 root=await render(<SessionProvider><Probe/></SessionProvider>);await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedOut",unlocked:false,erasure:true,known:false,loading:false}));
});
it("keeps native credential-read failure behind the logged-out gate during cold boot",async()=>{
 const read=storage.getItem;vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(key==="@mindpattern/token")throw new Error("native encrypted credential slot unavailable");return read(key);});
 root=await render(<SessionProvider><Probe/></SessionProvider>);await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedOut",unlocked:false,known:false,loading:false,erasure:false}));
});
it("retires the native deleted-account tuple and reports incomplete native erasure",async()=>{
 await mount();await act(async()=>session.markLoggedIn());stashDraft(USER,"deleted-account plaintext");vi.spyOn(files,"deleteAsync").mockRejectedValue(new Error("native erasure disk unavailable"));responseStatus=410;await act(async()=>session.refreshActiveDays());await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedOut",days:0,known:false,loading:false,erasure:true}));expect(peekDraft(USER)).toBeNull();expect(await api.getUserId()).toBeNull();
});
it.each([-1,0,0.5,1.5,366,NaN,Infinity,"45",null,undefined,{},[]])("retains the default gate when native metadata supplies an invalid unlock-days value %j",async value=>{serverUnlockDays=value;await mount(30);});
it.each([1,365])("adopts the native metadata gate's inclusive boundary %s",async value=>{serverUnlockDays=value;await mount(value);});
it.each([-1,0.5,"12",null,undefined,{},[],NaN,Infinity])("retains known progress when an actual native HTTP refresh returns %j",async value=>{
 await mount();serverDays=value;await act(async()=>session.refreshActiveDays());expect(state()).toMatchObject({days:typeof value==="number"&&Number.isFinite(value)&&value>=0?Math.floor(value):5,known:true,loading:false});
});
it("retains known progress and finishes loading after an actual native server failure",async()=>{await mount();responseStatus=500;await act(async()=>session.refreshActiveDays());expect(state()).toMatchObject({auth:"loggedIn",days:5,known:true,loading:false});});
it.each(["new request","new login"])("refuses an old native progress-owner read after a %s takes ownership",async action=>{
 await mount();const read=secureStore.getItem;let first=true,release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/user_id"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});
 let pending:ReturnType<typeof session.beginProgressRead>;await act(async()=>{pending=session.beginProgressRead();await started;});await act(async()=>{if(action==="new login")session.markLoggedIn();else{const next=await session.beginProgressRead();session.applyActiveDays(9,next!);}});
 try{let result:Awaited<typeof pending>;await act(async()=>{release();result=await pending;});expect(result!).toBeNull();expect(state()).toMatchObject({days:action==="new login"?5:9,known:true,loading:action==="new login"});}finally{release();await pending!;}
});
it("keeps the newest native HTTP refresh after an older response finishes",async()=>{
 await mount();const transport=fetch;let first=true,release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/insights")&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return response;});
 serverDays=7;let pending:Promise<void>;await act(async()=>{pending=session.refreshActiveDays();await started;});serverDays=9;await act(async()=>session.refreshActiveDays());expect(state()).toMatchObject({days:9,known:true,loading:false});try{await act(async()=>{release();await pending;});expect(state()).toMatchObject({days:9,known:true,loading:false});}finally{release();await pending!;}
});
it("removes the original account's native proof, preferences, biometric wrap and unlock caches on sign-out",async()=>{
 await mount();vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.alloc(32,3)},USER);await storeUnlockProof(vault.get().dataKey,USER);await recordCrisisDialogShown(USER,"2026-10-06");await recordCrisisDialogShown(USER,"2026-10-06","phq9-item9");await setMeasureReminderEnabled(USER,true);await recordMeasureCompleted(USER,"2026-10-06");await enableBiometricUnlock(USER,vault.get().dataKey);await storage.setItem(accountStorageKey.recompute(USER),"older recompute metadata");await api.cacheSalt("alice",Buffer.alloc(16,3).toString("base64"));
 await act(async()=>session.signOut());expect(await unlockProofExists(USER)).toBe(false);expect(await crisisDialogShownOn(USER,"2026-10-06")).toBe(false);expect(await crisisDialogShownOn(USER,"2026-10-06","phq9-item9")).toBe(false);expect((await getMeasureReminderPrefs(USER)).enabled).toBe(false);expect(await lastMeasureCompletedOn(USER)).toBeNull();expect(await hasBiometricUnlock(USER)).toBe(false);expect(await storage.getItem(accountStorageKey.recompute(USER))).toBeNull();expect(await api.getCachedSalt("alice")).toBeNull();expect(state().auth).toBe("loggedOut");
});
it("reports complete native erasure after the deleted account's physical slots have been removed",async()=>{
 await mount();await act(async()=>session.markLoggedIn());await recordCrisisDialogShown(USER,"2026-10-06");responseStatus=410;await act(async()=>session.refreshActiveDays());await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedOut",days:0,known:false,loading:false,erasure:false}));expect(await api.getUserId()).toBeNull();await vi.waitFor(async()=>expect(await crisisDialogShownOn(USER,"2026-10-06")).toBe(false));
});
it("blocks native hydration while a persisted erasure checkpoint still owns failed voice cleanup",async()=>{
 const origin=await getBaseUrl();await secureStore.setItem(accountStorageKey.erasure(origin,USER),JSON.stringify({origin,userId:USER,username:"alice"}));files.deleteAsync.mockImplementation(async(uri,options)=>{if(uri.includes("mindpattern-audio/"))throw new Error("native erasure disk unavailable");return nativeDelete(uri,options);});root=await render(<SessionProvider><Probe/></SessionProvider>);await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedOut",known:false,loading:false,erasure:true}));await act(async()=>{for(let i=0;i<256;i++)await Promise.resolve();});expect(state().unlockDays).toBe(30);expect(await secureStore.getItem(accountStorageKey.erasure(origin,USER))).not.toBeNull();
});
it.each(["sign-out","server origin","account deletion"])("never re-adopts a held native owner receipt after login followed by %s",async retirement=>{
 await mount();const read=secureStore.getItem;let first=true,release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/user_id"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});
 let pending!:ReturnType<typeof session.beginProgressRead>;await act(async()=>{pending=session.beginProgressRead();await started;});await act(async()=>{session.markLoggedIn();if(retirement==="sign-out")await session.signOut();else if(retirement==="server origin")await setBaseUrl("https://another.native.test");else{responseStatus=410;await api.insights().catch(()=>{});}});
 try{let result!:Awaited<typeof pending>;await act(async()=>{release();result=await pending;});expect(result).toBeNull();expect(state()).toMatchObject({auth:"loggedOut",known:false,loading:false});}finally{release();await pending;}
});
it("keeps a replacement login when old native cold-start hydration finishes with no credentials",async()=>{
 await api.clearSession();const read=secureStore.getItem;let first=true,release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/token"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});
 root=await render(<SessionProvider><Probe/></SessionProvider>);await started;await api.setSession("new-native-bearer",USER,"alice");await act(async()=>session.markLoggedIn());try{await act(async()=>{release();for(let i=0;i<32;i++)await Promise.resolve();});expect(state().auth).toBe("loggedIn");}finally{release();}
});
it.each(["voice scratch","erasure inventory"])("keeps a replacement login when old native boot %s fails",async boundary=>{
 let release!:()=>void,ready!:()=>void,first=true;const started=new Promise<void>(resolve=>{ready=resolve;});const wait=async()=>{if(!first)return;first=false;ready();await new Promise<void>(resolve=>{release=resolve;});throw new Error("retired native boot unavailable");};
 if(boundary==="voice scratch")files.deleteAsync.mockImplementation(async(uri,options)=>{await wait();return nativeDelete(uri,options);});else{const keys=storage.getAllKeys;vi.spyOn(storage,"getAllKeys").mockImplementation(async()=>{await wait();return keys();});}
 root=await render(<SessionProvider><Probe/></SessionProvider>);await started;await act(async()=>session.markLoggedIn());try{await act(async()=>{release();for(let i=0;i<32;i++)await Promise.resolve();});expect(state()).toMatchObject({auth:"loggedIn",erasure:false});}finally{release();}
});
it.each(["new login","replacement credentials"])("keeps the current metadata gate when its old native response spans %s",async replacement=>{
 const transport=fetch;let release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});serverUnlockDays=7;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/meta")){ready();await new Promise<void>(resolve=>{release=resolve;});}return response;});
 root=await render(<SessionProvider><Probe/></SessionProvider>);await started;await act(async()=>{session.setUnlockDays(45);if(replacement==="new login")session.markLoggedIn();else await api.setSession("replacement-bearer",OTHER,"bob");});try{await act(async()=>{release();for(let i=0;i<32;i++)await Promise.resolve();});expect(state().unlockDays).toBe(45);}finally{release();}
});
it("finishes a retired native HTTP refresh without closing the replacement login's progress read",async()=>{
 await mount();const transport=fetch;let first=true,release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/insights")&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return response;});let pending!:Promise<void>;await act(async()=>{pending=session.refreshActiveDays();await started;});await act(async()=>session.markLoggedIn());try{await act(async()=>{release();await pending;});expect(state()).toMatchObject({days:5,known:true,loading:true});}finally{release();await pending;}
});
it("finishes an older native HTTP refresh after a new read starts without closing the new read",async()=>{
 await mount();const transport=fetch;let first=true,release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/insights")&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return response;});let pending!:Promise<void>;await act(async()=>{pending=session.refreshActiveDays();await started;});await act(async()=>{await session.beginProgressRead();});try{await act(async()=>{release();await pending;});expect(state()).toMatchObject({days:5,known:true,loading:true});}finally{release();await pending;}
});
it("settles an ownerless native refresh before an unavailable unauthenticated endpoint could hold it open",async()=>{
 await mount();await api.clearSession();const transport=fetch;let release:()=>void=()=>{};vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(new URL(url).pathname.endsWith("/insights"))await new Promise<void>(resolve=>{release=resolve;});return transport(url,init);});let settled=false;const pending=session.refreshActiveDays().then(()=>{settled=true;});try{await act(async()=>{for(let i=0;i<128;i++)await Promise.resolve();});expect(settled).toBe(true);expect(state()).toMatchObject({days:0,known:false,loading:false});}finally{release();await pending;}
});
it("clears the visible count when native owner storage disappears before an ordinary refresh",async()=>{
 await mount();await api.clearSession();await act(async()=>session.refreshActiveDays());expect(state()).toMatchObject({days:0,known:false,loading:false});
});
it("locks the native vault on origin retirement even when no parent timer can still run",async()=>{
 await mount();await act(async()=>vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.alloc(32,3)},USER));await act(async()=>setBaseUrl("https://new-origin.native.test"));expect(vault.isUnlocked()).toBe(false);expect(state()).toMatchObject({auth:"loggedOut",unlocked:false});
});
it("removes the native AppState subscription and prevents a ghost idle timer after provider unmount",async()=>{
 await mount();vi.useFakeTimers();await act(async()=>vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.alloc(32,3)},USER));await act(async()=>{root!.unmount();root=undefined;});vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,12),dataKey:Buffer.alloc(32,13)},USER);emitAppState("background");await vi.advanceTimersByTimeAsync(300000);expect(vault.isUnlocked()).toBe(true);expect(vault.get().dataKey).toEqual(Buffer.alloc(32,13));
});
it("retires a legacy native bearer whose account identity disappeared when the server confirms deletion",async()=>{
 await mount();await secureStore.removeItem("@mindpattern/user_id");responseStatus=410;await act(async()=>{await api.insights().catch(()=>{});});await vi.waitFor(async()=>expect(await secureStore.getItem("@mindpattern/token")).toBeNull());expect(state()).toMatchObject({auth:"loggedOut",known:false,loading:false});
});
it("retires a native cold-start bearer with no owner without creating an unowned erasure checkpoint",async()=>{
 await secureStore.removeItem("@mindpattern/user_id");root=await render(<SessionProvider><Probe/></SessionProvider>);await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedOut",known:false,loading:false,erasure:false}));responseStatus=410;await act(async()=>{await api.insights().catch(()=>{});for(let i=0;i<256;i++)await Promise.resolve();});
 expect(await secureStore.getItem("@mindpattern/token")).toBeNull();expect(state()).toMatchObject({auth:"loggedOut",known:false,loading:false,erasure:false});expect((await storage.getAllKeys()).filter(key=>key.startsWith("@mindpattern/erasure"))).toEqual([]);
});
it("preserves the newest native progress value across a screen-read and provider-refresh cycle",async()=>{
 await mount();const transport=fetch;let first=true,release!:()=>void,ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/insights")&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return response;});serverDays=7;let pending!:Promise<void>;await act(async()=>{pending=session.refreshActiveDays();await started;});await act(async()=>{await session.beginProgressRead();});serverDays=9;await act(async()=>session.refreshActiveDays());expect(state().days).toBe(9);try{await act(async()=>{release();await pending;});expect(state()).toMatchObject({days:9,known:true,loading:false});}finally{release();await pending;}
});
it("preserves the new provider's native refresh quota after a prior login generation unmounts",async()=>{
 await mount();const oldSession=session,read=secureStore.getItem,transport=fetch;let first=true,release!:()=>void,ready!:()=>void,requests=0;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/user_id"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(new URL(url).pathname.endsWith("/insights")&&++requests>2){const refused=new Response('{"code":"rate_limited","detail":"native endpoint quota exhausted"}',{status:429});Object.defineProperty(refused,"url",{value:url});return refused;}return transport(url,init);});let pending!:Promise<void>;await act(async()=>{pending=oldSession.refreshActiveDays();await started;});await act(async()=>{oldSession.markLoggedIn();root!.unmount();root=undefined;});serverDays=9;root=await render(<SessionProvider><Probe/></SessionProvider>);await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedIn",days:9,known:true,loading:false}));try{await act(async()=>{release();await pending;});serverDays=11;await act(async()=>session.refreshActiveDays());expect(state()).toMatchObject({days:11,known:true,loading:false});}finally{release();await pending;}
});

it.each(["provider unmount","replacement credentials"])("an old native boot reminder cannot retire the current account's accepted schedule after %s",async retirement=>{
 await storage.setItem("@mindpattern/reminder.migration.v2.done","1");const read=secureStore.getItem;let reads=0,release:()=>void=()=>{};vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/user_id"&&++reads===2)await new Promise<void>(resolve=>{release=resolve;});return value;});await mount();await act(async()=>{if(retirement==="provider unmount"){root!.unmount();root=undefined;}else await api.setSession("replacement-bearer",OTHER,"bob");});const currentOwner=retirement==="provider unmount"?USER:OTHER;await setReminderEnabled(currentOwner,true);let permissionReady!:()=>void,allowPermission:()=>void=()=>{};const permissionStarted=new Promise<void>(resolve=>{permissionReady=resolve;});notificationDevice.permission=async()=>{permissionReady();await new Promise<void>(resolve=>{allowPermission=resolve;});return {authorizationStatus:1};};const current=syncReminderSchedule(currentOwner);await permissionStarted;try{release();for(let i=0;i<256;i++)await Promise.resolve();allowPermission();expect(await current).toBe(true);expect(notificationDevice.rows.has("mindpattern-daily-reminder")).toBe(true);}finally{release();allowPermission();await current;}
});

it("keeps native boot erasure status unasserted while scratch removal is still pending",async()=>{
 let release:()=>void=()=>{},ready!:()=>void,first=true;const started=new Promise<void>(resolve=>{ready=resolve;});files.deleteAsync.mockImplementation(async(uri,options)=>{if(first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return nativeDelete(uri,options);});root=await render(<SessionProvider><Probe/></SessionProvider>);await started;try{expect(state()).toMatchObject({auth:"loading",erasure:false,known:false,loading:false});}finally{await act(async()=>{release();for(let i=0;i<256;i++)await Promise.resolve();});}
});

it("refuses abandoned editor plaintext after native account deletion has closed the session",async()=>{
 await mount();await act(async()=>session.markLoggedIn());stashDraft(USER,"deleted-account plaintext");responseStatus=410;await act(async()=>session.refreshActiveDays());await vi.waitFor(()=>expect(state()).toMatchObject({auth:"loggedOut",known:false,loading:false}));stashDraft(USER,"abandoned editor cleanup plaintext");expect(peekDraft(USER)).toBeNull();
});

it("refuses a delivered native progress response when its final owner read belongs to a replacement account",async()=>{
 await mount();const read=secureStore.getItem;let delivered=false,release:()=>void=()=>{},ready!:()=>void,first=true;const started=new Promise<void>(resolve=>{ready=resolve;});const transport=fetch;vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/insights")){const json=response.json.bind(response);response.json=async()=>{const value=await json();delivered=true;return value;};}return response;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{if(key==="@mindpattern/user_id"&&delivered&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return read(key);});serverDays=19;let pending!:Promise<void>;await act(async()=>{pending=session.refreshActiveDays();await started;});await api.setSession("replacement-bearer",OTHER,"bob");try{await act(async()=>{release();await pending;});expect(state()).toMatchObject({days:5,known:true,loading:false});expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}finally{release();await pending;}
});

it.each(["provider unmount","replacement credentials"])("keeps the current native bearer usable when an old sign-out owner read spans %s",async retirement=>{
 await mount();const read=secureStore.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(secureStore,"getItem").mockImplementation(async key=>{const value=await read(key);if(key==="@mindpattern/user_id"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const transport=fetch,revoked=new Set<string>();vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const bearer=new Headers(init.headers).get("Authorization")??"";if(new URL(url).pathname.endsWith("/auth/logout"))revoked.add(bearer);if(revoked.has(bearer)&&new URL(url).pathname.endsWith("/meta")){const response=new Response(JSON.stringify({detail:"native bearer was revoked"}),{status:401});Object.defineProperty(response,"url",{value:url});return response;}return transport(url,init);});let pending!:Promise<void>;await act(async()=>{pending=session.signOut();await Promise.race([started,pending]);});await act(async()=>{if(retirement==="provider unmount"){root!.unmount();root=undefined;}else await api.setSession("replacement-bearer",OTHER,"bob");});try{await act(async()=>{release();await pending;});expect(await api.meta()).toMatchObject({unlock_days:45});expect(await secureStore.getItem("@mindpattern/token")).toBe(retirement==="provider unmount"?"native-bearer":"replacement-bearer");}finally{release();await pending;}
});

it.each(["provider unmount","replacement credentials"])("keeps native offline unlock caches when a delivered old logout response spans %s",async retirement=>{
 await mount();await api.cacheSalt("alice",Buffer.alloc(16,3).toString("base64"));const transport=fetch;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/auth/logout")&&first){first=false;const json=response.json.bind(response);response.json=async()=>{const value=await json();ready();await new Promise<void>(resolve=>{release=resolve;});return value;};}return response;});let pending!:Promise<void>;await act(async()=>{pending=session.signOut();await Promise.race([started,pending]);});await act(async()=>{if(retirement==="provider unmount"){root!.unmount();root=undefined;}else{await api.setSession("replacement-bearer",USER,"alice");await api.cacheSalt("alice",Buffer.alloc(16,9).toString("base64"));}});try{await act(async()=>{release();await pending;});expect(await api.getCachedSalt("alice")).toBe(Buffer.alloc(16,retirement==="provider unmount"?3:9).toString("base64"));expect(await secureStore.getItem("@mindpattern/token")).toBe(retirement==="provider unmount"?"native-bearer":"replacement-bearer");}finally{release();await pending;}
});

it("leaves the native device timer queue empty when a locked account receives foreground interaction",async()=>{
 await mount();vi.useFakeTimers({toFake:["setTimeout","clearTimeout"]});await act(async()=>session.touchActivity());expect(vault.isUnlocked()).toBe(false);expect(vi.getTimerCount()).toBe(0);await act(async()=>emitAppState("active"));await act(async()=>{for(let i=0;i<256;i++)await Promise.resolve();});expect(vi.getTimerCount()).toBe(0);
});

it("restores the opted-in native check-in notification from the persisted cadence on boot",async()=>{
 await storage.setItem("@mindpattern/reminder.migration.v2.done","1");await setMeasureReminderEnabled(USER,true);await recordMeasureCompleted(USER,new Date().toISOString().slice(0,10));await mount();await vi.waitFor(()=>expect(notificationDevice.rows.has("mindpattern-measure-reminder")).toBe(true));expect((await getMeasureReminderPrefs(USER)).enabled).toBe(true);
});

it.each(Array.from({length:24},(_,i)=>i+1))("preserves a replacement native bearer across the final sign-out cache delivery at turn %s",async turn=>{
 await mount();await api.cacheSalt("alice",Buffer.alloc(16,3).toString("base64"));const remove=storage.removeItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"removeItem").mockImplementation(async key=>{await remove(key);if(key==="@mindpattern/salt_alice"&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}});let pending!:Promise<void>;await act(async()=>{pending=session.signOut().catch(error=>{if(!(error instanceof ApiError&&error.status===0&&error.code==="stale_operation"))throw error;});await Promise.race([started,pending]);});try{await act(async()=>{release();for(let i=0;i<turn;i++)await Promise.resolve();await api.setSession("replacement-bearer",USER,"alice");await pending;});expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");expect(await api.getUserId()).toBe(USER);}finally{release();await pending;}
});

it("removes both physical native notification IDs when the opted-in account signs out",async()=>{
 await storage.setItem("@mindpattern/reminder.migration.v2.done","1");await setReminderEnabled(USER,true);await setMeasureReminderEnabled(USER,true);await recordMeasureCompleted(USER,new Date().toISOString().slice(0,10));await mount();await vi.waitFor(()=>expect([...notificationDevice.rows.keys()].sort()).toEqual(["mindpattern-daily-reminder","mindpattern-measure-reminder"]));await act(async()=>session.signOut());expect(notificationDevice.rows.size).toBe(0);
});

it("keeps an accepted login when old boot's last native erasure inventory still contains an unreadable checkpoint",async()=>{
 const origin=await getBaseUrl();await secureStore.setItem(accountStorageKey.erasure(origin,USER),"invalid persisted checkpoint");const read=storage.getAllKeys;let count=0,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getAllKeys").mockImplementation(async()=>{const value=await read();if(++count===2){ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});root=await render(<SessionProvider><Probe/></SessionProvider>);await started;await act(async()=>session.markLoggedIn());try{await act(async()=>{release();for(let i=0;i<256;i++)await Promise.resolve();});expect(state()).toMatchObject({auth:"loggedIn",erasure:false});}finally{release();}
});

it("uploads retained authenticated native voice ciphertext when the application returns to the foreground",async()=>{
 await mount();const dataKey=Buffer.alloc(32,17),blob=encryptAudio({dataKey},USER,"foreground-voice",Buffer.from("the account's retained spoken words"));await enqueueAudio({userId:USER,clientEntryId:"foreground-voice",...blob,mime:"audio/m4a",durationSeconds:4});const transport=fetch,received:Record<string,unknown>[]=[];vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{if(new URL(url).pathname.endsWith("/audio/attachments")){received.push(JSON.parse(String(init.body)));const response=new Response("{}",{status:200});Object.defineProperty(response,"url",{value:url});return response;}return transport(url,init);});await act(async()=>emitAppState("active"));await vi.waitFor(async()=>expect(await audioQueueCount(USER)).toBe(0));expect(received).toHaveLength(1);expect(decryptAudio({dataKey},USER,"foreground-voice",String(received[0].blob))).toEqual(Buffer.from("the account's retained spoken words"));
});

it.each(["origin change","sign-out"])("preserves the physical queue retirement outcome when an old malformed native row spans %s",async retirement=>{
 await mount();const origin=canonicalOrigin(new URL(await getBaseUrl()).origin),id=Buffer.from(`${origin}\0${USER}`).toString("base64url"),key=`${ACCOUNT_STORAGE_PREFIX.queue}.items.${id}`,quarantine=`${ACCOUNT_STORAGE_PREFIX.queue}.quarantine.${id}`,raw="the account's unreadable retained ciphertext";await storage.setItem(key,raw);const read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await read(slot);if(slot===key&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const pending=flushQueue(USER).catch(error=>error);await Promise.race([started,pending]);await act(async()=>{if(retirement==="origin change")await setBaseUrl("https://new-native-server.test");else await session.signOut();});try{release();await pending;expect(await storage.getItem(quarantine)).toBeNull();expect(await storage.getItem(key)).toBe(retirement==="origin change"?null:raw);}finally{release();await pending;}
});

it.each(Array.from({length:3},(_,i)=>i+1))("keeps the replacement metadata gate across native JSON delivery turn %s",async turn=>{
 serverUnlockDays=7;const transport=fetch;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/meta")&&first){first=false;const json=response.json.bind(response);response.json=async()=>{const value=await json();ready();await new Promise<void>(resolve=>{release=resolve;});return value;};}return response;});root=await render(<SessionProvider><Probe/></SessionProvider>);await started;await act(async()=>session.setUnlockDays(45));try{await act(async()=>{release();for(let i=0;i<turn;i++)await Promise.resolve();await api.setSession("replacement-bearer",OTHER,"bob");for(let i=0;i<256;i++)await Promise.resolve();});expect(state().unlockDays).toBe(45);expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}finally{release();}
});

it.each(Array.from({length:16},(_,i)=>i+1))("admits a same-owner replacement login without retired cleanup occupying unavailable native proof storage at turn %s",async turn=>{
 await mount();const remove=storage.removeItem;let first=true,replacementIntent=false,releaseFirst:()=>void=()=>{},releaseProof:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"removeItem").mockImplementation(async key=>{if(key===accountStorageKey.recompute(USER)&&first){first=false;ready();await new Promise<void>(resolve=>{releaseFirst=resolve;});}if(key===accountStorageKey.unlockProof(USER)&&replacementIntent)await new Promise<void>(resolve=>{releaseProof=resolve;});await remove(key);});const pending=session.signOut().catch(error=>{if(!(error instanceof ApiError&&error.status===0&&error.code==="stale_operation"))throw error;});await Promise.race([started,pending]);let adopted=false;try{releaseFirst();for(let i=0;i<turn;i++)await Promise.resolve();replacementIntent=true;const replacement=api.setSession("replacement-bearer",USER,"alice").then(()=>{adopted=true;});await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(adopted).toBe(true);expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");releaseProof();await replacement;await pending;}finally{releaseFirst();releaseProof();await pending;}
});

it("retains unreadable native outbox custody when an ownerless deletion retires an old queue read",async()=>{
 await mount();const origin=canonicalOrigin(new URL(await getBaseUrl()).origin),id=Buffer.from(`${origin}\0${USER}`).toString("base64url"),key=`${ACCOUNT_STORAGE_PREFIX.queue}.items.${id}`,quarantine=`${ACCOUNT_STORAGE_PREFIX.queue}.quarantine.${id}`,raw="retained unreadable ciphertext";await storage.setItem(key,raw);const read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await read(slot);if(slot===key&&first){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const pending=flushQueue(USER).catch(error=>error);await Promise.race([started,pending]);await secureStore.removeItem("@mindpattern/user_id");responseStatus=410;await act(async()=>api.insights().catch(()=>{}));try{release();await pending;expect(await storage.getItem(key)).toBe(raw);expect(await storage.getItem(quarantine)).toBeNull();}finally{release();await pending;}
});

it.each(["origin change","sign-out","ownerless deletion"])("admits the current native recording while a retired legacy migration's storage is unavailable after %s",async retirement=>{
 await mount();const origin=canonicalOrigin(new URL(await getBaseUrl()).origin),key=`${ACCOUNT_STORAGE_PREFIX.audioQueue}${origin}:${USER}:old-voice`,dataKey=Buffer.alloc(32,17),blob=encryptAudio({dataKey},USER,"old-voice",Buffer.from("the old account's spoken words"));await storage.setItem(key,JSON.stringify({blobB64:blob.blobB64,mime:"audio/m4a",durationSeconds:4,queuedAt:1}));const read=storage.getItem;let count=0,releaseFirst:()=>void=()=>{},releaseSecond:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async slot=>{const value=await read(slot);if(slot===key){if(++count===1){ready();await new Promise<void>(resolve=>{releaseFirst=resolve;});}else if(count===2)await new Promise<void>(resolve=>{releaseSecond=resolve;});}return value;});const pending=flushAudioQueue().catch(error=>error);await Promise.race([started,pending]);await act(async()=>{if(retirement==="origin change")await setBaseUrl("https://new-native-audio.test");else if(retirement==="sign-out")await session.signOut();else{await secureStore.removeItem("@mindpattern/user_id");responseStatus=410;await api.insights().catch(()=>{});}});await api.setSession("replacement-bearer",OTHER,"bob");let current:Promise<void>|undefined;try{releaseFirst();for(let i=0;i<32;i++)await Promise.resolve();let accepted=false;const next=encryptAudio({dataKey},OTHER,"new-voice",Buffer.from("the replacement account's spoken words"));current=enqueueAudio({userId:OTHER,clientEntryId:"new-voice",...next,mime:"audio/m4a",durationSeconds:4}).then(()=>{accepted=true;});await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(accepted).toBe(true);expect(await audioQueueCount(OTHER)).toBe(1);}finally{releaseFirst();releaseSecond();await pending;await current;}
});

it("keeps a replacement login's erasure status when old deleted-account cleanup finishes its final native inventory",async()=>{
 await mount();const read=storage.getAllKeys;let count=0,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getAllKeys").mockImplementation(async()=>{const value=await read();if(++count===3){ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});responseStatus=410;const deleted=api.insights().catch(()=>{});await deleted;await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));let replacement:Promise<void>|undefined;try{let adopted=false;replacement=api.setSession("replacement-bearer",OTHER,"bob").then(()=>{adopted=true;});await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));expect(adopted).toBe(true);responseStatus=200;await act(async()=>session.markLoggedIn());await act(async()=>{release();await deleted;for(let i=0;i<256;i++)await Promise.resolve();});expect(state()).toMatchObject({auth:"loggedIn",erasure:false});expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}finally{release();await deleted;await replacement;}
});

it.each(["current deletion","replacement login"])("scopes a Native erasure-origin provider failure to the %s receipt",async retirement=>{
 await mount();const transport=fetch,read=storage.getItem;let delivered=false,first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.stubGlobal("fetch",async(url:string,init:RequestInit)=>{const response=await transport(url,init);if(new URL(url).pathname.endsWith("/insights")&&response.status===410){const json=response.json.bind(response);response.json=async()=>{const value=await json();delivered=true;return value;};}return response;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{if(delivered&&first&&key==="@mindpattern/base_url"){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});throw new Error("Native erasure origin provider unavailable");}return read(key);});responseStatus=410;let pending!:Promise<void>;await act(async()=>{pending=session.refreshActiveDays();await Promise.race([started,pending]);});await new Promise<void>(resolve=>setImmediate(resolve));await new Promise<void>(resolve=>setImmediate(resolve));if(retirement==="replacement login")await act(async()=>{responseStatus=200;await api.setSession("replacement-bearer",OTHER,"bob");session.markLoggedIn();});
 try{await act(async()=>{release();await pending;await new Promise<void>(resolve=>setImmediate(resolve));});expect(state()).toMatchObject({auth:retirement==="replacement login"?"loggedIn":"loggedOut",erasure:retirement!=="replacement login"});if(retirement==="replacement login")expect(await secureStore.getItem("@mindpattern/token")).toBe("replacement-bearer");}finally{release();await pending;}
});

it("retires process-owned plaintext when an admitted Native origin change completes after provider unmount",async()=>{
 await mount();await act(async()=>{session.markLoggedIn();vault.unlock({masterKey:Buffer.alloc(32),authKey:Buffer.alloc(32,2),dataKey:Buffer.alloc(32,3)},USER);});stashDraft(USER,"old server's private unsent words");const read=storage.getItem;let first=true,release:()=>void=()=>{},ready!:()=>void;const started=new Promise<void>(resolve=>{ready=resolve;});vi.spyOn(storage,"getItem").mockImplementation(async key=>{const value=await read(key);if(first&&key==="@mindpattern/base_url"){first=false;ready();await new Promise<void>(resolve=>{release=resolve;});}return value;});const pending=setBaseUrl("https://another.native.test");await Promise.race([started,pending]);await act(async()=>{root!.unmount();root=undefined;});try{release();expect(await pending).toBeNull();expect(vault.isUnlocked()).toBe(false);expect(peekDraft(USER)).toBeNull();expect(await secureStore.getItem("@mindpattern/token")).toBeNull();}finally{release();await pending;}
});
