"""Spanish graded sentiment assets (2026-09-19).

The engine's first non-English lexicon: graded valences on the same -4..+4
scale as the English VADER-style base, plus the Spanish function-word/negator/
intensifier/contrast/absolutist sets. Design rules:

  * CURATED CONSERVATIVELY — ambiguous words (cognates whose meaning flips
    between the languages, or sense-ambiguous Spanish words) are omitted
    rather than guessed. A missed word delays a pattern; a wrong valence
    fabricates one.
  * Gender/number variants are listed explicitly (cansado/cansada/cansados/
    cansadas) — the English morphological rules only approximate Spanish
    plurals, and Spanish morphology deserves its own weight, not a hack.
  * Merged into the engine with ENGLISH WINS on collision (see brain.py):
    shared short words ("no", "sin" as negators) are unioned; graded
    entries never silently override an English reading.
  * Emoji are language-neutral and shared with the English engine.

Curation grounding: standard Spanish affect vocabulary aligned to the
VADER register (informal, first-person journal prose).
"""

from __future__ import annotations

# Graded sentiment, -4..+4 (the engine's SENTIMENT_SCALE maps ±4 → ±1).
#
# CONSTRAINT (audit round 2, 2026-09-21, F-5): both consumers of this map
# are PER-TOKEN lookups (the engine's `_word_valence` / topic eligibility
# consult single tokens and their word forms), so a key must never contain
# whitespace — a multi-word key can never match and is dead weight shipped
# to the on-device port. Phrase-level readings belong to the negation /
# intensifier window mechanisms, not to the key. A test pins this
# invariant; "eterno es", "por eso" and "darme cuenta" were removed for
# exactly this reason by the round-1 audit.
VADER_BASE_ES: dict[str, float] = {
    # --- positive: happiness/contentment ---
    "feliz": 2.8,
    "felices": 2.8,
    "felicidad": 3.0,
    "contento": 2.2,
    "contenta": 2.2,
    "contentos": 2.0,
    "contentas": 2.0,
    "alegre": 2.6,
    "alegres": 2.4,
    "alegría": 2.8,
    "alegria": 2.8,
    "gozoso": 2.4,
    "dichoso": 2.4,
    "encantado": 2.6,
    "encantada": 2.6,
    "ilusionado": 2.2,
    "ilusionada": 2.2,
    "ilusión": 2.0,
    "ilusion": 2.0,
    "entusiasmado": 2.8,
    "entusiasmada": 2.8,
    "entusiasmo": 2.6,
    "eufórico": 3.4,
    "euforico": 3.4,
    "jubiloso": 2.6,
    "radiante": 2.6,
    # --- positive: calm/wellbeing ---
    "tranquilo": 2.2,
    "tranquila": 2.2,
    "tranquilos": 2.0,
    "tranquilas": 2.0,
    "tranquilidad": 2.4,
    "calma": 2.0,
    "calmo": 2.0,
    "sereno": 2.2,
    "serena": 2.2,
    "serenidad": 2.4,
    "relajado": 2.4,
    "relajada": 2.4,
    "descansado": 2.0,
    "descansada": 2.0,
    "paz": 2.2,
    "cómodo": 1.8,
    "comodo": 1.8,
    "cómoda": 1.8,
    "comoda": 1.8,
    "agusto": 1.6,
    "bien": 1.6,
    "estupendo": 2.8,
    "estupenda": 2.8,
    "genial": 2.8,
    "excelente": 3.0,
    "perfecto": 2.8,
    "perfecta": 2.8,
    "maravilloso": 3.2,
    "maravillosa": 3.2,
    "maravillo": 2.8,
    "bueno": 1.8,
    "buena": 1.8,
    "buenísima": 2.4,
    "buenisima": 2.4,
    "bonito": 1.8,
    "bonita": 1.8,
    "hermoso": 2.4,
    "hermosa": 2.4,
    "precioso": 2.4,
    "preciosa": 2.4,
    "lindo": 1.8,
    "linda": 1.8,
    # --- positive: gratitude/hope/love ---
    "agradecido": 2.6,
    "agradecida": 2.6,
    "agradecimiento": 2.6,
    "gracias": 2.2,
    "gratitud": 2.6,
    "esperanzado": 2.4,
    "esperanzada": 2.4,
    "esperanza": 2.4,
    "espero": 1.2,
    "esperamos": 1.2,
    "optimista": 2.2,
    "confiado": 2.0,
    "confianza": 2.0,
    "amor": 3.2,
    "amo": 3.0,
    "amar": 2.8,
    # 0.3, matching EN "want" exactly (2026-09-20 audit H-8): "quiero" is
    # the highest-frequency Spanish verb and the old +2.2 read every
    # ideation phrase built on it ("quiero morir", "me quiero morir") as
    # strongly positive.
    "quiero": 0.3,
    "querido": 2.2,
    "querida": 2.2,
    "cariño": 2.6,
    "carino": 2.6,
    "cariñoso": 2.4,
    "carinoso": 2.4,
    "afecto": 2.2,
    "adoro": 3.0,
    "adorable": 2.6,
    "enamorado": 3.2,
    "enamorada": 3.2,
    "amado": 2.6,
    "amada": 2.6,
    # --- positive: pride/achievement ---
    "orgulloso": 2.6,
    "orgullosa": 2.6,
    "orgullo": 2.4,
    "logré": 2.6,
    "logre": 2.6,
    "logrado": 2.4,
    "lograda": 2.4,
    "logro": 2.2,
    "conseguí": 2.4,
    "consegui": 2.4,
    "conseguir": 2.0,
    "conseguido": 2.2,
    "superé": 2.6,
    "supere": 2.6,
    "supero": 2.2,
    "avancé": 2.2,
    "avance": 2.2,
    "progreso": 2.0,
    "triunfo": 2.8,
    "triunfante": 2.8,
    "victoria": 2.8,
    "gané": 2.4,
    "gane": 2.4,
    "ganando": 2.2,
    "éxito": 2.6,
    "exito": 2.6,
    "exitoso": 2.6,
    "exitosa": 2.6,
    "capaz": 1.8,
    "satisfecho": 2.4,
    "satisfecha": 2.4,
    "satisfacción": 2.4,
    "satisfaccion": 2.4,
    "realizado": 2.2,
    "realizada": 2.2,
    "útil": 1.8,
    "util": 1.8,
    # --- positive: fun/social ---
    "divertido": 2.4,
    "divertida": 2.4,
    "diversión": 2.4,
    "diversion": 2.4,
    "risa": 2.6,
    "riendo": 2.4,
    "reír": 2.4,
    "reir": 2.4,
    "bromeando": 1.8,
    "jugué": 2.0,
    "jugue": 2.0,
    "juge": 2.0,
    "jugando": 2.0,
    "baile": 2.2,
    "bailé": 2.2,
    "cantando": 2.0,
    "fiesta": 2.0,
    "vacaciones": 2.4,
    "celebrar": 2.4,
    "celebración": 2.4,
    "celebracion": 2.4,
    "celebré": 2.4,
    "celebre": 2.4,
    "disfruté": 2.6,
    "disfrute": 2.6,
    "disfrutar": 2.4,
    "disfrutando": 2.4,
    "gocé": 2.4,
    "goce": 2.4,
    # --- positive: comfort/reassurance ---
    "apoyado": 2.0,
    "apoyada": 2.0,
    "apoyo": 1.8,
    "acompañado": 2.0,
    "acompanado": 2.0,
    "acompañada": 2.0,
    "acompanada": 2.0,
    "seguro": 1.8,
    "protegido": 1.8,
    "protegida": 1.8,
    "escuchado": 2.0,
    "escuchada": 2.0,
    "entendido": 2.0,
    "entendida": 2.0,
    "quererme": 2.2,
    # --- negative: sadness ---
    "triste": -2.6,
    "tristes": -2.4,
    "tristeza": -2.8,
    "melancolía": -2.4,
    "melancolia": -2.4,
    "melancólico": -2.2,
    "melancolico": -2.2,
    "desanimado": -2.2,
    "desanimada": -2.2,
    "desánimo": -2.2,
    "desanimo": -2.2,
    "decaído": -2.2,
    "decaido": -2.2,
    "abatido": -2.6,
    "abatida": -2.6,
    "apagado": -2.2,
    "apagada": -2.2,
    "solo": -1.8,
    "sola": -1.8,
    "soledad": -2.8,
    "solitario": -2.4,
    "solitaria": -2.4,
    "aislado": -2.4,
    "aislada": -2.4,
    "vacío": -2.4,
    "vacio": -2.4,
    "vacía": -2.4,
    "vacia": -2.4,
    "desolado": -2.8,
    "desolada": -2.8,
    "llorando": -2.6,
    "llorar": -2.4,
    "lloré": -2.6,
    "llore": -2.6,
    "lágrimas": -2.4,
    "lagrimas": -2.4,
    "dolido": -2.4,
    "doler": -2.0,
    "duele": -2.4,
    "dolerme": -2.4,
    "pena": -2.4,
    "nostalgia": -1.8,
    "añoro": -1.8,
    "anoro": -1.8,
    "añoranza": -2.0,
    "anoranza": -2.0,
    "desamparo": -2.6,
    # --- negative: depression-adjacent (journal register) ---
    "deprimido": -3.0,
    "deprimida": -3.0,
    "depresión": -3.0,
    "depresion": -3.0,
    "desesperado": -3.2,
    "desesperada": -3.2,
    "desesperación": -3.2,
    "desesperacion": -3.2,
    "desesperanzado": -2.8,
    "desesperanzada": -2.8,
    "desesperanza": -3.0,
    "agotado": -2.4,
    "agotada": -2.4,
    "agotamiento": -2.4,
    "exhausto": -2.8,
    "exhausta": -2.8,
    "arrasado": -2.8,
    "arrasada": -2.8,
    "roto": -2.8,
    "rota": -2.8,
    "destrozado": -3.0,
    "destrozada": -3.0,
    "destruido": -3.0,
    "destruida": -3.0,
    "hundido": -2.8,
    "hundida": -2.8,
    "sumido": -2.4,
    "sumida": -2.4,
    "inútil": -2.8,
    "inutil": -2.8,
    "inutilidad": -2.6,
    "fracasado": -3.0,
    "fracasada": -3.0,
    "fracaso": -2.8,
    "frustrado": -2.6,
    "frustrada": -2.6,
    "frustración": -2.6,
    "frustracion": -2.6,
    # --- negative: death/self-harm ideation vocabulary (2026-09-20 audit
    # H-8: the class was absent — "pienso en el suicidio" scored 0.0 and
    # "quiero morir" scored POSITIVE via the old high "quiero" valence).
    # Values anchor to the English engine's own anchors (suicidal -3.8,
    # die/death -2.9, cut -1.1, disappear -0.9) so ES/EN ideation text
    # lands in the same band. "vivir" is deliberately POSITIVE: it is the
    # thing negators flip ("no quiero vivir" → mildly negative), which is
    # how the English engine reads "live".
    "suicidio": -3.8,
    "suicidios": -3.6,
    "suicida": -3.2,
    "suicidas": -3.0,
    "suicidarme": -3.8,
    "suicidarse": -3.4,
    "muerte": -2.9,
    "muertes": -2.6,
    "muerto": -2.6,
    "muertos": -2.4,
    "morir": -2.9,
    "morirme": -3.2,
    "matar": -2.6,
    "matarme": -3.0,
    "desaparecer": -0.9,
    "cortar": -1.1,
    "cortarme": -2.6,
    "vivir": 0.8,
    # --- negative: anxiety/fear ---
    "ansioso": -2.8,
    "ansiosa": -2.8,
    "ansiedad": -2.8,
    "nervioso": -2.2,
    "nerviosa": -2.2,
    "nervios": -2.0,
    "preocupado": -2.2,
    "preocupada": -2.2,
    "preocupación": -2.2,
    "preocupacion": -2.2,
    "miedo": -2.6,
    "temor": -2.6,
    "temiendo": -2.4,
    "temo": -2.4,
    "atemorizado": -2.8,
    "aterrorizado": -3.2,
    "aterrorizada": -3.2,
    "pánico": -3.0,
    "panico": -3.0,
    "angustia": -3.0,
    "angustiado": -3.0,
    "angustiada": -3.0,
    "inquieto": -1.8,
    "inquieta": -1.8,
    "inquietud": -2.0,
    "tenso": -2.0,
    "tensa": -2.0,
    "tensión": -2.2,
    "tension": -2.2,
    "estresado": -2.6,
    "estresada": -2.6,
    "estrés": -2.6,
    "estres": -2.6,
    "agobiado": -2.8,
    "agobiada": -2.8,
    "agobio": -2.6,
    "sobrepasado": -2.6,
    "sobrepasada": -2.6,
    "desbordado": -2.6,
    "desbordada": -2.6,
    "ahogo": -2.6,
    # --- negative: anger ---
    "enojado": -2.6,
    "enojada": -2.6,
    "enojo": -2.4,
    "enfurecido": -3.2,
    "enfurecida": -3.2,
    "furia": -3.0,
    "furioso": -3.0,
    "furiosa": -3.0,
    "rabia": -2.8,
    "molesto": -2.0,
    "molesta": -2.0,
    "molestia": -1.8,
    "irritado": -2.0,
    "irritada": -2.0,
    "irritable": -1.8,
    "irritación": -2.0,
    "irritacion": -2.0,
    "irritadísimo": -2.6,
    "irritadisimo": -2.6,
    "cabreado": -2.6,
    "cabreada": -2.6,
    "harto": -2.6,
    "harta": -2.6,
    "hartó": -2.4,
    "hartar": -2.2,
    "disgustado": -2.2,
    "disgustada": -2.2,
    "disgusto": -2.0,
    "odio": -3.2,
    "odiar": -3.0,
    "odiado": -3.0,
    "detesto": -3.0,
    "detestando": -2.8,
    "rencor": -2.6,
    "resentimiento": -2.4,
    "resentido": -2.4,
    "resentida": -2.4,
    "colérico": -2.8,
    "colerico": -2.8,
    "cólera": -2.6,
    "colera": -2.6,
    "indignado": -2.2,
    "indignada": -2.2,
    # --- negative: tiredness/physical ---
    "cansado": -1.8,
    "cansada": -1.8,
    "cansancio": -2.0,
    "fatigado": -2.0,
    "fatiga": -1.8,
    "insomnio": -2.6,
    "desvelado": -2.0,
    "pesado": -1.6,
    "pesada": -1.6,
    "pesadez": -1.8,
    "somnoliento": -1.4,
    "adormilado": -1.4,
    "mareado": -1.8,
    "náuseas": -2.0,
    "nauseas": -2.0,
    "dolor": -2.2,
    "doloroso": -2.2,
    "enfermo": -2.4,
    "enferma": -2.4,
    "enfermedad": -2.4,
    "fiebre": -1.8,
    "malestar": -2.0,
    # --- negative: difficulty/generic bad ---
    "mal": -2.2,
    "malo": -2.0,
    "mala": -2.0,
    "malísima": -2.6,
    "malisima": -2.6,
    "malísimo": -2.6,
    "malisimo": -2.6,
    "horrible": -3.0,
    "horroroso": -3.2,
    "horrorosa": -3.2,
    "horror": -3.0,
    "terrible": -3.0,
    "terriblemente": -3.0,
    "pésimo": -2.8,
    "pesimo": -2.8,
    "pésima": -2.8,
    "pesima": -2.8,
    "fatal": -2.8,
    "desastroso": -3.0,
    "desastrosa": -3.0,
    "desastre": -2.8,
    "catastrófico": -3.2,
    "catastrofico": -3.2,
    "insoportable": -3.0,
    "insoportablemente": -3.0,
    "difícil": -1.8,
    "dificil": -1.8,
    "dificultad": -1.8,
    "dificultades": -2.0,
    "duro": -1.6,
    "dura": -1.6,
    "complicado": -1.6,
    "complicada": -1.6,
    "problema": -1.8,
    "problemas": -2.0,
    "conflicto": -2.0,
    "conflictos": -2.0,
    "pelea": -2.2,
    "pelear": -2.0,
    "peleando": -2.2,
    "discusión": -2.0,
    "discusion": -2.0,
    "discutiendo": -2.0,
    "discutí": -2.0,
    "discuti": -2.0,
    "discutimos": -2.0,
    "lío": -1.6,
    "lio": -1.6,
    "vergüenza": -2.4,
    "verguenza": -2.4,
    "avergonzado": -2.2,
    "avergonzada": -2.2,
    "culpa": -2.4,
    "culpable": -2.4,
    "arrepentido": -2.2,
    "arrepentida": -2.2,
    "arrepiento": -2.2,
    "lamento": -2.0,
    "lamentando": -2.0,
    "perdí": -2.2,
    "perdi": -2.2,
    "perder": -1.8,
    "perdido": -2.0,
    "perdida": -2.0,
    "pérdida": -2.4,
    "fallo": -2.0,
    "fallé": -2.2,
    "falle": -2.2,
    "fallando": -1.8,
    "error": -1.8,
    "equivocado": -2.0,
    "equivocada": -2.0,
    "duda": -1.6,
    "dudas": -1.6,
    "confundido": -1.8,
    "confundida": -1.8,
    "confuso": -1.6,
    "confusa": -1.6,
    "descontrolado": -2.2,
    "impotente": -2.6,
    "indefenso": -2.6,
    "indefensa": -2.6,
    "abrumado": -2.6,
    "abrumada": -2.6,
}

# Spanish negators (flip a scoped valence with damping, like English).
NEGATORS_ES: frozenset[str] = frozenset(
    {
        "no",
        "nunca",
        "jamás",
        "jamas",
        "nada",
        "nadie",
        "ninguno",
        "ninguna",
        "ningún",
        "ningun",
        "tampoco",
        "ni",
        "sin",
        "apenas",
    }
)

# Spanish intensifiers (scale the next sentiment word). Same per-token
# constraint as VADER_BASE_ES above: the walk consults the PREVIOUS TOKEN,
# so keys containing whitespace can never match (F-5).
INTENSIFIERS_ES: dict[str, float] = {
    "muy": 1.4,
    "tan": 1.2,
    "tanto": 1.15,
    "realmente": 1.25,
    "bastante": 1.2,
    "super": 1.4,
    "súper": 1.4,
    "extremadamente": 1.6,
    "increíblemente": 1.6,
    "increiblemente": 1.6,
    "absolutamente": 1.6,
    "completamente": 1.55,
    "totalmente": 1.5,
    "profundamente": 1.45,
    "verdaderamente": 1.3,
    "sumamente": 1.5,
    "hyper": 1.5,
    "hiper": 1.5,
    "algo": 0.75,
    "ligeramente": 0.75,
    "medio": 0.8,
    "medía": 0.8,
}

# Contrast words ("pero" re-weighting, the English BUT_WORDS mechanism).
BUT_WORDS_ES: frozenset[str] = frozenset({"pero", "aunque", "sino", "salvo"})

# Absolutist words (Spanish register of Al-Mosaiwi & Johnstone 2018's list).
ABSOLUTIST_WORDS_ES: frozenset[str] = frozenset(
    {
        "siempre",
        "nunca",
        "jamás",
        "jamas",
        "todo",
        "todos",
        "toda",
        "todas",
        "nada",
        "nadie",
        "imposible",
        "imposiblemente",
        "eterno",
        "eternamente",
        "absoluto",
        "absolutamente",
        "total",
        "totalmente",
        "completamente",
        "inevitable",
        "inevitablemente",
        "definitivo",
        "definitivamente",
        "constantemente",
    }
)

# Sense-making words (causal + insight, the Spanish register of SENSE_WORDS).
SENSE_WORDS_ES: frozenset[str] = frozenset(
    {
        # causal
        "porque",
        "razón",
        "razones",
        "causa",
        "causas",
        "causado",
        "efecto",
        "efectos",
        "consecuencia",
        "consecuencias",
        "resultado",
        "resultados",
        "resultó",
        "resulto",
        "llevó",
        "llevo",
        # insight
        "entiendo",
        "entender",
        "entendí",
        "entendi",
        "comprendo",
        "comprender",
        "comprendí",
        "comprendi",
        "comprendido",
        "comprendida",
        "realizo",
        "realizar",
        "realicé",
        "realice",
        "realizado",
        "aprendo",
        "aprender",
        "aprendí",
        "aprendi",
        "aprendido",
        "noto",
        "notar",
        "noté",
        "note",
        "notado",
        "perspectiva",
        "explico",
        "explicar",
        "expliqué",
        "explique",
        "reflexiono",
        "reflexionar",
        "reflexioné",
        "reflexione",
        "entero",
        "memoricé",
    }
)

# Spanish function words — the language-DETECTION set (what distinguishes
# Spanish prose from English in hit-rate terms; graded words are shared
# via the merged lexicon and deliberately NOT counted here so detection
# works even on low-affect prose).
LANGUAGE_FUNCTION_WORDS_ES: frozenset[str] = frozenset(
    {
        "de",
        "la",
        "que",
        "el",
        "en",
        "y",
        "a",
        "los",
        "se",
        "del",
        "las",
        "un",
        "por",
        "con",
        "no",
        "una",
        "su",
        "para",
        "es",
        "al",
        "lo",
        "como",
        "más",
        "mas",
        "pero",
        "sus",
        "le",
        "ya",
        "este",
        "si",
        "porque",
        "esta",
        "entre",
        "cuando",
        "muy",
        "sin",
        "sobre",
        "también",
        "tambien",
        "me",
        "hasta",
        "hay",
        "donde",
        "quien",
        "desde",
        "todo",
        "nos",
        "durante",
        "todos",
        "uno",
        "les",
        "ni",
        "contra",
        "otros",
        "ese",
        "eso",
        "ante",
        "ellos",
        "esto",
        "mi",
        "antes",
        "algunos",
        "que",
        "unos",
        "yo",
        "tu",
        "él",
        "ella",
        "nosotros",
        "vosotros",
        "son",
        "estoy",
        "está",
        "estan",
        "están",
        "era",
        "fue",
        "ser",
        "tener",
        "tiene",
        "tengo",
        "tenía",
        "tenia",
        "había",
        "habia",
        "han",
        "ha",
        "sido",
        "hacer",
        "hice",
        "hizo",
        "puede",
        "puedo",
        "podía",
        "podia",
        "quiero",
        "quería",
        "queria",
        "sé",
        "sabe",
        "sabía",
        "sabia",
        "va",
        "voy",
        "iba",
        "fui",
        "vamos",
        "van",
        "viene",
        "vino",
        "dijo",
        "dice",
        "decir",
        "cosas",
        "cosa",
        "manera",
        "vez",
        "veces",
        "día",
        "dia",
        "días",
        "dias",
        "año",
        "ano",
        "años",
        "anos",
        "gente",
        "vida",
        "mano",
        "manos",
        "casa",
        "trabajo",
        "mucho",
        "mucha",
        "muchos",
        "muchas",
        "poco",
        "poca",
        "pocos",
        "pocas",
        "mismo",
        "misma",
        "mismos",
        "mismas",
        "otro",
        "otra",
        "otros",
        "otras",
        "tan",
        "tanto",
        "ahora",
        "aquí",
        "aqui",
        "allí",
        "alli",
        "hoy",
        "ayer",
        "mañana",
        "manana",
        "después",
        "despues",
        "luego",
        "siempre",
        "casi",
        "solo",
        "sólo",
        "bien",
        "mal",
        "así",
        "asi",
        "aún",
        "aun",
        "aunque",
        "sino",
        "cada",
        "cual",
        "cuales",
        "cuando",
        "cuánto",
        "cuanto",
        "dónde",
        "donde",
        "quées",
        "quien",
        "quiénes",
    }
)
