import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {buildFeedbackBlob,clearFeedback,recordFeedbackTap,recordPatternMute,type FeedbackReceipt} from "../src/questionFeedback";
import {buildAad} from "../src/crypto/aad";
import {decrypt,encrypt,fromBase64,toBase64} from "../src/crypto/core";
import {kv,setKvBackendForTests} from "../src/kvstore";
import {vault} from "../src/vault";
import {installSession,resetTestState} from "./helpers/api";
const USER="b".repeat(32),KEY=new Uint8Array(32).fill(9),SLOT=`mindpattern.feedback.${USER}`;
let map:Map<string,string>;
beforeEach(()=>{resetTestState();installSession(USER);vault.unlock({authKey:new Uint8Array(KEY),dataKey:new Uint8Array(KEY)},USER);map=new Map();setKvBackendForTests({async getItem(k){return map.get(k)??null;},async setItem(k,v){map.set(k,v);},async removeItem(k){map.delete(k);}});});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
async function snapshot(){let receipt:FeedbackReceipt|undefined;const blob=await buildFeedbackBlob(KEY,USER,value=>receipt=value);expect(blob).not.toBeNull();expect(receipt).toBeDefined();return receipt!;}
async function output(){const blob=await buildFeedbackBlob(KEY,USER);if(blob===null)return null;const bytes=await decrypt(KEY,fromBase64(blob),buildAad("feedback",USER,new Date().toISOString().slice(0,10)));return JSON.parse(new TextDecoder().decode(bytes));}
describe("acknowledged native feedback receipts",()=>{
 it("counts identical native entropy identities once for the delivered occurrence",async()=>{const native=crypto.getRandomValues.bind(crypto);vi.spyOn(crypto,"getRandomValues").mockImplementation(<T extends ArrayBufferView|null>(buffer:T):T=>{if(buffer instanceof Uint8Array&&buffer.byteLength===16){buffer.fill(23);return buffer;}return native(buffer as ArrayBufferView) as T;});await recordFeedbackTap(KEY,USER,"topic:same",true);const receipt=await snapshot(),permit=await kv.captureWritePermit(USER,KEY);await recordFeedbackTap(KEY,USER,"topic:same",true);await clearFeedback(USER,permit,{dataKey:KEY,receipt});expect(await output()).toEqual({feedback:[{pid:"topic:same",resonated:true}],muted:[],unmuted:[]});});
 for(const corrupt of ["not base64!", "not JSON"])it(`keeps a native unreadable feedback record absent from recompute: ${corrupt}`,async()=>{map.set(SLOT,corrupt==="not JSON"?toBase64(await encrypt(KEY,new TextEncoder().encode(corrupt),buildAad("feedback-local",USER))):corrupt);expect(await output()).toBeNull();});
 it("sanitizes authenticated scalar rows without publishing them as feedback",async()=>{map.set(SLOT,toBase64(await encrypt(KEY,new TextEncoder().encode(JSON.stringify([1,"scalar",null,false,{pid:"topic:actual",resonated:true}])),buildAad("feedback-local",USER))));expect(await output()).toEqual({feedback:[{pid:"topic:actual",resonated:true}],muted:[],unmuted:[]});});
 it("acknowledges a fully delivered native queue even when new device writes are refused",async()=>{await recordFeedbackTap(KEY,USER,"topic:delivered",true);const receipt=await snapshot(),permit=await kv.captureWritePermit(USER,KEY);setKvBackendForTests({async getItem(k){return map.get(k)??null;},async setItem(){throw new DOMException("native quota exceeded","QuotaExceededError");},async removeItem(k){map.delete(k);}});await expect(clearFeedback(USER,permit,{dataKey:KEY,receipt})).resolves.toBeUndefined();expect(map.has(SLOT)).toBe(false);expect(await output()).toBeNull();});
 it("joins a sibling tab's native browser transaction before appending its own event",async()=>{const tails=new Map<string,Promise<unknown>>();const locks={request:<T,>(name:string,run:()=>Promise<T>):Promise<T>=>{const result=(tails.get(name)??Promise.resolve()).then(run,run);tails.set(name,result.catch(()=>undefined));return result;}};vi.stubGlobal("navigator",{locks});let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);const sibling=locks.request(`mindpattern-feedback-${USER}`,async()=>{await held;const rows=[{pid:"topic:sibling",resonated:true,event_id:toBase64(crypto.getRandomValues(new Uint8Array(16)))}];map.set(SLOT,toBase64(await encrypt(KEY,new TextEncoder().encode(JSON.stringify(rows)),buildAad("feedback-local",USER))));});let completed=false;const own=recordFeedbackTap(KEY,USER,"topic:own",false).then(()=>{completed=true;});try{await new Promise(resolve=>setTimeout(resolve,10));expect(completed).toBe(false);release();await sibling;await own;expect(await output()).toEqual({feedback:[{pid:"topic:sibling",resonated:true},{pid:"topic:own",resonated:false}],muted:[],unmuted:[]});}finally{release();await Promise.allSettled([sibling,own]);}});
 for(const operation of ["append","acknowledge"]as const)it(`erases actual owned key and plaintext allocations after native ${operation}`,async()=>{await recordFeedbackTap(KEY,USER,"topic:before",true);const receipt=await snapshot(),permit=await kv.captureWritePermit(USER,KEY);await recordFeedbackTap(KEY,USER,"topic:late",false);const owned=new Set<Uint8Array>(),plaintext=new Set<Uint8Array>();const Native=Uint8Array,nativeSet=Native.prototype.set,nativeEncode=TextEncoder.prototype.encode;vi.stubGlobal("Uint8Array",new Proxy(Native,{construct(target,args){const value=Reflect.construct(target,args);if(value.length===32&&value.every((x:number)=>x===9))owned.add(value);return value;}}));vi.spyOn(Native.prototype,"set").mockImplementation(function(this:Uint8Array,values,offset){nativeSet.call(this,values,offset);if(this.length===32&&this.every(x=>x===9))owned.add(this);});vi.spyOn(TextEncoder.prototype,"encode").mockImplementation(function(this:TextEncoder,value){const bytes=nativeEncode.call(this,value);if(value?.includes("topic:"))plaintext.add(bytes);return bytes;});if(operation==="append")await recordFeedbackTap(KEY,USER,"topic:appended",true);else await clearFeedback(USER,permit,{dataKey:KEY,receipt});expect(owned.size).toBeGreaterThan(0);expect(plaintext.size).toBeGreaterThan(0);owned.forEach(bytes=>expect([...bytes]).toEqual(Array(32).fill(0)));plaintext.forEach(bytes=>expect(bytes.every(x=>x===0)).toBe(true));expect([...KEY]).toEqual(Array(32).fill(9));});
 it("keeps newer identical taps after the queue evicts the first submitted occurrence",async()=>{for(let i=0;i<64;i++)await recordFeedbackTap(KEY,USER,"topic:same",true);const receipt=await snapshot();await recordFeedbackTap(KEY,USER,"topic:same",true);await clearFeedback(USER,await kv.captureWritePermit(USER,KEY),{dataKey:KEY,receipt});expect(await output()).toEqual({feedback:[{pid:"topic:same",resonated:true}],muted:[],unmuted:[]});});
 it("consumes exactly the submitted taps and mute history while preserving later event order",async()=>{await recordFeedbackTap(KEY,USER,"topic:old",true);await recordPatternMute(KEY,USER,"topic:mutable",false);await recordPatternMute(KEY,USER,"topic:mutable",true);const receipt=await snapshot();await recordFeedbackTap(KEY,USER,"topic:new-1",false);await recordPatternMute(KEY,USER,"topic:mutable",false);await recordFeedbackTap(KEY,USER,"topic:new-2",true);await clearFeedback(USER,await kv.captureWritePermit(USER,KEY),{dataKey:KEY,receipt});expect(await output()).toEqual({feedback:[{pid:"topic:new-1",resonated:false},{pid:"topic:new-2",resonated:true}],muted:[],unmuted:["topic:mutable"]});expect(map.get(SLOT)).not.toContain("topic:");});
 it("replaying a consumed receipt cannot remove a later event with the same words and choice",async()=>{await recordFeedbackTap(KEY,USER,"topic:same",true);const receipt=await snapshot(),permit=await kv.captureWritePermit(USER,KEY);await clearFeedback(USER,permit,{dataKey:KEY,receipt});expect(await output()).toBeNull();await recordFeedbackTap(KEY,USER,"topic:same",true);await clearFeedback(USER,permit,{dataKey:KEY,receipt});expect(await output()).toEqual({feedback:[{pid:"topic:same",resonated:true}],muted:[],unmuted:[]});});
 it("legacy receipts count duplicate id-less occurrences without deleting a later current-producer tap",async()=>{const legacy=[{pid:"topic:same",resonated:true},{pid:"topic:same",resonated:true},{pid:"topic:other",mute:false}];const bytes=await encrypt(KEY,new TextEncoder().encode(JSON.stringify(legacy)),buildAad("feedback-local",USER));await kv.setItem(SLOT,toBase64(bytes),await kv.captureWritePermit(USER,KEY));const receipt=await snapshot();await recordFeedbackTap(KEY,USER,"topic:same",true);await clearFeedback(USER,await kv.captureWritePermit(USER,KEY),{dataKey:KEY,receipt});expect(await output()).toEqual({feedback:[{pid:"topic:same",resonated:true}],muted:[],unmuted:[]});});
 it("a native rewrite failure keeps the recoverable queue intact for the same receipt retry",async()=>{await recordFeedbackTap(KEY,USER,"topic:old",true);const receipt=await snapshot(),permit=await kv.captureWritePermit(USER,KEY);await recordFeedbackTap(KEY,USER,"topic:late",false);const raw=map.get(SLOT);vi.spyOn(crypto.subtle,"encrypt").mockRejectedValueOnce(new DOMException("native cipher unavailable","OperationError"));await expect(clearFeedback(USER,permit,{dataKey:KEY,receipt})).rejects.toThrow("native cipher unavailable");expect(map.get(SLOT)).toBe(raw);await clearFeedback(USER,permit,{dataKey:KEY,receipt});expect(await output()).toEqual({feedback:[{pid:"topic:late",resonated:false}],muted:[],unmuted:[]});});
 it("a receipt never exposes local event identities in the server-bound payload",async()=>{await recordFeedbackTap(KEY,USER,"topic:opaque",false);const receipt=await snapshot();expect(receipt.events[0]!.event_id).toBeTypeOf("string");expect(await output()).toEqual({feedback:[{pid:"topic:opaque",resonated:false}],muted:[],unmuted:[]});});
 it("a native lock refusal keeps the existing queue and rejects the public acknowledgement",async()=>{await recordFeedbackTap(KEY,USER,"topic:retained",true);const receipt=await snapshot(),raw=map.get(SLOT);vi.stubGlobal("navigator",{locks:{request:async()=>{throw new Error("native lock unavailable");}}});await expect(clearFeedback(USER,await kv.captureWritePermit(USER,KEY),{dataKey:KEY,receipt})).rejects.toThrow("native lock unavailable");expect(map.get(SLOT)).toBe(raw);});
});
