import { act } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { LoginView, passwordPolicyError } from "../src/views/LoginView";
import { hasSession } from "../src/api/client";
import { vault } from "../src/vault";
import { deriveMasterKey, fromBase64 } from "../src/crypto/core";
import { createRegistrationEnvelope } from "../src/crypto/envelope";
import { jsonResponse, resetTestState, stubFetch } from "./helpers/api";
import { isDisabled, press, render, setCheckbox, settle, textOf, textOfNode, typeInto } from "./helpers/rtr";
const USER="a".repeat(32), SALT="AAECAwQFBgcICQoLDA0ODw==", PASSWORD="quiet-morning-lantern-42";
beforeEach(resetTestState); afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
const token=(overrides:Record<string,unknown>={})=>({token:"signed-token",user_id:USER,expires_in:86400,role:"user",...overrides});
function routes(login:Record<string,unknown>=token(),status=200){return stubFetch(url=>url.endsWith("/auth/salt")?jsonResponse({salt:SALT}):jsonResponse(login,{status}));}
async function filled(register=false){const root=await render(<LoginView onSuccess={()=>undefined}/>);if(register)await press(root,"Create an account");await typeInto(root,"Username","alice");await typeInto(root,"Password",PASSWORD);if(register){await typeInto(root,"Confirm password",PASSWORD);await setCheckbox(root,"I am 18 or older",true);}return root;}
describe("native login UI completion",()=>{
 for(const [password,level]of [["",0],["tiny",1],["abcdefghijkl",2],["abcdefghijkl1!",3],["abcdefghijklmn1!",4]] as const){it(`shows exact accessible strength and bar classes for level ${level}`,async()=>{const root=await filled(true);await typeInto(root,"Password",password);const meter=root.root.findAll(n=>n.type==="div"&&n.props.className==="strength");if(level===0){expect(meter).toHaveLength(0);return;}expect(meter).toHaveLength(1);expect(meter[0]!.props.role).toBe("status");expect(meter[0]!.props["aria-label"]).toBe(`Password strength: ${["","Weak","Fair","Good","Strong"][level]}`);expect(meter[0]!.findAllByType("span").slice(0,4).map(n=>n.props.className)).toEqual(Array.from({length:4},(_,i)=>`strength__bar${i<level?` strength__bar--${level}`:""}`));expect(textOf(root)).toContain(["","Weak","Fair","Good","Strong"][level]);});}
 it("resets confirmation, age declaration, password, error and mode labels",async()=>{routes();const root=await filled(true);await typeInto(root,"Confirm password","wrong");await press(root,"Create journal");expect(textOf(root)).toContain("match");await press(root,"I have an account");expect(root.root.findAllByType("input").find(n=>n.props.type==="password")?.props.value).toBe("");expect(textOf(root)).not.toContain("match");await press(root,"Create an account");expect(root.root.findAllByType("input").filter(n=>n.props.type==="password").map(n=>n.props.value)).toEqual(["",""]);expect(root.root.findAllByType("input").find(n=>n.props.type==="checkbox")?.props.checked).toBe(false);expect(isDisabled(root,"Create journal")).toBe(true);});
 for(const username of ["ab","a".repeat(65),"alice!","alice\n"," alice","alice/../"]){it(`refuses invalid native username ${JSON.stringify(username)}`,async()=>{let dispatched=0;stubFetch(()=>{dispatched++;return jsonResponse(token());});const root=await filled();await typeInto(root,"Username",username);await press(root,"Sign in");expect(textOf(root)).toContain("3–64");expect(dispatched).toBe(0);});}
 it("an empty sign-in password stays a local validation error",async()=>{let dispatched=0;stubFetch(()=>{dispatched++;return jsonResponse(token());});const root=await filled();await typeInto(root,"Password","");await press(root,"Sign in");expect(textOf(root)).toContain("Enter your password");expect(dispatched).toBe(0);});
 it("a form submission cancels navigation and completes native sign-in",async()=>{routes();const root=await filled();let prevented=false;await act(async()=>{root.root.findByType("form").props.onSubmit({preventDefault(){prevented=true;}});});await settle(80,8);expect(prevented).toBe(true);expect(hasSession()).toBe(true);expect(textOf(root)).not.toContain("invalid response");expect(vault.ownerUserId()).toBe(USER);});
 it("a held native login disables submission and then restores its public action",async()=>{let release!:()=>void;const gate=new Promise<void>(r=>release=r);let reached=false;stubFetch(async url=>{if(url.endsWith("/auth/salt"))return jsonResponse({salt:SALT});reached=true;await gate;return jsonResponse({code:"invalid_credentials"},{status:401});});const root=await filled();await press(root,"Sign in");await settle(50,8);expect(reached).toBe(true);expect(isDisabled(root,"Working…")).toBe(true);await act(async()=>release());await settle(50,4);expect(isDisabled(root,"Sign in")).toBe(false);expect(textOf(root)).toContain("check your username and password");});
 for(const [mode,code,status,expected]of [[false,"conflict",409,"conflicts with something"],[true,"conflict",409,"already in use"],[false,"rate_limited",429,"Too many attempts"],[false,"server_error",500,"The server hit a problem"]]as const){it(`maps ${mode?"register":"signin"} native ${code} honestly without Retry-After`,async()=>{stubFetch(url=>url.endsWith("/auth/salt")?jsonResponse({salt:SALT}):jsonResponse({code,detail:"private-server-detail"},{status}));const root=await filled(mode);await press(root,mode?"Create journal":"Sign in");await settle(80,8);expect(textOf(root)).toContain(expected);expect(textOf(root)).not.toContain("private-server-detail");expect(textOf(root)).not.toContain("NaN");expect(hasSession()).toBe(false);});}
 for(const register of [false,true])for(const invalid of [token({role:"therapist"}),token({user_id:USER+"f"}),token({user_id:USER+"\n"})]){it(`rejects ${register?"register":"signin"} native ${invalid.role}/${JSON.stringify(invalid.user_id)}`,async()=>{const root=await filled(register);const originals=new Set<Uint8Array>();const native=crypto.subtle.deriveBits.bind(crypto.subtle);vi.spyOn(crypto.subtle,"deriveBits").mockImplementation(async(...args)=>{const result=await native(...args);originals.add(new Uint8Array(result));return result;});routes(invalid);await press(root,register?"Create journal":"Sign in");await settle(80,9);expect(hasSession()).toBe(false);expect(vault.isUnlocked()).toBe(false);expect(textOf(root)).toContain(invalid.role==="therapist"?"therapist portal":"invalid response");expect(originals.size).toBeGreaterThanOrEqual(3);expect([...originals].every(bytes=>bytes.every(x=>x===0))).toBe(true);});}
 for(const iterations of [600000,800000]){it(`unwraps an actual independently prepared v2 ${iterations} profile`,async()=>{const salt=fromBase64(SALT);const master=await deriveMasterKey(PASSWORD,salt,iterations);const envelope=await createRegistrationEnvelope(master,salt,"alice",{algorithm:"pbkdf2-sha256",version:1,iterations});stubFetch(url=>{if(url.endsWith("/auth/salt"))return jsonResponse({salt:SALT});if(url.endsWith("/auth/login"))return jsonResponse(token({key_scheme:"v2"}));if(url.endsWith("/auth/key-envelope"))return jsonResponse({key_scheme:"v2",salt:SALT,wrapped_data_key:envelope.wrappedDataKeyB64,kdf_params:envelope.kdfParams});return jsonResponse({code:"not_found"},{status:404});});const root=await filled();await press(root,"Sign in");await settle(100,12);expect(hasSession()).toBe(true);expect(vault.get().dataKey).toEqual(envelope.dataKey);});}
 it("erases every native derived allocation when a v2 registration request fails",async()=>{const root=await filled(true);const owned:Uint8Array[]=[];const native=crypto.subtle.deriveBits.bind(crypto.subtle);vi.spyOn(crypto.subtle,"deriveBits").mockImplementation(async(...args)=>{const result=await native(...args);owned.push(new Uint8Array(result));return result;});routes({code:"server_error"},500);await press(root,"Create journal");await settle(80,8);expect(hasSession()).toBe(false);expect(vault.isUnlocked()).toBe(false);expect(owned.length).toBeGreaterThanOrEqual(4);expect(owned.every(bytes=>bytes.every(x=>x===0))).toBe(true);});
 for(const [password,expected]of [["12345678901", "at least 12"],["aaaaaaaaaaaa","three of"],["AAAAAAAAAAA!","three of"],["11111111111!","three of"],["ABCDEFGH12!x",null],["abcdefgh12!x",null],["ABCDEFGHijkl", "three of"],["abcdefghijklmno", "three of"],["abcdefghijklmnop",null],["abcdefghijkl1!",null],["B^70strong-phrase",null],["mQ7!zz0123xx",null],["0123-mQ7!zzzz","too common"],["Ab!1-PASSWORDzzz","too common"]]as const){it(`enforces literal password ${password}`,()=>{const error=passwordPolicyError(password);if(expected===null)expect(error).toBeNull();else expect(error).toContain(expected);});}
 it("a held native login rejects a second keyboard submission",async()=>{let release!:()=>void;const gate=new Promise<void>(r=>release=r);let requests=0;stubFetch(async url=>{if(url.endsWith("/auth/salt"))return jsonResponse({salt:SALT});requests++;await gate;return jsonResponse({code:"invalid_credentials"},{status:401});});const root=await filled();await press(root,"Sign in");await settle(50,6);expect(requests).toBe(1);await act(async()=>{root.root.findByType("form").props.onSubmit({preventDefault(){}});});await settle(50,6);expect(requests).toBe(1);await act(async()=>release());await settle(50,4);expect(isDisabled(root,"Sign in")).toBe(false);});
 for(const v2 of [false,true])it(`native registration ${v2?"v2":"legacy v1"} erases the discarded data key`,async()=>{const root=await filled(true);const nativeBits=crypto.subtle.deriveBits.bind(crypto.subtle),nativeRandom=crypto.getRandomValues.bind(crypto);let label:Uint8Array|undefined,random:Uint8Array|undefined;vi.spyOn(crypto.subtle,"deriveBits").mockImplementation(async(...args)=>{const result=await nativeBits(...args);const params=args[0]as HkdfParams;if(params.name==="HKDF"&&new TextDecoder().decode(params.info).endsWith("data/v1"))label=new Uint8Array(result);return result;});vi.spyOn(crypto,"getRandomValues").mockImplementation(array=>{const result=nativeRandom(array);if((result as unknown as Uint8Array).length===32)random=result as unknown as Uint8Array;return result;});routes(token(v2?{key_scheme:"v2"}:{}));await press(root,"Create journal");await settle(80,8);expect(hasSession()).toBe(true);expect(textOf(root)).not.toContain("invalid response");expect(label).toBeDefined();expect(random).toBeDefined();if(v2){expect(label!.every(x=>x===0)).toBe(true);expect(vault.get().dataKey).toEqual(random);}else{expect(random!.every(x=>x===0)).toBe(true);expect(vault.get().dataKey).toEqual(label);}});
 it("native rejected credentials erase all actual KDF allocations",async()=>{const root=await filled();const owned:Uint8Array[]=[];const native=crypto.subtle.deriveBits.bind(crypto.subtle);vi.spyOn(crypto.subtle,"deriveBits").mockImplementation(async(...args)=>{const result=await native(...args);owned.push(new Uint8Array(result));return result;});routes({code:"invalid_credentials"},401);await press(root,"Sign in");await settle(80,8);expect(hasSession()).toBe(false);expect(owned).toHaveLength(3);expect(owned.every(bytes=>bytes.every(x=>x===0))).toBe(true);});

 it("registration headings, password autofill and advice follow the native account form",async()=>{const root=await filled(true);expect(root.root.findByType("h2").props.children).toBe("Create your journal");expect(root.root.findAllByType("input").filter(n=>n.props.type==="password").map(n=>n.props.autoComplete)).toEqual(["new-password","new-password"]);expect(textOf(root)).toContain("12+ characters (16+, or three character classes");const strengthText=root.root.findAllByType("span").find(n=>n.props.className==="note note--muted"&&n.props.children==="Strong");expect(strengthText?.props.style).toEqual({whiteSpace:"nowrap"});await press(root,"I have an account");expect(root.root.findByType("h2").props.children).toBe("Sign in");expect(root.root.findAllByType("input").find(n=>n.props.type==="password")?.props.autoComplete).toBe("current-password");expect(textOf(root)).not.toContain("Stryker");});
 it("native Enter submission without age attestation has its own exact error alert",async()=>{const root=await filled(true);await setCheckbox(root,"I am 18 or older",false);await act(async()=>root.root.findByType("form").props.onSubmit({preventDefault(){}}));expect(root.root.findAll(n=>n.props.role==="alert").map(n=>n.props.children)).toHaveLength(1);expect(textOfNode(root.root.findAll(n=>n.props.role==="alert")[0])).toContain("Please confirm you are 18 or older to");});
 it("native unknown HTTP refusal uses the localized generic fallback",async()=>{const root=await filled();routes({code:"unknown",detail:"private"},400);await press(root,"Sign in");await settle(80,8);expect(textOf(root)).toContain("Something went wrong");expect(textOf(root)).not.toContain("private");});
 for(const variant of ["argon2","salt","scheme","tamper","v2-therapist","v2-invalid-id","cost800k"]){it(`owns every native v2 allocation through ${variant}`,async()=>{const salt=fromBase64(SALT),iterations=variant==="cost800k"?800000:600000,master=await deriveMasterKey(PASSWORD,salt,iterations),env=await createRegistrationEnvelope(master,salt,"alice",{algorithm:"pbkdf2-sha256",version:1,iterations});const envelope={key_scheme:variant==="scheme"?"v3":"v2",salt:variant==="salt"?"AQEBAQEBAQEBAQEBAQEBAQ==":SALT,kdf_params:variant==="argon2"?{algorithm:"argon2id",version:1,iterations:3,memory_kib:65536,parallelism:1}:env.kdfParams,wrapped_data_key:variant==="tamper"?env.wrappedDataKeyB64.slice(0,-4)+"AAAA":env.wrappedDataKeyB64};stubFetch(url=>url.endsWith("/auth/salt")?jsonResponse({salt:SALT}):url.endsWith("/auth/login")?jsonResponse(token({key_scheme:"v2",...(variant==="v2-therapist"?{role:"therapist"}:{}),...(variant==="v2-invalid-id"?{user_id:USER+"f"}:{})})):jsonResponse(envelope));const root=await filled();const owned:Uint8Array[]=[];const native=crypto.subtle.deriveBits.bind(crypto.subtle);vi.spyOn(crypto.subtle,"deriveBits").mockImplementation(async(...args)=>{const value=await native(...args);owned.push(new Uint8Array(value));return value;});await press(root,"Sign in");await settle(100,12);if(variant==="cost800k"){expect(hasSession()).toBe(true);expect(vault.get().dataKey).toEqual(env.dataKey);expect(owned.filter(bytes=>bytes.buffer!==vault.get().authKey.buffer).every(bytes=>bytes.every(x=>x===0))).toBe(true);}else{expect(hasSession()).toBe(false);expect(vault.isUnlocked()).toBe(false);expect(owned.length).toBeGreaterThanOrEqual(3);expect(owned.every(bytes=>bytes.every(x=>x===0))).toBe(true);}expect(textOf(root)).not.toContain("Stryker");});}

 for(const register of [false,true])it(`native ${register?"register":"signin"} server unavailability with Retry-After does not become a rate-limit claim`,async()=>{const root=await filled(register);stubFetch(url=>url.endsWith("/auth/salt")?jsonResponse({salt:SALT}):jsonResponse({code:"server_error"},{status:503,headers:{"Retry-After":"30"}}));await press(root,register?"Create journal":"Sign in");await settle(80,8);expect(textOf(root)).toContain("The server hit a problem");expect(textOf(root)).not.toContain("about 30s");expect(textOf(root)).not.toContain("username is already");});
 it("native WebCrypto failure displays the localized login failure without internal provider copy",async()=>{routes();const root=await filled();vi.spyOn(crypto.subtle,"deriveBits").mockRejectedValue(new DOMException("native KDF provider unavailable","OperationError"));await press(root,"Sign in");await settle(30,4);expect(textOf(root)).toContain("Something went wrong");expect(textOf(root)).not.toContain("native KDF provider unavailable");expect(hasSession()).toBe(false);});
 it("the default envelope uses its already-owned master when a later native KDF provider is unavailable",async()=>{const salt=fromBase64(SALT),master=await deriveMasterKey(PASSWORD,salt),env=await createRegistrationEnvelope(master,salt,"alice");stubFetch(url=>url.endsWith("/auth/salt")?jsonResponse({salt:SALT}):url.endsWith("/auth/login")?jsonResponse(token({key_scheme:"v2"})):jsonResponse({key_scheme:"v2",salt:SALT,kdf_params:env.kdfParams,wrapped_data_key:env.wrappedDataKeyB64}));const root=await filled();const native=crypto.subtle.deriveBits.bind(crypto.subtle);let derives=0;vi.spyOn(crypto.subtle,"deriveBits").mockImplementation(async(...args)=>{if((args[0] as Algorithm).name==="PBKDF2"&&++derives===2)throw new DOMException("native KDF provider unavailable","OperationError");return native(...args);});await press(root,"Sign in");await settle(100,10);expect(hasSession()).toBe(true);expect(vault.get().dataKey).toEqual(env.dataKey);expect(textOf(root)).not.toContain("could not");});

 it("refuses a native JSON array whose only element is an otherwise authenticated envelope",async()=>{const salt=fromBase64(SALT),master=await deriveMasterKey(PASSWORD,salt),env=await createRegistrationEnvelope(master,salt,"alice");stubFetch(url=>url.endsWith("/auth/salt")?jsonResponse({salt:SALT}):url.endsWith("/auth/login")?jsonResponse(token({key_scheme:"v2"})):jsonResponse({key_scheme:"v2",salt:SALT,kdf_params:env.kdfParams,wrapped_data_key:[env.wrappedDataKeyB64]}));const root=await filled();await press(root,"Sign in");await settle(100,10);expect(hasSession()).toBe(false);expect(vault.isUnlocked()).toBe(false);expect(textOf(root)).toContain("key envelope could not be opened");});
});
