import { act } from "react";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { SafetyPlanView } from "../src/views/SafetyPlan";
import { EMPTY_SAFETY_PLAN,loadSafetyPlan,preserveSafetyPlan,saveSafetyPlan,type SafetyPlan } from "../src/safetyPlan";
import { setKvBackendForTests,type KvBackend } from "../src/kvstore";
import { vault } from "../src/vault";
import { resetTestState,installSession } from "./helpers/api";
import { isDisabled,press,render,settle,textOf,typeArea } from "./helpers/rtr";
const USER="a".repeat(32),KEY=new Uint8Array(32).fill(4),SLOT=`mindpattern.safetyPlan.${USER}`;
const PLAN:SafetyPlan={warningSigns:"old warning",coping:"old coping",peoplePlaces:"old people",helpers:"old helpers",professionals:"old professional",saferEnvironment:"old environment"};
let map:Map<string,string>,backend:KvBackend;
beforeEach(()=>{resetTestState();installSession(USER);vault.unlock({authKey:new Uint8Array(KEY),dataKey:new Uint8Array(KEY)},USER);map=new Map();backend={async getItem(k){return map.get(k)??null;},async setItem(k,v){map.set(k,v);},async removeItem(k){map.delete(k);},async keys(){return [...map.keys()];}};setKvBackendForTests(backend);});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals();});
async function ready(){const root=await render(<SafetyPlanView onCrisis={()=>undefined}/>);await settle(25,4);return root;}
const warning=(root:Awaited<ReturnType<typeof render>>)=>root.root.findAllByType("textarea")[0]!.props.value;
describe("native local plan completion",()=>{
 it("the initialized editor preserves a dirty plan through the actual navigation seal",async()=>{const root=await ready();await typeArea(root,"My warning signs","new unsaved writing");await preserveSafetyPlan();expect(await loadSafetyPlan(KEY,USER)).toEqual({...EMPTY_SAFETY_PLAN,warningSigns:"new unsaved writing"});expect(map.get(SLOT)).not.toContain("new unsaved writing");});
 it("a clean restored editor leaves a subsequently authored durable receipt untouched",async()=>{await saveSafetyPlan(KEY,USER,PLAN);await ready();await saveSafetyPlan(KEY,USER,{...PLAN,coping:"new other screen"});const raw=map.get(SLOT);await preserveSafetyPlan();expect(map.get(SLOT)).toBe(raw);expect((await loadSafetyPlan(KEY,USER))?.coping).toBe("new other screen");});
 it("a save clears dirty custody so a later navigation cannot resurrect its old receipt",async()=>{const root=await ready();await typeArea(root,"My warning signs","saved writing");await press(root,"Save my plan");await settle(25,4);expect(textOf(root)).toContain("Saved — encrypted on this device");expect(textOf(root)).not.toContain("Stryker");await saveSafetyPlan(KEY,USER,PLAN);const raw=map.get(SLOT);await preserveSafetyPlan();expect(map.get(SLOT)).toBe(raw);});
 it("a subsequent edit clears the visible saved note and becomes the preserved plan",async()=>{const root=await ready();await typeArea(root,"My warning signs","saved writing");await press(root,"Save my plan");await settle(25,4);expect(textOf(root)).toContain("Saved — encrypted");await typeArea(root,"What helps me cope","a newer cope");expect(textOf(root)).not.toContain("Saved — encrypted");await preserveSafetyPlan();expect((await loadSafetyPlan(KEY,USER))?.coping).toBe("a newer cope");});
 it("actual native commit failure retains written fields and removes a prior saved note",async()=>{const root=await ready();await typeArea(root,"My warning signs","first writing");await press(root,"Save my plan");await settle(25,4);await typeArea(root,"My warning signs","new failed writing");backend.setItem=async()=>{throw new Error("native disk quota");};await press(root,"Save my plan");await settle(25,4);expect(warning(root)).toBe("new failed writing");expect(textOf(root)).toContain("Writing was not saved on this device");expect(textOf(root)).not.toContain("Saved — encrypted");expect(isDisabled(root,"Save my plan")).toBe(false);backend.setItem=async(k,v)=>{map.set(k,v);};expect((await loadSafetyPlan(KEY,USER))?.warningSigns).toBe("first writing");});
 it("a held native commit advertises busy while keeping newer edits dirty",async()=>{const root=await ready();await typeArea(root,"My warning signs","accepted writing");let release!:()=>void;const gate=new Promise<void>(r=>release=r);let reached=false;backend.setItem=async(k,v)=>{reached=true;await gate;map.set(k,v);};await press(root,"Save my plan");await settle(25,4);expect(reached).toBe(true);expect(isDisabled(root,"Saving…")).toBe(true);await typeArea(root,"My warning signs","newer typed writing");await act(async()=>release());await settle(25,4);expect(warning(root)).toBe("newer typed writing");expect(textOf(root)).not.toContain("Saved — encrypted");expect(isDisabled(root,"Save my plan")).toBe(false);backend.setItem=async(k,v)=>{map.set(k,v);};await preserveSafetyPlan();expect((await loadSafetyPlan(KEY,USER))?.warningSigns).toBe("newer typed writing");});
 it("a held initial restore preserves early typed fields and protects untouched stored fields",async()=>{await saveSafetyPlan(KEY,USER,PLAN);let release!:()=>void;const gate=new Promise<void>(r=>release=r);const get=backend.getItem.bind(backend);let first=true;const before=map.get(SLOT);backend.getItem=async k=>{const value=await get(k);if(k===SLOT&&first){first=false;await gate;}return value;};const root=await render(<SafetyPlanView onCrisis={()=>undefined}/>);await typeArea(root,"My warning signs","early typed warning");await preserveSafetyPlan();expect(map.get(SLOT)).toBe(before);await act(async()=>release());await settle(25,4);expect(warning(root)).toBe("early typed warning");expect(root.root.findAllByType("textarea")[1]!.props.value).toBe(PLAN.coping);await preserveSafetyPlan();expect(await loadSafetyPlan(KEY,USER)).toEqual({...PLAN,warningSigns:"early typed warning"});});
 it("the public retry retires an earlier native restore success",async()=>{await saveSafetyPlan(KEY,USER,PLAN);let release!:()=>void;const gate=new Promise<void>(r=>release=r);let first=true;const get=backend.getItem.bind(backend);backend.getItem=async k=>{const value=await get(k);if(k===SLOT&&first){first=false;await gate;}return value;};const root=await render(<SafetyPlanView onCrisis={()=>undefined}/>);await saveSafetyPlan(KEY,USER,{...PLAN,coping:"latest durable coping"});await press(root,"Retry restoring saved plan");await settle(25,4);expect(warning(root)).toBe(PLAN.warningSigns);await typeArea(root,"My warning signs","newer retry edit");await act(async()=>release());await settle(25,4);expect(warning(root)).toBe("newer retry edit");expect(root.root.findAllByType("textarea")[1]!.props.value).toBe("latest durable coping");expect(textOf(root)).not.toContain("could not");});
 it("the public retry retires an earlier native restore failure",async()=>{let release!:()=>void;const gate=new Promise<void>(r=>release=r);let first=true;const get=backend.getItem.bind(backend);backend.getItem=async k=>{if(k===SLOT&&first){first=false;await gate;throw new Error("old native read failure");}return get(k);};const root=await render(<SafetyPlanView onCrisis={()=>undefined}/>);await press(root,"Retry restoring saved plan");await settle(25,4);await act(async()=>release());await settle(25,4);expect(textOf(root)).not.toContain("Local encrypted records could not be read");await typeArea(root,"My warning signs","new writing");await press(root,"Save my plan");await settle(25,4);expect(textOf(root)).toContain("Saved — encrypted");});
 it("an unhydrated unreadable plan refuses save and stays recoverable",async()=>{map.set(SLOT,"unreadable-recoverable");const root=await ready();expect(textOf(root)).toContain("could not be authenticated");await typeArea(root,"My warning signs","early unsaved");await preserveSafetyPlan();expect(map.get(SLOT)).toBe("unreadable-recoverable");await press(root,"Save my plan");expect(textOf(root)).toContain("Restore the existing encrypted plan");expect(map.get(SLOT)).toBe("unreadable-recoverable");});
 it("the clean flag resets dirty field tracking before a later native restore retry",async()=>{await saveSafetyPlan(KEY,USER,PLAN);let fail=true;const get=backend.getItem.bind(backend);backend.getItem=async k=>{if(k===SLOT&&fail){fail=false;throw new Error("native restore failed");}return get(k);};const root=await ready();await typeArea(root,"My warning signs","early edit");await press(root,"Retry restoring saved plan");await settle(25,4);await press(root,"Save my plan");await settle(25,4);expect((await loadSafetyPlan(KEY,USER))?.warningSigns).toBe("early edit");});
 it("a public save after actual vault lock reports the locked session",async()=>{const root=await ready();await typeArea(root,"My warning signs","unsaved");vault.lock();await press(root,"Save my plan");expect(textOf(root)).toContain("Your session locked — sign in again.");expect(map.has(SLOT)).toBe(false);});
 it("a second native save failure clears the old success receipt without another edit",async()=>{const root=await ready();await typeArea(root,"My warning signs","same writing");await press(root,"Save my plan");await settle(25,4);expect(textOf(root)).toContain("Saved — encrypted");backend.setItem=async()=>{throw new Error("native write unavailable");};await press(root,"Save my plan");await settle(25,4);expect(textOf(root)).toContain("Writing was not saved on this device");expect(textOf(root)).not.toContain("Saved — encrypted");});

 it("an empty-message native crypto failure still reports the local save fallback",async()=>{const root=await ready();await typeArea(root,"My warning signs","retained writing");vi.spyOn(crypto.subtle,"encrypt").mockRejectedValueOnce(new DOMException("","OperationError"));await press(root,"Save my plan");await settle(25,4);expect(textOf(root)).toContain("Could not save your plan — it is still on screen.");expect(warning(root)).toBe("retained writing");});

});
