/**
 * Native-feature seams (2026-09-17).
 *
 * The repo ships JS/TS source only (ios/android projects are generated by
 * the RN toolchain at build time), so features needing native modules —
 * local journaling reminders and biometric unlock — cannot be linked yet.
 * This module is the SEAM: capability detection with a hard guarantee that
 * a missing module degrades to "unavailable", never a crash. When the
 * native dependency is added to package.json and linked, these return real
 * capabilities and the Settings/UI affordances light up with no further
 * changes.
 *
 * Design contracts for the future implementations:
 *  - Reminders: LOCAL notifications only (notifee-style scheduled at a
 *    user-chosen time), max one per day, opt-in from onboarding, no
 *    streak-shaming copy — the calm-tone rules the rest of the app follows.
 *  - Biometrics: wraps the DERIVED data key with a Keychain
 *    biometry-current-set access control at unlock time; the password
 *    path always remains as fallback. Distinct from the secureStore
 *    device-key custody item (mobile/README checklist).
 */

export interface NativeCapability {
  available: boolean;
  /** Why not (rendered once, in Settings, when unavailable). */
  reason?: string;
}

function probe(moduleName: string): unknown | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require(moduleName);
    return mod ?? null;
  } catch {
    return null;
  }
}

export function reminderCapability(): NativeCapability {
  const mod = probe("@notifee/react-native");
  if (mod === null) {
    return {
      available: false,
      reason: "notification module not linked in this build",
    };
  }
  return { available: true };
}

export function biometricCapability(): NativeCapability {
  const mod = probe("react-native-biometrics");
  if (mod === null) {
    return {
      available: false,
      reason: "biometric module not linked in this build",
    };
  }
  return { available: true };
}
