/**
 * Native-feature seams (2026-09-17; reminders implemented 2026-09-19).
 *
 * The repo ships JS/TS source only (ios/android projects are generated by
 * the RN toolchain at build time), so features needing native modules —
 * local journaling reminders and biometric unlock — cannot be linked yet.
 * This module is the SEAM: capability detection with a hard guarantee that
 * a missing module degrades to "unavailable", never a crash. When the
 * native dependency is added to package.json and linked, these return real
 * capabilities and the Settings/UI affordances light up with no further
 * changes.
 *
 * Design contracts:
 *  - Reminders: LOCAL notifications only (notifee-style scheduled at a
 *    user-chosen time), max one per day, opt-in from onboarding, no
 *    streak-shaming copy — the calm-tone rules the rest of the app follows.
 *    Implemented below as scheduleDailyReminder/cancelDailyReminder over
 *    the probed @notifee/react-native module; the preference record lives
 *    in reminders.ts and reminderSync.ts reconciles the two.
 *  - Biometrics: wraps the DERIVED data key with a Keychain
 *    biometry-current-set access control at unlock time; the password
 *    path always remains as fallback. Distinct from the secureStore
 *    device-key custody item (mobile/README checklist). Implemented in
 *    biometricUnlock.ts over react-native-keychain (already a dependency).
 */

import { nextReminderFireTime } from "./reminders";
import { t } from "./strings";

export interface NativeCapability {
  available: boolean;
  /** Why not (rendered once, in Settings, when unavailable). */
  reason?: string;
}

function probe(moduleName: string): unknown | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require(moduleName);
    return mod ?? null;
  } catch {
    return null;
  }
}

/** Async resolution for the ACTION seams: the synchronous require first
 *  (the RN bundler path — a linked module resolves statically), then a
 *  dynamic import so test builds can inject the module through the module
 *  runner (vi.mock intercepts `import()`, not `require()`). Both failures
 *  read as "absent" — never a throw. */
async function probeAsync(moduleName: string): Promise<unknown | null> {
  const mod = probe(moduleName);
  if (mod !== null) return mod;
  try {
    return await import(moduleName);
  } catch {
    return null;
  }
}

export function reminderCapability(): NativeCapability {
  const mod = probe("@notifee/react-native");
  if (mod === null) {
    return {
      available: false,
      reason: "notification module not linked in this build",
    };
  }
  return { available: true };
}

// 2026-09-26 audit LOW: biometricCapability() deleted — it probed
// react-native-biometrics, which is NOT a dependency (biometrics actually
// ride react-native-keychain via biometricUnlock.ts) and had zero callers.

/** The notifee API surface this module touches (the real module exports
 *  far more; this keeps the seam typed without importing it). */
interface NotifeeModule {
  requestPermission(): Promise<unknown>;
  createTriggerNotification(notification: unknown, trigger: unknown): Promise<unknown>;
  cancelAllNotifications(): Promise<unknown>;
  createChannel?(channel: unknown): Promise<unknown>;
}

/** notifee.AuthorizationStatus.AUTHORIZED — the only answer that counts as
 *  permission granted (provisional stays "not granted" for a daily nudge:
 *  quiet delivery is not what the user agreed to). */
const AUTHORIZATION_STATUS_AUTHORIZED = 1;
/** notifee TriggerType.TIMESTAMP / RepeatFrequency.DAILY fallbacks for a
 *  module build that does not export its enums; the module's own values
 *  are preferred whenever present so the real runtime never guesses. */
const FALLBACK_TRIGGER_TYPE_TIMESTAMP = 0;
const FALLBACK_REPEAT_FREQUENCY_DAILY = 1;

/** Reminders are the ONLY notifications this app schedules, so a stable
 *  channel id is safe and lets the OS surface "Journal reminders" in
 *  system settings honestly. */
const REMINDER_CHANNEL_ID = "mindpattern-reminders";

/** Calm copy for the notification itself: an invitation, never a debt —
 *  no streak counts, no "you missed", nothing to feel bad about. Resolved
 *  through the catalog at schedule time (audit fix 22, 2026-09-21) so the
 *  nudge speaks the app locale; the title is the app name and stays fixed
 *  in every language. */
function reminderNotification(): {
  title: string;
  body: string;
  android: { channelId: string };
} {
  return {
    title: "MindPattern",
    body: t("notify.reminderBody"),
    android: { channelId: REMINDER_CHANNEL_ID },
  };
}

function notifeeFrom(mod: unknown): NotifeeModule | null {
  if (mod === null || typeof mod !== "object") return null;
  // The package's default export carries the API; tolerate a bare object.
  const candidate = (mod as { default?: unknown }).default ?? mod;
  if (typeof candidate !== "object" || candidate === null) return null;
  const api = candidate as Partial<NotifeeModule>;
  if (typeof api.requestPermission !== "function") return null;
  if (typeof api.createTriggerNotification !== "function") return null;
  if (typeof api.cancelAllNotifications !== "function") return null;
  return api as NotifeeModule;
}

function authorizationGranted(result: unknown): boolean {
  // requestPermission answers either a bare AuthorizationStatus number or a
  // permission-status record; only an explicit AUTHORIZED counts.
  const status = typeof result === "number" ? result : (result as { authorizationStatus?: unknown } | null)?.authorizationStatus;
  return status === AUTHORIZATION_STATUS_AUTHORIZED;
}

/**
 * Schedule (or reschedule) the single daily LOCAL reminder at hour:minute.
 * Rescheduling replaces any previous trigger: notifee has no per-trigger
 * cancel here, and reminders are the app's only notification, so the
 * schedule call itself is the update. Returns false — never throws — when
 * the module is absent, permission is denied, or the native call fails;
 * the UI treats false as "not available in this build / not scheduled".
 */
export async function scheduleDailyReminder(hour: number, minute: number): Promise<boolean> {
  const mod = await probeAsync("@notifee/react-native");
  const api = notifeeFrom(mod);
  if (api === null) return false;
  try {
    if (!authorizationGranted(await api.requestPermission())) return false;
    // Prefer the module's own enum values (named exports
    // TriggerType.TIMESTAMP / RepeatFrequency.DAILY); the constants above
    // are only a fallback for builds that stopped exporting them.
    const enums = mod as {
      TriggerType?: { TIMESTAMP?: number };
      RepeatFrequency?: { DAILY?: number };
    };
    const triggerType = enums.TriggerType?.TIMESTAMP ?? FALLBACK_TRIGGER_TYPE_TIMESTAMP;
    const repeatFrequency = enums.RepeatFrequency?.DAILY ?? FALLBACK_REPEAT_FREQUENCY_DAILY;
    // Android delivers through a channel; creating it again is an idempotent
    // update. A channel-less Android notification never shows. The channel
    // NAME is user-visible in system settings, so it localizes too (fix 22).
    if (typeof api.createChannel === "function") {
      await api.createChannel({ id: REMINDER_CHANNEL_ID, name: t("notify.channelName") });
    }
    await api.createTriggerNotification(reminderNotification(), {
      type: triggerType,
      // The first fire is the next H:M still ahead of now; the daily repeat
      // keeps that time-of-day (reminders.ts computes it in LOCAL time).
      timestamp: nextReminderFireTime(new Date(), hour, minute).getTime(),
      repeatFrequency,
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Remove the scheduled reminder. Reminders are this app's only
 * notifications, so cancelAllNotifications is exactly the reminder
 * schedule. Returns false — never throws — when the module is absent or
 * the native call fails; a stale notification that survives a failed
 * cancel is a benign next-day nudge, not a security or data event.
 */
export async function cancelDailyReminder(): Promise<boolean> {
  const api = notifeeFrom(await probeAsync("@notifee/react-native"));
  if (api === null) return false;
  try {
    await api.cancelAllNotifications();
    return true;
  } catch {
    return false;
  }
}
