/**
 * Crisis resources — offline, always reachable, safe-messaging compliant.
 *
 * Industry expectation (APA app-evaluation model; #chatsafe guidelines):
 * crisis help must be reachable within one or two interactions from any
 * screen, must work offline (numbers cached in the app binary, no API
 * round-trip), and must never be generated by AI. This screen is static
 * content with direct call/text/chat actions. Nothing here diagnoses,
 * tracks, or alerts anyone — it just puts real humans one tap away.
 *
 * Call anxiety is the top barrier to using a hotline, so the screen says
 * plainly what calling is like. Locale awareness (device region via Intl —
 * no new dependencies): outside the US, findahelpline.com leads and the
 * US-only services say so honestly. Every open failure still falls back to
 * speaking the number aloud — a dead tap here is the worst possible bug.
 */
import React from "react";
import { Alert, Linking, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useTheme } from "../theme";

/** Texting a crisis line uses a different query separator per platform:
 *  Android's "?body=" is silently dropped by iOS (which wants "&body="),
 *  and "HOME" pre-filled is the whole point of the shortcut. */
function crisisTextUrl(): string {
  return `sms:741741${Platform.select({ ios: "&body=HOME", default: "?body=HOME" })}`;
}

/** Every external open can reject (no dialer, no browser, a simulator) —
 *  and a dead tap on THIS screen is the worst possible failure. Fall back
 *  to telling the user the number/address itself. */
function openExternal(url: string, fallback: string): void {
  Linking.openURL(url).catch(() => {
    Alert.alert("Couldn't open it from here", fallback);
  });
}

/** The device's region from its locale ("en-US" → "US"), or null when the
 *  platform won't say. No native module needed; failure keeps US-first. */
export function deviceRegion(): string | null {
  try {
    const locale = Intl.DateTimeFormat().resolvedOptions().locale;
    const match = /[-_]([A-Za-z]{2})\b/.exec(locale);
    const region = match?.[1];
    return region ? region.toUpperCase() : null;
  } catch {
    return null;
  }
}

function ActionButton({
  label,
  detail,
  onPress,
  theme,
}: {
  label: string;
  detail: string;
  onPress: () => void;
  theme: ReturnType<typeof useTheme>;
}) {
  return (
    <TouchableOpacity
      style={[
        styles.action,
        {
          backgroundColor: theme.colors.card,
          borderRadius: theme.radius.lg,
          minHeight: theme.minTouch,
        },
      ]}
      onPress={onPress}
      accessibilityRole="button"
      accessibilityLabel={`${label} — ${detail}`}
    >
      <View style={{ flex: 1 }}>
        <Text style={[styles.actionLabel, { color: theme.colors.text }]}>{label}</Text>
        <Text style={[styles.actionDetail, { color: theme.colors.muted, fontSize: 13 }]}>{detail}</Text>
      </View>
      <Text style={[styles.actionGo, { color: theme.colors.accent }]}>Go</Text>
    </TouchableOpacity>
  );
}

/** `region` is injectable for tests; production callers leave it to the
 *  device locale. */
export function CrisisScreen({ region }: { region?: string }): React.JSX.Element {
  const t = useTheme();
  const effectiveRegion = region ?? deviceRegion();
  // null (unknown) keeps the US-first layout — the services are US-based,
  // and a misdetection must never hide them from a US user mid-crisis.
  const usFirst = effectiveRegion === null || effectiveRegion === "US";

  const usServices = (
    <>
      <ActionButton
        label="Call or text 988"
        detail="988 Suicide & Crisis Lifeline — call 988 or text it, any time"
        onPress={() => openExternal("tel:988", "You can still dial or text 988 from your phone — it is free and answers 24/7.")}
        theme={t}
      />
      <ActionButton
        label="Text HOME to 741741"
        detail="Crisis Text Line — text conversation with a trained counselor"
        onPress={() => openExternal(crisisTextUrl(), "You can still text HOME to 741741 from your messages app.")}
        theme={t}
      />
      <ActionButton
        label="Chat online at 988lifeline.org"
        detail="The same lifeline, in your browser — no phone call needed"
        onPress={() =>
          openExternal("https://988lifeline.org/chat", "You can still visit 988lifeline.org/chat in a browser.")
        }
        theme={t}
      />
      <ActionButton
        label={usFirst ? "Call 911" : "Call 911 (US)"}
        detail="If you are in immediate danger or have already hurt yourself"
        onPress={() => openExternal("tel:911", "You can still dial 911 from your phone.")}
        theme={t}
      />
    </>
  );

  const helpline = (
    <TouchableOpacity
      style={[styles.link, { minHeight: t.minTouch, justifyContent: "center" }]}
      hitSlop={t.touchSlop}
      onPress={() => openExternal("https://findahelpline.com", "You can still visit findahelpline.com in a browser.")}
      accessibilityRole="link"
      accessibilityLabel="Open findahelpline.com — crisis lines worldwide"
    >
      <Text style={[styles.linkText, { color: t.colors.accent }]}>Open findahelpline.com</Text>
    </TouchableOpacity>
  );

  return (
    <ScrollView
      style={[styles.container, { backgroundColor: t.colors.bg }]}
      contentContainerStyle={{ padding: t.spacing.xl, gap: 14 }}
    >
      <Text style={[styles.headline, { color: t.colors.text }]}>If you are thinking about harming yourself</Text>
      <Text style={[styles.body, { color: t.colors.body }]}>
        Please reach out right now. These services are free, confidential, and staffed by trained
        people — 24 hours a day.
      </Text>
      <Text style={[styles.body, { color: t.colors.body }]}>
        What to expect when you call or text: a trained counselor answers, and you can say as much
        or as little as you want — there is no script and no wrong way to start.
      </Text>

      {usFirst ? (
        <>
          {usServices}
          <Text style={[styles.body, { color: t.colors.body }]}>
            These are US services. Outside the US, find your local line at findahelpline.com.
          </Text>
          {helpline}
        </>
      ) : (
        <>
          <Text style={[styles.body, { color: t.colors.body }]}>
            Your region doesn't look like the US — find your local line first:
          </Text>
          {helpline}
          <Text style={[styles.body, { color: t.colors.body }]}>
            In the US, these are the national services (988 and 741741 are US-only):
          </Text>
          {usServices}
        </>
      )}

      <View style={[styles.divider, { backgroundColor: t.colors.border }]} />
      <Text style={[styles.note, { color: t.colors.muted }]}>
        MindPattern is a journal that shows you your own patterns. It is not therapy, not a medical
        device, and not an emergency service. Talking to a professional is never a wrong move.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  headline: { fontSize: 20, fontWeight: "700", lineHeight: 27 },
  body: { fontSize: 15, lineHeight: 22 },
  action: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 12,
  },
  actionLabel: { fontSize: 16, fontWeight: "700" },
  actionDetail: { marginTop: 3, lineHeight: 18 },
  actionGo: { fontSize: 14, fontWeight: "700" },
  link: { padding: 4 },
  linkText: { fontSize: 15, fontWeight: "600" },
  divider: { height: 1, marginTop: 6 },
  note: { fontSize: 12, lineHeight: 18 },
});
