/**
 * Crisis resources — offline, always reachable, safe-messaging compliant.
 *
 * Industry expectation (APA app-evaluation model; #chatsafe guidelines):
 * crisis help must be reachable within one or two interactions from any
 * screen, must work offline (numbers cached in the app binary, no API
 * round-trip), and must never be generated by AI. This screen is static
 * content with direct call/text actions. Nothing here diagnoses, tracks,
 * or alerts anyone — it just puts real humans one tap away.
 */
import React from "react";
import { Alert, Linking, Platform, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";

/** Texting a crisis line uses a different query separator per platform:
 *  Android's "?body=" is silently dropped by iOS (which wants "&body="),
 *  and "HOME" pre-filled is the whole point of the shortcut. */
function crisisTextUrl(): string {
  return `sms:741741${Platform.select({ ios: "&body=HOME", default: "?body=HOME" })}`;
}

/** Every external open can reject (no dialer, no browser, a simulator) —
 *  and a dead tap on THIS screen is the worst possible failure. Fall back
 *  to telling the user the number/address itself. */
function openExternal(url: string, fallback: string): void {
  Linking.openURL(url).catch(() => {
    Alert.alert("Couldn't open it from here", fallback);
  });
}

function ActionButton({ label, detail, onPress }: { label: string; detail: string; onPress: () => void }) {
  return (
    <TouchableOpacity style={styles.action} onPress={onPress} accessibilityRole="button">
      <View style={{ flex: 1 }}>
        <Text style={styles.actionLabel}>{label}</Text>
        <Text style={styles.actionDetail}>{detail}</Text>
      </View>
      <Text style={styles.actionGo}>Go</Text>
    </TouchableOpacity>
  );
}

export function CrisisScreen(): React.JSX.Element {
  return (
    <ScrollView style={styles.container} contentContainerStyle={{ padding: 20, gap: 14 }}>
      <Text style={styles.headline}>If you are thinking about harming yourself</Text>
      <Text style={styles.body}>
        Please reach out right now. These services are free, confidential, and staffed by trained
        people — 24 hours a day, in the United States:
      </Text>

      <ActionButton
        label="Call or text 988"
        detail="988 Suicide & Crisis Lifeline — call 988 or text it, any time"
        onPress={() => openExternal("tel:988", "You can still dial or text 988 from your phone — it is free and answers 24/7.")}
      />
      <ActionButton
        label="Text HOME to 741741"
        detail="Crisis Text Line — text conversation with a trained counselor"
        onPress={() => openExternal(crisisTextUrl(), "You can still text HOME to 741741 from your messages app.")}
      />
      <ActionButton
        label="Call 911"
        detail="If you are in immediate danger or have already hurt yourself"
        onPress={() => openExternal("tel:911", "You can still dial 911 from your phone.")}
      />

      <Text style={styles.body}>Outside the US? Find your local line at findahelpline.com.</Text>
      <TouchableOpacity
        style={styles.link}
        onPress={() => openExternal("https://findahelpline.com", "You can still visit findahelpline.com in a browser.")}
      >
        <Text style={styles.linkText}>Open findahelpline.com</Text>
      </TouchableOpacity>

      <View style={styles.divider} />
      <Text style={styles.note}>
        MindPattern is a journal that shows you your own patterns. It is not therapy, not a medical
        device, and not an emergency service. Talking to a professional is never a wrong move.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#0f1115" },
  headline: { color: "#e8eaf0", fontSize: 20, fontWeight: "700", lineHeight: 27 },
  body: { color: "#b6bdc9", fontSize: 15, lineHeight: 22 },
  action: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1a1e26",
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  actionLabel: { color: "#e8eaf0", fontSize: 16, fontWeight: "700" },
  actionDetail: { color: "#8a91a3", fontSize: 13, marginTop: 3, lineHeight: 18 },
  actionGo: { color: "#7f9bff", fontSize: 14, fontWeight: "700" },
  link: { padding: 4 },
  linkText: { color: "#7f9bff", fontSize: 15, fontWeight: "600" },
  divider: { height: 1, backgroundColor: "#22273335", marginTop: 6 },
  note: { color: "#5c6370", fontSize: 12, lineHeight: 18 },
});
